### ISSUE TITLE
Subgrid

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#1]
**Description**
Subgrid makes it possible to nest grids while having the items of the nested grid line up with the main grid. (Simply nesting `display: grid` doesn't allow this.)

**Specification**
https://drafts.csswg.org/css-grid-2/

**Tests**
https://wpt.fyi/results/css/css-grid/subgrid?label=experimental&label=master&aligned

As evident from these tests, only Firefox currently implements Subgrid.

**Rationale**
* Identified as a pain point in [MDN 2020 Browser Compatibllity Report](https://insights.developer.mozilla.org/reports/mdn-browser-compatibility-report-2020.html)
* Identified as a [top compat pain point](https://github.com/web-platform-tests/interop-2022/issues/7) in State of CSS 2021
* Grid usage in general is [high and growing](https://www.chromestatus.com/metrics/feature/timeline/popularity/1693)

(Originally proposed by @scottlow in https://github.com/web-platform-tests/rfcs/pull/99#issuecomment-948125730 before this repo was created.)

**Comment by foolip** [comment]
Based on the State of CSS 2021 results in https://github.com/web-platform-tests/interop-2022/issues/7, I think the case for Subgrid is strong.

**Comment by jgraham** [comment]
Linking some information I'd like to see in proposals, which I happen to have for subgrid: 
# Specs
https://drafts.csswg.org/css-grid-2/
# Tests
https://wpt.fyi/results/css/css-grid/subgrid?label=experimental&label=master&aligned
# Rationale
(taken from https://github.com/web-platform-tests/interop-2022/issues/1#issue-1039675037)
* Identified as a pain point in [MDN 2020 Browser Compatibllity Report](https://insights.developer.mozilla.org/reports/mdn-browser-compatibility-report-2020.html)
* Identified as a [top compat pain point](7) in State OF CSS 2021
* Grid usage in general is [high and growing](https://www.chromestatus.com/metrics/feature/timeline/popularity/1693)

**Comment by gsnedders** [comment]
Related to #2 would be the question as to whether we treat subgrid as a separate feature to grid generally, or whether we just extend grid to include subgrid.

**Comment by foolip** [comment]
I have labeled the tests with the `interop-2022-rfc` label here:
https://wpt.fyi/results/css/css-grid/subgrid?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-rfc

I excluded two crashtests in the directory, but labeled everything else. If anyone thinks we should include crashtests, please comment.

Is anyone aware of additional test coverage that can/should be added here?

**Comment by foolip** [comment]
> Related to #2 would be the question as to whether we treat subgrid as a separate feature to grid generally, or whether we just extend grid to include subgrid.

I think we should treat it as a separate feature, WDYT?

**Comment by karlcow** [comment]
What would be the pros and cons on both side of the argument?

If as a separate feature it increases the likelihood of being implemented (because not drowned in grid papercuts), probably separate would be better indeed.

* https://bugs.webkit.org/show_bug.cgi?id=202115
* https://bugs.chromium.org/p/chromium/issues/detail?id=618969
* https://bugzilla.mozilla.org/show_bug.cgi?id=1240834

Everyone is treating it as a kind of a separate feature.

**Comment by foolip** [comment]
IMHO, main advantage of separating them is that it's easier to understand and communicate. Subgrid is distinct enough to warrant its own entries on [caniuse.com](https://caniuse.com/css-subgrid) and [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Subgrid#browser_compatibility) so we'd be in good company.

The main advantage to merging that I can see is that it sets a precedent for significantly updating the test list of a focus area between two years. We might want to do the same for viewport measurement for 2023, and would have sorted out any issues by then.

**Comment by foolip** [comment]
A proposed list of tests has been labeled with [`interop-2022-subgrid`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-subgrid). It would be great if someone from each browser engine team can look over this list and comment if there are any issues.

**Comment by dlibby-** [comment]
That list LGTM, but I suspect we'll be adding more tests as part of implementing subgrid. We should probably come up with a process for adding tests to the list or agree that we will only score against the tests in the initial snapshot.
