### ISSUE TITLE
Keep an eye on `flex-aspect-ratio-002` + CSS spec work in progress

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/interop#105]
** Test List **

https://wpt.fyi/results/css/css-sizing/aspect-ratio/flex-aspect-ratio-002.html?label=experimental&label=master&aligned

** Rationale **

This Aspect Ratio test is dependent on a part of the Flexbox specification that's being debating by the CSSWG at https://github.com/w3c/csswg-drafts/issues/6794

The spec was unclear, and different implementors interpreted it differently, thus the lack of Interop. Hopefully the CSSWG will resolve soon. It's likely the test will need to be rewritten. (See the discussion towards the end.) Meanwhile, implementors are unable to move forward, and this test fails in 2 of 3 browser engines. 

I wanted to open this issue to make a note, so we can keep track of progress. No action to take yet.

**Comment by nt1m** [comment]
This is the same as #139, I think it's resolved now.
