### ISSUE TITLE
Remove css-scroll-snap/capturing-snap-positions.html 

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#108]
** Test List **

* css-scroll-snap/capturing-snap-positions.html

** Rationale **

@nmoucht investigated this, and found this is testing an "at-risk" feature of css-scroll-snap, see: https://github.com/w3c/csswg-drafts/issues/4496

It's also worth noting this is failing in all 3 browsers.

**Comment by foolip** [comment]
@flackr WDYT?

**Comment by nt1m** [comment]
@emilio @theres-waldo @jgraham What do you think?

**Comment by theres-waldo** [comment]
cc @hikezoe

**Comment by hiikezoe** [comment]
Thanks Botond for CCing me.  Honestly I wasn't aware of https://github.com/w3c/csswg-drafts/issues/4496 at all. In fact the situation in Gecko is pretty much same as what Majido mentioned in https://github.com/w3c/csswg-drafts/issues/4496#issuecomment-706333521 . We don't care non scroll containers at all as of now, Handling non scroll containers wouldn't be too hard in Gecko, but I am not a big fan of it. I wonder web developers can intuitively understand the scroll-snap-type property behavior for such cases. 

Anyway though I don't quite understand what the expected outcomes of the interop 2022 tasks are, dropping the test sounds reasonable to me.

**Comment by nt1m** [comment]
@flackr Hi! Have you had a chance to look at this?

**Comment by flackr** [comment]
This is a tricky one. It's at risk and not implemented by any browsers so on track for removal, but it is still in the spec and in https://github.com/w3c/csswg-drafts/issues/4496 there were good arguments for this feature making scroll snap more ergonomic, being relatively straigtforward to implement, and the plan is to revisit its removal after the rest of the spec is implemented. I do not think it makes sense to remove the test so long as it is still "planned" - perhaps rename it to be a tentative test instead to reflect its current at risk position?

**Comment by nt1m** [comment]
@flackr Thanks for taking a look! If it's a tentative test, I think we should at least exclude it from Interop 2022 (not necessarily remove the test from WPT).

**Comment by nt1m** [comment]
@foolip It seems like there's general agreement to remove it from Interop, should I (or you) move forward with the change?

**Comment by foolip** [comment]
@nt1m sorry for the delay, I'll remove the label now.

**Comment by foolip** [comment]
Done in https://github.com/web-platform-tests/wpt-metadata/pull/3007.
