### ISSUE TITLE
Interpolation color space for gradients

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#109]
** Test List **

* css/css-images/gradient/gradient-eval-002.html
* css/css-images/gradient/gradient-eval-003.html
* css/css-images/gradient/gradient-eval-005.html
* css/css-images/gradient/gradient-eval-006.html
* css/css-images/gradient/gradient-eval-007.html
* css/css-images/gradient/gradient-eval-008.html
* css/css-images/gradient/gradient-eval-009.html
* css/css-images/parsing/gradient-interpolation-method-valid.html
* css/css-images/parsing/gradient-interpolation-method-invalid.html
* css/css-images/parsing/gradient-interpolation-method-computed.html

** Rationale **

When I originally audited all the CSS Color tests in #20, I did consider adding these (see follow up comments), though it wasn't clear at the time that:

1. It would be deemed ready to ship by CSSWG
2. If other browsers needed some kind of fuzzing

Things are more clear now:

1. Yes, this feature was deemed ready to ship: https://github.com/w3c/csswg-drafts/issues/7310#issuecomment-1156717607
2. Many tests in the test list need to be changed to fail if the syntax isn't supported (by adding a red background underneath for instance). Also, many tests in the directory test color spaces, so I think we shouldn't need fuzzy matching, but if we do turn out to need it, we can always use our existing fuzzy meta tag.

I don't feel super strongly at this point in the year, I'm mostly filing this issue since to me this seemed more of an unintentional omission than intentional one.

WDYT? @emilio @argyleink

**Comment by foolip** [comment]
@sesse WDYT?

**Comment by nt1m** [comment]
@emilio @jgraham What do you think?

**Comment by sesse** [comment]
The gradient-eval-* parts seem reasonable to me; they're fairly core functionality in the gradient spec. I don't fully understand the gradient-interpolation-method-* tests offhand, so I can't say much about them.

**Comment by nt1m** [comment]
@sesse They're about the new syntax that allows specifying the color-space used for interpolation in gradient functions, e.g. `linear-gradient(in lch, red, blue)` for instance.

**Comment by svgeesus** [comment]
I agree with the rationale, and am happy to review a PR which adds a red fail if the syntax is unsupported (just an `@supports` would work there).

**Comment by lilles** [comment]
Yes.

**Comment by lilles** [comment]
Making sure the tests fail without lab/lch support: https://chromium-review.googlesource.com/c/chromium/src/+/3902032

**Comment by foolip** [comment]
@jgraham can you chase someone for a Gecko position?

**Comment by jensimmons** [comment]
It sounds like we are going to add these to Interop 2022. If for some reason we don't, adding for Interop 2023 would be good to do. We haven't filed an issue, however, since it's likely to go into 2022.... but typing out this comment to reserve the possibility of sticking in the 2023 pile for consideration if needed.

**Comment by nt1m** [comment]
Let's make this a proposal for next year.

**Comment by foolip** [comment]
@nt1m since this isn't a focus area proposal, we should handle it like the flex/grid expansion, would you agree?

**Comment by nt1m** [comment]
Could go either way, this could perfectly be a new focus area given this is a separate spec (CSS images), but this does also fit into "Color spaces". I have no strong opinion here.

**Comment by foolip** [comment]
There are 196 existing tests in "Color Spaces and Functions" and the suggestion is to add 10. That means the worst case reduction in score would be from 100% to 95%.

We have support from representatives of all 3 engines on this thread, so I think we should bring this up in a future meeting to see if we can just label the tests and be done with it. In particular I'd want @jgraham to weigh in then.

**Comment by foolip** [comment]
In the [MDN short survey on CSS & HTML](https://github.com/web-platform-tests/interop/issues/245), "CSS color spaces and functions (`color()`, `lab()`, gradients, etc.)" was selected by ~25% of survey takers, putting it in the top third of the 20 options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/245#issuecomment-1311874383) as with any survey data.)

**Comment by foolip** [comment]
Thank you for proposing interpolation color space for gradients for inclusion in Interop 2023.

We are pleased to let you know that this proposal was accepted as part of the Color Spaces and Functions focus area. You can follow the progress of this Focus Area on the [Interop 2023 dashboard](https://wpt.fyi/interop-2023).

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you for contributing to Interop 2023!

_Posted on behalf of the Interop team._
