### ISSUE TITLE
Remove test relying on contain-intrinsic-size

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#112]
** Test List **

* css/css-sizing/aspect-ratio/abspos-014.html

** Rationale **

contain-intrinsic-size is still an editor draft for CSS Sizing level 4, we should not have tests relying on contain-intrinsic-size. Only Chrome has a shipping implementation, Firefox & WebKit have a WIP implementation behind a flag.

I think this property could be its own focus area for 2023, but I do not think it is ready to ship for 2022.

cc @emilio @jgraham

**Comment by foolip** [comment]
@lilles can you help review? Would it be fine to drop this test from Interop 2022?

**Comment by lilles** [comment]
@bfgeek would know more

**Comment by emilio** [comment]
Seems reasonable to drop this. Gecko is also not shipping contain-intrinsic-size yet.

**Comment by bfgeek** [comment]
lgtm

**Comment by nt1m** [comment]
https://github.com/web-platform-tests/wpt-metadata/commit/50fd64f3cf0216d5888f3ed751baa7df1aaaa76e
