### ISSUE TITLE
Remove tests for font-variant @font-face descriptor

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#113]
** Test List **

* css/css-fonts/font-variant-descriptor-01.html
* css/css-fonts/font-variant-05.xht
* css/css-fonts/font-variant-06.xht

** Rationale **

This is referring to:
```
@font-face X {
    [...]
    font-variant: [...];
}
```
This was removed in https://github.com/w3c/csswg-drafts/commit/d3db8697852a6ccc1c8dafcb4aff1f516198bb50 and never re-instated into the specification. The tests should not be part of interop (possibly we should look into removing the tests entirely from WPT given the fact I'm not seeing this feature in [css-fonts-4](https://drafts.csswg.org/css-fonts-4/) or [css-fonts-5](https://drafts.csswg.org/css-fonts-5/)).

cc @jfkthame @litherum and @foolip (Is the chromium contact @drott for fonts?)

**Comment by nt1m** [comment]
Looks like @jfkthame did notice it here when we first labeled the tests: https://github.com/web-platform-tests/interop/issues/13#issuecomment-1008997232

**Comment by foolip** [comment]
Thanks @nt1m, removing the tests from WPT makes the question for interop easy :)
