### ISSUE TITLE
dialog & ::backdrop

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/interop#12]
**Description**
Implement / update implementations of the dialog element & ::backdrop pseudo-element.

**Specifications**
- [dialog element](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element)
- [::backdrop pseudo-element](https://fullscreen.spec.whatwg.org/#::backdrop-pseudo-element)

**Tests**
[dialog tests](https://wpt.fyi/results/html/semantics/interactive-elements/the-dialog-element?label=master&label=experimental&aligned)
tests needed for [tabindex + <dialog>.showModal()](https://github.com/whatwg/html/issues/1929) and [focus of dialog element](https://github.com/whatwg/html/pull/4184) 

**Rationale**
[The `<dialog>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) has been highly requested for years. If it's not appearing on recent surveys, it may just be because web developers have given up hope. The need to create overlays has not disappeared, and `dialog` gives web developers an accessible built-into-the-web technology to do so well.  

[The `::backdrop` pseudo-element](https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop) gives developers a way to style the modal box. 

According to Can I Use and MDB BDC, dialog & ::backdrop are supported by Chromium browsers, and need to be implemented in Gecko & WebKit. It seems progress was blocked for years by [disagreement](https://github.com/whatwg/html/issues/1929) [about](https://github.com/whatwg/html/pull/4184) accessibility details, especially regarding how to handle focus. There are now two implementers agreeing on what the HTML spec should be. 

- Gecko, to implement dialog: https://bugzilla.mozilla.org/show_bug.cgi?id=840640
- Gecko, to implement backdrop: https://bugzilla.mozilla.org/show_bug.cgi?id=1064843
- Webkit, to implement: https://bugs.webkit.org/show_bug.cgi?id=84635
- Chromium, to update their implementation: https://bugs.chromium.org/p/chromium/issues/detail?id=383230

**Comment by bkardell** [comment]
Really high interop on a newly landing in several browsers feature like this, very quickly, seems kind of good to me.

**Comment by josepharhar** [comment]
There was a recent change to the spec and tests here:
- https://github.com/whatwg/html/pull/7285
- https://github.com/web-platform-tests/wpt/pull/31523

And here is a crbug for changing that behavior: https://bugs.chromium.org/p/chromium/issues/detail?id=383230
The new tests are already included in the same directory as the WPT link in the issue description.

**Comment by foolip** [comment]
> **Rationale** [The `<dialog>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) has been highly requested for years. If it's not appearing on recent surveys, it may just be because web developers have given up hope.

While `<dialog>` wasn't among the top categories in https://github.com/web-platform-tests/interop-2022/issues/7, there were a few mentions of it in State of CSS 2021, enough for me to remember at least. Here they are:
-

**Comment by foolip** [comment]
I just found an old email from @nt1m, who pointed out that we have some tests for `<dialog>` in Chromium:
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/html/dialog/

Looking through the history, I see that some were already converted and upstreamed to WPT by @shanmuga-m:
https://github.com/web-platform-tests/wpt/pull/7338
https://github.com/web-platform-tests/wpt/pull/7859
https://github.com/web-platform-tests/wpt/pull/8174

However, a bunch of the tests that remain probably still make sense to upstream. I don't know who might be able to work on that (if this proposal is accepted) but I will ask around.

**Comment by josepharhar** [comment]
@foolip here is a related crbug: https://bugs.chromium.org/p/chromium/issues/detail?id=1240798

**Comment by jensimmons** [comment]
We should make sure we use modern tests that match the HTML spec version that Mozilla & Apple are endorsing, and not the older version from the past that isn't accessible. IOW, I'm not sure that older tests are testing the right version of the spec.

**Comment by jensimmons** [comment]
I wanted to get another data point for a sense of whether or not this is important to web developers. After 6 years of doing this research non-stop, my instincts say yes, `dialog` is highly requested. But hey, looking for new information to double check long-held beliefs is always a good idea. So I wrote [a tweet](https://twitter.com/jensimmons/status/1462908246985949185). 
<img width="601" alt="Screen Shot 2021-11-29 at 5 23 10 PM" src="https://user-images.githubusercontent.com/108474/143952164-42445ea7-8d3a-4511-a137-7a8c3cc6dce8.png">

63% of responders said, yes, `dialog` is important to them. They will use it. It should be a priority. 

More than that, however, the number of people who answered the poll tells me a lot. Over 2,000 people answered in 24 hours — which is far more than my quick informal twitter polls usually get. There was excitement about and clarity in expressing an opinion about `dialog`. Fifty-two people replied as well, with why & how they'll use it. Read the replies to get a sense of how people feel.

People want this element. They will use it. They've been waiting a really long time. And they are going to be really frustrated if we don't have interop.

**Comment by foolip** [comment]
> More than that, however, the _number_ of people who answered the poll tells me a lot. Over 2,000 people answered in 24 hours — which is far more than my quick informal twitter polls usually get.

Thanks for pointing this out, I agree that's a strong signal in itself.

> We should make sure we use modern tests that match the HTML spec version that Mozilla & Apple are endorsing, and not the older version from the past that isn't accessible. IOW, I'm not sure that older tests are testing the right version of the spec.

Do you know which spec changes were made around this? The WHATWG working mode involves adding tests, so PRs like https://github.com/web-platform-tests/wpt/pull/31523 might have made the necessary changes.

**Comment by foolip** [comment]
@nt1m thanks, I've asked internally about that PR and if there are any other `<dialog>` issues related to focus or accessibility that need attention. Do you know of others, or is some resolution of https://github.com/whatwg/html/pull/4184 the only outstanding issue here?

**Comment by josepharhar** [comment]
> We should make sure we use modern tests that match the HTML spec version that Mozilla & Apple are endorsing, and not the older version from the past that isn't accessible. IOW, I'm not sure that older tests are testing the right version of the spec.

The only WPT which is explicitly concerned with the behavior in the [proposed spec change](https://github.com/whatwg/html/pull/4184) is [show-modal-focusing-steps.html](https://wpt.fyi/results/html/semantics/interactive-elements/the-dialog-element/show-modal-focusing-steps.html).

I [made a patch](https://chromium-review.googlesource.com/c/chromium/src/+/3312914) for the proposed change in chromium based on [the firefox one](https://phabricator.services.mozilla.com/D109950) in order to find out which WPTs would also fail, and I found that [these tests also fail](https://test-results.appspot.com/data/layout_results/linux-rel/869772/blink_web_tests%20%28with%20patch%29/layout-test-results/results.html):
- dialog-focus-shadow.html
- dialog-cancel-with-select.html
- dialog-showModal.html
- inert-node-is-unfocusable.html
- shadowdom-in-dialog.html

These tests aren't necessarily concerned with the proposed focus changes, and perhaps could even be changed to pass regardless of which focus behavior is implemented. Some have many subtests where only one fails with the proposed changes.

**Comment by nt1m** [comment]
I think we can probably just use `autofocus` on tests unrelated which rely on focusing the first item.

**Comment by josepharhar** [comment]
I have opened PRs to migrate the rest of the chrome-only dialog tests to WPT:
- https://github.com/web-platform-tests/wpt/pull/31789
- https://github.com/web-platform-tests/wpt/pull/31864
- https://github.com/web-platform-tests/wpt/pull/31887
- https://github.com/web-platform-tests/wpt/pull/31889
- https://github.com/web-platform-tests/wpt/pull/31891

**Comment by josepharhar** [comment]
All of the dialog tests from my last comment have been merged!
If there any issues with any of them I'm happy to address them, but we can at least collect the test names now.
@foolip

**Comment by foolip** [comment]
Thanks @josepharhar! I've labeled all the tests (I think!) and you can see them here:
https://wpt.fyi/results/html/semantics/interactive-elements/the-dialog-element?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-rfc

**Comment by nt1m** [comment]
dialog-focusing-steps-inert.html and dialog-inert.tentative.html should be unlabeled, they test the `inert` attribute which isn't in the HTML spec yet.

**Comment by foolip** [comment]
@nt1m done in https://github.com/web-platform-tests/wpt-metadata/pull/2303

**Comment by nt1m** [comment]
Can these 2 tests be labeled? https://github.com/web-platform-tests/wpt/commit/b3958a2b77988a3e4c6948dfce1b62f7b0ab04cf

They test `::backdrop` + animation

**Comment by foolip** [comment]
@nt1m I've labeled those in https://github.com/web-platform-tests/wpt-metadata/pull/2327

**Comment by foolip** [comment]
A proposed list of tests has been labeled with [`interop-2022-dialog`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-dialog). It would be great if someone from each browser engine team can look over this list and comment if there are any issues.

**Comment by josepharhar** [comment]
I just looked through the tests, and it seems that `modal-dialog-scroll-height.html` fails in all browsers even though it passes locally for me with `content_shell` and `chrome`... maybe there is something different about the machines that wpt.fyi runs on?
`inert-label-focus.html` also has a weird error, it says `MISSING` in chrome and firefox.
I added both of these tests when I upstreamed the chrome dialog tests.

**Comment by emilio** [comment]
(Same about `modal-dialog-in-table-column.html`... seems dubious at least that should work. For context they come from https://bugs.webkit.org/show_bug.cgi?id=103477)

**Comment by nt1m** [comment]
I fixed inert-label-focus.html in https://github.com/web-platform-tests/wpt/pull/32308.

- `focus-after-close.html` WebKit failure: not directly due to the dialog implementation, but rather because of [intentional WebKit special scrolling behavior](https://bugs.webkit.org/show_bug.cgi?id=181575). It could be rewritten to make waiting for scrolling asynchronously, but not sure how to do that right (maybe @rniwa could take a look if they have time).
- `modal-dialog-in-replaced-renderer.html` & `modal-dialog-in-table-column.html`: I agree with emilio here, this isn't really specified in the top layer spec. The tests were added in an older WebKit implementation (which has since been reverted).
- `modal-dialog-scroll-height.html`: needs investigation/removal since it fails in all 3 browsers.

The rest seem like genuine bugs in WebKit.

**Comment by emilio** [comment]
> I'm technically on PTO, but from a quick look the tests that Firefox fail are about backdrop-animation (which is sort - of unrelated to dialog, it's about ~every non-element backed pseudo in Gecko, and affects `:fullscreen` too).

Well given this is `<dialog>` and `::backdrop` these are legit I suppose :-)

**Comment by josepharhar** [comment]
I'll contact the author of `modal-dialog-scroll-height.html` and see if we can test the same behavior without the exact height expectation thats causing the failure

**Comment by foolip** [comment]
I've sent https://github.com/web-platform-tests/wpt-metadata/pull/2352 to drop modal-dialog-scroll-height.html from Interop 2022. If another test can be added to test the same thing in a better way soon, maybe we can include that.

**Comment by josepharhar** [comment]
I believe I found a way to fix modal-dialog-scroll-height.html by replacing the hard coded height with window.innerHeight:
https://chromium-review.googlesource.com/c/chromium/src/+/3379191
https://github.com/web-platform-tests/wpt/pull/32319

**Comment by josepharhar** [comment]
@foolip Can you put modal-dialog-scroll-height.html back on the list? The new version is passing in all browsers: https://wpt.fyi/results/html/semantics/interactive-elements/the-dialog-element/modal-dialog-scroll-height.html

**Comment by nt1m** [comment]
Done: https://github.com/web-platform-tests/wpt-metadata/pull/2399/

**Comment by foolip** [comment]
One test came up in my analysis in https://github.com/web-platform-tests/interop-2022/issues/48. It looks like a solved problem, but quoting for visibility:

> [/html/semantics/interactive-elements/the-dialog-element/backdrop-receives-element-events.html](https://wpt.fyi/results/html/semantics/interactive-elements/the-dialog-element/backdrop-receives-element-events.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is TIMEOUT in Safari with the single subtest being NOTRUN. It's linked to https://webkit.org/b/233072 which was recently fixed, confirmed with [Safari + WebKitGTK](https://wpt.fyi/results/html/semantics/interactive-elements/the-dialog-element/backdrop-receives-element-events.html?run_id=6276661696790528&run_id=5083300671520768).

**Comment by criskrzysiu** [comment]
What about `:modal` pseudoclass?
https://chromestatus.com/feature/5192833009975296
https://www.w3.org/TR/selectors-4/#modal-state

**Comment by foolip** [comment]
@criskrzysiu that's newer than Interop 2022, and changes to the tests we include for scoring need to be reviewed, so that the target doesn't change much throughout the year.

But we have both added and removed tests, for various reasons. If you want to suggest that, you can file a new issue in this repo. Whether everyone is on board with it probably depends mostly on whether they already intend to ship `:modal` this year.

**Comment by jgraham** [comment]
Without knowing anything about Gecko's plans here, I don't like the idea of making major changes to the scope of a focus area during the year. I think test additions / removals should be scope-neutral and only used to address issues of correctness or completeness within the agreed boundaries of the focus area.

**Comment by criskrzysiu** [comment]
Turns out there already is test that checks for `:modal` introduced by this PR https://github.com/web-platform-tests/wpt/pull/34107/files

**Comment by criskrzysiu** [comment]
update - `:modal` is shipping in Chrome106 [Chromestatus](https://chromestatus.com/feature/5192833009975296)
