### ISSUE TITLE
[charter] How to request to join

### ISSUE THREAD

**Issue by karlcow** [web-platform-tests/interop#124]
How does an organization request to join? Open an issue? A Template?

**Comment by foolip** [comment]
I wasn't sure what to write here, so I guess people reading it also won't know :)

I think the simplest answer is a pull request on this repo, would that do? It would be nice if the charter isn't overly dependent on how we're managing our documents.

**Comment by foolip** [comment]
This is defined in https://github.com/web-platform-tests/interop/pull/102 now as emailing interop@web-platform-tests.org. That address does not exist, and if it's not trivial to configure, we should use some other email or means of private communication.
