### ISSUE TITLE
Agenda for Aug 31 meeting

### ISSUE THREAD

**Issue by robnyman** [web-platform-tests/interop#126]
_Note: this meeting is in an APAC-friendly time_

What we'd like to discuss is:

- The [information for public proposals](https://www.google.com/url?q=https://github.com/web-platform-tests/interop/pull/115&sa=D&source=calendar&ust=1662271205985380&usg=AOvVaw1kcYGGZeWsNosjs0rplsNS) ([file view](https://www.google.com/url?q=https://github.com/web-platform-tests/interop/blob/c0854004f009530480b89647a6519e2cdb892e64/2023/README.md&sa=D&source=calendar&ust=1662271205985380&usg=AOvVaw1PWQOlA-RrvSR6kjiw-caT)) 
- The [charter](https://www.google.com/url?q=https://github.com/web-platform-tests/interop/pull/102&sa=D&source=calendar&ust=1662271205985380&usg=AOvVaw2WwX4xDAEAzOQN4u0O14QJ) ([file view](https://www.google.com/url?q=https://github.com/web-platform-tests/interop/blob/876c6edcf1a223a20a38e27b5caf59444d80058a/charter.md&sa=D&source=calendar&ust=1662271205985380&usg=AOvVaw0xNm5emQtqxqdndc0RsuiG))
- _Tip: Philip posted [a nice tip for Tip on reviewing markdown on GitHub](https://www.google.com/url?q=https://github.com/web-platform-tests/interop/issues/120&sa=D&source=calendar&ust=1662271205985380&usg=AOvVaw2t9c4Pm1w3NlYt8Ycx0bDT)_

This discussion is completely optional, and if you are interested in talking more about these topics, you are more than welcome!

Looking forward to talking more!

**Comment by foolip** [comment]
These are the issues we need to resolve for the charter:
- https://github.com/web-platform-tests/interop/issues/121
- https://github.com/web-platform-tests/interop/issues/122
- https://github.com/web-platform-tests/interop/issues/123
- https://github.com/web-platform-tests/interop/issues/124

For https://github.com/web-platform-tests/interop/pull/115, the main issue is documenting investigation effort proposals, in particular what advice we should give for defining the investigation scope, and how liaising with standards groups should work.

**Comment by foolip** [comment]
_Meeting notes_

Present: @foolip @karlcow @robnyman

### [How to request to join](https://github.com/web-platform-tests/interop/issues/124)

@karlcow: Point of contact via email, or open issue in repo? Has anyone new requested to join yet?
@foolip: No, we formed the group last year, and haven't had requests to join. Risk of having a totally open process to join is that anyone can join and oppose everything. Not likely, but an unnecessary risk.
@robnyman: For Open Web Docs, we have a Governing Committee and Steering Committee split. The SC can jointly decide to invite more members.
@karlcow: One model is that the team can invite new members, as opposed to others requesting to join.
@foolip: Looking at what we have right now, and we just define how to request to join, would that be OK with everyone? Public or private request?
@karlcow: Private would be better.
@foolip: Do we set up interop@web-platform-tests.org? Who owns the domain again?
@gsnedders That's @jgraham.

Resolution: Define that a request to join is sent to a joint email address. Leaving by request or consensus.

**Comment by foolip** [comment]
For anyone following links to traverse meetings, this meeting was between https://github.com/web-platform-tests/interop/issues/118 and https://github.com/web-platform-tests/interop/issues/127.
