### ISSUE TITLE
Agenda for September 8th Meeting

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/interop#128]
* Admin:
  - Need someone to take notes so they end up in this GH issue.
* Expect Interop 2023 Proposals period to start in 1 week:
  - #115 review/merge required before opening proposals period
  - Any other blockers?
  - Accept Test262 submissions in proposals?
  - Plans around communication / getting proposals from a wider audience?
* Interop team charter
  - https://github.com/web-platform-tests/interop/pull/102
* How to handle previous Interop metrics on the web site?
 * Interop 2022 progress reports
 * Proposed test changes:
   - https://github.com/web-platform-tests/interop/issues?q=is%3Aissue+is%3Aopen+label%3Atest-change-proposal

**Comment by jgraham** [comment]
* Expect Interop 2023 Proposals period to start in 1 week: 

jgraham: We have an open PR to document the process. Some open comments. Need to get that landed to kick off the process.
Simon: Easier to read with the rich diff.
jgraham: Two main parts, a README and an issue template.
Tantek: How does the schedule compare to last year?
Jen: This is earlier than last year. We didn't get all the proposals by the deadline last year and we didn't announce until March.
Tantek: Also the Ukraine invasion caused a delay. We need a critical mass of proposals to launch and I don't know if that's captured in the process document. Last year we had to extend the deadlines to get a viable project. Should we suggest that the deadline can be extended?
Jen: I hope we take the deadline more seriously this year, and the experience from last year will help us hit the ground running. We are already thinking about possible proposals.
Tantek: I agree with that overall assessment. Now that we have practice we should be able to frontload high-level thinking. If we think there's no risk of having insufficient proposals that's fine, but we don't have a minimum bar.
Jen: I think this is missing a clear introduction for external people to give what's expected. I can volunteer to write a paragraph explaining that context and which proposals will help us meet those goals. Want to avoid getting proposals from people with a very different idea about what the scope is.
Tantek: I agree that would be useful. https://wpc.guide/skills/#testing is quite welcoming. We might need a bridge between that and interop work. What do others think?
Simon: Sounds like a good idea.
jgraham: Please get issues on the PR asap so that we can get feedback incorporated.
Tantek: Breakaout session at TPAC for launch?
Simon: I will be remote
Jen: +1 to remote
jgraham: I think it makes sense to have one, but foolip also won't be there in person.
Simon: Are we planning any blog posts for the launch?
Jen: Apple aren't planning a blog post. Often marketing efforts are about getting a large group of people taking action. Last year proposals (all?) came from the orgs who are working on this effort. It's really about browser developers comining together. Open to having other people submit, but we don't necessarily want to strive for the most possible submissions. I think we should write blog posts at the end of the year to let developers know we care about their problems and show the work we've done to improve it.
Tantek: I agree there's a concern that we might be overwhelmed by proposals. Don't think it would be useful to have to do a lot of proposal triage. Might want to add more to the README to discourage out of scope proposals, e.g. things in incubation.
jgraham: The proposal template has a list of allowed standards orgs/tracks, but also an exception. We could remove that from the template since people who could reasonably get an exception are probably insiders.
Tantek: Yes, people involved enough to propose something in incubation can also get the proposal onto a standards track.
Simon: In the template we could also ask for a list of wpt tests as part of the initial proposal.
Chris: That's already in the template. We're running close to the timeline we wanted. Can we get this done?
Jen: I do think that we should have the introductory paragraph to ensure we minimise the number of inappropriate proposals.
Chris: Could we land this PR with a note to say it's not totally finalised? I agree that content sounds good.
Jen: Let's land the PR and then make changes.
Tantek: Agreed.
Chris: I'll ask foolip to do it when he's back tomorrow.
jgraham: Do we accept Test262 submissions?
Simon: Could we use Test262 report as a way to get the results?
jgraham: Only if we can integrate that with wpt.fyi in some way.
Jen: We really need to be able to include the results in the dashboard. Not confident that we will manage that in time if we don't have a clear plan.
Chris: Not sure if there's a specific feature we have in mind for this. Would need to be a compelling proposal.
Jen: Investigate projects are still at 0% scoring. What's the status there? Would really like to see some non-zero scores there. Hard to explain that the metrics scores are still out of 90. 
jgraham: Yes. For editing there's progress, but we haven't agreed a score yet.
Jen: Would be good to resolve proposed test changes, so please take a look.
Tantek: Chris can you coordinate with foolip about proposing in interop session for TPAC?
Chris: Yes.

**Comment by foolip** [comment]
I've suggested the TPAC breakout session here:
https://www.w3.org/wiki/TPAC/2022/SessionIdeas#Interop_2023
