### ISSUE TITLE
Tag `parsing/color-mixed-num-pct.html` as Interop2022

### ISSUE THREAD

**Issue by svgeesus** [web-platform-tests/interop#129]
### Test List

https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-mixed-num-pct.html

### Rationale

I wrote this test because mixtures of `<number>`, `<percentage>` and `none` in the `color()` function were allowed per spec but untested. This falls into the Color section of Interop2022, so the tag needs to be added and I don't know how to do it.

**Comment by svgeesus** [comment]
Ok I discovered triage mode, here is the PR
https://github.com/web-platform-tests/wpt-metadata/pull/2986

**Comment by jgraham** [comment]
Hmm that got auto-merged, but we generally require explicit confirmation that it's OK to add a test to an existing interop focus area.

@emilio might be a good person to comment on behalf of Gecko.
@jensimmons @foolip can you look for someone who can make a call for WebKit and Blink?

**Comment by jgraham** [comment]
I've reverted the metadata change for now; apologies for the confusion.

**Comment by svgeesus** [comment]
Sorry, I had expected the PR to get reviewed not auto-approved.

This test is similar to css-color/parsing/color-valid.html and css-color/parsing/color-invalid.html, which are already tagged, but is more thorough in testing all combinations.

**Comment by jensimmons** [comment]
Discussing it with folks here, we think including this test in Interop 2022 is a good idea.

**Comment by foolip** [comment]
@lilles can you review this for Chromium?

**Comment by lilles** [comment]
sgtm

**Comment by emilio** [comment]
Agreed this should be included.

**Comment by foolip** [comment]
Alright, I think we have consensus in the form of support from each browser engine.

**Comment by foolip** [comment]
I've labeled the test in https://github.com/web-platform-tests/wpt-metadata/pull/3019.
