### ISSUE TITLE
:has() pseudo-class

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/interop#134]
### Description

The :has() pseudo-class fulfills the decades-long desire for a "parent selector", while adding even more power to CSS. 

`:has( )` allows other selectors as arguments, including :pseudo-classes. Exactly which :pseudo-classes are supported is likely not yet 100% interoperable. As of the writing of [this article](https://webkit.org/blog/13096/css-has-pseudo-class/), for example, Safari supports: :nth-child, :nth-last-child, :first-child, :last-child, :only-child, :nth-of-type, :nth-last-of-type, :first-of-type, :last-of-type, :only-of-type, :modal, :target. And does not yet support dynamic media pseudo-classes like :playing, :paused, :muted, etc. It would be useful to align browsers on which :pseudo-classes are supported.

Pseudo-elements should [not be allowed](https://github.com/w3c/csswg-drafts/issues/7463) inside :has(). And there are other disallowed things, including :has() — you cannot create :has(:has()). Making sure browsers are interoperable on what they disallow is also useful for web developers. 

There is no part of the definition of :has() that should not be included in Interop 2023. 

### Rationale

[Listed as number two in 2021 State of CSS](https://2021.stateofcss.com/en-US/opinions/#currently_missing_from_css_wins)

### Specification

https://drafts.csswg.org/selectors-4/#relational

### Tests

Existing tests:
- [has-argument-with-explicit-scope.html](https://wpt.fyi/results/css/selectors/has-argument-with-explicit-scope.html?label=experimental&label=master&aligned)
- [has-basic.html](https://wpt.fyi/results/css/selectors/has-basic.html?label=experimental&label=master&aligned)
- [has-error-recovery.html](https://wpt.fyi/results/css/selectors/has-error-recovery.html?label=experimental&label=master&aligned)
- [has-matches-to-uninserted-elements.html](https://wpt.fyi/results/css/selectors/has-matches-to-uninserted-elements.html?label=experimental&label=master&aligned)
- [has-relative-argument.html](https://wpt.fyi/results/css/selectors/has-relative-argument.html?label=experimental&label=master&aligned)
- [has-specificity.html](https://wpt.fyi/results/css/selectors/has-specificity.html?label=experimental&label=master&aligned)
- [has-visited.htm](https://wpt.fyi/results/css/selectors/has-visited.html?label=experimental&label=master&aligned)

More tests may be needed, ~~including for invalidation.~~

**Comment by lilles** [comment]
There's a massive amount of invalidation tests for :has() in https://wpt.fyi/results/css/selectors/invalidation

**Comment by jensimmons** [comment]
It would be great to help update the MDN BDC data for `:has()`, so pseudo-class support is enumerated for each possibility, like `:has(:target)`.

**Comment by foolip** [comment]
> It would be great to help update the MDN BDC data for `:has()`, so pseudo-class support is enumerated for each possibility, like `:has(:target)`. That will help web developers know what works where, and avoid confusing bugs.

@jensimmons can you file an issue at https://github.com/mdn/browser-compat-data/issues? That sounds valuable, but I think some guidance is needed to get it right. In particular, what the distinct possibilities are, is `:target` special or is it all pseudo-classes, and so on...

**Comment by jensimmons** [comment]
@foolip Good idea. Done: https://github.com/mdn/browser-compat-data/issues/17818 

`:target` is not special. It's just top of mind.

**Comment by Westbrook** [comment]
Support `:host(:has(...))`!!!

**Comment by foolip** [comment]
Adding to the rationale, `:has()` was one of the most common responses the State of CSS 2022 question about browser incompatibilities, ~19% of the question responses, see https://github.com/web-platform-tests/interop/issues/248.

**Comment by foolip** [comment]
Thank you for proposing `:has()` for inclusion in Interop 2023.

We are pleased to let you know that this proposal was accepted as the `:has()` focus area. You can follow the progress of this Focus Area on the [Interop 2023 dashboard](https://wpt.fyi/interop-2023).

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you for contributing to Interop 2023!

_Posted on behalf of the Interop team._
