### ISSUE TITLE
`inert` attribute + `:modal` pseudo-class

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/interop#135]
### Description

The `:modal` pseudo-class targets a dialog when it's in an open state.

The `inert` attribute provides web developers with a way to make an element inert, similar to the content behind a `dialog` — useful for situations that do not involve dialog.

It might make sense to add these two items to the dialog focus area. Or perhaps not, and put them someplace else.  

### Rationale

These two features, `inert` and `:modal` feel like work that was done to round out `dialog` and make sure web developers have all of what they need to accessibly provide this kind of interactive UI. Adding these to Interop 2023 ensures such details are implemented fully interoperable. 

### Specification

Inert in HTML: https://html.spec.whatwg.org/multipage/interaction.html#the-inert-attribute

:modal in CSS: https://w3c.github.io/csswg-drafts/selectors-4/#modal-state

### Tests

Existing tests:
- [modal-pseudo-class.html](https://wpt.fyi/results/css/selectors/modal-pseudo-class.html?label=experimental&label=master&aligned)

More tests are needed.

**Comment by jensimmons** [comment]
[Inert tests](https://wpt.fyi/results/inert?label=experimental&label=master&aligned&view=subtest)

**Comment by gsnedders** [comment]
> Existing tests:
> 
> * [modal-pseudo-class.html](https://wpt.fyi/results/css/selectors/modal-pseudo-class.html?label=experimental&label=master&aligned)

https://wpt.fyi/results/css/selectors?label=master&label=experimental&aligned&view=subtest&q=modal shows there's also one in `invalidation` (albeit combined with `:has`, #134). If we accept both proposals, we'll need to decide which (or both!) of the focus areas to count that test towards.

**Comment by foolip** [comment]
Thank you for proposing `inert` and `:modal` for gradients for inclusion in Interop 2023.

We are pleased to let you know that this proposal was accepted as part of the Inert and CSS Pseudo-classes focus areas. You can follow the progress of these Focus Areas on the [Interop 2023 dashboard](https://wpt.fyi/interop-2023).

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you for contributing to Interop 2023!

_Posted on behalf of the Interop team._
