### ISSUE TITLE
Issues with images?

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#136]
This isn't a propsal, just a discussion.

In https://www.w3.org/2022/09/14-interop-minutes.html @ydaniv said:

> Huge demand for SVG. Images are also a problem. Features like loading attribute. It's important to get this 100% across browsers. AVIF shipped in Safari, could be a chance to get servers to start transcoding to AVIF. Bugs can hurt performance.

@ydaniv I wonder if you have more information about images, to understand if a general "Images" focus area could make sense. Does the `loading` attribute not work properly across browsers still? (It [seems to be](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#browser_compatibility) supported.) Are there other issues around images you had in mind?

**Comment by ydaniv** [comment]
Thanks @mathiasbynens, +1!

@foolip the issue that was on my mind at the time was [this bug with `loading=lazy` in Webkit](https://bugs.webkit.org/show_bug.cgi?id=237703) which prevents from using this feature altogether.
So it's bugs like this which cause interop headaches, but I'm not sure I can think of anything interesting here, interop-wise, since this is quite a specific scenario.
And `fetchpriority` doesn't look like something that can actually block anything critical.

So I gave this another thought (w/ @eportis-cloudinary - anything to add?), maybe nothing actionable at this point, besides the above, and random specific engine issues.

**Comment by foolip** [comment]
@ydaniv it looks like that bug was fixed just 7 days ago in https://github.com/WebKit/WebKit/commit/0c40ba62b482511fe03646f1d4982efd727475dd. I'd guess that it'll be in the next Safari Technology Preview, but you'd have to read release notes ([like these](https://webkit.org/blog/13148/release-notes-for-safari-technology-preview-153/)) to know for sure. If you have the possibility, perhaps you could re-test this in the next release of STP?

**Comment by gsnedders** [comment]
Let's label this as a focus area proposal despite it being kinda undefined so we don't forget about this.

**Comment by mathiasbynens** [comment]
> WPT covers animated AVIF in the `ImageDecoder` tests: https://wpt.fyi/results/webcodecs/image-decoder.https.any.html?label=experimental&label=master&aligned (Subtests: “Test multi-track AVIF image decoding”) However, since `ImageDecoder` is not universally available yet, it would be nice to have some tests that do not depend on `ImageDecoder` as well, perhaps following the example in https://github.com/web-platform-tests/wpt/tree/master/apng.

**Update:** It looks like we can’t “just” follow the APNG example. That test relies on last frame being shown after a certain timeout, which depends on the animation not looping — but AVIF animations always loop indefinitely.

**Comment by foolip** [comment]
@mathiasbynens can we have a very long animated AVIF? If variable frame length isn't possible, then just 1 red frame and lots of green ones? A total of 10 seconds or so should do it.

**Comment by ydaniv** [comment]
@foolip sure, we're on it, hoping this will be in 16.1

**Comment by mathiasbynens** [comment]
> @mathiasbynens can we have a very long animated AVIF? If variable frame length isn't possible, then just 1 red frame and lots of green ones? A total of 10 seconds or so should do it.

https://github.com/web-platform-tests/wpt/pull/36044

**Comment by styfle** [comment]
And this Firefox [white background while loading image bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1556156)l which is not fixed. Its very noticeable for websites with dark backgrounds.

**Comment by mathiasbynens** [comment]
Interop 2023 proposals relevant to this topic:

- https://github.com/web-platform-tests/interop/issues/176
- https://github.com/web-platform-tests/interop/issues/182

**Comment by foolip** [comment]
I'll go ahead and close this issue, as it's not a full proposal. If anyone has image-related features they'd like to suggest for Interop 2023, please see https://github.com/web-platform-tests/interop/blob/main/2023/README.md for the process.

**Comment by jzern** [comment]
> > WPT covers animated AVIF in the `ImageDecoder` tests: https://wpt.fyi/results/webcodecs/image-decoder.https.any.html?label=experimental&label=master&aligned (Subtests: “Test multi-track AVIF image decoding”) However, since `ImageDecoder` is not universally available yet, it would be nice to have some tests that do not depend on `ImageDecoder` as well, perhaps following the example in https://github.com/web-platform-tests/wpt/tree/master/apng.
> 
> **Update:** It looks like we can’t “just” follow the APNG example. That test relies on last frame being shown after a certain timeout, which depends on the animation not looping — but AVIF animations always loop indefinitely.

Looping with animated AVIF should be controllable with an edit-list, as defined by MIAF.
