### ISSUE TITLE
Remove scroll-target-align-001.html & scroll-target-align-002.html

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#137]
### Test List

* css/css-scroll-snap/scroll-target-align-001.html
* css/css-scroll-snap/scroll-target-align-002.html

### Rationale

@nmoucht investigated, and found that this is testing an optional feature from the spec.

"If a page is navigated to a fragment that defines a target element (e.g. one that would be matched by [:target](https://www.w3.org/TR/selectors-4/#target-pseudo), or the target of scrollIntoView()), and that element defines some [snap positions](https://www.w3.org/TR/css-scroll-snap-1/#scroll-snap-position), the user agent must [snap](https://www.w3.org/TR/css-scroll-snap-1/#scroll-snap) to one of that element’s snap positions if its nearest [scroll container](https://www.w3.org/TR/css-overflow-3/#scroll-container) is a [scroll snap container](https://www.w3.org/TR/css-scroll-snap-1/#scroll-snap-container). The user agent may also do this even when the scroll container has [scroll-snap-type: none](https://www.w3.org/TR/css-scroll-snap-1/#propdef-scroll-snap-type)."

The tests are testing the last sentence which has "may" which suggests this is optional.

In fact, both tests have `<meta name="flags" content="may">` in the code.

**Comment by nt1m** [comment]
cc @flackr @hiikezoe @theres-waldo

**Comment by hiikezoe** [comment]
@nt1m I wonder why scroll-target-align-003.html is out of the candidates, it also has `<meta name="flags" content="may">`.

**Comment by nt1m** [comment]
It was passing in WebKit so we didn't look at it closely, but yes, if it is for an optional feature, we should remove it from Interop 2022. The assert does suggest that the test is for the same feature.

**Comment by nt1m** [comment]
I think we can close this and re-open if there's any objection.
