### ISSUE TITLE
Review css/css-sizing/aspect-ratio/flex-aspect-ratio-004.html

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#139]
### Test List

* [css/css-sizing/aspect-ratio/flex-aspect-ratio-004.html](https://wpt.fyi/results/css/css-sizing/aspect-ratio/flex-aspect-ratio-004.html)

### Rationale

Not suggesting anything specific here, but mostly a review of that test, given it fails in the same identical way across the 3 engines.

cc @davidsgrogan @aethanyc who are the authors of this test.

**Comment by foolip** [comment]
This is the actual screen in all browsers:

![image](https://user-images.githubusercontent.com/498917/191530511-d332e540-0246-4b86-abf6-c715c703b9ae.png)

**Comment by davidsgrogan** [comment]
This is subject to the ongoing discussion in https://github.com/w3c/csswg-drafts/issues/6794

**Comment by nt1m** [comment]
The CSSWG issue seems to have a resolution and is closed, do the tests need to be updated?

**Comment by davidsgrogan** [comment]
It has a resolution for an ancillary point. The underlying issue is not resolved. See the very bottom of the IRC log:
```
<heycam> Rossen: still not hearing a concrete path forward here
<heycam> ... I think this would benefit from some whiteboarding
```

**Comment by foolip** [comment]
We talked about this briefly in https://github.com/web-platform-tests/interop/issues/140. @davidsgrogan, to ensure the CSSWG are aware of this specific issue, can you describe it in https://github.com/w3c/csswg-drafts/issues/6794, or file a new one if it's not quite the right issue?

We'll probably keep this issue open until the spec discussion has happened, but if it takes a very long time we'll probably drop the test from Interop 2021.

**Comment by davidsgrogan** [comment]
I looked at this test some more. Both of the competing spec proposals in https://github.com/w3c/csswg-drafts/issues/6794 dictate this test's rendering to match all the current implementations. So I will just change the test to match all current implementations. (Yay!)

But both proposals also make flex-aspect-ratio-002.html's rendering match Firefox's rendering, not Blink and WebKit's. Currently Blink and WebKit pass flex-aspect-ratio-002.html and Firefox fails it.

So when I change -004 to match the behavior dictated by both proposals, then following the exact same principle, I'll change -002 to match the behavior dictated by both proposals.

This will result in no net score difference for Blink and WebKit and a minor score increase for Firefox.

-002 and -004 test the same idea, just that -002 is for row flexboxes and -004 is for column flexboxes.

Firefox's behavior in -002 is what the spec authors originally intended. There are no champions for the Blink/WebKit behavior among the commenters in https://github.com/w3c/csswg-drafts/issues/6794.

As for mentioning this case in the WG issue, the CSSWG is already well aware of it. There are just competing proposals how to best fix it, with debate around the effects each proposal would have on cases other than -002 and -004.

**Comment by foolip** [comment]
Since the test now passes in all browsers I'll go ahead and close this. @nt1m please reopen if you think there's more we need to do here.
