### ISSUE TITLE
URL Standard – `new URL()`

### ISSUE THREAD

**Issue by annevk** [web-platform-tests/interop#145]
### Description

Let's make 2023 the year all browsers agree on a fundamental piece of the web: URLs as defined in the [URL Standard](https://url.spec.whatwg.org).

### Rationale

URLs are extremely widely used and as such would benefit from being fully interoperable.

Developers have also complained that `new URL()` doesn't work the same across browsers and doesn't always give the expected results for non-special schemes (e.g., non-WebKit browsers tend to stuff everything in the path).

### Specification

https://url.spec.whatwg.org

### Tests

https://wpt.fyi/results/url

**Comment by tbondwilkinson** [comment]
URL compat is a P2 for Google's [closure library](https://github.com/google/closure-library).

"Could turn down goog.url and possibly help further migration off of goog.uri."

**Comment by foolip** [comment]
In the [MDN short survey on APIs & JavaScript](https://github.com/web-platform-tests/interop/issues/246), "URL (parsing and API)" was selected by ~21% of survey takers, putting it in the top third of options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/246#issuecomment-1312098410) as with any survey data.)

**Comment by gsnedders** [comment]
From https://github.com/web-platform-tests/interop/issues/253:

> [@foolip] URLs - using variants to https://github.com/web-platform-tests/wpt/pull/37372 out the tests (file:, mailto: and javascript:) that were deemed to be too risky.

**Comment by nairnandu** [comment]
Thank you for proposing URL standard for inclusion in Interop 2023.

We are pleased to let you know that this proposal was accepted as the URL focus area. You can follow the progress of this Focus Area on the [Interop 2023 dashboard](https://wpt.fyi/interop-2023).

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you for contributing to Interop 2023!

_Posted on behalf of the Interop team._
