### ISSUE TITLE
Machine Learning in the Browser

### ISSUE THREAD

**Issue by AmitMY** [web-platform-tests/interop#152]
### Description

Access to tensor-accelerators such as GPUs or TPUs  is fragmented and lacking cross browser support.
Running machine learning models, I am using WebGPU on Chrome Canary, WebGL on Chrome stable, WebGL on Safari's main thread, but not Worker thread, where I have to use WASM, etc...

### Rationale

Machine learning is the future of software development.
However, nowadays support is fragmented, and runtime is extremely slow.

### Specification

- https://www.w3.org/TR/webnn/
- https://www.w3.org/TR/webgpu/
- https://caniuse.com/offscreencanvas

### Tests

- https://wpt.fyi/results/html/canvas/offscreen/2d.conformance.requirements.basics.html?label=experimental&label=master&aligned
- https://wpt.fyi/results/webnn/idlharness.https.any.html?label=master&label=experimental&aligned
- WebGPU tests are missing

**Comment by foolip** [comment]
Thanks for submitting a proposal, @AmitMY!

It looks like this proposal overlaps with https://github.com/web-platform-tests/interop/issues/161 for OffscreenCanvas and https://github.com/web-platform-tests/interop/issues/185 for WebGPU. (Although note that WebGPU is a Investigation Effort proposal, since there are no tests.)

If WebNN is the missing piece, I would suggest filing a proposal for just that. What do you think?

**Comment by nairnandu** [comment]
Thank you for proposing Machine Learning in the Browser for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. We had many strong proposals, and could not accept them all. As mentioned in the issue comments, [WebGPU](https://github.com/web-platform-tests/interop/issues/185) and [OffscreenCanvas](https://github.com/web-platform-tests/interop/issues/161) were considered separately for Interop 2023. 

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
