### ISSUE TITLE
Progress reporting for 2022 Investigation

### ISSUE THREAD

**Issue by stof** [web-platform-tests/interop#157]
As of today, the 3 Investigation efforts of Interop 2022 are still at 0%. As a web developer not directly involved in the spec processes (and so not seeing the work being done in those areas directly if it is not communicated), this feels like "nothing has been done there", even though [I heard it is not the case](https://twitter.com/jensimmons/status/1567948002517549056). Analysing it further, it could be seen in several ways:

1. no progress has been made --> adding it as an Interop-2022 topic failed
2. the group doing work on that topic does not care about reporting progress for Interop-2022 --> adding it as an Interop-2022 failed from a communication point of view
3. there is a near-infinite amount of investigation to be done so any progress effectively represents 0% (by a rounding margin)

With Interop-2023 being in the planning, it would be great to sort out the state of the 2022 investigation efforts (or to reconsider the inclusion of investigation efforts in the interop score if this is expected to end up the same next year).

**Comment by foolip** [comment]
Hi @stof, thanks for raising this! You're absolutely right that we haven't been transparent about the progress of these investigation efforts. We did [recently](https://github.com/web-platform-tests/interop/issues/131) review the progress of the viewport investigation effort and decided to score it as 60%. That isn't reflected on the public dashboard however.

Getting this update is tracked by https://github.com/web-platform-tests/wpt.fyi/issues/2971, and I think that's the minimum that we should do.

Do you think it would be valuable to have something beyond the scores to explain what has been done?

**Comment by stof** [comment]
Having the dashboard updated is indeed the minimum I would expect.
At some point, a blog post showing the results of the investigation would be great too. But that could happen at the end of the year for instance (or whenever makes sense for that group).

**Comment by jgraham** [comment]
Since 2022 is over I'm going to close this.
