### ISSUE TITLE
Better support for `@property`

### ISSUE THREAD

**Issue by Afif13** [web-platform-tests/interop#158]
### Description

I will quote a few parts from the specification that should give clear description of the feature:

> [[css-variables]](https://drafts.css-houdini.org/css-properties-values-api/#biblio-css-variables) provides primitive means for defining user-controlled properties, however these properties always take token lists as values, must always inherit, and can only impact document layout or paint by being re-incorporated into the value of other properties via a var() reference.

> This specification extends [[css-variables]](https://drafts.css-houdini.org/css-properties-values-api/#biblio-css-variables), allowing the registration of properties that have a value type, an initial value, and a defined inheritance behaviour

```css
@property --size {
    syntax: "<length>";
    inherits: false;
    initial-value: 0px;
  }
```

### Rationale

* A better way to animate things: Registered custom properties allow us to animate almost anything. 

* Syntax validation: A non-registered custom property can contain any value which can easily lead to errors. A registered custom property follow a syntax and cannot accept any values. 

> A [custom property](https://drafts.csswg.org/css-variables-2/#custom-property) can become a registered custom property, making it act more like a UA-defined property: giving it a syntax that’s checked by the UA, an initial value, and a specific inheritance behavior.

* Better JavaScript manipulation: Unregistered custom properties are mainly strings so we are obliged to do an extra manipulation to get their data. With registered custom properties we no more have such issue. Below a screenshot to illustrate the difference:

![image](https://user-images.githubusercontent.com/14073250/192372839-ce2ebd0d-3d45-4b6a-a5b5-b8098bfdb5a3.png)

* Chromium browser support this feature since too long (https://ishoudinireadyyet.com/) which leads us to the famous "Chrome-only" demos so it would be good to have a better support for such feature

* It's part of the Houdini project so it closely linked to other features like the Paint API and the Layout API. 

>This specification is complementary to [[css-paint-api-1]](https://drafts.css-houdini.org/css-properties-values-api/#biblio-css-paint-api-1) and [[css-layout-api-1]](https://drafts.css-houdini.org/css-properties-values-api/#biblio-css-layout-api-1), which allow custom properties to directly impact paint and layout behaviours respectively.

### Specification

https://drafts.css-houdini.org/css-properties-values-api/

### Tests

https://wpt.fyi/results/css/css-properties-values-api?label=master&label=experimental&aligned&view=subtest&q=property

**Comment by Afif13** [comment]
Here an article where I am exploring the power of `@property` in creating complex animation without using keyframes: https://css-tricks.com/build-complex-css-transitions-using-custom-properties-and-cubic-bezier/

**Comment by Afif13** [comment]
Back in 2018, Ana Tudor (@thebabydino) explored Gradients animation using this feature: https://css-tricks.com/the-state-of-changing-gradients-with-css-transitions-and-animations/

More articles around this:
- https://dev.to/afif/we-can-finally-animate-css-gradient-kdk
- https://web.dev/at-property/
- https://css-tricks.com/what-houdini-means-for-animating-transforms/
- https://www.smashingmagazine.com/2020/03/practical-overview-css-houdini/

**Comment by lilles** [comment]
Regarding tests, I don't think we should filter out tests without "property".

We should exclude this test unless typed om also becomes part of Interop 2023: https://wpt.fyi/results/css/css-properties-values-api/typedom.html

The crashtests directory probably doesn't make sense to add (even if all engines would typically pass).

There are some subtests that rely on other features that engines don't necessarily ship. I recently added a cycle test for the lh unit in unit-cycles.html, for instance.

**Comment by andruud** [comment]
We may want to exclude tests which cover:

* Syntax:`<transform>`, `<transform-list>`, because we can't currently represent computed values of interpolated transforms which contain percentages. (It's possible with the newly added `mix()` function, but should probably not scope-creep that into this proposal).
* Syntax: `<image>`, unless we now have good specs for how generated images should interpolate. Last time a looked, we did _not_, but that's a while ago now.

**Comment by foolip** [comment]
Custom properties or variables came up a fair bit in the State of CSS 2022 question about browser incompatibilities, mentioned in ~2% of responses, see https://github.com/web-platform-tests/interop/issues/248. Examples from those responses:

- CSS custom properties
- Custom properties due to inability to use within media query declarations (i.e. `@media (min-width: var(--small)`)
- CSS custom properties and CSS grid for clients that need deeper browser support.
- Houdini (`@property`)
- `@property` is missing from Safari and Firefox.
- Custom Property Types
- css property registration

**Comment by foolip** [comment]
In the [MDN short survey on CSS & HTML](https://github.com/web-platform-tests/interop/issues/245), "CSS custom properties (`@property`)" was selected by ~28% of survey takers, putting it in the top third of the 20 options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/245#issuecomment-1311874383) as with any survey data.)

**Comment by foolip** [comment]
Thank you for proposing `@property` for inclusion in Interop 2023.

We are pleased to let you know that this proposal was accepted as the Container Queries focus area. You can follow the progress of this Focus Area on the [Interop 2023 dashboard](https://wpt.fyi/interop-2023).

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you for contributing to Interop 2023!

_Posted on behalf of the Interop team._

**Comment by SebastianZ** [comment]
> We are pleased to let you know that this proposal was accepted as the Container Queries focus area. 

I guess that meant Custom Properties, not Container Queries.

Sebastian

**Comment by foolip** [comment]
Yes, of course! Sorry about the copypasta.
