### ISSUE TITLE
OffscreenCanvas

### ISSUE THREAD

**Issue by fserb** [web-platform-tests/interop#161]
### Description

OffscreenCanvas allows for a faster graphics API that is detached from the Document. It also enables out-of-main-thread graphics API on WebWorkers. The support should include 2D, WebGL, and WebGPU support, both on main thread and on workers.

### Rationale

[OffscreenCanvas](https://chromestatus.com/metrics/feature/timeline/popularity/1624) on Workers has a pretty strong developer demand. We can see [tutorials](https://evilmartians.com/chronicles/faster-webgl-three-js-3d-graphics-with-offscreencanvas-and-web-workers) and [demos](https://threejs.org/examples/webgl_worker_offscreencanvas.html) all over the place. Developers [recognize](https://twitter.com/BenDelarre/status/1536413233929629696) and identify the multiple use cases: out of main thread rendering, and faster DOM-independent operations. OffscreenCanvas is also widely used inside Google.

On WASM codebases, it’s a necessary API to support out-of-main-thread rendering, which is common in games (with the WebGL context). 

For 2D context, the extra performance (a lot of operations are faster on OffscreenCanvas due to its independence from the Document and style) and the ability to step outside the main thread processing (which is often a contentious resource), makes it a widely used feature.

Firefox tracking bug: [OffscreenCanvas](https://bugzilla.mozilla.org/show_bug.cgi?id=1390089), [2D](https://bugzilla.mozilla.org/show_bug.cgi?id=801176).
WebKit tracking bug: [OffscreenCanvas](https://bugs.webkit.org/show_bug.cgi?id=183720).

### Specification

WHATWG relevant spec:
https://html.spec.whatwg.org/multipage/canvas.html#the-offscreencanvas-interface

The spec needs some refreshment that we are ready to work on and would do it sooner, if this gets picked up by Interop: we need to clean up the old commit() spec that doesn’t exist anymore, and write a new rendering model for Workers.

### Tests

Canvas2D: [wpt/html/canvas/offscreen](https://wpt.fyi/results/html/canvas/offscreen)
WebGL: [wpt/webgl](https://wpt.fyi/results/webgl)
WebGPU: [gpuweb/cts](https://github.com/gpuweb/cts/tree/main/src/webgpu/web_platform)

The coverage for 2D is pretty broad, including WebWorker, transferred OffscreenCanvas, and main thread. 
WebGL has a worker.js IDL test, but it seems to be missing on the repo.
WebGPU has only minor coverage on WPT. We would add at least some basic usage tests (not the full CTS).

**Comment by benjamind** [comment]
We at Adobe are strongly in support of adding this!

OffscreenCanvas is an essential capability for highly performant apps that do any sort of rendering.

**Comment by foolip** [comment]
In the [MDN short survey on APIs & JavaScript](https://github.com/web-platform-tests/interop/issues/246), "OffscreenCanvas" was selected by ~12% of survey takers, putting it in the bottom third of options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/246#issuecomment-1312098410) as with any survey data.)

**Comment by jgraham** [comment]
We think that this should exclude canvas filter tests, since that's just part of the normal canvas API that isn't directly related to offscreen canvas.

**Comment by foolip** [comment]
Thank you for proposing Offscreen Canvas for inclusion in Interop 2023.

We are pleased to let you know that this proposal was accepted as the Offscreen Canvas focus area. You can follow the progress of this Focus Area on the [Interop 2023 dashboard](https://wpt.fyi/interop-2023).

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you for contributing to Interop 2023!

_Posted on behalf of the Interop team._
