### ISSUE TITLE
Typed OM (houdini)

### ISSUE THREAD

**Issue by jsnkuhn** [web-platform-tests/interop#163]
### Description

from spec:

> Converting CSSOM value strings into meaningfully typed JavaScript representations and back can incur a significant performance overhead. This specification exposes CSS values as typed JavaScript objects, to make manipulating them both easier and more performant.

an explainer article from chrome: https://developer.chrome.com/blog/cssom/

### Rationale

Most painAPI demos (like those at houdini.how) accept only unitless values for custom properties. This is because unitless pixel values are what is needed for the JS worklet code. Not accepting normal CSS units like em/rem/% gets around having to parsing strings and convert values into unitless pixel values. This is currenly a pain to do.

TypedOM gives us JS objects instead of stings for CSS values that are much eaiser to work with. Makes it easier to seperate a value from its unit and covert from for example em to px.

I believe this requires registered custom properties so it works together with the Properties and Values API (i.e. @property)

Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1278697

### Specification

https://drafts.css-houdini.org/css-typed-om/

### Tests

https://wpt.fyi/results/css/css-typed-om?label=experimental&label=master&aligned&view=subtest

**Comment by andruud** [comment]
We should exclude the parts related to [list-valued properties](https://drafts.css-houdini.org/css-typed-om-1/#list-valued-properties). That concept needs work, since reality is more complicated than "property is either list-valued or not".

**Comment by foolip** [comment]
In the [MDN short survey on CSS & HTML](https://github.com/web-platform-tests/interop/issues/245), "CSS Typed Object Model (`computedStyleMap()` API)" was selected by ~9% of survey takers, putting it in the bottom third of the 20 options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/245#issuecomment-1311874383) as with any survey data.)

**Comment by nairnandu** [comment]
Thank you for proposing Typed OM for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. We had many strong proposals, and could not accept them all. This should not be taken as a comment on the technology as a whole, and resubmitting a proposal for this feature as part of a future round of Interop would be welcome.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
