### ISSUE TITLE
Editing, contenteditable and execCommand

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/interop#17]
**Description**
contenteditable, execCommand and editing

**Specification**
https://w3c.github.io/editing/docs/execCommand/
https://w3c.github.io/contentEditable/

**Tests**
https://wpt.fyi/results/editing?label=experimental&label=master&aligned
https://wpt.fyi/results/contenteditable?label=experimental&label=master&aligned

**Rationale**
contenteditable/execCommand are widely used by web pages to implement rich editing functionality. The editing model, and behaviour of execCommand differs substantially across browsers. This causes a significant number of compat issues (see e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1341152 and other bugs referenced therein). Fixing these issues would allow editors to work without either requiring browser-specific codepaths or breaking in some implementations.

**Concerns**
Although these areas have specifications, the actual implementations largely predate the specs, and came from reverse-engineering competitors. Therefore it's unclear if the specs represent a model that everyone wants/is able to converge on. An additional difficulty here is that because some libraries already assume implementation-specific behaviour it can be that converging on a single behaviour causes breakage in the short term.

It is possible/likely that preliminary work to find a viable path forward is required before we can make this part of the Interop 202x effort. That may make it difficult to include in Interop 2022. However given the magnitude of the problem, we should prioritize that preliminary work so we're able to include this as a focus area as soon as possible.

**Comment by foolip** [comment]
I've created the `requires:spec-maturity` label and applied it due to the status of https://w3c.github.io/editing/docs/execCommand/, which calls itself Unofficial Draft and has a big scary warning at the top.

I haven't gone through all proposals to see what else the label might apply to.

**Comment by foolip** [comment]
Based on the Dec 9 meeting, with outcomes summarized in https://github.com/web-platform-tests/interop-2022/issues/39#issuecomment-991001758, we won't include this proposal in Interop 2022.

However, I'm leaving it open since we still need to have a discussion about whether we want to collaborate in some way to address the most important sources of site compat issues for Gecko in editing.

**Comment by foolip** [comment]
@annevk @jgraham do you have thoughts on what we could do jointly to improve things in this area? https://bugzilla.mozilla.org/show_bug.cgi?id=1341152 was linked and there are lots of bugs, but do you know if bugs are concentrated around specific issues? Is there a subset of `contenteditable` or `execCommand()` where some spec+test work could do a lot of good?

(There are [lots of differences](https://wpt.fyi/results/editing?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=is%3Adifferent) and presumably it's not all equally important, and possibly very important things are missing.)

**Comment by jgraham** [comment]
I think we need to get some editing experts from various engines together to set the goals for this area. 

I've set up https://github.com/web-platform-tests/interop-2022-editing as a venue for discussions. @masayuki-nakano is the gecko engineer working most on editing topics and @karlcow knows about the compatibility challenges; we also need some Blink and WebKit contributors who are able to provide relevant expertise to move this forward.

**Comment by foolip** [comment]
@dlibby- do you have a contact at Microsoft for someone who knows editing well and could participate in this effort?

**Comment by dlibby-** [comment]
@BoCupp-Microsoft can help out here.

**Comment by foolip** [comment]
Closing this, discussion continues in https://github.com/web-platform-tests/interop-2022-editing
