### ISSUE TITLE
RegExp lookbehind assertions

### ISSUE THREAD

**Issue by mathiasbynens** [web-platform-tests/interop#171]
### Description

Lookarounds are zero-width assertions that match a string without consuming anything. ECMAScript has long supported lookahead assertions that do this in forward direction. Positive lookahead ensures a pattern is followed by another pattern, and negative lookahead ensures a pattern is not followed by another pattern.

ES2018 added support for lookbehind assertions, which are lookarounds that go backwards. Positive lookbehind ensures a pattern is preceded by another pattern, and negative lookbehind ensures a pattern is not preceded by another pattern.

### Rationale

Lookbehinds enable developers to ensure that a pattern is or isn’t preceded by another, which is a common use case when dealing with regular expressions — e.g. matching a dollar amount without capturing the dollar sign:

```js
// Positive lookbehind:
const pattern = /(?<=\$)\d+/;
const result = pattern.exec('$42');
// → result[0] === '42'
```

Or, conversely, matching numbers that aren’t dollar amounts:

```js
// Negative lookbehind:
const pattern = /(?<!\$)\d+/;
const result = pattern.exec('€42');
// → result[0] === '42'
```

Unlike many other JavaScript language features, **lookbehind support cannot accurately be polyfilled or transpiled**. Only interoperable engine-level support can fill the gap.

[Chrome 62 (stable in 2017-10)](https://bugs.chromium.org/p/v8/issues/detail?id=4545) and [Firefox 78 (stable in 2020-06)](https://hacks.mozilla.org/2020/06/a-new-regexp-engine-in-spidermonkey/) have shipped support, but until all browsers provide support, compatibility issues continue to pop up. Examples:

- [steamcommunity.com - Page doesn't load after signing into Steam account · Issue #51385 · webcompat/web-bugs](https://github.com/webcompat/web-bugs/issues/51385)
- [“I've hit a website in the wild that uses lookbehind assertions and does not load on Safari.”](https://bugs.webkit.org/show_bug.cgi?id=174931#c17)
- [“just hit this bug trying to load a local instance of backstage (https://github.com/backstage/backstage)”](https://bugs.webkit.org/show_bug.cgi?id=174931#c21)

### Specification

https://tc39.es/ecma262/#prod-Assertion

### Tests

https://test262.report/browse/built-ins/RegExp/lookBehind?engines=javascriptcore%2Cspidermonkey%2Cv8 (corresponding to https://github.com/tc39/test262/tree/main/test/built-ins/RegExp/lookBehind)

**Note that since there are no other Interop proposals that need tests from Test262, it would be overkill to set up full Test262 integration just for this one feature. If this proposal is accepted, I volunteer to write equivalent WPT tests for this feature.**

**Update:** https://github.com/web-platform-tests/wpt/pull/37928

**Comment by foolip** [comment]
Here are some tweets about this that we've come across:
https://twitter.com/LeaVerou/status/1561671321242796032
https://twitter.com/jvhellemond/status/1564153860561817601

**Comment by karlcow** [comment]
to note that one of the reasons that Firefox [implemented it ](https://bugzilla.mozilla.org/show_bug.cgi?id=1225665) was webcompat pressure. such as [steam community chat](https://bugzilla.mozilla.org/show_bug.cgi?id=1629092)

**Comment by gsnedders** [comment]
> Note that since there are no other Interop proposals that need tests from Test262

#169 would beg to differ 🙃

**Comment by mathiasbynens** [comment]
> > Note that since there are no other Interop proposals that need tests from Test262
> 
> #169 would beg to differ 🙃 (plus, of course, several weeks remaining for others to submit such proposals!)

I stand corrected :) Regardless, my offer to write WPT tests if needed still stands.

**Comment by tbondwilkinson** [comment]
RegExp lookbehind assertions is a P2 for Google's [closure library](https://github.com/google/closure-library)

"Consolidate functionality across browsers; potentially replace some string library usage and generally improve code health if used appropriately."
