### ISSUE TITLE
`:dir()`  improved support

### ISSUE THREAD

**Issue by brandonmcconnell** [web-platform-tests/interop#177]
## Description

"The `:dir()` pseudo-class in CSS allows elements to be selected based on the direction of the language, as determined in the HTML markup. There are really only two directions language can flow in a document, which are left-to-right and right-to-left. Think of this as a way to style elements that are distinguished by different language directionality."
– @geoffgraham (via [CSS Tricks](https://css-tricks.com/almanac/selectors/d/dir/))

I couldn't have explained it better, myself. Thanks, Geoff 🙏🏼

## Rationale

`:dir()` support is important to the effort of internationalization. This pseudo-class has been a long time coming and has been a topic of discussion for a while now as well:

Formal (docs-style)
* https://developer.mozilla.org/en-US/docs/Web/CSS/:dir
* https://www.geeksforgeeks.org/css-dir-selector/
* https://www.w3docs.com/learn-css/dir.html

Informal
* https://css-tricks.com/almanac/selectors/d/dir/
* https://tympanus.net/codrops/css_reference/dir/
* https://www.youtube.com/watch?v=lG-tFqMZYPs

Directionality can currently be set in two primary ways— setting the HTML `dir` attribute to either `ltr` or `rtl`, or setting the `direction` property in CSS to either of those same values.

Elements explicitly setting `dir="rtl"` (or similar) can already be targeted with CSS using an attribute selector. However, this is usually an edge case, as that property is usually set once on a document, and does not necessarily apply that same directionality to all elements on the page.

`:dir()` is the solution here:
* matches `[dir="rtl"]` (or similar)
* matches `direction: rtl` (or similar)
* matches directionality that is either inherited or purposefully not inherited from a parent element

## Specification

https://w3c.github.io/csswg-drafts/selectors-4/#the-dir-pseudo

## Tests

* https://wpt.fyi/results/css/css-pseudo?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=subtest&q=dir
* https://wpt.fyi/results/css/selectors?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=subtest&q=dir%20

More tests will likely be needed for this.

**Comment by gsnedders** [comment]
> Relevant but not comprehensive: https://wpt.fyi/results/css/css-pseudo?label=master&label=experimental&aligned&view=subtest&q=dir

there's more tests in https://wpt.fyi/results/css/selectors?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=subtest&q=dir%20

**Comment by brandonmcconnell** [comment]
@gsnedders Thanks! Is there a readme or guide (or video for that matter) to help find relevant tests like this? I have such a hard time navigating wpt.fyi sometimes, as much as I love the site and the value it adds.

Thanks again! 🙏🏼

**Comment by foolip** [comment]
@brandonmcconnell I know wpt.fyi is very much a power user interface and there are plenty of things in hard-to-discover UI and documentation. If you have specific tasks you're trying to get done and can't, can you file an issue at https://github.com/web-platform-tests/wpt.fyi/issues?

When it comes to finding tests, searching in a local checkout of https://github.com/web-platform-tests/wpt is probably most effective, since you can then search for the test contents, not just their names.

**Comment by gsnedders** [comment]
In the above case, I just started searching for "dir" and looked at where matched—that pseudo-classes (which are defined in Selectors) have tests in the Selectors directory isn't particularly surprising, given that knowledge about where they're specified.

**Comment by karlcow** [comment]
> When it comes to finding tests, searching in a local checkout of https://github.com/web-platform-tests/wpt is probably most effective, since you can then search for the test contents, not just their names.

**This**. What @foolip said

I have been experimenting a couple of times with this. 
For example for `:dir()`, on the repo once you have done a local clone on your computer.

`find . -name '*.html' ! -name '*-ref.html' -type f -exec grep -H ':dir(' {} \;`

which will give all matches. If you want something more browsable.

`find . -name '*.html' ! -name '*-ref.html' -type f -exec grep -H ':dir(' {} \; | sed -e 's,:.*,,' | sort | uniq | sed -e 's,^\.,https://wpt.fyi,'`

https://wpt.fyi/css/css-scoping/shadow-directionality-001.tentative.html
https://wpt.fyi/css/css-scoping/shadow-directionality-002.tentative.html
https://wpt.fyi/css/selectors/dir-selector-auto-direction-change-001.html
https://wpt.fyi/css/selectors/dir-selector-auto.html
https://wpt.fyi/css/selectors/dir-selector-change-001.html
https://wpt.fyi/css/selectors/dir-selector-change-002.html
https://wpt.fyi/css/selectors/dir-selector-change-003.html
https://wpt.fyi/css/selectors/dir-selector-change-004.html
https://wpt.fyi/css/selectors/dir-selector-ltr-001.html
https://wpt.fyi/css/selectors/dir-selector-ltr-002.html
https://wpt.fyi/css/selectors/dir-selector-ltr-003.html
https://wpt.fyi/css/selectors/dir-selector-querySelector.html
https://wpt.fyi/css/selectors/dir-selector-rtl-001.html
https://wpt.fyi/css/selectors/dir-selector-white-space-001.html
https://wpt.fyi/css/selectors/dir-style-01a.html
https://wpt.fyi/css/selectors/dir-style-01b.html
https://wpt.fyi/css/selectors/dir-style-02a.html
https://wpt.fyi/css/selectors/dir-style-02b.html
https://wpt.fyi/css/selectors/dir-style-03a.html
https://wpt.fyi/css/selectors/dir-style-03b.html
https://wpt.fyi/css/selectors/dir-style-04.html
https://wpt.fyi/html/semantics/selectors/pseudo-classes/dir-html-input-dynamic-text.html
https://wpt.fyi/html/semantics/selectors/pseudo-classes/dir.html
https://wpt.fyi/html/semantics/selectors/pseudo-classes/dir01.html
https://wpt.fyi/shadow-dom/directionality-002.tentative.html

**Comment by karlcow** [comment]
Better suggestion from @heycam and a lot faster 

`time grep -lR ':dir(' | grep -v '[-]ref.html$' | sort | uniq | sed -e 's,^\.,https://wpt.fyi,'`

**Comment by brandonmcconnell** [comment]
@karlcow @heycam Nice! I compiled that into a shell function I'll use when searching for tests from now on 👏🏼

```bash
function find-wpt-tests(){
  cd "/path/to/wpt" # <-- replace with the path to the `wpt` directory on your local machine
  grep -lR "$@" | grep -v "[-]ref.html$" | sed -e "s,^\.,https://wpt.fyi,"
}

# usage
find-wpt-tests ":dir("
```

**Comment by brandonmcconnell** [comment]
@karlcow @heycam @gsnedders I've put together a sightly more sophisticated version of this function ☝🏼 which handles formatting flags for the returned results—`-m` for shortlinking via markdown and `-l` for returning the results as a bulleted list—and little niceties like loading-state verbiage and error handling for invalid search terms.

```bash
function find-wpt-tests(){
  cwd=$(pwd)
  local md=0
  local list=0
  while getopts 'ml' OPTION; do
    case "$OPTION" in 
      m) 
        md=1
        ;;
      l)
        list=1
        ;;
      ?) 
        echo "\nUsage: [-m] [-l] $(basename $0)"
        return 1
        ;;
    esac
  done
  shift $(( OPTIND - 1 ))

  cd "/Users/brandon.mcconnell/Projects/wpt"
  echo "Searching...\n"
  local results=($(grep -lR $1 | grep -v "[-]ref.html$" | sed -e "s,^\.,https://wpt.fyi,"))
  local filtered_results=()
  local link_prefix="https://wpt.fyi"
  for item in "${results[@]}"; do
    if [[ $item == *"$link_prefix"* ]]; then
      filtered_results+=($item)
    fi
  done

  if [ ${#filtered_results[*]} -gt 0 ]; then
    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
    for item in "${filtered_results[@]}"; do
      local print_prefix=""
      [[ $list -eq 1 ]] && print_prefix=" - "
      local print_link="${item}"
      local abbr_link="${item#$link_prefix}"
      [[ $md -eq 1 ]] && print_link="[${abbr_link}](${item})"
      echo "${print_prefix}${print_link}"
    done
    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
    echo "\nFound ${#filtered_results[*]} tests related to your search term \"$1\""
  else
    echo "No tests found. Try refining your search."
  fi
  cd $cwd
  return 0
}
```

The flags can also naturally be combined, so if you want both enabled, you can use them like this:

```bash
find-wpt-tests -ml ":dir("
```

which returns:

```bash
Searching...

-------------------------------------------------------------------------------------------------------------------------------------------------------------------
 - [/css/css-scoping/shadow-directionality-002.tentative.html](https://wpt.fyi/css/css-scoping/shadow-directionality-002.tentative.html)
 - [/css/css-scoping/shadow-directionality-001.tentative.html](https://wpt.fyi/css/css-scoping/shadow-directionality-001.tentative.html)
 - [/css/selectors/dir-selector-ltr-003.html](https://wpt.fyi/css/selectors/dir-selector-ltr-003.html)
 - [/css/selectors/dir-style-03a.html](https://wpt.fyi/css/selectors/dir-style-03a.html)
 - [/css/selectors/dir-selector-auto.html](https://wpt.fyi/css/selectors/dir-selector-auto.html)
 - [/css/selectors/dir-style-01a.html](https://wpt.fyi/css/selectors/dir-style-01a.html)
 - [/css/selectors/dir-selector-ltr-002.html](https://wpt.fyi/css/selectors/dir-selector-ltr-002.html)
 - [/css/selectors/dir-selector-auto-direction-change-001.html](https://wpt.fyi/css/selectors/dir-selector-auto-direction-change-001.html)
 - [/css/selectors/dir-style-02a.html](https://wpt.fyi/css/selectors/dir-style-02a.html)
 - [/css/selectors/dir-selector-change-001.html](https://wpt.fyi/css/selectors/dir-selector-change-001.html)
 - [/css/selectors/dir-style-02b.html](https://wpt.fyi/css/selectors/dir-style-02b.html)
 - [/css/selectors/dir-selector-querySelector.html](https://wpt.fyi/css/selectors/dir-selector-querySelector.html)
 - [/css/selectors/dir-selector-change-002.html](https://wpt.fyi/css/selectors/dir-selector-change-002.html)
 - [/css/selectors/dir-selector-white-space-001.html](https://wpt.fyi/css/selectors/dir-selector-white-space-001.html)
 - [/css/selectors/dir-selector-change-003.html](https://wpt.fyi/css/selectors/dir-selector-change-003.html)
 - [/css/selectors/dir-style-01b.html](https://wpt.fyi/css/selectors/dir-style-01b.html)
 - [/css/selectors/dir-selector-ltr-001.html](https://wpt.fyi/css/selectors/dir-selector-ltr-001.html)
 - [/css/selectors/dir-style-04.html](https://wpt.fyi/css/selectors/dir-style-04.html)
 - [/css/selectors/dir-style-03b.html](https://wpt.fyi/css/selectors/dir-style-03b.html)
 - [/css/selectors/dir-selector-change-004.html](https://wpt.fyi/css/selectors/dir-selector-change-004.html)
 - [/css/selectors/dir-selector-rtl-001.html](https://wpt.fyi/css/selectors/dir-selector-rtl-001.html)
 - [/css/css-pseudo/dir-pseudo-on-input-element.html](https://wpt.fyi/css/css-pseudo/dir-pseudo-on-input-element.html)
 - [/css/css-pseudo/dir-pseudo-on-bdi-element.html](https://wpt.fyi/css/css-pseudo/dir-pseudo-on-bdi-element.html)
 - [/html/semantics/selectors/pseudo-classes/dir01.html](https://wpt.fyi/html/semantics/selectors/pseudo-classes/dir01.html)
 - [/html/semantics/selectors/pseudo-classes/dir-html-input-dynamic-text.html](https://wpt.fyi/html/semantics/selectors/pseudo-classes/dir-html-input-dynamic-text.html)
 - [/html/semantics/selectors/pseudo-classes/dir.html](https://wpt.fyi/html/semantics/selectors/pseudo-classes/dir.html)
 - [/shadow-dom/directionality-002.tentative.html](https://wpt.fyi/shadow-dom/directionality-002.tentative.html)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

Found 27 tests related to your search term ":dir("
```

**Comment by brandonmcconnell** [comment]
I'll leave it there, so we don't further pollute this issue 👌🏼

**Comment by bkardell** [comment]
There is also an open issue/pr about resolving these in shadow dom which would add a slew of tests when it lands https://github.com/web-platform-tests/wpt/pull/29820

**Comment by brandonmcconnell** [comment]
@bkardell Great find. Thanks, Brian!

**Comment by jensimmons** [comment]
We do want to limit potential Inteorp 2023 tests to only include ones that don't fail because an unrelated technology is not supported. For example, if the test is for :dir() + foobar, and only passes if both are supported — and foobar is not supported in all the browser engine already, then it should not be part of Interop 2023. 

Why? Because foobar isn't part of Interop 2023. (Presuming it isn't). Engines should get scored according to their :dir() implementation, not on foobar.

**Comment by brandonmcconnell** [comment]
@jensimmons Fine point. I can see how those tests would likely be a better fit for a future shadow DOM rather than `:dir()`

**Comment by zcorpan** [comment]
> More tests will likely be needed for this.

Also see https://github.com/web-platform-tests/wpt/issues/25569

**Comment by foolip** [comment]
In the State of CSS 2022 question about browser incompatibilities, there were two mentions of `:dir()`, so not enough to make the top list in https://github.com/web-platform-tests/interop/issues/248. The comments were ":did(RTL)" (typo, manually identified) and ":dir() selector".

**Comment by foolip** [comment]
In the [MDN short survey on CSS & HTML](https://github.com/web-platform-tests/interop/issues/245), "CSS `:dir()` pseudo-class" was selected by ~5% of survey takers, putting it in the bottom third of the 20 options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/245#issuecomment-1311874383) as with any survey data.)

**Comment by foolip** [comment]
Some of the tentative tests here depend on https://github.com/whatwg/html/issues/3699 / https://github.com/whatwg/html/pull/7424. @meyerweb do you think that can be resolved soonish?

**Comment by foolip** [comment]
Thank you for proposing `:dir()` for gradients for inclusion in Interop 2023.

We are pleased to let you know that this proposal was accepted as part of the CSS Pseudo-classes focus area. You can follow the progress of this Focus Area on the [Interop 2023 dashboard](https://wpt.fyi/interop-2023).

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you for contributing to Interop 2023!

_Posted on behalf of the Interop team._
