### ISSUE TITLE
`:user-invalid` & `:user-valid` browser support

### ISSUE THREAD

**Issue by brandonmcconnell** [web-platform-tests/interop#178]
## Description

Quoting the [specification](https://w3c.github.io/csswg-drafts/selectors-4/#user-pseudos):

>The [`:user-invalid`](https://w3c.github.io/csswg-drafts/selectors-4/#user-invalid-pseudo) and the [`:user-valid`](https://w3c.github.io/csswg-drafts/selectors-4/#user-valid-pseudo) pseudo-classes represent an element with incorrect or correct input, respectively, but only after the user has significantly interacted with it.
>
>The [`:user-invalid`](https://w3c.github.io/csswg-drafts/selectors-4/#user-invalid-pseudo) pseudo-class must match an [`:invalid`](https://w3c.github.io/csswg-drafts/selectors-4/#invalid-pseudo), [`:out-of-range`](https://w3c.github.io/csswg-drafts/selectors-4/#out-of-range-pseudo), or blank-but-[`:required`](https://w3c.github.io/csswg-drafts/selectors-4/#required-pseudo) elements between the time the user has attempted to submit the form and before the user has interacted again with the form element.
>
>The [`:user-valid`](https://w3c.github.io/csswg-drafts/selectors-4/#user-valid-pseudo) pseudo-class must match a [`:valid`](https://w3c.github.io/csswg-drafts/selectors-4/#valid-pseudo) element between the time the user has attempted to submit the form and before the user has interacted again with the form element.
>
>User-agents may allow them to match such elements at other times, as would be appropriate for highlighting an error to the user. For example, a UA may choose to have [`:user-invalid`](https://w3c.github.io/csswg-drafts/selectors-4/#user-invalid-pseudo) match an [`:invalid`](https://w3c.github.io/csswg-drafts/selectors-4/#invalid-pseudo) element once the user has typed some text into it and changed the focus to another element, and to stop matching only after the user has successfully corrected the input.

## Rationale

There has been plenty of discussions and workarounds supporting this for over a decade now (or at least as far back as I can remember)— not so much the pseudo itself so much as clunky methods to accomplish what this pseudo would provide effortlessly.
* https://www.bram.us/2021/01/28/form-validation-you-want-notfocusinvalid-not-invalid/
* https://github.com/angular/material/issues/1633
* https://github.com/angular/components/issues/7558
* https://github.com/angular/components/issues/7558
* https://stackoverflow.com/questions/40529817/reactive-forms-mark-fields-as-touched
* Angular's `markAsTouched`, `markAsUntouched`, `markAsDirty`, `markAsPristine` → https://angular.io/api/forms/AbstractControl
  * https://stackoverflow.com/questions/59885764/angular-is-there-a-way-to-markastouched-a-field-without-a-form
  * https://stackoverflow.com/questions/60759030/both-markallastouched-and-markastouched-dont-affect-subforms
* https://github.com/vmware/clarity/issues/3191

Oftentimes, we want to validate/invalidate form data, but we don't want to show the field as valid or invalid until after the first change event so the user has a chance to interact with the form field before the page applies successful/failure styling to the element.

## Specification

https://w3c.github.io/csswg-drafts/selectors-4/#user-pseudos

## Tests

* `:user-invalid`: https://wpt.fyi/results/css/selectors/user-invalid.html?label=master&label=experimental&aligned&view=subtest&q=user-invalid
* `:user-valid`: https://wpt.fyi/results/css/selectors/user-valid.html?label=master&label=experimental&aligned&view=subtest&q=user-valid

**Comment by foolip** [comment]
Looks like this is supported in Firefox, and these are the implementation bugs for Chromium and WebKit:
https://bugs.chromium.org/p/chromium/issues/detail?id=1156069
https://bugs.webkit.org/show_bug.cgi?id=222267

(Linked in BCD in https://github.com/mdn/browser-compat-data/pull/17930.)

**Comment by annevk** [comment]
I wonder if whoever implemented these in Firefox can help out with https://github.com/whatwg/html/issues/8452 as it's not completely work how they work in terms of HTML. Selectors doesn't dictate the rules for host languages after all.

**Comment by jgraham** [comment]
Seems like @emilio did the Gecko implementation.

**Comment by emilio** [comment]
I mostly rejiggered `:-moz-ui-{valid,invalid}`, which were pre-existing. The rules are a bit complex, but I can try to explain them:

 * For `<button>`, `:valid` and `:user-valid` are equivalent ([code](https://searchfox.org/mozilla-central/rev/185db4a5f794fa6afbbd446944bdeaf640ba7d72/dom/html/HTMLButtonElement.cpp#404-410)
 * Seems like the same is true for form-associated custom-elements ([code](https://searchfox.org/mozilla-central/rev/185db4a5f794fa6afbbd446944bdeaf640ba7d72/dom/html/HTMLElement.cpp#205-209)). That was implemented afterwards, maybe @EdgarChen can comment. Might be useful to allow authors to customize them.
 * For `<input>`, `<select>` and `<textarea>` the rules are described in [this comment](https://searchfox.org/mozilla-central/rev/185db4a5f794fa6afbbd446944bdeaf640ba7d72/dom/html/HTMLInputElement.cpp#5953-5970). `<select>` code is [here](https://searchfox.org/mozilla-central/rev/185db4a5f794fa6afbbd446944bdeaf640ba7d72/dom/html/HTMLSelectElement.cpp#1248-1259), `<textarea>` is [here](https://searchfox.org/mozilla-central/rev/185db4a5f794fa6afbbd446944bdeaf640ba7d72/dom/html/HTMLTextAreaElement.cpp#760-779).

**Comment by annevk** [comment]
I think for this to be part of Interop 2023 someone would have to turn that into a PR against the HTML Standard. A lot of it looks somewhat straightforward, but some of the state keeping and when to invalidate that state might be tricky I suppose. And yeah, I suspect that for form-associated elements we need to reconsider when they would apply.

**Comment by foolip** [comment]
In the State of CSS 2022 question about browser incompatibilities, there was one mention of `:user-invalid` and one of `:user-valid`, so not enough to make the top list in https://github.com/web-platform-tests/interop/issues/248.

(I'm commenting on all proposals where I could find some mention at all in State of CSS results.)

**Comment by foolip** [comment]
In the [MDN short survey on CSS & HTML](https://github.com/web-platform-tests/interop/issues/245), "CSS `:user-invalid` and `:user-valid` pseudo-classes" was selected by ~11% of survey takers, putting it in the bottom third of the 20 options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/245#issuecomment-1311874383) as with any survey data.)

**Comment by mfreed7** [comment]
> I think for this to be part of Interop 2023 someone would have to turn that into a PR against the HTML Standard. A lot of it looks somewhat straightforward, but some of the state keeping and when to invalidate that state might be tricky I suppose. And yeah, I suspect that for form-associated elements we need to reconsider when they would apply.

I agree with this comment. It's tough to tell what the standardized behavior is or should be for this. E.g. there seems to be a lot of flexibility built into this sentence:
> User-agents may allow them to match such elements at other times, as would be appropriate for highlighting an error to the user. 

@emilio  would it be possible to expand on your [comment](https://github.com/web-platform-tests/interop/issues/178#issuecomment-1308648986) just a bit to summarize the behavior itself?

**Comment by foolip** [comment]
Thank you for proposing `:user-invalid` and `:user-valid` for gradients for inclusion in Interop 2023.

We are pleased to let you know that this proposal was accepted as part of the Custom Properties focus area. You can follow the progress of this Focus Area on the [Interop 2023 dashboard](https://wpt.fyi/interop-2023).

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you for contributing to Interop 2023!

_Posted on behalf of the Interop team._

**Comment by brandonmcconnell** [comment]
> Thank you for proposing `:user-invalid` and `:user-valid` for gradients for inclusion in Interop 2023.

@foolip Just to confirm, this is unrelated to gradients

**Comment by foolip** [comment]
@brandonmcconnell sorry, of course, that was copypasta.
