### ISSUE TITLE
URL IDNA interop

### ISSUE THREAD

**Issue by annevk** [web-platform-tests/interop#18]
**Description**
IDNA allows for us non-ASCII code points in domain names.

**Specification**
https://url.spec.whatwg.org/#idna

**Tests**
https://wpt.fyi/results/url/toascii.window.html (to be modified by https://github.com/web-platform-tests/wpt/pull/31596 to show the issue better)

**Rationale**
Firefox and Safari follow the URL Standard and use Transitional_Processing set to false, but Chrome does not. Firefox has some unrelated failures on this particular test, I'm not sure whether those should be in scope or not.

**Comment by foolip** [comment]
How would this affect developers? Is this something that currently leads to site compat issues, or do web developers have to avoid IDNA domain names because of issues like this?

**Comment by annevk** [comment]
Yeah, for instance German speakers cannot have domains with `ß` in them as they do not work in Chrome (becomes `ss` rather than `xn--zca`). And on the other side, URLs such as `https://www.👨‍🦰.tk/` only work in Chrome (but shouldn't).

**Comment by jgraham** [comment]
I'm going to move this to be a candiate for #9 rather than a standalone proposal.

**Comment by foolip** [comment]
@annevk is https://bugs.chromium.org/p/chromium/issues/detail?id=694157 the right Chromium bug for this? I see Transitional_Processing vs. Nontransitional_Processing but maybe there was a rename at some point?

**Comment by foolip** [comment]
Yep, it was renamed in https://github.com/whatwg/url/pull/404.

**Comment by dholbert** [comment]
> Firefox has some unrelated failures on this particular test, I'm not sure whether those should be in scope or not.

Following up on these: I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1788115 on these failures, and that bug's just been fixed, making Firefox fully pass this test now.  Hooray!

**Comment by gsnedders** [comment]
#145 covers a superset of this in Interop 2023. (And the above linked tests are still failing in Chrome.)
