### ISSUE TITLE
@scope

### ISSUE THREAD

**Issue by andruud** [web-platform-tests/interop#183]
### Description

This proposal includes the `@scope` rule, as specified by: https://drafts.csswg.org/css-cascade-6/#scope-atrule

It does not include:

- [Selector scoping notation](https://drafts.csswg.org/css-cascade-6/#selector-scoping). (This will likely be removed from the spec).
- The [>>](https://drafts.csswg.org/css-cascade-6/#scope-combinator) combinator.
- The [~~](https://github.com/w3c/csswg-drafts/issues/7233#issuecomment-1248655289) combinator.

### Rationale

It’s on the list of missing features in the State of CSS survey.

https://2021.stateofcss.com/en-US/opinions/#currently_missing_from_css_wins

### Specification

https://drafts.csswg.org/css-cascade-6/#scope-atrule

### Tests

[`https://wpt.fyi/results/css/css-cascade/*scope*`](https://wpt.fyi/results/css/css-cascade?label=master&label=experimental&aligned&view=subtest&q=scope):

at-scope-parsing.html
scope-deep.html
scope-evaluation.html
scope-invalidation.html
scope-proximity.html
scope-specificity.html

**Comment by tbondwilkinson** [comment]
This is the most important feature for CSS infrastructure in Google.

"Even without widespread browser implementations, a solid CSS scoping spec gives the CSS team a target for our polyfills and designs for the next generation of component scoping, allowing us to stay in line with standard CSS rather than needing to reinvent the wheel"

**Comment by foolip** [comment]
There were a handful of mentions of scoping in State of CSS 2022, although not enough to make the top list in https://github.com/web-platform-tests/interop/issues/248. There were two direct mentions of `@scope`, and a few others like these:

- Scoping is a somewhat solved issue, but no real way to handle it in native CSS without plugins.
- too many solutions for scoping
- styling of scoped content (overriding)

**Comment by gsnedders** [comment]
> There were two direct mentions of `@scope`

Are you just looking at the `interoperability_features_freeform`, and not the other freeform responses? If you look across all the freeform responses, there's four direct mentions, plus about another 32 mentions of scoping (most of which just say "scope" with no further detail)?

**Comment by foolip** [comment]
@gsnedders yes, just the results of that question in what I'm reporting from https://github.com/web-platform-tests/interop/issues/248. I haven't vetted the results of the other two questions, and I think https://github.com/web-platform-tests/interop/issues/155 is the only case so far where I happened to notice a lot of mentions and called that out.

Going through the results of those two questions systematically would be great, if you or anyone else has time. I might spend time on it next week, but can't promise.

**Comment by foolip** [comment]
In the [MDN short survey on CSS & HTML](https://github.com/web-platform-tests/interop/issues/245), "CSS scoping (`@scope` at-rule)" was selected by ~16% of survey takers, putting it in the middle third of the 20 options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/245#issuecomment-1311874383) as with any survey data.)

**Comment by nairnandu** [comment]
Thank you for proposing @scope for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. We had many strong proposals, and could not accept them all. However this should not be taken as a comment on the technology as a whole, and resubmitting a proposal for this feature as part of a future round of Interop would be welcome.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
