### ISSUE TITLE
Import Maps

### ISSUE THREAD

**Issue by LeviPesin** [web-platform-tests/interop#184]
### Description

Import maps are really useful and really needed for very many developers. They are supported everywhere except Safari and Firefox.

### Rationale

They are extremely useful for JavaScript libraries and their developers, for example [three.js](https://github.com/mrdoob/three.js).

### Specification

https://wicg.github.io/import-maps/

### Tests

https://wpt.fyi/results/?label=master&label=experimental&aligned&view=subtest&q=import-maps

**Comment by foolip** [comment]
It looks like the spec here isn't on the W3C Recommendation Track. @domenic, as the editor of the spec, what's the likely destination of this once it leaves incubation, and when might that happen?

**Comment by foolip** [comment]
Excellent, thanks @domenic!

**Comment by annevk** [comment]
One potential problem here is that WebKit supports a superset: https://github.com/whatwg/html/issues/8355. It would be undesirable if supporting external import maps would give you a lower score.

(Also note that with 3 engines "everywhere except 2" leaves 1. 😊)

**Comment by foolip** [comment]
This was mentioned by WordPress developer @youknowriad in https://make.wordpress.org/core/2022/10/10/seeking-proposals-for-interop-2023/#comment-43928:

> import maps: Would love support without polyfills as this would allows us to improve the way scripts are registered/handled in WP and introduce lazy loaded scripts…

Thanks Riad for sharing!

**Comment by gsnedders** [comment]
We probably want to exclude `/import-maps/acquiring/modulepreload.html` and `/import-maps/acquiring/modulepreload-link-header.html`.

**Comment by tbondwilkinson** [comment]
Import maps are a P4 for Google's [closure library](https://github.com/google/closure-library)

"It's possible this could help with polyfills, maybe?"

**Comment by LeviPesin** [comment]
There is a [es-module-shims polyfill](https://github.com/guybedford/es-module-shims).

**Comment by gsnedders** [comment]
Note [`/import-maps/data-driven/`](https://wpt.fyi/results/import-maps/data-driven?label=master&label=experimental&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk&view=subtest) are currently failing in WebKit for [unrelated reasons](https://bugs.webkit.org/show_bug.cgi?id=245719) (related to when load events are fired on `iframe` elements).

I don't know how difficult this would be to workaround (it might be as simple as passing `{once: true}` to event listener), but we probably ought not test totally unrelated behaviour here.

**Comment by foolip** [comment]
In the [MDN short survey on APIs & JavaScript](https://github.com/web-platform-tests/interop/issues/246), "Import Maps" was selected by ~13% of survey takers, putting it in the bottom third of options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/246#issuecomment-1312098410) as with any survey data.)

**Comment by foolip** [comment]
Thank you for proposing Import Maps for inclusion in Interop 2023.

We are pleased to let you know that this proposal was accepted as part of the Modules focus area. You can follow the progress of this Focus Area on the [Interop 2023 dashboard](https://wpt.fyi/interop-2023).

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you for contributing to Interop 2023!

_Posted on behalf of the Interop team._
