### ISSUE TITLE
WebTransport

### ISSUE THREAD

**Issue by LeviPesin** [web-platform-tests/interop#186]
### Description

WebTransport is an API for accesing HTTP/3 protocol in browser, similar to WebSockets but with very nice UDP features like unreliable and out-of-order (but very much faster) delivery.

### Rationale

It is very useful in web games, because it allows for a very fast (but unreliable) messaging.

It is enabled in desktop Chrome, Edge, and Opera, and mobile Samsung Internet and Android Browser.

### Specification

https://w3c.github.io/webtransport/

### Tests

https://wpt.fyi/results/?label=master&label=experimental&aligned&view=subtest&q=webtransport

**Comment by tbondwilkinson** [comment]
WebTransport is a P4 for Google's [closure library](https://github.com/google/closure-library)

"This is probably relevant to goog.net somehow? (but I'm not particularly familiar with that part of the library)"

**Comment by foolip** [comment]
In the [MDN short survey on APIs & JavaScript](https://github.com/web-platform-tests/interop/issues/246), "WebTransport" was selected by ~11% of survey takers, putting it in the bottom third of options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/246#issuecomment-1312098410) as with any survey data.)
