### ISSUE TITLE
css-contain-2 and contain-intrinsic-size

### ISSUE THREAD

**Issue by vmpstr** [web-platform-tests/interop#189]
### Description

CSS Containment Module, Level 2, specifies the `contain` and `content-visibility`
properties. The contain-intrinsic-size property is specified in CSS Sizing Module, Level 4.

The proposal is for the following properties:
`content-visibility: hidden` value.
`content-visibility: auto` value.
`contain-intrinsic-size` css property, supporting all values.

### Rationale

CSS Containment Module Level 2 provides performance primitives to help developers
scale their content. Specifically the `content-visibility` property enables
developers to control how much or how little of their content is rendered:
* `content-visibility: hidden` allows pages to represent hidden or cached SPA route content in the DOM without paying a rendering cost.
* `content-visibility: auto` allows pages to avoid rendering cost for content not currently in or near the viewport.

The `contain` CSS property is a prerequisite for `content-visibility`, but that is already part of Interop 2022. The `contain-intrinsic-size` property is important to provide an easy way to reserve placeholder sizing for `content-visibility` subtrees. It also enables full `content-visibility: auto` adoption without the need for any script.

When compared to `display: none`, `content-visibility: auto` elements have an
added benefit of being _searchable_ by find-in-page, and available to assistive
technologies via the accessibility tree. This further unlocks features such as
`hidden=until-found` and automatic searchability of content in `<details>` elements.

Implementor status:

* Blink: `css-contain-2`, including `content-visibility` is implemented. Over [4%](https://chromestatus.com/metrics/css/timeline/popularity/662) of page loads use `content-visibility`, despite it only being available in Blink at the moment.
* WebKit: work ongoing: [content-visibility bug / patch list](https://bugs.webkit.org/buglist.cgi?quicksearch=content-visibility)
* Gecko: work ongoing: [content-visibility bug / patch list](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=content-visibility)
* Mozilla RFP status: [worth prototyping](https://github.com/mozilla/standards-positions/issues/135#issuecomment-650923098)
* [Intent to ship](https://twitter.com/intenttoship/status/1575588545233702912) for contain-intrisic-size on Gecko.

Community feedback:

[Vincent Riemer](https://twitter.com/vincentriemer/status/1288668233457758208), React / Meta engineer:
> Just did a quick test and boi oh boi — the upcoming `content-visibility` CSS property has the potential to be one of the biggest performance improvements to SPAs (if properly leveraged) I've seen in a long time.

[Addy Osmani](https://twitter.com/addyosmani/status/1368479029683122180), Google engineer:
> CSS "content-visibility:auto" is amazing: skip rendering & painting offscreen content until needed. I got a ~1s faster render on a long HTML document on desktop, ~3s on mobile.

[Benoit Girard](https://twitter.com/b56girard/status/1417918695792201732), Databricks engineer, ex-Meta engineer:
> Saved over 1 seconds of restyle time on a very large list with 2 lines of CSS using content-visibility, under 1 hour of work

Article:
https://web.dev/content-visibility/

### Specification

https://www.w3.org/TR/css-contain-2/
https://www.w3.org/TR/css-sizing-4/

### Tests

https://wpt.fyi/results/css/css-contain/content-visibility
https://wpt.fyi/results/css/css-contain
https://wpt.fyi/results/css/css-sizing/contain-intrinsic-size

**Comment by foolip** [comment]
I have a question in https://github.com/web-platform-tests/interop/issues/133#issuecomment-1269530351 about how this would add up with the Container Queries proposal and the 2022 containment focus area.

**Comment by foolip** [comment]
There were two mentions of `content-visibility` in State of CSS 2022, which was not enough to make the top list in https://github.com/web-platform-tests/interop/issues/248, but I'm commenting on all proposals where there's some signal. The comments were "content-visibility in Chrome (breaks a11y tree, reported)" and "content-visibility property".

**Comment by foolip** [comment]
In the [MDN short survey on CSS & HTML](https://github.com/web-platform-tests/interop/issues/245), "CSS containment (`contain`, `contain-intrinsic-size`, `content-visibility`)" was selected by ~19% of survey takers, putting it in the middle third of the 20 options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/245#issuecomment-1311874383) as with any survey data.)
