### ISSUE TITLE
Splitting proposals

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#191]
In https://github.com/web-platform-tests/interop/issues/190 we identified that a number of proposals already have comments suggesting splitting:
- [x] https://github.com/web-platform-tests/interop/issues/143
- [x] https://github.com/web-platform-tests/interop/issues/147
- [ ] https://github.com/web-platform-tests/interop/issues/152
- [x] https://github.com/web-platform-tests/interop/issues/170
- [x] https://github.com/web-platform-tests/interop/issues/181
- [ ] https://github.com/web-platform-tests/interop/issues/218

It's up to the person who proposed to decide if they want to split it, but here's a tracking issue with checklists so that we can follow up on that.

**Comment by gsnedders** [comment]
> It's up to the person who proposed to decide if they want to split it

Or to someone else to file a counter-proposal which is a subset of the original one.

**Comment by gsnedders** [comment]
https://github.com/web-platform-tests/interop/issues/181 seems to be the only one still needing split at this point; it seems like https://github.com/web-platform-tests/interop/issues/143 and #152 don't need split (albeit the descriptions perhaps changed?). Are we still going to accept a split, even after the deadline for proposals has past?

**Comment by foolip** [comment]
Closing as we're passed the deadline to refine proposals now.
