### ISSUE TITLE
Non-responsive image loading

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/interop#195]
### Description

This investigate area will look at what's required to specify image loading that's compatible with web content.

### Rationale

Updating gecko to match the spec for <img src> loading caused some test failures that pointed to likely webcompat regressions that prevented the patches from landing. 

In particular, tests under https://github.com/web-platform-tests/wpt/tree/master/html/canvas/element/drawing-images-to-the-canvas broke when implementing the spec as written. After some investigation and an attempt to "fix" the tests in https://github.com/web-platform-tests/wpt/pull/5060 it was decided that the spec is too different to existing behavior when setting the src attribute for it to be implementable.

The current status of the issue is recorded in various bugs and spec issues:

https://bugzilla.mozilla.org/show_bug.cgi?id=1076583
https://github.com/whatwg/html/issues/2429
https://github.com/whatwg/html/issues/4884
https://github.com/whatwg/html/issues/1872 

Having a usable specification of fundamental platform features is required to avoid compat hazards and ensure that all implementations are able to converge on the same behaviour. It also opens the door to confidently adding future functionality without worrying that differences between the spec and implementations may lead to problems when it comes to shipping the features.

### Investigation Roadmap

* Write test cases to cover edge cases of image loading, including observed regressions from implementing the current spec.
* Run the tests cross-browser to find existing areas of difference.
* Agree on a model and use it to derive "correct" behaviour for each test.
* Use telemetry, archive crawls, experimental implementation, etc. to provide supporting data for the web compatibility of the proposed model.
* Write up the proposal as a PR to the HTML spec.

**Comment by nairnandu** [comment]
Thank you for proposing Non-responsive image loading for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. We believe this investigation is out of scope for Interop 2023. We encourage you to start a conversation with the WHATWG to get any issues resolved.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
