### ISSUE TITLE
MDN short surveys design

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#196]
I have proposed to run short surveys on MDN to get some additional signals on the relative interest in the different features being proposed for Interop 2023.

**This is not the only input for Interop 2023, just one more data point, and will have its blind spots.**

We have a lot of proposals, and some of them have a very different target audience. Most of MDNs page views are for JavaScript reference docs like `Array`, so asking all MDN visitors about all features is not practical. Instead I've tried to created groups and targeting based on topic.

In the lists below, the survey wording is the first level and the proposals these map to (**not shown in survey**) is in a nested level. This is inherently an imperfect mapping, and wording choice can affect the results.

## Prompt and Question

Survey prompt before expanding: "Browser vendors are working together to improve feature support across browsers. Shape the future of the web by taking this 1-question survey!"

(I'm open to toning down the "Shape the future of the web" bit.)

Question: "For your needs as a developer, which features should be improved across browsers in the coming year? This means enabling support or fixing bugs. Please rank up to 5. (This is not a complete list, other features may also be planned.)"

## CSS & HTML

For pages under [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) and [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML), show this list:

- CSS attribute references (`attr()` function)
  - https://github.com/web-platform-tests/interop/issues/86
- CSS `backdrop-filter` property
  - https://github.com/web-platform-tests/interop/issues/210
- CSS `:blank` and `:empty` pseudo-classes
  - https://github.com/web-platform-tests/interop/issues/179
- CSS color font feature detection and palettes
  - https://github.com/web-platform-tests/interop/issues/164
- CSS color spaces and functions (`color()`, `lab()`, gradients, etc.)
  - https://github.com/web-platform-tests/interop/issues/109
  - https://github.com/web-platform-tests/interop/issues/168
  - https://github.com/web-platform-tests/interop/issues/226
- CSS containment (`contain`, `contain-intrinsic-size`, `content-visibility`)
  - https://github.com/web-platform-tests/interop/issues/189
- CSS custom properties (`@property`)
  - https://github.com/web-platform-tests/interop/issues/158
- CSS `:dir()` pseudo-class
  - https://github.com/web-platform-tests/interop/issues/177
- CSS `outline` property (including `outline-color`)
  - https://github.com/web-platform-tests/interop/issues/166
- CSS images (`border-image`, `image()`, `image-set()`)
  - https://github.com/web-platform-tests/interop/issues/144
  - https://github.com/web-platform-tests/interop/issues/146
  - https://github.com/web-platform-tests/interop/issues/153
- CSS `leading-trim` property
  - https://github.com/web-platform-tests/interop/issues/155
- CSS `mask` property (`mask-image`, `mask-mode`, etc.)
  - https://github.com/web-platform-tests/interop/issues/148
- CSS math functions (`round()`, `sin()`, `pow()`, `abs()`, etc.)
  - https://github.com/web-platform-tests/interop/issues/149
- CSS motion path (`offset-path`, `offset-distance`, etc.)
  - https://github.com/web-platform-tests/interop/issues/227
- CSS media queries range syntax (example: `@media screen and (428px < width < 744px)`)
  - https://github.com/web-platform-tests/interop/issues/141
  - https://github.com/web-platform-tests/interop/issues/154
- CSS  `:nth-child()` pseudo-class with selector-list argument
  - https://github.com/web-platform-tests/interop/issues/225
- CSS scoping (`@scope` at-rule)
  - https://github.com/web-platform-tests/interop/issues/183
- CSS Typed Object Model (`computedStyleMap()` API)
  - https://github.com/web-platform-tests/interop/issues/163
- CSS `:user-invalid` and `:user-valid` pseudo-classes 
  - https://github.com/web-platform-tests/interop/issues/178
  - https://github.com/web-platform-tests/interop/issues/180
- Custom Paint API (Paint Worklet)
  - https://github.com/web-platform-tests/interop/issues/160

## APIs & JavaScript

For pages under [API](https://developer.mozilla.org/en-US/docs/Web/API) and [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript), show this list:

- Canvas text rendering
  - https://github.com/web-platform-tests/interop/issues/159
- Clipboard API (`navigator.clipboard`)
  - https://github.com/web-platform-tests/interop/issues/143
- Editing (`contenteditable`)
  - https://github.com/web-platform-tests/interop/issues/188
- File System (`navigator.storage.getDirectory()`)
  - https://github.com/web-platform-tests/interop/issues/172
- History API (`window.history`)
  - https://github.com/web-platform-tests/interop/issues/199
- Import Maps
  - https://github.com/web-platform-tests/interop/issues/184
- Intersection Observer
  - https://github.com/web-platform-tests/interop/issues/173
- Navigation API (`window.navigation`)
  - https://github.com/web-platform-tests/interop/issues/200
- OffscreenCanvas
  - https://github.com/web-platform-tests/interop/issues/161
- Pointer Events
  - https://github.com/web-platform-tests/interop/issues/202
- Priority Hints (`fetchpriority` HTML attribute)
  - https://github.com/web-platform-tests/interop/issues/223
- Push notifications
  - https://github.com/web-platform-tests/interop/issues/218
- Storage quota estimation (`navigator.storage.estimate()`)
  - https://github.com/web-platform-tests/interop/issues/221
- Temporal API
  - https://github.com/web-platform-tests/interop/issues/169
- URL (parsing and API)
  - https://github.com/web-platform-tests/interop/issues/145
- User agent client hints (`navigator.userAgentData`)
  - https://github.com/web-platform-tests/interop/issues/219
- Web Codecs (`AudioDecoder`, `VideoDecoder`, etc.)
  - https://github.com/web-platform-tests/interop/issues/175
- Web Components (custom elements, Shadow DOM, etc.)
  - https://github.com/web-platform-tests/interop/issues/181
  - https://github.com/web-platform-tests/interop/issues/203
  - https://github.com/web-platform-tests/interop/issues/204
  - https://github.com/web-platform-tests/interop/issues/206
  - https://github.com/web-platform-tests/interop/issues/207
  - https://github.com/web-platform-tests/interop/issues/208
  - https://github.com/web-platform-tests/interop/issues/212
  - https://github.com/web-platform-tests/interop/issues/216
- WebTransport
  - https://github.com/web-platform-tests/interop/issues/186

## Not Included

These proposals aren't included, for a variety of reasons:

- https://github.com/web-platform-tests/interop/issues/64 (hard to explain succinctly)
- https://github.com/web-platform-tests/interop/issues/114 (https://github.com/web-platform-tests/interop/issues/196#issuecomment-1294024370)
- https://github.com/web-platform-tests/interop/issues/133 (already have strong signals, likely to dominate results if included)
- https://github.com/web-platform-tests/interop/issues/134 (already have strong signals, likely to dominate results if included)
- https://github.com/web-platform-tests/interop/issues/135 (https://github.com/web-platform-tests/interop/issues/196#issuecomment-1294723206)
- https://github.com/web-platform-tests/interop/issues/142 (hard to explain the exact scope)
- https://github.com/web-platform-tests/interop/issues/152 (https://github.com/web-platform-tests/interop/issues/196#issuecomment-1290713702)
- https://github.com/web-platform-tests/interop/issues/165 (target audience is mainly automation frameworks, not general web developers)
- https://github.com/web-platform-tests/interop/issues/167 (hard to explain succinctly)
- https://github.com/web-platform-tests/interop/issues/171 (too small?)
- https://github.com/web-platform-tests/interop/issues/174 (already supported, unclear if there are bugs)
- https://github.com/web-platform-tests/interop/issues/176 (unclear which bucket makes sense)
- https://github.com/web-platform-tests/interop/issues/182 (unclear which bucket makes sense)
- https://github.com/web-platform-tests/interop/issues/185 (investigation effort)
- https://github.com/web-platform-tests/interop/issues/187 (mix of features)
- https://github.com/web-platform-tests/interop/issues/192 (this limitation is probably not widely known)
- https://github.com/web-platform-tests/interop/issues/193 (new feature, likely to be conflated with flex gap)
- https://github.com/web-platform-tests/interop/issues/195 (hard to explain succinctly)
- https://github.com/web-platform-tests/interop/issues/197 (unclear which bucket makes sense)
- https://github.com/web-platform-tests/interop/issues/201 (test infrastructure)
- https://github.com/web-platform-tests/interop/issues/211 (not web exposed, affects users, not developers?)
- https://github.com/web-platform-tests/interop/issues/213 (network feature, unclear which bucket makes sense)
- https://github.com/web-platform-tests/interop/issues/214 (very broad, like MathML unclear which bucket)
- https://github.com/web-platform-tests/interop/issues/215 (investigation effort)
- https://github.com/web-platform-tests/interop/issues/217 (network feature, doesn't fit either bucket)
- https://github.com/web-platform-tests/interop/issues/220 (unlikely to be recognized by web developers, not documented anywhere yet?)
- https://github.com/web-platform-tests/interop/issues/222 (could be included under APIs, but hit limit of 20)
- https://github.com/web-platform-tests/interop/issues/224 (could be included under CSS, but hit limit of 20)

**Comment by captainbrosset** [comment]
Just a thought: should highly requested features like Container Queries or `:has` be removed? I think we already know developers want them, and they will probably dwarf all of the other features in the survey.

**Comment by foolip** [comment]
@captainbrosset I think those two are indeed the two that will be the most popular choices, based on State of CSS results. The question becomes if people will notice the glaring omissions and conclude our survey is nonsense and abandon. And to what extent will this be mitigated by saying it's not a complete list?

**Comment by foolip** [comment]
As for the wording, my suggestion is:

Survey prompt before expanding: "Browser vendors are working together to improve CSS support across browsers. Shape the future of CSS by taking this 1-question survey!"

Question: "Which CSS features would you most like to see implemented or improved across browsers in the coming year? Please rank up to 3. (This is not a complete list, other features may also be planned.)"

I don't think it's helpful to name Interop 2023 explicitly, so no links in the above.

The survey would be randomly shown to a subset of visitors to CSS sections on MDN. We can have some input into how many developers see the survey, but expect on the order of 500 or less, not thousands.

**Comment by foolip** [comment]
I've updated this issue to describe two targeted surveys. It's hard to make a perfect split and two features are listed in both, while others aren't included in either. Open to feedback. I think we shouldn't exceed 20 options for either survey, that starts to be unreasonable.

**Comment by foolip** [comment]
I want to highlight a few things I think are tricky for discussion in https://github.com/web-platform-tests/interop/issues/209:
- Should Web Components be broken down further? I can't see how, and suspect developers don't know the names of all the parts, or use different terminology than I would come up with.
- Should we ask about AVIF and JPEG XL support?
- Should we ask about MathML?

**Comment by jgraham** [comment]
Being asked to compare fixing existing features with adding new features is quite strange e.g. the "History API" proposal is mostly fixing existing features and is only somewhat related to the `location` object. There's also a number of other problems here e.g. we know that editing APIs are so complex that editing basically has to be implemented using additional js libraries, so I wouldn't expect those things to come up very high, but that doesn't mean that work to make those libraries more reliable isn't going to make the web better for users.

Also the options aren't very fungible on the browser side; although maybe the CSS-* features are more or less the same team, there isn't a prioritisation decision to be made on those features vs e.g. clipboard APIs because different people would do the work.

Overall I'm not sure that the premise of having a survey that maps ~ 1:1 with proposals is really likely to give us data that is unambigously useful.

**Comment by tapananand** [comment]
Just a thought regarding exclusion of https://github.com/web-platform-tests/interop/issues/213 from the survey, I think the developer impact here primarily is not being able to use WebAssembly threads and SharedArrayBuffer, so could that be considered under the JavaScript category similar to other things like WebNN or WebTransport?

**Comment by foolip** [comment]
I've updated the proposal again, keeping to 20 options in each survey. Some hard and subjective calls were required, and in the end I had to just omit some features like https://github.com/web-platform-tests/interop/issues/224 because there was no obvious other option to remove instead.

When reviewing or proposing changes, when suggesting an addition, please also suggest a removal so that we stick to 20.

**Comment by foolip** [comment]
@tapananand sorry I didn't respond earlier. I think both WebAssembly and SharedArrayBuffer would be recognizable options to developers, but also much broader than what's proposed in https://github.com/web-platform-tests/interop/issues/213. If we did have a strong signal that wasm (for example) was important, I'm therefore not sure how to use that signal. We have this problem to some degree in other cases as well, like "CSS color functions" actually being more broad than what is proposed as an addition for Interop 2023. I've done as well as I could with the proposal now, but recognize it's imperfect. It's still open to suggestions though.

**Comment by foolip** [comment]
OK, so now tweaking the question a bit in response to https://github.com/web-platform-tests/interop/issues/209, @jensimmons's feedback in particular. I suggest:

> For your needs as a developer, which features should be improved across browsers in the coming year? This means enabling support or fixing bugs. Please rank up to 3. (This is not a complete list, other features may also be planned.)

Regarding "Please rank up to 3", I've learned that we can pick another number. Given that we now have 20 options in each survey, I suggest we allow up to 5 choices instead.

**Comment by nt1m** [comment]
@foolip #225 and #224 could be grouped under the "CSS pseudo-classes" category.

**Comment by foolip** [comment]
@nt1m the pseudo-classes are a bit of an odd category already, and the existing ones (`:blank`, `:empty`, `:modal`, `:user-invalid`, `:user-valid`) aren't really a natural grouping, but I thought it'd be better than listing them individually or not at all. It would be a very long list if we add in https://github.com/web-platform-tests/interop/issues/225 and https://github.com/web-platform-tests/interop/issues/224.

I do actually think that both https://github.com/web-platform-tests/interop/issues/225 and https://github.com/web-platform-tests/interop/issues/224 are more likely to be recognized and picked than at least https://github.com/web-platform-tests/interop/issues/114, so if we could find one additional optional to remove, we could add them both separately. We'd also need to rename the existing option for pseudo-classes I think, but not sure to what?

**Comment by foolip** [comment]
There are staging links for the two surveys now for review:
- https://survey.alchemer.com/collab/7081564/MDN-Interop-2023-CSS-HTML
- https://survey.alchemer.com/collab/7081727/MDN-Interop-2023-APIs-JavaScript

@web-platform-tests/interop please review. (I'll put this on Thursday's agenda as well.)

**Comment by nt1m** [comment]
@foolip Thanks for putting these together! Here are my initial thoughts:
* "Web Components" should only be in one of the two surveys, possibly just the JS one (most the APIs involve JS)
* "Custom Paint API" should only be in one of the two surveys, possibly just the CSS one
* "Neural Network API" I doubt that is going to be part of next year's effort, due to the early stage of the spec and the fact that it's difficult to test, so I'd rather leave it out for something that is more likely going to get in.
* CSS color spaces or CSS images could include gradient color space interpolation (issue #109)
* I think issue #225 could actually fit in "CSS pseudo-classes" as ":nth-child() with selector-list argument" as it's an extension to existing pseudo-classes.

**Comment by foolip** [comment]
We discussed this in https://github.com/web-platform-tests/interop/issues/240 and agreed to the following changes:
- "Web Components" only in APIs & JavaScript
- "Custom Paint API" only in CSS & HTML
- Drop "Neural Network API"

Then I was to work through the last two bullets and suggest on the issue. Here are my suggestions.

Change the wording from:

> CSS color functions (`color()`, `lab()`, etc.)

to:

> CSS color spaces and functions (`color()`, `lab()`, gradients, etc.)

The final bullet is the trickiest. The pseudo-class option is currently:

> CSS pseudo-classes (`:blank`, `:empty`, `:modal`, `:user-invalid`, `:user-valid`)

It's already stretching what's reasonable to group, and if this options ranks highly we'll have to do a bit of guessing about which pseudo-classes drew the attention. Adding `:nth-child()` makes this even harder, but here's what it would look like:

> CSS pseudo-classes (`:blank`, `:empty`, `:modal`, `:user-invalid`, `:user-valid`, `:nth-child()` with selector-list argument)

I think my best suggestion in the end is to split it like this:

- CSS `:blank` and `:empty` pseudo-classes
- CSS `:user-invalid` and `:user-valid` pseudo-classes 
- CSS  `:nth-child()` pseudo-class with selector-list argument

That would push the total option count to 21, so we'd remove the `speak-as` option, as the one I _guess_ will have the least recognition of all the options. (Accessibility is first and foremost a user need and also a developer specialization, so judging its importance by overall web developer demand is hard.)

@nt1m between the different options for pseudo-classes, do you have a preference?

**Comment by foolip** [comment]
Given time constraints I'll make a decision myself, to split pseduo-classes into 3 and drop `speak-as`. The `:modal` pseudo class also won't be listed, it's a small fix to implement and I think the case for it is strong without survey results. (We're planning to support https://github.com/web-platform-tests/interop/issues/135.)

**Comment by foolip** [comment]
I've made the updates now. Since there was now room in the API section, I added "Storage quota estimation (`navigator.storage.estimate()`)"

**Comment by foolip** [comment]
This survey is now live on MDN, as "pick up to 5" questions.

**Comment by romainmenke** [comment]
@foolip Where and how was this shared?
Is there a way to be notified of surveys like these?

**Comment by foolip** [comment]
@romainmenke I got the results from MDN via email and posted them to https://github.com/web-platform-tests/interop/issues/245 + https://github.com/web-platform-tests/interop/issues/246, so that's how they were shared this time. Mozilla is still working on the process for MDN short surveys, and this was only the 3rd such survey, so it's still in "beta" it's fair to say.

There's also a newly formed [WebDX Community Group](https://www.w3.org/blog/2022/11/webdx-improving-the-experience-for-web-developers/) where we're collaborating on research like this, and https://github.com/web-platform-dx/developer-research/issues/9 is the issue to follow for how we intend to make results public by default, not just via ad-hoc GitHub issues like I've done here. Please consider joining the CG if that sort of thing interests you!

**Comment by romainmenke** [comment]
> Please consider joining the CG if that sort of thing interests you!

Joined :)
Thank you for sharing this.
