### ISSUE TITLE
Score for each Focus Area

### ISSUE THREAD

**Issue by karlcow** [web-platform-tests/interop#198]
Should there be a 4th column with a score for the feature?
 
The condition for the score should be that each tests is a PASS for the 3 browsers. If any test fails in one or more browsers, it is not being counted.

So For example Focus Area 2022 for Cascade Layers.
As of today, there are:
1 FAIL for Chrome
2 FAIL for Firefox
0 FAIL for Safari
on 31 tests

Cascade Layers: 90% (28/31)
Color Spaces and Functions: 43% (88/203)
etc.

**Comment by foolip** [comment]
This was implemented as the INTEROP score in the Interop 2023 dashboard, see https://wpt.fyi/interop-2023
