### ISSUE TITLE
The navigation API

### ISSUE THREAD

**Issue by domenic** [web-platform-tests/interop#200]
### Description

This proposal is about getting interop on the [navigation API](https://github.com/WICG/navigation-api), which provides a much cleaner model for history and navigation and some new capabilities developers have requested. (This spec is currently in the WICG, but will be merged into the HTML Standard in October.)

### Rationale

Navigation and history has historically been a large pain for developers; see some of the discussion in #199. The navigation API solves many of these issues by its design. Quantitatively, it has [second-most](https://github.com/WICG/proposals/issues?q=is%3Aissue+sort%3Areactions-%2B1-desc+) of any WICG proposal to date.

### Specification

All contents of https://wicg.github.io/navigation-api/, which will be part of HTML's  "Loading web pages" section in October.

### Tests

[`navigation-api/`](https://wpt.fyi/results/navigation-api?label=experimental&label=master&aligned&view=subtest) (this will be moved into `html/browsers/` in ~October)

**Important note:** wpt.fyi is especially fragile for these sorts of tests, often giving incorrect failures. (I.e., failures that don't match what a user sees by loading the corresponding test in the browser on wpt.live.) See https://github.com/web-platform-tests/wpt/issues/33590. Fixing this would probably need to be a priority for the wpt.fyi infrastructure team, to make this project feasible.

**Comment by tbondwilkinson** [comment]
The Navigation API is P2 for Google's [closure library](https://github.com/google/closure-library).

"We have a goog.history API that could probably be simplified or obviated entirely. This is also a point of confusion for many developers."

**Comment by gsnedders** [comment]
> All contents of https://wicg.github.io/navigation-api/, which will be part of HTML's "Loading web pages" section in October.

It is now November, and I still [can't see any issue or PR referencing this](https://github.com/whatwg/html/issues?q=%22navigation+api%22).

**Comment by domenic** [comment]
Apologies, we're running a week or so behind schedule! My understanding was that the true deadline was December 31, 2022, but we're working as fast as we can to be done well in advance of that.

**Comment by foolip** [comment]
This case is similar to https://github.com/web-platform-tests/interop/issues/235#issuecomment-1297244086, where I suggested that people can express conditional support. The proposal selection period is during November, and Nov 17 is our deadline for positions, so you can think of that as a deadline for when folks will want confidence that any outstanding spec and test work is going to be done.

It's still an individual judgement, so if there's anyone who's on the fence, spelling out here what you're looking for would be very helpful.

**Comment by gsnedders** [comment]
Yeah, there's no hard deadline, _but_ having some issue tracking it to easily check on the status would be nice!

**Comment by tbondwilkinson** [comment]
Navigation API is P1 for Google's internal web framework

"Reduce gaps in existing History API, significantly simplify internal framework code for navigation, new browser features and behavior for navigations."

**Comment by foolip** [comment]
In the [MDN short survey on APIs & JavaScript](https://github.com/web-platform-tests/interop/issues/246), "Navigation API (`window.navigation`)" was selected by ~18% of survey takers, putting it in the middle third of options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/246#issuecomment-1312098410) as with any survey data.)

**Comment by nairnandu** [comment]
Thank you for proposing Navigation API for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. We had many strong proposals, and could not accept them all. This should not be taken as a comment on the technology as a whole, and resubmitting a proposal for this feature as part of a future round of Interop would be welcome.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
