### ISSUE TITLE
Form-Associated Custom Elements

### ISSUE THREAD

**Issue by Westbrook** [web-platform-tests/interop#203]
### Description

The form-associated custom elements APIs enable custom elements to participate in form submission and validation lifecycles.

This agreed upon spec is not fully delivered cross browser. Following the Web Platform Test link below, you will find the it is currently missing in Safari and suffers from a number of failures in Firefox.

### Rationale

- Enable custom elements to participate in form submission by adding a value to the FormData object, adding to the HTMLFormElement.prototype.elements object and in other submission formats.
- Enables custom elements to participate in the form validation lifecycle by providing APIs similar to and building on top of the constraint validation APIs.

### Specification

https://html.spec.whatwg.org/multipage/custom-elements.html#form-associated-custom-elements

### Tests

https://github.com/web-platform-tests/wpt/tree/master/custom-elements/form-associated

**Comment by karlcow** [comment]
[WebKit Bug](https://bugs.webkit.org/show_bug.cgi?id=197963)

**Comment by josepharhar** [comment]
Here is some potentially additional description and rationale: https://w3c.github.io/webcomponents-cg/#form-associated-custom-elements

In addition to the `custom-elements/form-associated` directory in WPT, I believe that these tests also test form-associated custom elements:
- https://wpt.fyi/results/custom-elements/element-internals-shadowroot.html
- https://wpt.fyi/results/custom-elements/HTMLElement-attachInternals.html

**Comment by hsinyi** [comment]
Based on the discussion with @jcsteh , we'd like to exclude the ones tested with `ARIA idref` attributes under https://wpt.fyi/results/custom-elements/form-associated/ElementInternals-accessibility.html

We are interested in keeping the `non-idref` part in the scope. However, there appear to be open spec issues for this part : 
https://github.com/w3c/aria/issues/1110
https://github.com/w3c/aria/issues/1239

How likely is it that we can get consensus on the spec issues before the start of the Interop period?

**Comment by josepharhar** [comment]
I am happy to drop ElementInternals-accessibility.html or separate subtests of it if needed. I don't have context on those aria issues and I don't know how likely they are to be resolved before the start of the interop period.

**Comment by domenic** [comment]
> Based on the discussion with @jcsteh , we'd like to exclude the ones tested with `ARIA idref` attributes under https://wpt.fyi/results/custom-elements/form-associated/ElementInternals-accessibility.html

Honestly this test seems to be in the wrong directory. It is not related to form-associated custom elements and should be in the parent directory.

**Comment by josepharhar** [comment]
> Honestly this test seems to be in the wrong directory. It is not related to form-associated custom elements and should be in the parent directory.

Sound good to me, I created a PR to do it: https://github.com/web-platform-tests/wpt/pull/36875

**Comment by foolip** [comment]
In the [MDN short survey on APIs & JavaScript](https://github.com/web-platform-tests/interop/issues/246), "Web Components (custom elements, Shadow DOM, etc.)" was the most popular choice by a fairly wide margin, selected by ~39% of survey takers.

Web Components was split into many granular proposals, and the survey results don't tell us which aspects web developers want the most, but it's fair to say that _something_ about Web Components is important. (I'm posting this comment on each of the split proposals.)

**Comment by nairnandu** [comment]
Thank you for proposing Form-Associated Custom Elements for inclusion in Interop 2023.

We are pleased to let you know that this proposal was accepted as part of the Web Components focus area. You can follow the progress of this Focus Area on the [Interop 2023 dashboard](https://wpt.fyi/interop-2023).

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you for contributing to Interop 2023!

_Posted on behalf of the Interop team._
