### ISSUE TITLE
Constructable Stylesheets & adoptedStyleSheets

### ISSUE THREAD

**Issue by Westbrook** [web-platform-tests/interop#204]
### Description

[Constructable Stylesheets](https://wicg.github.io/construct-stylesheets/) and adoptedStyleSheets enable adding styles directly to DOM trees, e.g. document and shadow roots, without creating new DOM elements. Because a single stylesheet object can be adopted by multiple scopes, it also allows sharing of styles that can be centrally modified.

General consensus; shipped in both [Chrome](https://web.dev/constructable-stylesheets/) and [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1520690), not available in Safari

### Rationale

- There is no effective way to share styles across components while allowing them to be centrally modified.
- Creating <style> elements for each style used in each shadow root has a measurable performance overhead.
- CSS Module Scripts, another critical feature, depends on constructible stylesheets.

### Specification

https://w3c.github.io/csswg-drafts/cssom-1/

### Tests

Those including "constructable" in https://github.com/web-platform-tests/wpt/tree/master/css/cssom

**Comment by gsnedders** [comment]
> https://wicg.github.io/construct-stylesheets/

This should be https://w3c.github.io/csswg-drafts/cssom-1/ (see https://github.com/WICG/construct-stylesheets/issues/140).

**Comment by Westbrook** [comment]
Interesting.

For my understanding, "csswg-drafts" feels less _official_, is that just my interpretation, or does this difference actually say something about the progress of this spec at large?

**Comment by jogibear9988** [comment]
Link to Webkit Bug:

https://bugs.webkit.org/show_bug.cgi?id=228684

**Comment by jogibear9988** [comment]
Maybe this Bug also: 
https://bugs.webkit.org/show_bug.cgi?id=231054

**Comment by gsnedders** [comment]
> Interesting.
> 
> For my understanding, "csswg-drafts" feels less _official_, is that just my interpretation, or does this difference actually say something about the progress of this spec at large?

In principle the WICG is a group in which specifications are incubated, which then get moved into a working group (such as the CSS WG) which standardises them.

**Comment by josepharhar** [comment]
Here is some potentially additional description and rationale: https://w3c.github.io/webcomponents-cg/#constructable-stylesheets-adoptedstylesheets
Here is a WPT link which should hopefully give us the right tests: https://wpt.fyi/results/css/cssom?label=experimental&label=master&aligned&view=subtest&q=adopt%20or%20construct

**Comment by foolip** [comment]
In the [MDN short survey on APIs & JavaScript](https://github.com/web-platform-tests/interop/issues/246), "Web Components (custom elements, Shadow DOM, etc.)" was the most popular choice by a fairly wide margin, selected by ~39% of survey takers.

Web Components was split into many granular proposals, and the survey results don't tell us which aspects web developers want the most, but it's fair to say that _something_ about Web Components is important. (I'm posting this comment on each of the split proposals.)

**Comment by nairnandu** [comment]
Thank you for proposing Constructable Stylesheets & adoptedStyleSheets for inclusion in Interop 2023.

We are pleased to let you know that this proposal was accepted as part of the Web Components focus area. You can follow the progress of this Focus Area on the [Interop 2023 dashboard](https://wpt.fyi/interop-2023).

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you for contributing to Interop 2023!

_Posted on behalf of the Interop team._
