### ISSUE TITLE
Add subtotals to the 2022 dashboard 

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/interop#205]
It's very confusing to everyone that a browser could pass 96.4% of the tests, but only have an 88 score. For 2023, we should redesign how we display the data. But meanwhile, for 2022, could we please add subtotals for each section. 

Perhaps like this:
![image](https://user-images.githubusercontent.com/108474/195371073-d917819b-034c-4f35-a52b-7a0ae26ddb73.png)

It's incredible discouraging to be closing in on 100%, having put in a lot of effort, only to have that effort be basically invisible. 84 or 88 sounds like each browser has a long way to go to fix their bugs and implement missing features. Which is misleading.

**Comment by foolip** [comment]
@DanielRyanSmith do you think this would be easy to implement?

**Comment by DanielRyanSmith** [comment]
Yes, this should be a relatively straightforward change 👍

**Comment by DanielRyanSmith** [comment]
I'm working on this today. Do we want to show a subtotal for the investigation scores? For example:
![Screen Shot 2022-10-19 at 10 24 56 AM](https://user-images.githubusercontent.com/56164590/196764750-45f237d6-3759-4c5f-944b-c052d00b141c.png)
I added this subtotal row initially, but I can revert it as desired.

**Comment by jensimmons** [comment]
This looks great. I do believe the Focus areas should have a subtotal, too. (The original drawing didn't only because it was something someone made quickly to make a point in another context.)
