### ISSUE TITLE
CSS Module Scripts

### ISSUE THREAD

**Issue by Westbrook** [web-platform-tests/interop#206]
### Description

CSS Module Scripts allow JavaScript modules to import style sheets. They can then be applied to a document or shadow root using adoptedStyleSheets in the same way as constructible style sheets.

Not currently available cross browser (Safari) effecting adoption.

### Rationale

- CSS modules will allow styles to be loaded in component definitions without adding <style> or <link> elements that need to be created in each element instance.
- Authors today often use inlined CSS strings in JS modules, but many of them want to move the CSS into separate .css files.
- Without CSS-in-JS it's difficult to ensure that CSS is loaded before the component is defined and rendered. CSS module scripts provide the same ordering guarantee.
- Component authors may need to import a resource that is only available as an external .css file, and don't have control over the resource to wrap it in a JS module.

### Specification

https://github.com/tc39/proposal-import-assertions

### Tests

https://github.com/tc39/test262/commit/18834b2e19f46a05efa766c4013c98af8ef9acc3

**Comment by gsnedders** [comment]
> ### Specification
> https://github.com/tc39/proposal-import-assertions

The integration for CSS modules is defined in HTML, too, IIRC.
 
> ### Tests
> [tc39/test262@18834b2](https://github.com/tc39/test262/commit/18834b2e19f46a05efa766c4013c98af8ef9acc3)

These all just appear to be the general import assertions tests, nothing specifically about CSS modules?

**Comment by Westbrook** [comment]
Yep, while CSS is spec'd and agreed to, I'm not sure any tests have been added for it, specifically.

**Comment by jogibear9988** [comment]
And the Sfari Bug for this:
https://bugs.webkit.org/show_bug.cgi?id=227967

**Comment by jogibear9988** [comment]
I think in Firefox they are also not yet ready:
https://bugzilla.mozilla.org/show_bug.cgi?id=1720570

**Comment by foolip** [comment]
Tests are here:
https://wpt.fyi/results/html/semantics/scripting-1/the-script-element/css-module?label=experimental&label=master&aligned

**Comment by annevk** [comment]
This is part of #236 in a way and I have the same concern here with https://github.com/whatwg/html/issues/7233 not being sorted. I'd really like to have clarity around CSP first.

**Comment by emilio** [comment]
It'd also be good to know whether they are intended to be de-duplicated etc, see https://github.com/WICG/webcomponents/issues/870 etc.

**Comment by foolip** [comment]
In the [MDN short survey on APIs & JavaScript](https://github.com/web-platform-tests/interop/issues/246), "Web Components (custom elements, Shadow DOM, etc.)" was the most popular choice by a fairly wide margin, selected by ~39% of survey takers.

Web Components was split into many granular proposals, and the survey results don't tell us which aspects web developers want the most, but it's fair to say that _something_ about Web Components is important. (I'm posting this comment on each of the split proposals.)

**Comment by nairnandu** [comment]
Thank you for proposing CSS Module Scripts for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. As discussed in the issue comments, there are still open spec questions around CSP. To make progress on this area in the future it will first be necessary to ensure that the feature has a clear specification in a standards track document. We would be happy to see the proposal submitted for a future round of Interop once these spec questions are resolved.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._

**Comment by jogibear9988** [comment]
The proposal is already in the html spec (i think)

**Comment by annevk** [comment]
Correct, but it has known issues as pointed out [above](https://github.com/web-platform-tests/interop/issues/206#issuecomment-1295176255).

**Comment by jogibear9988** [comment]
And seem to be downgraded to stage 2
https://dev.to/hemanth/updates-from-the-94th-tc39-meeting-48mb
https://docs.google.com/presentation/d/1HbWhyo4tSnpv4vMZqCa2YQvi_mKdpDi4JWWBtSUQqQY/edit#slide=id.p
