### ISSUE TITLE
Imperative Slot Assignment

### ISSUE THREAD

**Issue by Westbrook** [web-platform-tests/interop#207]
### Description

The ability to imperatively assign content to a `<slot>` element is available in Chrome and Firefox, and while merged in WebKit not currently available in Safari.

### Rationale

Some of the scenarios called out in the proposal include not having to pre-compute the slot names ahead of time, as well as being able to conditionally load content into a slot.

### Specification

https://github.com/whatwg/html/pull/6561

### Tests

- In WPT: https://wpt.fyi/results/shadow-dom/slots-imperative-slot-api.tentative.html?label=master&label=experimental&aligned&q=slots-imperative-slot-api.tentative.html
- In WPT: [https://wpt.fyi/results/shadow-dom/slots](https://wpt.fyi/results/shadow-dom/slots-imperative-api-slotchange.tentative.html?label=master&label=experimental&aligned)

**Comment by gsnedders** [comment]
> ### Tests
> * In WPT: https://wpt.fyi/results/shadow-dom/slots-imperative-slot-api.tentative.html?label=master&label=experimental&aligned&q=slots-imperative-slot-api.tentative.html
> * In WPT: [https://wpt.fyi/results/shadow-dom/slots](https://wpt.fyi/results/shadow-dom/slots-imperative-api-slotchange.tentative.html?label=master&label=experimental&aligned)

Maybe https://wpt.fyi/results/shadow-dom?label=master&label=experimental&aligned&view=subtest&q=imperative%20slot%20path%3A%2Fshadow-dom (the other two don't seem to point at anything at this point)?

**Comment by foolip** [comment]
In the [MDN short survey on APIs & JavaScript](https://github.com/web-platform-tests/interop/issues/246), "Web Components (custom elements, Shadow DOM, etc.)" was the most popular choice by a fairly wide margin, selected by ~39% of survey takers.

Web Components was split into many granular proposals, and the survey results don't tell us which aspects web developers want the most, but it's fair to say that _something_ about Web Components is important. (I'm posting this comment on each of the split proposals.)

**Comment by nairnandu** [comment]
Thank you for proposing Imperative Slot Assignment for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year.  We looked at the results in WPT, and found that this feature is already largely interoperable between browsers.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
