### ISSUE TITLE
Scroll-behavior & overscroll-behavior

### ISSUE THREAD

**Issue by una** [web-platform-tests/interop#21]
**Description**
The scroll-behavior CSS property sets the behavior for a scrolling box when scrolling is triggered by the navigation or CSSOM scrolling APIs. 
- [MDN Link -- Scroll Behavior](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior)
- [MDN Link -- Overscroll Behavior](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior)

**Specification**
[CSSOM View Module](https://www.w3.org/TR/cssom-view-1/)

**Tests**
- scroll-behavior -- need to find tests
- [Overscroll-behavior](https://wpt.fyi/results/css/css-overscroll-behavior?label=master&label=experimental&aligned&q=css%20scroll)

**Rationale**
- Identified as a pain point in [MDN 2020 Browser Compatibllity Report](https://insights.developer.mozilla.org/reports/mdn-browser-compatibility-report-2020.html) (Scrolling, smooth animations -- 19% feedback + interviews)
- Identified as a [top compat pain point](https://github.com/web-platform-tests/interop-2022/issues/7) in State of CSS 2021 (2nd under [subgrid](#1) for cross-browser support)

**Comment by gsnedders** [comment]
> scroll-behavior -- need to find tests

https://wpt.fyi/results/css/cssom-view?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=scroll-behavior

**Comment by foolip** [comment]
@flackr can you help judge if the tests here are sufficient? There are tests for both properties, but it's hard for me to tell if they're missing important things.

**Comment by flackr** [comment]
It looks like we don't have any tests of the difference between `overscroll-behavior: contain` and `overscroll-behavior: none`. There is only a difference on certain platforms - I think Mac, iOS and Android - but we could write tests that pass if there is no observable default scroll overflow behavior on the current platform.

The CSS scroll-behavior tests look sufficient for the CSS property, though I haven't been able to find any that test the JS scrolling APIs with `behavior: smooth`, e.g. `elem.scrollIntoView({behavior: 'smooth'});`. There's [scrollIntoView-smooth.html](https://wpt.fyi/results/css/cssom-view?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=scrollintoview-smooth) however it doesn't seem to have any checks that the scroll is not instant.

**Comment by flackr** [comment]
The proposed list is a good start, though we should work on adding support for the areas I mentioned above:
1. The difference between `overscroll-behavior: contain` and `overscroll-behavior: none` on root and non-root scrollers. E.g. see [crbug.com/1256902](https://bugs.chromium.org/p/chromium/issues/detail?id=1256902).
2. Consider whether we can test that scrollIntoView-smooth.html is smooth reliably? E.g. maybe keep scrolling between 2 points until we observe a scroll that is somewhere in between.

**Comment by foolip** [comment]
A bunch of scrolling tests came up in my analysis in https://github.com/web-platform-tests/interop-2022/issues/48. It spans this issue and https://github.com/web-platform-tests/interop-2022/issues/14, but I'll past the whole comment since the root cause seems shared across the two in one case:

> There are 3 tests that use `new test_driver.Actions().scroll(...)` and either ERROR or TIMEOUT in Firefox/Safari:
> 
> * [/css/css-overscroll-behavior/overscroll-behavior.html](https://wpt.fyi/results/css/css-overscroll-behavior/overscroll-behavior.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is ERROR in both Firefox and Safari.
> * [/css/css-scroll-snap/input/snap-area-overflow-boundary.html](https://wpt.fyi/results/css/css-scroll-snap/input/snap-area-overflow-boundary.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is ERROR in Firefox and TIMEOUT in Safari.
> * [/css/css-scroll-snap/snap-at-user-scroll-end.html](https://wpt.fyi/results/css/css-scroll-snap/snap-at-user-scroll-end.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is ERROR in both Firefox and Safari.
> 
> https://bugzil.la/1746601 is the Gecko bug about this testdriver API. The harness errors can probably be fixed with the proper `t.step_func` wrapping or similar.
> 
> [/css/css-scroll-snap/input/keyboard.html](https://wpt.fyi/results/css/css-scroll-snap/input/keyboard.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is TIMEOUT in Firefox and Safari, but the first test runs and fails in Firefox. I don't think this is due to a missing testdriver.js API, but it needs investigation.
> 
> [/css/cssom-view/scroll-behavior-smooth.html](https://wpt.fyi/results/css/cssom-view/scroll-behavior-smooth.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is ERROR in Chrome and TIMEOUT in Safari. Needs investigation.

**Comment by lilles** [comment]
I wrote the initial tests in /css/cssom-view/scroll-behavior-smooth.html, but tests using fragment navigation and history.back() was added later and they time out because the history behavior is different in Chrome than in Firefox. Seem like a history entry is not added for Chrome and history.back() in that test will navigate out of the test page resulting in a time out.

I split out the navigation tests into a separate scroll-behavior-smooth-navigation.html here: https://chromium-review.googlesource.com/c/chromium/src/+/3403031 and reported an issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=1289222

**Comment by foolip** [comment]
@lilles this raises the question of whether scroll-behavior-smooth-navigation.html should be included in Interop 2022. @flackr can you have a look at this test and give advice?
