### ISSUE TITLE
backdrop-filter

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#210]
### Description

The unprefixed `backdrop-filter` CSS property, which can be used to apply a filter effect to the underlying elements. The most common effect is probably a blur effect, as in this example from MDN:

![image](https://user-images.githubusercontent.com/498917/194866800-eb145e5e-fe2a-471c-9715-00d82da424f7.png)

According to [caniuse.com](https://caniuse.com/css-backdrop-filter) / [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter#browser_compatibility), the property was recently shipped in Firefox, and still requires a prefix in Safari.

### Rationale

_This rationale will be updated when the results of State of CSS 2022 are available._

In [State of CSS 2021](https://2021.stateofcss.com/en-US/opinions/#browser_interoperability_features), `backdrop-filter` was the 6th most common answer to the free-form question “Are there any CSS features you have difficulties using because of differences between browsers?”

In [Chrome’s usage metrics](https://chromestatus.com/metrics/css/timeline/popularity/508), `backdrop-filter` is used on ~16% of page views, and recently saw a sharp increase. (Hypothesis: This was caused by Firefox shipping support.)

While the developer need here is likely mostly met by support in Firefox, the proposal is to sort out the remaining few wrinkles so that developers can depend on `backdrop-filter` without any caveats.

This proposal, if accepted, could perhaps be grouped with other small filter/mask/image-related proposals.

### Specification

https://drafts.fxtf.org/filter-effects-2/#BackdropFilterProperty

### Tests

https://wpt.fyi/results/css/filter-effects?label=master&label=experimental&aligned&view=subtest&q=backdrop-filter

**Comment by karlcow** [comment]
* [WebKit bugs](https://bugs.webkit.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&list_id=8651684&query_format=advanced&short_desc=backdrop-filter&short_desc_type=allwordssubstr)
* [Gecko](https://bugzilla.mozilla.org/buglist.cgi?short_desc=backdrop-filter&list_id=16243316&query_format=advanced&short_desc_type=allwordssubstr&resolution=---)
* [Blink](https://bugs.chromium.org/p/chromium/issues/list?q=summary%3Abackdrop-filter&can=2)

**Comment by foolip** [comment]
Thanks @karlcow! Going through bugs and checking if there are tests seems like a worthwhile exercise.

**Comment by foolip** [comment]
Adding to the rationale, `backdrop-filter ` was a common responses the State of CSS 2022 question about browser incompatibilities, mentioned in ~3% of responses, see https://github.com/web-platform-tests/interop/issues/248.

Representative examples are "Inconsistent backdrop-filter" and "backdrop-filter can be a pain!"

**Comment by foolip** [comment]
In the [MDN short survey on CSS & HTML](https://github.com/web-platform-tests/interop/issues/245), "CSS `backdrop-filter` property" was selected by ~21% of survey takers, putting it in the top third of the 20 options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/245#issuecomment-1311874383) as with any survey data.)

**Comment by nairnandu** [comment]
Thank you for proposing backdrop-filter for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. As of today, backdrop-filter is relatively well supported across all browsers. We have had many strong CSS proposals, and making backdrop-filter more interoperable was judged to be a lower priority than other proposals.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
