### ISSUE TITLE
@font-face and @property constructs in Shadow Roots

### ISSUE THREAD

**Issue by Westbrook** [web-platform-tests/interop#212]
### Description

Whether it is `@font-face` or `@property`, an intersection of confusing spec'ing and partial implementation leaves a number of nice capabilities out of reach of shadow root users. Placing `@font-face` or `@property` within shadow roots is ignored in some browsers degrading the experience of pre-packaged web components cross browser. This is an area where WPT could also be leveraged to support not falling into this same trap with other and future `@` sigil based CSS APIs.

@font-face
- FF bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1077396
- Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=336876

@property
- Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1231135

### Rationale

The code needed to packages a custom element for reuse should be usage within the custom element package.

### Specification

https://github.com/w3c/csswg-drafts/issues/1995

**Comment by gsnedders** [comment]
> Whether is @font-face or @property an intersection of confusing spec'ing and partial implementation leaves a number of nice capabilities out of reach of shadow root users.

I can't understand what this means?

**Comment by gsnedders** [comment]
To be clear, I meant I _literally couldn't understand the sentence_. Like,

> Whether it [what's "it?"] is `@font-face` or `@property` [,] an intersection of confusing spec'ing and partial implementation leaves a number of nice capabilities out of reach of shadow root users.

Is this basically:

> An intersection of confusing spec'ing and partial implementation leaves `@font-face` and `@property` out of reach of shadow root users.

?

**Comment by gsnedders** [comment]
> ### Specification

https://drafts.csswg.org/css-scoping/#shadow-names

I think?

**Comment by gsnedders** [comment]
And while not one of the at-rules mentioned, these tests cover [`@keyframes`](https://wpt.fyi/results/css/css-scoping?label=master&label=experimental&aligned&view=subtest&q=keyframes).

One could probably make some largely derivative tests of those for `@font-face`, which I believe is the only other at-rule which defines a global name supported cross-browser.

**Comment by gsnedders** [comment]
And to be explicit: I think we should consider this proposal to cover "at-rules that define global names", rather than specifically `@font-face` and `@property`. There's value in fixing the rest of this even without #158 (`@property`).

**Comment by foolip** [comment]
@gsnedders can you work with @Westbrook to update the issue description if you want to expand the focus?

**Comment by gsnedders** [comment]
To be clear, I think we should just test the at-rules that define global names which are supported; I don't think we should require every browser to implement `@property` (or `@color-profile`, etc.) as part of this.

**Comment by emilio** [comment]
Did everyone agree in a consistent model for this? `@keyframe` sorta-kinda-works in a sorta-kinda-interoperable way, but it's a mess, and definitely not something we can do for `@font-face`.

**Comment by emilio** [comment]
Ah current spec text is https://drafts.csswg.org/css-scoping/#shadow-names which is mentioned above indeed. In general, fixing this up is sensible, and the spec seems reasonable.

**Comment by foolip** [comment]
https://drafts.csswg.org/css-scoping/#shadow-names doesn't mention `@property` so I went to look for the spec for this. I found https://drafts.css-houdini.org/css-properties-values-api/#at-property-rule which says:

> A `@property` is invalid if it occurs in a stylesheet inside of a shadow tree, and must be ignored.

I suspect that makes https://bugs.chromium.org/p/chromium/issues/detail?id=1231135 invalid, but I've asked to confirm.

**Comment by nairnandu** [comment]
Thank you for proposing `@font-face` and `@property` in shadow trees for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. We had many strong proposals, and could not accept them all. As discussed in the issue comments, we could not find any tests for `@font-face` or `@property` in shadow trees. We would welcome this proposal being resubmitted for a future round of Interop once there are tests covering the behavior.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
