### ISSUE TITLE
EditContext API

### ISSUE THREAD

**Issue by svoisen** [web-platform-tests/interop#220]
### Description

The EditContext is a new API that simplifies the process of integrating a web app with [advanced text input methods](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/EditContext/explainer.md#example-text-input-methods), improves accessibility and performance, and unlocks new capabilities for web-based editors.

This API allows web developers to create sophisticated input methods such as an improved IME experience by decoupling text input from the HTML DOM view. Rather than having the web platform infer the data required to enable sophisticated text input mechanisms from the HTML DOM, the author can provide that data explicitly through the API surface of the EditContext.

It is currently only supported in Chromium-based browsers.

### Rationale

Any developer wishing to build rich application such as drawing tools, web-based code editors, web-based word processors and the like which require IME support, improved accessibility, or custom emoji pickers will benefit from this API.

At Adobe, we are already using it in our web-based creative tools (where it is available) to provide much improved IME UX for Chinese, Japanese, and Korean users. This allows us to meet these customers' text input needs in applications where we perform our own text rendering on HTML canvas.

### Specification

https://w3c.github.io/editing/docs/EditContext/

**Comment by foolip** [comment]
Looks like there are no tests for `EditContext` in WPT, and only two tests in Chromium:
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/editing/input/edit-context.html;drc=d1e6590d733a2ea1b056759f3ea5cb06fa2c91b3
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/editing/input/edit-context-dom-mutation.html;drc=d1e6590d733a2ea1b056759f3ea5cb06fa2c91b3

**Comment by foolip** [comment]
Looks like this is behind the experimental web platform flag in Chrome:
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/runtime_enabled_features.json5;l=1104-1108;drc=75efd6f877f8404c51134160ecffd52b4b9dd9c7

**Comment by nairnandu** [comment]
Thank you for proposing the EditContext API for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. We had many strong proposals, and could not accept them all. The web standard for this technology has not yet reached a point where inclusion in the Interop project makes sense. Resubmitting a proposal for this feature as part of a future round of Interop would be welcome. 

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
