### ISSUE TITLE
StorageManager.estimate

### ISSUE THREAD

**Issue by svoisen** [web-platform-tests/interop#221]
### Description

The StorageManager interface of the [Storage API](https://developer.mozilla.org/en-US/docs/Web/API/Storage_API) provides an interface for managing persistence permissions and estimating available storage. `StorageManager.estimate` returns a Promise that resolves to an object containing usage and quota numbers for an origin.

Not all browsers support the `estimate` method on `StorageManager`. And where it is supported, implementations are inconsistent. For instance:

* WebKit does not support `estimate` at all.
* Gecko supports `estimate` but not details such as `usageDetails`.

### Rationale

For applications that make heavy use of local storage, this API becomes increasingly critical in order to understand when an application is about to hit storage limits and warn users or take preventative measures. This becomes even more important as more applications use newer quota-limited storage APIs such as OPFS (+ AccessHandles) which will soon be supported in all browsers.

### Specification

https://storage.spec.whatwg.org/#ref-for-dom-storagemanager-estimate

### Tests

https://wpt.fyi/results/storage/storagemanager-estimate.https.any.html?label=experimental&label=master&aligned
https://wpt.fyi/results/storage/estimate-usage-details-caches.https.tentative.any.worker.html

**Comment by foolip** [comment]
I see one of the tests is tentative. Does anyone know why that is?

**Comment by mkruisselbrink** [comment]
> I see one of the tests is tentative. Does anyone know why that is?

Probably because the spec for `usageDetails` currently only lives in a PR (https://github.com/whatwg/storage/pull/69), because of lack of cross-browser interest.

**Comment by foolip** [comment]
In the [MDN short survey on APIs & JavaScript](https://github.com/web-platform-tests/interop/issues/246), "Storage quota estimation (`navigator.storage.estimate()`)" was selected by ~8% of survey takers, putting it in the bottom third of options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/246#issuecomment-1312098410) as with any survey data.)

**Comment by nt1m** [comment]
WebKit just implemented StorageManager.estimate in https://github.com/WebKit/WebKit/commit/a793d8b68a12b37482e8734a578926405f7edc45

**Comment by nairnandu** [comment]
Thank you for proposing the StorageManager.estimate for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. We had many strong proposals, and could not accept them all. This should not be taken as a comment on the technology as a whole.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
