### ISSUE TITLE
requestAnimationFrame in WorkerGlobalScope

### ISSUE THREAD

**Issue by svoisen** [web-platform-tests/interop#222]
### Description

Allows use of `requestAnimationFrame` in web workers.

Currently this is unsupported in WebKit.

### Rationale

This is necessary for any applications that wish to perform tasks such as animation rendering off the main thread, perhaps in conjunction with `OffscreenCanvas`.

### Specification

https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#dom-animationframeprovider-requestanimationframe

### Tests

https://wpt.fyi/results/workers/WorkerGlobalScope_requestAnimationFrame.tentative.worker.html

**Comment by foolip** [comment]
I see that the test here is tentative. @Ms2ger you added this in https://github.com/web-platform-tests/wpt/pull/12293, do you know if it still needs to be tentative?

**Comment by gsnedders** [comment]
> ### Rationale
> This is necessary for any applications that wish to perform tasks such as animation rendering off the main thread, perhaps in conjunction with `OffscreenCanvas`.

You say "perhaps", but is there any use-case for this _without_ OffscreenCanvas?

**Comment by foolip** [comment]
Thank you for proposing `requestAnimationFrame` in `WorkerGlobalScope` for inclusion in Interop 2023.

We are pleased to let you know that this proposal was accepted as part of the Offscreen Canvas focus area. You can follow the progress of this Focus Area on the [Interop 2023 dashboard](https://wpt.fyi/interop-2023).

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you for contributing to Interop 2023!

_Posted on behalf of the Interop team._
