### ISSUE TITLE
Priority hints

### ISSUE THREAD

**Issue by kara** [web-platform-tests/interop#223]
### Description

Priority hints allow developers to explicitly communicate the relative priority of resources. Browsers can consider these hints when fetching resources.

Example:
```html
<img src="cat.png" alt="My cat" fetchpriority="high" />
```

### Rationale

For applications that use client-side rendering, it can be tricky to optimize the loading of critical resources like in-viewport critical content images.

Preload hints traditionally help with discovery, so it's not necessary to wait for the framework code to download and execute before the image starts to load but don’t necessarily signal relative importance of content. 

However, there are still a few gaps:

- Adding the preload to the <head> can be challenging in a CSR scenario. In Angular apps, for example, the index.html is shared by the whole application and the UI for the route is built dynamically. As such, it's not easy to add a preload for one particular route; every tag you add to the index.html is included in every route, so you end up with all the preloads for every page on all pages. It's also not easy to create a directive or component to add the preload dynamically because when using CSR, by the time the directive or component renders, it's too late for the preload to be of any use.

- Depending on their placement, preloads can also compete with the loading of the framework code itself, delaying the generation of the UI the image belongs in. They can also compete with other critical resources like render-blocking scripts. There isn't currently a way to denote which is most important to load first.

- Some enterprise teams are split up such that one team has control over the index.html (e.g. marketing or a CMS team) and another front-end team is responsible for the CSR-ed app. In this case, adding something to the <head> can actually require making a request through slow, bureaucratic channels. The ability to mark an image's priority on the tag itself is valuable in this case.

There are additional issues that aren't specific to CSR, e.g.:

- Mixing preload with responsive images can be difficult to get right.

- Keeping the preloads up-to-date with content changes can sometimes be difficult, leading to loading of stale content that is no longer used.

Priority hints would help with these problems.

- With priority hints, a developer could preload an image and then tag it as low priority to avoid it competing with the framework code.

- As hints can be added to the image tag directly, developers won't run into issues with sharing the <head> with other routes and it's easy to wrap the behavior into a higher-level component. This also helps in the case that organizational issues make the markup uneditable directly.

- Hints work also seamlessly with responsive images.

Priority hints can also be used to nudge the fetching order of other non-blocking assets. In particular, async scripts can benefit from an explicit signal for how important they are to the user experience as both critical application code and analytics or other behind-the-scenes code can be loaded asynchronously with no differentiation.
 
**Relevant data points:**

- In less than a year, priority hints are already present in [1.5% of Chrome page loads](https://chromestatus.com/metrics/feature/timeline/popularity/2738). 

- Many popular origins, like [yahoo.com](https://www.yahoo.com/?guccounter=1), [ebay.co.uk](https://www.ebay.co.uk/itm/304504527536), and https://www.nintendo.com/  already use fetchpriority.

- The [Angular image optimization directive](https://angular.io/guide/image-directive) is already using priority hints, with an implementation coming soon in the [Next.js image component](https://nextjs.org/docs/basic-features/image-optimization). These directives work slightly less well for browsers without priority hint support.

### Specification

https://wicg.github.io/priority-hints/ 

Note: The plan is for the draft spec above to be converted to a standards track spec in the next month:

- Week of Oct 17: W3C web perf working group will vote on adopting the API
- November: first public working draft will be completed

### Tests

You can see the WPT status for this feature [here](https://wpt.fyi/results/priority-hints?label=experimental&label=master&aligned).

**Comment by ebizindia** [comment]
Very useful because we as developers know which are the critical images for the user experience. There may be some image which is vital for the user experience even though there may be many images in the initial  viewport.

Please consider making it a web standard.

**Comment by gsnedders** [comment]
> Note: The plan is for the draft spec above to be converted to a standards track spec in the next month:
> 
> * Week of Oct 17: W3C web perf working group will vote on adopting the API
> * November: first public working draft will be completed

Is there any issue tracking that?

**Comment by tbondwilkinson** [comment]
This would be useful for Google's server framework.

"We want to provide customers with best possible performance out of the box and priority hints could be used for this (though I don't think we use them today). Having cross-browser support would be important for investing more here."

**Comment by gsnedders** [comment]
> > Note: The plan is for the draft spec above to be converted to a standards track spec in the next month:
> > 
> > * Week of Oct 17: W3C web perf working group will vote on adopting the API
> > * November: first public working draft will be completed
> 
> Is there any issue tracking that?

Ping?

The [WebPerf WG agenda](https://docs.google.com/document/d/10dz_7QM5XCNsGeI63R864lF9gFqlqQD37B4q8Q46LMM/edit?usp=sharing) nor the [mailing list](https://lists.w3.org/Archives/Public/public-web-perf/2022Oct/thread.html) have any mention of Priority Hints nor any vote?

**Comment by yoavweiss** [comment]
I added it to the [agenda](https://docs.google.com/document/d/10dz_7QM5XCNsGeI63R864lF9gFqlqQD37B4q8Q46LMM/edit?pli=1#heading=h.i355nhfs4g2) for the next call. In previous discussions, the general sentiment was it would be better to have the spec integrated directly into HTML/Fetch, which seems reasonable to me.

**Comment by foolip** [comment]
@yoavweiss do you think there will be clarity on the destination of https://wicg.github.io/priority-hints/ before Nov 17? (That's our deadline for individual positions on each Interop 2023 proposal.)

**Comment by yoavweiss** [comment]
^^ @Bas-moz - following offline discussions

**Comment by valenting** [comment]
Hi all, we plan to implement priority hints in Gecko in Q1 of 2023. Thanks!

**Comment by yoavweiss** [comment]
Thanks for the update, @valenting! :) Any opinions regarding the right venue for the spec to live in? Would integrating it directly into HTML and Fetch work for y'all?

**Comment by valenting** [comment]
> Thanks for the update, @valenting! :) Any opinions regarding the right venue for the spec to live in? Would integrating it directly into HTML and Fetch work for y'all?

Yes, I think that's the best approach. Thanks!

**Comment by pmeenan** [comment]
The spec is being merged into the core HTML and fetch specs with issues and PR's for both in-flight.

Fetch: [Issue](https://github.com/whatwg/fetch/issues/1319), [PR](https://github.com/whatwg/fetch/pull/1523)
HTML: [Issue](https://github.com/whatwg/html/issues/7150), [PR](https://github.com/whatwg/html/pull/8470)

There is also a [Chrome CL](https://chromium-review.googlesource.com/c/chromium/src/+/4008682) with additions to the web platform tests to test it more thoroughly (there are already a few tests under priority-hints).

The spec PR's have links to the issue trackers for the various browsers for integration.

**Comment by foolip** [comment]
In the [MDN short survey on APIs & JavaScript](https://github.com/web-platform-tests/interop/issues/246), "Priority Hints (`fetchpriority` HTML attribute)" was selected by ~6% of survey takers, putting it in the bottom third of options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/246#issuecomment-1312098410) as with any survey data.)

In hindsight it would have made more sense to put this option in https://github.com/web-platform-tests/interop/issues/245 (which was fielded on HTML sections of MDN) but nobody spotted this during the survey review, unfortunately.

**Comment by nairnandu** [comment]
Thank you for proposing Priority Hints for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. As of the deadline, the specifications for Priority Hints were not yet complete enough to allow interoperable implementations. To make progress on this area in the future it will first be necessary to ensure that the feature has a clear specification in a standards track document.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
