### ISSUE TITLE
Media pseudo classes: `:paused`/`:playing`/`:seeking`/`:buffering`/`:stalled`/`:muted`/`:volume-locked`

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#224]
### Description

Pseudo classes to target specific states of video/audio.

### Rationale

They are implemented in WebKit, but not Blink/Gecko, seems like low hanging fruit for web developers to have those implemented everywhere.

### Specification

W3C: https://w3c.github.io/csswg-drafts/selectors-4/#resource-pseudos

### Tests

WPT:

css/selectors/media/media-loading-state.html
css/selectors/media/media-playback-state.html
css/selectors/media/sound-state.html

**Comment by marcoscaceres** [comment]
Sam suggested we might look into "trickle" for stalled cases... might help. Otherwise, there might be a way of hacking it with a service worker.

**Comment by marcoscaceres** [comment]
Tests ported https://github.com/web-platform-tests/wpt/pull/36565

**Comment by foolip** [comment]
Does `:volume-locked` ever match in Safari? I can't tell what it's for from reading the spec alone.

**Comment by nt1m** [comment]
Sure, we can exclude `:volume-locked`

**Comment by foolip** [comment]
Even better would be if it was defined though. Does anyone know what it does?

**Comment by marcoscaceres** [comment]
@foolip do you mean beyond [what's specified in Selectors 4](https://www.w3.org/TR/selectors-4/#selectordef-volume-locked)? 

I'm just guessing here, but presumedly the format somehow forbids changing the volume of the `<audio>` or `<video>`.

**Comment by marcoscaceres** [comment]
I asked internally. This is what I learned: 

On some platforms, programmatically changing the media’s `.volume` property won’t actually change the output volume. That’s because the media element’s volume is tied to the overall system volume level. There is no per-media-element gain control.

So, websites shouldn’t display their own volume controls on those platforms. Using `:volume-locked` is how they would know whether or not to display a volume slider.

That makes total sense!

**Comment by foolip** [comment]
Thanks @marcoscaceres! I've filed https://github.com/w3c/csswg-drafts/issues/8061 to clarify the spec.

I used to work on media elements and think this looks like a pretty simple thing to implement, but I do wonder about the rationale. Having gone through the State of CSS 2022 results to produce https://github.com/web-platform-tests/interop/issues/248, there wasn't any mention of this feature. Is there other evidence of web developer demand for this?

**Comment by foolip** [comment]
I've also filed https://bugs.chromium.org/p/chromium/issues/detail?id=1383480.

**Comment by lilles** [comment]
Implementation of :playing/:paused is behind a test flag in Blink, but shipping[1] seemingly stalled because there was no html spec for the media states. Is that properly in place now?

[1] https://groups.google.com/a/chromium.org/g/blink-dev/c/kz3w-yOMDks/m/Ue71o4xYAAAJ

**Comment by nairnandu** [comment]
Thank you for proposing media pseudo classes for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. We had many strong proposals, and could not accept them all. This should not be taken as a comment on the technology as a whole, and resubmitting a proposal for this feature as part of a future round of Interop would be welcome.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
