### ISSUE TITLE
CSS Relative Color Syntax

### ISSUE THREAD

**Issue by nilaallj** [web-platform-tests/interop#226]
### Description

The relative color syntax makes it possible to manipulate the channel values of any color using any color model.

### Examples

```PostCSS
:root {
 /* Defining a new color relative to a color defined in a custom property */
 --brand-clr: deeppink;
 --brand-clr-transparent: hsl(from var(--brand-clr) h s l / 0.5);
 --accent-clr: hsl(from var(--brand-clr) calc(h - 180deg) s l);

 /* The syntax also works between different color models and spaces */
 --darker-red: lch(from rgb(255 0 0) calc(l - 20%) c h);
 --pinkish-hue: oklch(from limegreen l c 10deg);
}
```

### Rationale

Color theming is an important aspect of UI design, and being able to define relative colors would make this process much more streamlined and and less repetitive. Many developers already use [Sass color functions](https://sass-lang.com/documentation/modules/color) to preprocess relative colors. There are also libraries such as [Color.js](https://colorjs.io) which offers similar functionality.

In last year's State of CSS survey, "Functions for manipulating color values" [scored high](https://2021.stateofcss.com/en-US/opinions/#currently_missing_from_css_wins) on "Features missing from CSS".

### Specification

- [CSS Color Module Level 5 <br/> # relative-colors](https://www.w3.org/TR/css-color-5/#relative-colors)
- [CSS Color Module Level 5 <br/> # serial-relative-color](https://www.w3.org/TR/css-color-5/#serial-relative-color)

### Tests

- https://wpt.fyi/results/css/css-color/parsing/color-computed-relative-color.html
- https://wpt.fyi/results/css/css-color/parsing/color-invalid-relative-color.html
- https://wpt.fyi/results/css/css-color/parsing/color-valid-relative-color.html

**Comment by nt1m** [comment]
See also https://github.com/w3c/csswg-drafts/issues/7978

**Comment by emilio** [comment]
This seems more of a new feature rather than interop?

**Comment by nilaallj** [comment]
@emilio
This is already implemented behind a flag in Safari, and has a W3C specification.

**Comment by gsnedders** [comment]
> This seems more of a new feature rather than interop?

There have been a variety of proposals which are new features, and we didn't exclude new features from being included. (And we did this last year, e.g. Cascade Layers.)

**Comment by foolip** [comment]
Color functions and related features were a common response to the State of CSS 2022 question about browser incompatibilities, see https://github.com/web-platform-tests/interop/issues/134.

About 3% of responses mentioned color functions directly or indirectly, usually as "color function" or "color()", but also things like "display-p3", "LCH color" or "OKLab support".

There were only 6 direct mentions of relative colors, such as "css relative colors (colors math)".

This becomes difficult to untangle since we don't know how many people know that `color()` as spec'd does include relative colors.

Personally, I see it as a medium-to-strong signal.

**Comment by foolip** [comment]
In the [MDN short survey on CSS & HTML](https://github.com/web-platform-tests/interop/issues/245), "CSS color spaces and functions (`color()`, `lab()`, gradients, etc.)" was selected by ~25% of survey takers, putting it in the top third of the 20 options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/245#issuecomment-1311874383) as with any survey data.)

**Comment by nairnandu** [comment]
Thank you for proposing CSS Relative Color Syntax for inclusion into Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. We had many strong proposals, and could not accept them all. However this should not be taken as a comment on the technology as a whole, and resubmitting a proposal for this feature as part of a future round of Interop would be welcome.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
