### ISSUE TITLE
CSS Motion Path (offset properties)

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/interop#227]
### Description

CSS Motion Path is now supported in all three engines. But there are remaining test failures. This would be a good project for Interop 2023, to make sure we reach a higher bar of interoperability, and make it more possible for developers to use Motion Path without problems. 

### Specification

Editor's Draft: https://drafts.fxtf.org/motion-1/
Official Working Draft (needs to be republished): https://www.w3.org/TR/motion-1/

### Tests

https://wpt.fyi/results/css/motion?label=experimental&label=master&aligned

**Comment by foolip** [comment]
In the [MDN short survey on CSS & HTML](https://github.com/web-platform-tests/interop/issues/245), "CSS motion path (`offset-path`, `offset-distance`, etc.)" was selected by ~7% of survey takers, putting it in the bottom third of the 20 options. (There is [some uncertainty](https://github.com/web-platform-tests/interop/issues/245#issuecomment-1311874383) as with any survey data.)

**Comment by foolip** [comment]
Thank you for proposing CSS Motion Path (offset properties) for inclusion in Interop 2023.

We are pleased to let you know that this proposal was accepted as part of the Motion Path focus area. You can follow the progress of this Focus Area on the [Interop 2023 dashboard](https://wpt.fyi/interop-2023).

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you for contributing to Interop 2023!

_Posted on behalf of the Interop team._
