### ISSUE TITLE
css/css-grid/grid-layout-properties.html expects shortest computed style

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#228]
### Test List

* css/css-grid/grid-layout-properties.html

### Rationale

That test is expecting that getComputedStyle() returns the shortest possible computed style, causing failures in Blink & WebKit: https://wpt.fyi/results/css/css-grid/grid-layout-properties.html?label=master&label=experimental&aligned&view=subtest

It's reasonable to ask for the specified style to be the shortest form, since the CSSOM spec says serialization should always try to use the shortest form. 

But the CSS cascade spec says for computed style:
> For example, serialization rules often allow omitting certain values which are implied during parsing; but those values are nonetheless part of the computed value.

https://www.w3.org/TR/css-cascade/#computed

**Comment by Loirooriol** [comment]
Blink & WebKit failing for serializing `grid-template` as `50px 50px 50px / 150px / none` is not the fault of the test, that's an invalid value according to the grammar, they are just serializing wrong.

That said, testcases like `100px / "a b" 50px` are the fault of the test, that's again an invalid value, the test should probably check `"a b" 100px / 50px` instead, and also use `CSS.supports()`.

> those values are nonetheless part of the computed value

Sure, but the test is checking the serialization and not the raw computed value, so it should use the shortest serialization principle.

**Comment by nt1m** [comment]
Yeah, I think this can be fixed on our side too.
