### ISSUE TITLE
Miscellaneous Shadow DOM

### ISSUE THREAD

**Issue by josepharhar** [web-platform-tests/interop#230]
This was split from https://github.com/web-platform-tests/interop/issues/181

## Description
This is a bunch of WPTs in the shadow-dom directory that are failing. I don’t think they correspond to any particular big feature, they were just made from random one-off bugs.

## Rationale
Basic Shadow DOM behavior should be interoperable.

## Shadow DOM focus navigation, delegatesFocus, and element.focus()
Tests:
[https://wpt.fyi/results/shadow-dom/focus-navigation](https://wpt.fyi/results/shadow-dom/focus-navigation?label=experimental&label=master&aligned)
[https://wpt.fyi/results/shadow-dom/focus](https://wpt.fyi/results/shadow-dom/focus?label=experimental&label=master&aligned)
Spec:
https://html.spec.whatwg.org/C/#focus-processing-model
https://html.spec.whatwg.org/C/#sequential-focus-navigation

## Shadow DOM events and retargeting
Tests:
[https://wpt.fyi/results/shadow-dom/DocumentOrShadowRoot-prototype-elementFromPoint.html](https://wpt.fyi/results/shadow-dom/DocumentOrShadowRoot-prototype-elementFromPoint.html?label=experimental&label=master&aligned)
[https://wpt.fyi/results/shadow-dom/MouseEvent-prototype-offsetX-offsetY.html](https://wpt.fyi/results/shadow-dom/MouseEvent-prototype-offsetX-offsetY.html?label=experimental&label=master&aligned)
[https://wpt.fyi/results/shadow-dom/capturing-and-bubbling-event-listeners-across-shadow-trees.html](https://wpt.fyi/results/shadow-dom/capturing-and-bubbling-event-listeners-across-shadow-trees.html?label=experimental&label=master&aligned)
Spec:
- https://drafts.csswg.org/cssom-view-1/#dom-document-elementfrompoint
- MouseEvent is defined here but there is no definition for offsetX or offsetY: https://w3c.github.io/uievents/#idl-mouseevent
- capturing-and-bubbling-event-listeners-across-shadow-trees.html was discussed here: https://github.com/whatwg/dom/issues/742

**Comment by josepharhar** [comment]
If consensus is not reached in time, then I think we can just drop those two test files. There are plenty of other tests in the `focus` and `focus-navigation` directories.

**Comment by foolip** [comment]
In the [MDN short survey on APIs & JavaScript](https://github.com/web-platform-tests/interop/issues/246), "Web Components (custom elements, Shadow DOM, etc.)" was the most popular choice by a fairly wide margin, selected by ~39% of survey takers.

Web Components was split into many granular proposals, and the survey results don't tell us which aspects web developers want the most, but it's fair to say that _something_ about Web Components is important. (I'm posting this comment on each of the split proposals.)

**Comment by nairnandu** [comment]
Thank you for proposing Miscellaneous Shadow DOM for inclusion in Interop 2023.

We are pleased to let you know that this proposal was accepted as part of the Web Components focus area. You can follow the progress of this Focus Area on the [Interop 2023 dashboard](https://wpt.fyi/interop-2023).

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you for contributing to Interop 2023!

_Posted on behalf of the Interop team._
