### ISSUE TITLE
Declarative Shadow DOM

### ISSUE THREAD

**Issue by josepharhar** [web-platform-tests/interop#232]
This was split from https://github.com/web-platform-tests/interop/issues/181

## Description
https://w3c.github.io/webcomponents-cg/#declarative-shadow-dom
Declarative Shadow DOM is a mechanism to express Shadow DOM using only HTML, with no dependency on JavaScript, much like light DOM can be declaratively expressed today.

## Rationale
https://w3c.github.io/webcomponents-cg/#declarative-shadow-dom
Without Declarative Shadow DOM, web components depend on rendering environments that support JavaScript. This limits their use in server-side rendering and javascript-less environments.

## Tests
[https://wpt.fyi/results/shadow-dom/declarative](https://wpt.fyi/results/shadow-dom/declarative?label=experimental&label=master&aligned)

## Spec
https://github.com/whatwg/dom/pull/892
https://github.com/whatwg/html/pull/5465

**Comment by smaug----** [comment]
It is unclear which version of the declarative shadow DOM this is about. The one shipping in Chrome or the more recent streaming based? Or just generic proposal to have some way to have declarative shadow DOM?

**Comment by josepharhar** [comment]
I don't think any of the tests are for streaming at this point, but we have a prototype of streaming in chromium and webkit sounded supportive. Therefore, if it must be streaming or not-streaming I suppose I choose streaming.

**Comment by foolip** [comment]
In the [MDN short survey on APIs & JavaScript](https://github.com/web-platform-tests/interop/issues/246), "Web Components (custom elements, Shadow DOM, etc.)" was the most popular choice by a fairly wide margin, selected by ~39% of survey takers.

Web Components was split into many granular proposals, and the survey results don't tell us which aspects web developers want the most, but it's fair to say that _something_ about Web Components is important. (I'm posting this comment on each of the split proposals.)

**Comment by nairnandu** [comment]
Thank you for proposing Declarative Shadow DOM for inclusion into Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. As discussed in the issue, there were concerns about the maturity of the specification and the availability of automated tests. These issues will need to be addressed in the relevant standards organization. However this should not be taken as a comment on the technology as a whole. If these issues are resolved, resubmitting a proposal for this feature as part of a future round of Interop would be welcome.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
