### ISSUE TITLE
Custom Builtins

### ISSUE THREAD

**Issue by josepharhar** [web-platform-tests/interop#234]
This was split from https://github.com/web-platform-tests/interop/issues/181

I had a hard time finding a good description and rationale for this feature, but it is in the HTML spec and has WPTs.

## Tests
- https://wpt.fyi/results/custom-elements/builtin-coverage.html
- https://wpt.fyi/results/custom-elements/customized-built-in-constructor-exceptions.html
- https://wpt.fyi/results/custom-elements/pseudo-class-defined.html
- https://wpt.fyi/results/custom-elements/parser
- https://wpt.fyi/results/custom-elements/reactions/HTMLAreaElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLBaseElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLButtonElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLCanvasElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLDataElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLDetailsElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLEmbedElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLFieldSetElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLImageElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLLabelElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLLIElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLMapElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLMediaElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLMetaElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLMeterElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLModElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLOListElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLOptGroupElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLParamElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLProgressElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLQuoteElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLSlotElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLSourceElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLStyleElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLTableCellElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLTableColElement.html
- https://wpt.fyi/results/custom-elements/reactions/HTMLTimeElement.html
- https://wpt.fyi/results/custom-elements/Document-createElementNS.html
- https://wpt.fyi/results/custom-elements/htmlconstructor/newtarget.html
- https://wpt.fyi/results/custom-elements/HTMLElement-constructor.html
- https://wpt.fyi/results/custom-elements/upgrading/Document-importNode.html
- https://wpt.fyi/results/custom-elements/upgrading/Node-cloneNode.html

## Spec
https://html.spec.whatwg.org/multipage/custom-elements.html#customized-built-in-element

**Comment by domenic** [comment]
> I had a hard time finding a good description and rationale for this feature

I think https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-customized-builtin-example and the following section serve that purpose.

**Comment by gsnedders** [comment]
This is another case where our existing scoring absolutely falls apart due to only having two tests, and with those two tests have very different numbers of subtests: each of the subtests in `customized-built-in-constructor-exceptions.html` would be worth 10%, and each element in `builtin-coverage.html` (each with four tests) would be worth 0.45%.

**Comment by josepharhar** [comment]
I just added the pseudo-class-defined.html and custom-elements/parser/ tests to this issue because they are only failing in safari and only due to custom builtins.

**Comment by foolip** [comment]
In the [MDN short survey on APIs & JavaScript](https://github.com/web-platform-tests/interop/issues/246), "Web Components (custom elements, Shadow DOM, etc.)" was the most popular choice by a fairly wide margin, selected by ~39% of survey takers.

Web Components was split into many granular proposals, and the survey results don't tell us which aspects web developers want the most, but it's fair to say that _something_ about Web Components is important. (I'm posting this comment on each of the split proposals.)

**Comment by josepharhar** [comment]
I just moved a bunch of tests from the misc. custom elements proposal into this one: https://github.com/web-platform-tests/interop/issues/231#issuecomment-1319288301

**Comment by nairnandu** [comment]
Thank you for proposing Custom Builtins for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. We had many strong proposals, and could not accept them all. Every technology that’s chosen for Interop must have a web standard created from consensus between the parties involved. Custom Builtins does not have such an agreement.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._
