### ISSUE TITLE
Some tests assume a certain working color space

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#237]
### Test List

* css/css-color/t422-rgba-onscreen-b.xht
* css/css-color/t422-rgba-onscreen-multiple-boxes-c.xht
* css/css-color/t425-hsla-onscreen-b.xht
* css/css-color/t425-hsla-onscreen-multiple-boxes-c.xht

### Rationale

@smfr found that these tests pass if you change the device color profile from display-p3 to sRGB on Safari.

It seems like the test is making incorrect assumptions about what the working color space is.

We may want to remove these tests from WPT entirely.

cc @svgeesus @weinig @sesse @lilles @emilio @jgraham

**Comment by nt1m** [comment]
Actually nevermind, the issues seen on wpt.fyi are due to bad color channel rounding in WebKit.

**Comment by nt1m** [comment]
Wait, these tests currently pass on WebKitGTK, so these are not the tests actually affected by rounding. So it is effectively a color profile issue.

**Comment by svgeesus** [comment]
Looking at [Compositing-1]() a basic problem is that it specified blending in CSS and SVG, and Compositing and Blending in Canvas.

It then goes on to talk about advanced compositing, but does not actually define Compositing in CSS.

However, the equations clearly operate on gamma-encoded sRGB values and assume that the color space used for specifying color (sRGB, given the age of the spec) and the color space used for display, are the same.

![image](https://user-images.githubusercontent.com/2506926/198393922-5e2e2b7b-1d63-4fa9-9d3b-b10a74f2f3d0.png)

**Comment by svgeesus** [comment]
> We may want to remove these tests from WPT entirely.

That may be the best option, because the assumptions in the test are invalid (and unrelated to the test purpose, which is distinguishing alpha from group opacity)

@dbaron ?

**Comment by nt1m** [comment]
https://github.com/web-platform-tests/wpt/pull/36732

**Comment by dbaron** [comment]
> That may be the best option, because the assumptions in the test are invalid (and unrelated to the test purpose, which is distinguishing alpha from group opacity)

Do we have other tests in WPT that test this distinction?
