### ISSUE TITLE
Angular input on Interop 2023

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#238]
@robnyman has talked to the Angular team to get input on the Interop 2023 proposals. The source is
the [Angular input on Interop 2023](https://docs.google.com/spreadsheets/d/1biX_Lfia2J2u4JV4Vqnkl2V6MnNeYXdeQyZyX6xrmIk/edit?usp=sharing) spreadsheet, inlined here for convenience:

Feature | Rank | Affected area | Why it matters to Angular
-- | -- | -- | --
[CSS Scoping](https://github.com/web-platform-tests/interop/issues/183) | P0 | Framework | Angular (along with Vue and Svelte) emulates CSS scoping, keeping component styles from leaking out, but still allowing global styles to appy. Browser support for this behavior would simplify the implementations of all of these frameworks.
[Produce consistent accessibility trees](https://github.com/web-platform-tests/interop/issues/211) | P1 | Components | We've run into issues over the years with different behaviors between browsers. While it's true that most problems stem from screen reader differences, having consistent browser behavior would reduce one source of variance.
[Navigation API](https://github.com/web-platform-tests/interop/issues/200) | P1 | Framework | Stands to simplify Angular's router implementation if it were consistently supported in all browsers
[Import Maps](https://github.com/web-platform-tests/interop/issues/184) | P1 | Framework | Supports deploying code as ES modules directly, without a bundling step
[Sanitizer API?](https://github.com/WICG/sanitizer-api/) | P2 | Framework | This would reduce the code necessary for Angular to sanitize HTML content
[Container queries](https://github.com/web-platform-tests/interop/issues/133) | P2 | Components | Game-changing power feature for CSS authors, not much needs to be said
[:has](https://github.com/web-platform-tests/interop/issues/134) | P2 | Components | Game-changing power feature for CSS authors, not much needs to be said
[Temporal](https://github.com/web-platform-tests/interop/issues/169) | P2 | Framework & components | Might simplify some datetime handing in a few framework APIs, but would make it possible to build a high quality datepickers and time pickers on the UI components side without complicated adapters for 3rd party libraries (Moment, Luxon, date-fns, Date.js, goog.date)
[Pointer and mouse events](https://github.com/web-platform-tests/interop/issues/202) | P2 | Components | Inconsistent behavior here is a common source of debugging woes for UI component development
[inert](https://github.com/orgs/web-platform-tests/projects/2/views/1?groupedBy%5BcolumnId%5D=16577147) | P3 | Components | We have [quite a bit of code to do focus trapping](https://github.com/angular/components/tree/8fee9a7db62919aa01560ccc6b33ff97b77b8d5c/src/cdk/a11y/focus-trap) for dialogs today; inert could potentially simplify this
[:dir](https://github.com/web-platform-tests/interop/issues/177) | P3 | Components | More correct over current approach of `[dir="rtl"]` and would eliminate the need for custom code to [track the direction in JS](https://github.com/angular/components/blob/c381a6c5ae1bd0b25e91384bc8bf03198064aa2b/src/cdk/bidi/directionality.ts)
[:blank](https://github.com/web-platform-tests/interop/issues/179) | P3 | Components | Convenient, especially for Material-style floating label inputs (in combination with `:has`)
[:empty](https://github.com/web-platform-tests/interop/issues/180) | P3 | Components | Convenient, especially for Material-style floating label inputs (in combination with `:has`)
[Clipboard API](https://github.com/web-platform-tests/interop/issues/143) | P4 | Components | Nice to have, but [current solution](https://github.com/angular/components/tree/df2eb8b76e1c99bbaec2e5c9fa9314029e910d74/src/cdk/clipboard) is mostly fine
[Focus outline](https://github.com/web-platform-tests/interop/issues/166) | P4 | Components | Could simplify focus rings (go/gm3-focus-rings in Wiz, [strong focus](https://github.com/angular/components/blob/74b0c5fc58a6d8cd69275f2bd6cd379064878d55/src/material/core/focus-indicators/_private.scss) in Angular), but would need to also include `outline-radius`
[Range syntax for media and container queries](https://github.com/web-platform-tests/interop/issues/141) | P4 | Components | Convenient, nice to have

**Comment by robnyman** [comment]
I should just mention that @kara at Google has also helped a lot with gathering these needs.

**Comment by BearCooder** [comment]
Just a quick suggestion - if you gather input from Angular team for interop proposals it would be great to get input from the React and Vue team too.

You can get in touch with Dan[Dan](https://mobile.twitter.com/dan_abramov)  for React for example. He is even tweeting about borked things across different browser sometimes.

**Comment by gsnedders** [comment]
Could you copy these into each of the respective issues? Easier to know what was said about each one, rather than having to reference this.

**Comment by kara** [comment]
> Just a quick suggestion - if you gather input from Angular team for interop proposals it would be great to get input from the React and Vue team too.

Agreed! We asked those two teams for input last week (as well as a few others) and are waiting to hear back.

**Comment by kbrilla** [comment]
Hi @kara, is there any response from React/Vue/Svelte, etc.. teams?

**Comment by foolip** [comment]
@kbrilla note that we're in the final stages of finishing up Interop 2023 for launch, so additional feedback at this point won't change Interop 2023.

That being said, it could always inform what we do in the future.

**Comment by foolip** [comment]
Interop 2023 launched yesterday, so closing this.
