### ISSUE TITLE
Update grid/flex test-suites for 2023

### ISSUE THREAD

**Issue by bfgeek** [web-platform-tests/interop#242]
### Test List

https://wpt.fyi/results/css/css-flexbox?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2021-flexbox

Include all of the flex tests above except for:
1) Tests relating to the "new" intrinsic sizing algorithm.
flex-container-max-content-001.html
flex-container-min-content-001.html
intrinsic-size/*

2) Tests relating to "visibility: collapse" (additional feature).
flexbox_visibility-collapse-line-wrapping.html
flexbox_visibility-collapse.html
flexbox-collapsed-item-baseline-001.html
flexbox-collapsed-item-horiz-001.html
flexbox-collapsed-item-horiz-002.html
flexbox-collapsed-item-horiz-003.html

https://wpt.fyi/results/css/css-grid?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2021-grid

Include all of the grid tests above except for:
1) Masonry feature:
masonry/*

2) The align-content:baseline feature (additional feature).
alignment/grid-item-content-baseline-001.html
alignment/grid-item-content-baseline-002.html
alignment/grid-item-content-baseline-003.html
alignment/grid-item-content-baseline-004.html
alignment/grid-item-mixed-baseline-001.html
alignment/grid-item-mixed-baseline-002.html
alignment/grid-item-mixed-baseline-003.html
alignment/grid-item-mixed-baseline-004.html 
alignment/grid-baseline-align-001.html
alignment/grid-baseline-justify-001.html 

3) Non web-compatible:
grid-definition/grid-inline-template-columns-rows-resolved-values-001.tentative.html
grid-definition/grid-template-columns-rows-resolved-values-001.tentative.html

### Rationale

Over the last 1-2 years we've slowly added test-cases to the suites from bug reports we've received[1], or spec clarifications/behaviour changes[2].

Additionally this is updated for the "last baseline" alignment feature which all engines have basic support for now.

[1] https://bugs.chromium.org/p/chromium/issues/detail?id=1126609 or https://bugs.chromium.org/p/chromium/issues/detail?id=768999
[2] https://github.com/web-platform-tests/wpt/commit/fc109c534f9825c5b02816e37bcab1805c7e576c

Ian

**Comment by jgraham** [comment]
I'm not sure there's a well defined process here; we (with agreement) accept updates to the 2022 testsuites, but generally adding scope for a subsequent year should be in the context of a new focus area.

If there are areas where bugs are showing up as site breakage or compat problems, the tests might be suitable for the web compatibility focus area.

**Comment by foolip** [comment]
Self-assigning to label the tests with a temporary label to show what the impact on the scores would be.

**Comment by foolip** [comment]
I'm going through and labeling with `interop-2021-flexbox-expansion` and `interop-2021-grid-expansion`. I see there are some tentative tests, and I'm not labeling those:
https://wpt.fyi/results/css/css-flexbox/alignment/flex-align-baseline-line-clamp-001.tentative.html
https://wpt.fyi/results/css/css-flexbox/alignment/flex-align-baseline-line-clamp-002.tentative.html
https://wpt.fyi/results/css/css-flexbox/alignment/flex-align-baseline-line-clamp-003.tentative.html

**Comment by foolip** [comment]
I also won't label anything names -print or -crash.

**Comment by bfgeek** [comment]
You likely want to keep those tentative tests, they just need spec text surrounding them..

**Comment by foolip** [comment]
@bfgeek do you know which spec issue those tests depend on? (Nothing is linked from the tests.)

**Comment by foolip** [comment]
Here are views of the existing + proposed tests:
- [Flexbox](https://wpt.fyi/results/css/css-flexbox?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2021-flexbox%20or%20label%3Ainterop-2021-flexbox-expansion)
- [Grid](https://wpt.fyi/results/css/css-grid?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2021-grid%20or%20label%3Ainterop-2021-grid-expansion)

**Comment by jgraham** [comment]
@emilio @dholbert do these tests look reasonable to include in Interop going forward.

**Comment by foolip** [comment]
Thank you for proposing updated grid/flex tests for inclusion in Interop 2023.

We are pleased to let you know that this proposal was accepted as part of the existing Flexbox and Grid focus areas. You can follow the progress of these Focus Areas on the [Interop 2023 dashboard](https://wpt.fyi/interop-2023).

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you for contributing to Interop 2023!

_Posted on behalf of the Interop team._
