### ISSUE TITLE
Investigation project scores are incomplete

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/interop#252]
We agreed in our meeting Dec 1 to raise these two scores: 
- Editing, contenteditable, and execCommand to 46%
- Pointer and Mouse Events to 79% 

The dashboard now reflects the second change, but not the first. 

<img width="456" alt="Screenshot 2022-12-02 at 5 48 28 PM" src="https://user-images.githubusercontent.com/108474/205402648-7215dded-d0c5-42bd-a7e2-d2fd47a5a9bc.png">

**Comment by foolip** [comment]
We've updated a bunch of these now. Another update is in https://github.com/web-platform-tests/wpt.fyi/pull/3084, so I'll put this on the agenda for Dec 22 to approve that.

**Comment by foolip** [comment]
We had another update for the pointer investigation in https://github.com/web-platform-tests/interop-2022-pointer/issues/7#issuecomment-1351616023 last week. I'll send a PR for that too.

**Comment by foolip** [comment]
All 3 updated in draft PRs:
  - https://github.com/web-platform-tests/wpt.fyi/pull/3084
  - https://github.com/web-platform-tests/wpt.fyi/pull/3085
  - https://github.com/web-platform-tests/wpt.fyi/pull/3086

Together they will make the overall investigation score 80%, up 19% from 61%, which should increase all scores by at least 1%, probably 2%, depending on hidden decimals.

**Comment by DanielRyanSmith** [comment]
Deployment of the 3 changes above has been completed and should be visible and served to all new traffic shortly.
