### ISSUE TITLE
Add new tests to interop-2023-container

### ISSUE THREAD

**Issue by Loirooriol** [web-platform-tests/interop#258]
The [new container-queries tests](https://wpt.fyi/results/css/css-contain/container-queries?q=!label%3Ainterop-2023-container) should be added to interop-2023-container. At the moment, the list is:
- [container-units-ineligible-container.html](https://wpt.fyi/results/css/css-contain/container-queries/container-units-ineligible-container.html)
- [nested-query-containers.html](https://wpt.fyi/results/css/css-contain/container-queries/nested-query-containers.html)
- [pseudo-elements-006.html](https://wpt.fyi/results/css/css-contain/container-queries/pseudo-elements-006.html)
- [pseudo-elements-007.html](https://wpt.fyi/results/css/css-contain/container-queries/pseudo-elements-007.html)
- [pseudo-elements-008.html](https://wpt.fyi/results/css/css-contain/container-queries/pseudo-elements-008.html)
- [style-not-sharing-float.html](https://wpt.fyi/results/css/css-contain/container-queries/style-not-sharing-float.html)

There is also [dirty-rowgroup-crash.html](https://wpt.fyi/results/css/css-contain/container-queries/dirty-rowgroup-crash.html) but that one should probably just be moved into the crashtests directory and not added to interop-2023-container.

**Comment by foolip** [comment]
Labeled in https://github.com/web-platform-tests/wpt-metadata/pull/3442. I agree about the crash test, @Loirooriol do you want to send a PR to move it?

**Comment by Loirooriol** [comment]
@foolip https://github.com/web-platform-tests/wpt/pull/37705

**Comment by Loirooriol** [comment]
New tests:
 - dialog-backdrop-create.html
 - dialog-backdrop-remove.html

**Comment by foolip** [comment]
I've labeled those two tests now as well.
