### ISSUE TITLE
WebM Opus <audio> playback on iOS

### ISSUE THREAD

**Issue by anisabboud** [web-platform-tests/interop#261]
**Summary:** Audio recorded on Chrome (WebM Opus format) cannot be played on iPhone.

1. Safari supports audio recording via the MediaRecorder API https://webkit.org/blog/11353/mediarecorder-api/
   Recording format is **audio/mp4** which can be played by `<audio>` element in all major browsers.

2. Chrome & Firefox also support audio recording via the MediaRecorder API https://web.dev/media-recording-audio/
   But the recording format is **audio/webm;codecs=opus** which can be played by `<audio>` element on Chrome, Firefox, and _Safari on Mac_, **but not by Safari on iOS**! See https://bugs.webkit.org/show_bug.cgi?id=238546

**Comment by foolip** [comment]
Hi @anisabboud! The proposal period for Interop 2023 has already ended and we're launching Interop 2023 soon, so unfortunately it's too late for new proposals at this point.

This could be a proposal for the next iteration of Interop, but I have to ask that it's submitted again then, and using the template we'll make available then.

In the meantime, it looks like https://bugs.webkit.org/show_bug.cgi?id=238546 is the right bug to follow, and https://caniuse.com/opus is the caniuse entry for this. The footnotes there talk about the CAF format, but doesn't say anything about WebM, so I'm not sure it's accurate.

**Comment by foolip** [comment]
I'll close this now, but submitting this proposal again for the next iteration of Interop would be welcome.
