### ISSUE TITLE
Add new tests to interop-2023-contain

### ISSUE THREAD

**Issue by Loirooriol** [web-platform-tests/interop#263]
The [new contain tests](https://wpt.fyi/results/css/css-contain?q=%21label%3Ainterop-2022-contain%20%21label%3Ainterop-2023-contain) should probably be added to interop-2023-contain. At the moment, the list is:
- [contain-style-ol-ordinal-li-container.html](https://wpt.fyi/results/css/css-contain/contain-style-ol-ordinal-li-container.html)
- [contain-style-ol-ordinal-pseudo-reversed.html](https://wpt.fyi/results/css/css-contain/contain-style-ol-ordinal-pseudo-reversed.html)
- [contain-style-ol-ordinal-pseudo.html](https://wpt.fyi/results/css/css-contain/contain-style-ol-ordinal-pseudo.html)
- [contain-style-ol-ordinal-reversed.html](https://wpt.fyi/results/css/css-contain/contain-style-ol-ordinal-reversed.html)
- [contain-style-ol-ordinal-start-reversed.html](https://wpt.fyi/results/css/css-contain/contain-style-ol-ordinal-start-reversed.html)
- [contain-style-ol-ordinal-start.html](https://wpt.fyi/results/css/css-contain/contain-style-ol-ordinal-start.html)
- [contain-style-ol-ordinal.html](https://wpt.fyi/results/css/css-contain/contain-style-ol-ordinal.html)

There is also [contain-crash.html](https://wpt.fyi/results/css/css-contain/contain-crash.html) but that one should probably just be moved into the crashtests directory and not added to interop-2023-contain.

**Comment by foolip** [comment]
I've labeled those 7 tests in https://github.com/web-platform-tests/wpt-metadata/pull/3594.

I also wonder about these 3 `content-visibility` tests:
https://wpt.fyi/results/css/css-contain/content-visibility?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21%28label%3Ainterop-2022-contain%20or%20label%3Ainterop-2023-contain%29%20%21crash

@Loirooriol do you think those should be labeled?

**Comment by Loirooriol** [comment]
Ah, yes, I guess so.

**Comment by foolip** [comment]
Alright, done in https://github.com/web-platform-tests/wpt-metadata/pull/3596.

**Comment by nt1m** [comment]
Please feel free to reopen if there is something else to be done here.
