### ISSUE TITLE
Interop 2023: "Math Functions" could be labelled as "CSS Math Functions"?

### ISSUE THREAD

**Issue by myakura** [web-platform-tests/interop#269]
At first, I thought that was about some methods in the ECMAScript `Math` object. People may understand that's CSS, but it could be better if being more precise. What do you think?

**Comment by foolip** [comment]
@myakura I've moved this issue to the interop repo so we can make a decision on this next time we meet. I think your suggested rename makes sense.

**Comment by foolip** [comment]
We resolved to make this change in https://github.com/web-platform-tests/interop/issues/278.

@DanielRyanSmith can you make the change on the dashboard?
