### ISSUE TITLE
Mouse events on disabled input elements

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/interop#27]
**Description**
The spec requires that disabled form controls don't receive `click` events. Gecko follows this and also prevents further event propogation, but other browsers apply it to all mouse events and allow further event propogation (I think; more comprehensive tests are required). This has created a number of serious site compatibility issues.

**Bug reports**
https://bugzilla.mozilla.org/show_bug.cgi?id=1653882
https://webcompat.com/issues/65773
webcompat/web-bugs#73699
webcompat/web-bugs#72988

**Specification**
https://html.spec.whatwg.org/multipage/forms.html#enabling-and-disabling-form-controls:-the-disabled-attribute
https://github.com/whatwg/html/issues/2368

**Tests**
https://wpt.fyi/results/html/semantics/forms/attributes-common-to-form-controls/disabled-elements-01.html?label=master&label=experimental&aligned but this case isn't covered.

This is a bug to include in #9

**Comment by gsnedders** [comment]
This also appears in https://github.com/web-platform-tests/interop-2022/issues/11#issuecomment-976047408, albeit linking to further tests in https://wpt.fyi/results/dom/events/Event-dispatch-click.html?label=experimental&label=master&aligned (though again doesn't test propagation AFAICT).

**Comment by foolip** [comment]
I've added the `requires:tests` label but presume that added a test is fairly trivial, so that's not a blocker in my mind.

**Comment by josepharhar** [comment]
I'm happy to work on this in chromium in 2022.

> https://wpt.fyi/results/html/semantics/forms/attributes-common-to-form-controls/disabled-elements-01.html?label=master&label=experimental&aligned but this case isn't covered.

>  https://wpt.fyi/results/dom/events/Event-dispatch-click.html?label=experimental&label=master&aligned (though again doesn't test propagation AFAICT).

So between `disabled-elements-01.html` and `Event-dispatch-click.html` we still are missing a case?

> though again doesn't test propagation AFAICT

Could you elaborate the propagation case? I'd be happy to add test coverage

**Comment by jgraham** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1653882#c14 is relevant to this issue.
