### ISSUE TITLE
Allow CSS counter integer to be in data- attribute 

### ISSUE THREAD

**Issue by dragontheory** [web-platform-tests/interop#271]
Auto pagination and so many other features could be done in pure CSS if unique IDs could be generated on the fly. One easy way to do that and keep everything in order would be to allow a `data-` attribute access to the CSS counter or ordered list `:marker` integer. 

In combination with `:has()`, "self aware" GUIs, watching for the presence of data changes (on the fly validation) and or easily counting number of children, siblings, and or parents, would become a welcome reality. 

Preset repetitive GUI logic (open/close, hide/show DOM elements, etc.) governed by application business logic and suddenly it's running on its own. 

No more obfuscated workarounds. Straight forward logic. Less developer cognitive load. 

Let the CSS renaissance begin!

Thank you for your time and consideration.

**Comment by nt1m** [comment]
That sounds like https://github.com/web-platform-tests/interop/issues/86

**Comment by foolip** [comment]
Hi @dragontheory, thanks for suggesting this! However, we've just launched Interop 2023 and have not yet begun the process for next year. As @nt1m says this sounds similar to https://github.com/web-platform-tests/interop/issues/86. When the proposal period starts for next year, this would be a welcome proposal.

I'll go ahead and close this, but don't take that as a rejection of the idea, we're just not ready yet!
