### ISSUE TITLE
Interop 2023 process and launch retrospective

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#274]
Now that we have launched Interop 2023 (🎉) we should take some time to look back at our process, what we think worked well, and what could be improved. (We did this for Interop 2022 in https://github.com/web-platform-tests/interop/issues/68 and that resulted in good changes to the process, IMHO.)

The same prompts as last time:
- What worked well and not so good with our proposal process?
- What additional research or data could have helped?
- How did the spreadsheet for tallying positions work?
- How did the launch itself go?

**Comment by gsnedders** [comment]
Do we want this all on a single issue, or to what degree do we want to file new issues for them?

**Comment by foolip** [comment]
In the previous meeting we discussed separating retrospective from decision making and process changes. For the retrospective, we're not in decision making mode, just gathering our thoughts. Some of that might not make sense as issues.

However, something like "we need to have survey results earlier" clearly makes sense as an issue to track. And where we expect discussion, an issue makes sense to keep it "threaded". A link from here would be good in that case.

Which is is to say, everyone gets to use their own best judgment about what warrants a separate issue :)

**Comment by foolip** [comment]
For things that aren't big enough for their own issues, I suggest we use headings (prefix with `##`) in issues, so it's easy to spot the distinct issues by scrolling through the comments.

**Comment by foolip** [comment]
## Caching issue resulted in blank dashboard for some users

Soon after the launch https://github.com/web-platform-tests/wpt.fyi/issues/3137 was reported. It was quickly fixed by https://github.com/web-platform-tests/wpt.fyi/pull/3139 (thanks @DanielRyanSmith!) and https://github.com/web-platform-tests/wpt.fyi/issues/3142 tracks how we could avoid this.

More generally, what can we do to discover this kind of problem ahead of time? It's still not clear why this problem never happened in staging.

**Comment by foolip** [comment]
## Proposer experience

See https://github.com/web-platform-tests/interop/issues/285

**Comment by foolip** [comment]
Notes for the discussion around this are in https://github.com/web-platform-tests/interop/issues/291.
