### ISSUE TITLE
Investigation Effort goals and tracking

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#277]
We have 2 investigation efforts accepted in Interop 2023: Accessibility Testing and Mobile Testing.

We'll need a main point of contact for each, as well as a GitHub repo for collaboration. Then we'll need to agree on the detailed goals and how we'll communicate progress during the year.

I think we have an opportunity to improve compared to 2022, see https://github.com/web-platform-tests/interop/issues/157 for some feedback we got then.

**Comment by jgraham** [comment]
We already have GitHub repos for each: https://github.com/web-platform-tests/interop-2023-mobile-testing and https://github.com/web-platform-tests/interop-2023-accessibility-testing

**Comment by zcorpan** [comment]
Status for Accessibility Testing is tracked in https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/3

We've also updated the score on https://wpt.fyi/interop-2023
