### ISSUE TITLE
Test change: remove Media Queries 5 tests from Interop 2023 Media Queries 4 focus area

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/interop#280]
### Test List

https://wpt.fyi/results/css/mediaqueries?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-mediaqueries%20prefers-

(There might be more, I haven't reviewed all of the tests.)

### Rationale

I noticed that `prefers-reduced-data` is part of the Media Queries 4 focus area, even though no browser has shipped this per https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-data#browser_compatibility and it's specified in Level 5, not Level 4: https://drafts.csswg.org/mediaqueries-5/#prefers-reduced-data

All `prefers-*` media features are in Level 5.

**Comment by gsnedders** [comment]
At this point, I kinda suspect we don't need to go through the full test-change-proposal process for things that are clearly not within the scope of the focus area, and we should just instead remove them and provide an FYI?

**Comment by nt1m** [comment]
There's a few more level 5 features covered fwiw:
* dynamic-range
* forced-colors
* color-gamut
