### ISSUE TITLE
Dashboard no longer reports accurate scores for Cascade Layers

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/interop#281]
Cascade Layers used to report: Chrome 100 / Firefox 96.3 / Safari 100 (preview scores)
Now it reports: Chrome 96.7 / Firefox 93.1 / Safari 96.7 (preview scores)

If you click through to see [the tests & the results](https://wpt.fyi/results/css/css-cascade?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2022-cascade), you can see that the earlier numbers are the correct numbers. So currently, the dashboard is wrong.

This may be happening for other focus areas, too.

**Comment by robnyman** [comment]
@DanielRyanSmith If you know why this could be?

**Comment by gsnedders** [comment]
The dashboard matches https://github.com/web-platform-tests/results-analysis/blob/cc161045215088212e0eb4c678024cd221e7d07e/data/interop-2022/interop-2022-experimental-v2.csv, so it's not a dashboard problem per-se.

The Cascade Layers runs today don't show this; I presume [this](https://wpt.fyi/results/css/css-cascade?sha=bb42e522ef&label=master&label=experimental&max-count=1&product=chrome&product=firefox&product=safari&view=interop&q=label%3Ainterop-2022-cascade) is the exact set of runs being scored. And that still doesn't show these scores.

Could we somehow have fetched web-platform-tests/results-analysis-cache in some intermediary state?

**Comment by gsnedders** [comment]
So the following columns have changes in the last two rows:

In Interop 2023:

chrome-interop-2022-cascade
firefox-interop-2022-cascade
firefox-interop-2022-dialog
safari-interop-2022-cascade
safari-interop-2023-contain
safari-interop-2023-flexbox
safari-interop-2023-offscreencanvas

In Interop 2022:

chrome-interop-2022-cascade
firefox-interop-2022-cascade
firefox-interop-2022-dialog
safari-interop-2021-flexbox
safari-interop-2022-cascade

**Comment by foolip** [comment]
> Could we somehow have fetched web-platform-tests/results-analysis-cache in some intermediary state?

I have theory of what's gone wrong, but I don't think so. Each run gets a tag only once the tree is built/committed, so there should be no intermediary state to fetch.

It's possible a broken conversion has happened, but that then isn't going to fix itself.

@DanielRyanSmith what do you think?

**Comment by gsnedders** [comment]
> I have no theory of what's gone wrong, but I don't think so. Each run gets a tag only once the tree is built/committed, so there should be no intermediary state to fetch.

The alternative is it gets written to the cache in an intermediary state, depending on when wpt.fyi starts serving it?

**Comment by gsnedders** [comment]
`git diff run/5128159591137280/results..run/5192142658469888/results -- css/css-cascade` shows quite a lot of changes (that should be from yesterday's to the current run today, for Chrome).

**Comment by gsnedders** [comment]
Ohhh, @DanielRyanSmith: this is because all-prop-revert-layer-noop.html is labelled, and thus considered part of the total number of tests, but we don't have any results for it because it's been split into variants.

**Comment by gsnedders** [comment]
> Is this something that requires changing the wpt-metadata to remove the old labeled tests? This is a new scenario that I don't think we've prepared for, and just changing the test name/path could change the historical data overall, as they're listed in older runs with a different path.

Yeah, this has been the problem anything like this happens, which is always unfortunate. This is was probably most apparent in 2021 where the tests were being revised pretty much throughout the year.

I've filed https://github.com/web-platform-tests/wpt-metadata/pull/3769 to change the metadata, and filed https://github.com/web-platform-tests/results-analysis/issues/149 to try and make this easier to debug.

**Comment by foolip** [comment]
I've filed https://github.com/web-platform-tests/interop/issues/284 about the generic problem.

@nt1m unlabeled the test in https://github.com/web-platform-tests/wpt-metadata/pull/3750 which should restore the Cascade Layers scores to 100 where they were before.

Leaving this issue open to decide what we do about the split test, which is now 8 individual tests. I'll comment on https://github.com/web-platform-tests/interop/issues/256 about what I think makes sense in general.

**Comment by nt1m** [comment]
> @nt1m unlabeled the test in https://github.com/web-platform-tests/wpt-metadata/pull/3750 which should restore the Cascade Layers scores to 100 where they were before.

I also merged Sam's PR: https://github.com/web-platform-tests/wpt-metadata/pull/3769 which relabeled the tests, the change that unlabeled the test was just temporary in order to merge the WPT manifest PR.

**Comment by foolip** [comment]
OK, so the scores are now back to 100 for both 2022 and 2023 dashboards. But historical scores before the new tests existing will be lower. We should work this out in https://github.com/web-platform-tests/interop/issues/283 + https://github.com/web-platform-tests/interop/issues/286.

**Comment by foolip** [comment]
And https://github.com/web-platform-tests/interop/issues/284 actually, that's the issue directly about this problem.
