### ISSUE TITLE
Propogation of overscroll-behaviour from body to root

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/interop#29]
**Description**
Blink propogates the `overflow-behavior` from the `<body>` element to the viewport, instead of from the root element to the viewport. See https://docs.google.com/document/d/1-pqljDgzzgRVve2oWUq237JPgtT12wcoctxbtBaHZdU/edit# for more.

**Bug reports**
[CHR-954423](https://bugs.chromium.org/p/chromium/issues/detail?id=954423)

**Specification**
https://drafts.csswg.org/css-overscroll/Overview.html
https://github.com/w3c/csswg-drafts/issues/6406

**Tests**
https://wpt.fyi/results/css/css-overflow?label=master&label=experimental&aligned&q=propagation (need to check exactly which tests cover this issue).

This is a bug to include in #9

**Comment by gsnedders** [comment]
> https://wpt.fyi/results/css/css-overflow?label=master&label=experimental&aligned&q=propagation (need to check exactly which tests cover this issue).

I'm unsure any of these tests actually cover this, looking at where there are differences?

**Comment by foolip** [comment]
@jgraham you've mentioned `overflow:scroll` but linked bugs and issues are about `overscroll-behavior`. Is that a typo, or is `overflow:scroll` a part of this too?

Also, are there examples of site compat issues caused by this?

**Comment by foolip** [comment]
The test for https://github.com/web-platform-tests/interop-2022/issues/30 does involve `overflow: scroll` so now I suspect there's just been a mixup of adjacent issues. @jgraham can you confirm?

**Comment by jgraham** [comment]
Yes, sorry this should have been `overscroll-behaviour`. I believe the bug and google doc linked are correct, and that browser match for `scroll-behaviour`, although I'm not certain about that. The Google doc has a big list of sites which are affected by the `overscroll-behaviour` difference. Some of the gecko bugs are developers running into this e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1560237

**Comment by jgraham** [comment]
@emilio might be able to confirm whether this issue is now correct :)

**Comment by emilio** [comment]
Yeah, this should probably just be about `overscroll-behavior`. Unfortunately are no WPT tests for this it seems, because we don't quite have the facility to test overscroll in WPT I think, and propagated styles are not exposed programmatically.

**Comment by jensimmons** [comment]
@smfr believes this is probably be very risky to change.

**Comment by jensimmons** [comment]
@jgraham Could you rewrite the title & description of this item, so we can all make sure we are talking about the same thing?

**Comment by smfr** [comment]
Oh, if this is about `overscroll-behaviour` then I have no concerns.

**Comment by jgraham** [comment]
> @jgraham Could you rewrite the title & description of this item, so we can all make sure we are talking about the same thing?

Done. Aplogies for the muddle on this one.
