### ISSUE TITLE
Retrospective: transparency in proposal selection and feedback

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#290]
This is part of https://github.com/web-platform-tests/interop/issues/274.

⚠️ First, I want to acknowledge that this is potentially a controversial topic, and I'm trying to represent things as fairly as I can. Still, how this played out will look different to different people and this is _my_ perspective, not a neutral/objective summary.

As we were starting proposal evaluation &ndash; around the time of https://github.com/web-platform-tests/interop/issues/240 &ndash; we discovered that there was a difference of opinion/preference within the interop team about what parts of our process should be public. What we ended up doing is documented in [Interop 2023 Proposal Selection](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). In summary only the outcome of the process was made public, and feedback on proposals was given by the interop team jointly, after considerable review of that feedback.

A few things didn't work great, from my point of view:
- The issue was not discussed in https://github.com/web-platform-tests/rfcs/pull/116 and not documented in [the RFC](https://github.com/web-platform-tests/rfcs/blob/master/rfcs/interop_2023.md). My assumption and intention was that the process would be transparent, making per-proposal decisions by consensus, and documenting those decisions in meeting notes or equivalent. I made this assumption because almost everything in web standards and WPT is public by default, and the Interop 2022 positions were made public via GitHub issues.
- Because we didn't have agreement to make individual positions public, we had to write joint feedback on proposals. In some cases the result was crisp and clear, IMHO better than individual feedback would have been. But in other cases the feedback was watered down since we didn't always agree about importance or priority, and used a common response instead.
- It's unclear what expectations we have for participants talking about their _own_ positions on features in public, since doing so would implicitly say something about _others'_ positions.

I'll not suggest any changes to the process in this issue, but I'd like to revisit this for Interop 2024 and I think we'd all benefit from documenting this clearly up-front before the process starts.

**Comment by slightlyoff** [comment]
@dandclark and I have been chatting, and while Microsoft has a concern about the lack of transparency in votes and vetoes, it would seem to me that the larger issue is that we're no longer feeding Interop from a needs assessment survey. 

That is to say, the legitimacy of selections has historically derived from direct evidence of developer interest, whereas in recent years that has not been so tightly paired with the categories that have made the cut. 

This risks eroding the project's value and and creating the perception that selections are political or can be gamed. A lack of transparency in voting and vetoes potentially bolsters this perception. Until and unless the selection process is re-grounded on evidence, sunlight regarding proposal support feels like an essential minimum to ensure the effort doesn't fall into disrepute.

**Comment by foolip** [comment]
@slightlyoff I'm glad to hear that Microsoft has also been discussing the process, that's great!

On developer interest, I think that we actually did pretty well with gathering feedback this time around:
- https://github.com/web-platform-tests/interop/issues/238
- https://github.com/web-platform-tests/interop/issues/245
- https://github.com/web-platform-tests/interop/issues/246
- https://github.com/web-platform-tests/interop/issues/248

There hasn't been a big survey like the MDN Web Developer Needs Assessment since 2020, but I agree that would be valuable. Over in https://www.w3.org/community/webdx/ we're looking at various forms of shared research, and I hope that for next year we'll have more input than we could get from State of CSS + MDN short surveys + frameworks this year.

Anyway, can I suggest another issue or comment in https://github.com/web-platform-tests/interop/issues/274 about developer needs?

**Comment by myakura** [comment]
Hi Interop! Sorry for joining late.

Thanks for evaluating and selecting [my proposal (Range Syntax in Media Queries)](https://github.com/web-platform-tests/interop/issues/141). I even saw Safari TP added support soon after. So wow. It's truly happening and I'm excited :)

What were good/helpful for me were:

* templates; not only description, rationale, but letting proposer to provide link to spec and tests makes (at least for me) think whether the feature I'm proposing is mature enough (so likely to be accepted) as a focus area
  * and comments like https://github.com/web-platform-tests/interop/issues/141#issuecomment-1255403150 are great guide to the wpt or spec internals and fun to read
* @foolip's comments on State of CSS / MDN short survey are also great. Those comments not only told me if the feature has developer (non-)interest, but also gave the thread a heartbeat, making me feel Interop team do care and seriously work on evaluating features.

What may not work well were:

* Mine is pretty great. But I see some other proposals didn't get much test feedback or heartbeat comments.
* I read the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md), but that reads a work mode document for the Interop team, not for proposers.
  * For those who whose proposal didn't get selected might wonder the reason or criteria to select a focus area.

I saw #290 and I hope I'll see the better summary in the next iteration :)
