### ISSUE TITLE
[css-color-4] Big number serialization problem

### ISSUE THREAD

**Issue by danielsakhapov** [web-platform-tests/interop#296]
### Test List

wpt.fyi/css/css-color/parsing/color-computed-color-function.html

Line:
test_computed_value("color", "color(display-p3 184 1.00001 2347329746587)", "color(display-p3 184 1.00001 2347329700000)", "[Display P3 color with component > 1 should not clamp]");

### Rationale

Turned out there is an issue with CSS numbers serialization being completely different from browser to browser with none of them being correct spec compliant: https://drafts.csswg.org/cssom/#serializing-css-values.

So, for the sake of Interopt 2023 progress, I propose we move this test case to a separate file like this:
https://chromium-review.googlesource.com/c/chromium/src/+/4303721.

And solve the problem of serialization separately.

**Comment by foolip** [comment]
This split makes sense to me, since serialization is a generic problem. If we can agree in this issue we don't need to spend meeting time on it.

@jgraham WDYT for Gecko?
@jensimmons WDYT for WebKit?

**Comment by jgraham** [comment]
I'm going to defer to @emilio

**Comment by emilio** [comment]
The whole point of this test is making sure that no clamping to 1 happens right? There's no need to use a massive number, can we just tweak the test to use, I dunno, `1000` rather than `2347329746587`?

The precision imposed by the spec is [here](https://drafts.csswg.org/css-color-4/#serializing-color-function-values), where you need 10 bits at least for display-p3.

I haven't done the math but I'm not sure that number would necessarily round-trip with a half-float or a 10-bit representation for components.

**Comment by foolip** [comment]
@emilio the test was tweaked to use 234732 instead of 2347329746587, but do you mean we don't need the (split out) serialization test for big numbers at all?

**Comment by emilio** [comment]
Probably they'd be useful? But they are not specific to `<color>` at all right?

**Comment by foolip** [comment]
The tests use the `color()` function, but I assume the same difference can be observed with many property values. I wouldn't be surprised if there are difference in serialization in different contexts, so testing a few different things from different eras of CSS would be good.

**Comment by gsnedders** [comment]
Given the name of "Display P3 color with component > 1 should not clamp", it seems like we can reduce the value we're using in the test to anything > 1, and we definitely don't need a number anywhere near as high as the number currently in the test. As such, it seems reasonable to keep the test in Interop with a vastly lower value (like 1000, as @Emilio suggested).

If people in Interop believe the CSS WG should specify what the actual range that round-trips is (which CSS has historically shied away from, thus historic problems with decimal percentages and max `z-index` values, which has affected the majority of browser engines at some point), that seems like something to (once again) take to the CSS WG.

**Comment by foolip** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/4303721 has landed
