### ISSUE TITLE
Remove Offscreen Canvas filter tests

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#297]
### Test List

https://wpt.fyi/results/html/canvas/offscreen/filters?label=experimental&label=master&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-offscreencanvas

### Rationale

Filters are orthogonal to Offscreen Canvas and also apply to normal canvases too.

**Comment by nt1m** [comment]
Also, CanvasFilter is not standardized currently.

**Comment by jgraham** [comment]
Gecko proposed removing these tests as part of the original issue: https://github.com/web-platform-tests/interop/issues/161#issuecomment-1316644751

**Comment by foolip** [comment]
Done in https://github.com/web-platform-tests/wpt-metadata/pull/3952.
