### ISSUE TITLE
Remove tests that depend on CSS zoom

### ISSUE THREAD

**Issue by emilio** [web-platform-tests/interop#298]
### Test List

https://wpt.fyi/results/css/css-masking/clip-path?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-cssmasking%20clip-path%20with-zoom

### Rationale

They depend on the non-standard `zoom` CSS property.

**Comment by nt1m** [comment]
Sounds fine

**Comment by foolip** [comment]
Yep, that seems fine.

**Comment by foolip** [comment]
Unlabeled in https://github.com/web-platform-tests/wpt-metadata/pull/3955.
