### ISSUE TITLE
Remove `appearance` cssom tests that require the removal of values needed for compat

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/interop#299]
### Test List

https://wpt.fyi/results/css/css-ui/appearance-cssom-001.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2022-forms%20or%20label%3Ainterop-2023-forms

### Rationale

We are failing four  subtests _because we support:_
- `-webkit-appearance: -apple-pay-button`
- `appearance: -apple-pay-button` 
- `-webkit-appearance: slider-vertical (invalid)`
- `appearance: slider-vertical (invalid)`

We will not be removing support for vertical sliders or Apple Pay buttons from WebKit. Doing so would create intolerable compat problems with existing sites and WebKit clients. 

The Interop project is striving for interoperability between browsers. When one browser supports an optional non-standard value that another browser does not support, that state does not create an interoperability problem for web developers. 

Whenever Interop and Compat are at odds, compat should win. We cannot break the web for the sake of tests.

**Comment by nt1m** [comment]
We could split the test in 2, one for legacy values (not included in Interop), one for values that need to be supported for compat.
