### ISSUE TITLE
Line boxes don't contribute to scrollable overflow

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/interop#30]
**Description**
In Gecko line boxes contribute directly to scrollable overflow, whereas in Chromium only the text within those line boxes contributes to scrollable overflow.

**Bug reports**
[CHR-1082517](https://bugs.chromium.org/p/chromium/issues/detail?id=1082517)
https://bugzilla.mozilla.org/show_bug.cgi?id=1637511
https://github.com/webcompat/web-bugs/issues/53125

**Specification**
https://drafts.csswg.org/css-overflow-3/#scrollable

**Tests**
?

This is a bug to include in #9

**Comment by foolip** [comment]
In discussion with @bfgeek, the Chrome team can try to ship https://bugs.chromium.org/p/chromium/issues/detail?id=1082517 again, but if that breaks too much, can we revisit the spec'd behavior and try changing Gecko instead?

When testing https://bug1637511.bmoattachments.org/attachment.cgi?id=9148082 I see the same behavior in Chrome and Safari, and being able to scroll to the text does seem like it's better.

Also, having WebKit on board with trying to change this seems important. cc @jensimmons @gsnedders

**Comment by jensimmons** [comment]
@jgraham We'd appreciate it if when you find such bugs, you check against all the engines, not just Chromium, and file bugs at [bugs.webkit.org](http://bugs.webkit.org) as well.

WebKit matches Chromium's behavior here. It does seem like investigation is needed to see if this can be changed.

**Comment by jensimmons** [comment]
Testing in Safari, it looks like WebKit matches the spec. 

Safari produces scrollbars for both blocks: 
![image](https://user-images.githubusercontent.com/108474/145068401-7003ed49-a113-4b85-a5ef-a8e39a0cc819.png)

**Comment by gsnedders** [comment]
> When testing https://bug1637511.bmoattachments.org/attachment.cgi?id=9148082 I see the same behavior in Chrome and Safari, and being able to scroll to the text does seem like it's better.

I see Safari and Firefox matching?
