### ISSUE TITLE
Tests (and spec) for `:user-valid` and `:user-invalid` are... light

### ISSUE THREAD

**Issue by mfreed7** [web-platform-tests/interop#304]
### Test List

https://wpt.fyi/results/css/selectors/user-invalid.html
https://wpt.fyi/results/css/selectors/user-valid.html

### Rationale

These tests of `:user-valid` and `:user-invalid` will 100% pass if:
 1. Those two pseudo classes are parsed as valid by the CSS parser.
 2. They never match any elements.

Here is the `:user-valid` test, in its entirety:
```javascript
  const input = document.querySelector('input');
  assert_true(input.validity.valid);
  // The selector can't match because no interaction has happened.
  assert_false(input.matches(':user-valid'));
```

The spec is located here:
https://w3c.github.io/csswg-drafts/selectors-4/#user-pseudos

It uses phrasing like "the user has significantly interacted with it" and "interacted again" as a criterion for when to apply these pseudos, but I'm not clear that we've defined those cases clearly enough to be interoperable. There's an open discussion in the interop issue for this set of features, and this comment (https://github.com/web-platform-tests/interop/issues/178#issuecomment-1308648986) attempts to define the behavior in terms of links to Gecko code. That's great, and I'm sure the proposed behavior is reasonable. But I think that this Interop2023 issue is kind of pointless unless we have significantly more testing, and that will require significantly more discussion about exactly how to spec the feature. Chromium is supportive of this feature, but only if it can be implemented, spec'd, and tested interoperably.

How should we proceed?

@emilio @annevk

**Comment by annevk** [comment]
Right, see https://github.com/whatwg/html/issues/8452.

**Comment by mfreed7** [comment]
> Right, see [whatwg/html#8452](https://github.com/whatwg/html/issues/8452).

Ahh, thanks! I missed that issue.

**Comment by mfreed7** [comment]
> I'm going to take on the work to spec user-invalid/valid

Awesome, thanks!

**Comment by nt1m** [comment]
Here's might first attempt at specifying: https://github.com/whatwg/html/pull/9047

**Comment by nt1m** [comment]
These are the changes fwiw: https://github.com/web-platform-tests/wpt/commit/b669c6ca5fcf14a9c59807f93f1b769acf5cfb8b

**Comment by mfreed7** [comment]
> @mfreed7 Can you let us know if the new tests are sufficient and close the issue if needed? I'll work on the spec & further tests when I have more time.

Thanks - the new tests look pretty good. I can't think of another case to check, off-hand, but we'll possibly find more as we start to implement it. But for now I think this is great, so I'll close it.

**Comment by nt1m** [comment]
Given Chromium is implementing :user-valid/:user-invalid, I'm going to close this: https://chromium-review.googlesource.com/4800294

I'm hoping the spec PR can be merged soon as well.
