### ISSUE TITLE
CQ tests that depend on other features

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/interop#305]
### Test List

See below.

### Rationale

@emilio found these are failing in Gecko for reasons unrelated to CQ:

- Some depend on TypedOM: [container-units-typed-om.html](https://wpt.fyi/results/css/css-contain/container-queries/container-units-typed-om.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-container), [container-units-computational-independence.html](https://wpt.fyi/results/css/css-contain/container-queries/container-units-computational-independence.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-container)
- Some depend on a super-old ::first-letter/::first-line interop issue (where we don’t let ::first-letter/line cross to child blocks): [inner-first-line-non-matching.html](https://wpt.fyi/results/css/css-contain/container-queries/inner-first-line-non-matching.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-container), [pseudo-elements-002.html](https://wpt.fyi/results/css/css-contain/container-queries/pseudo-elements-002.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-container)
  - This would need to split the test since the others are valuable.
- Some depend on `@property`: [container-inner-at-rules.html](https://wpt.fyi/results/css/css-contain/container-queries/container-inner-at-rules.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-container)
  - Maybe OK to keep since `@property` is another focus area.
- Some depend on custom layout: [custom-layout-container-001.https.html](https://wpt.fyi/results/css/css-contain/container-queries/custom-layout-container-001.https.html?label=experimental&label=master&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-container)
  - This one was removed in https://github.com/web-platform-tests/wpt-metadata/pull/3953

**Comment by nt1m** [comment]
This seems fine to me.

**Comment by foolip** [comment]
@nairnandu has checked with @lilles, this one is OK for Chromium.

@zcorpan can you prepare a PR to drop the tests?

**Comment by zcorpan** [comment]
>     * Some depend on TypedOM: [container-units-typed-om.html](https://wpt.fyi/results/css/css-contain/container-queries/container-units-typed-om.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-container), [container-units-computational-independence.html](https://wpt.fyi/results/css/css-contain/container-queries/container-units-computational-independence.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-container)

https://github.com/web-platform-tests/wpt-metadata/pull/4055
 
>     * Some depend on a super-old ::first-letter/::first-line interop issue (where we don’t let ::first-letter/line cross to child blocks): [inner-first-line-non-matching.html](https://wpt.fyi/results/css/css-contain/container-queries/inner-first-line-non-matching.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-container), [pseudo-elements-002.html](https://wpt.fyi/results/css/css-contain/container-queries/pseudo-elements-002.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-container)
>       
>       * This would need to split the test since the others are valuable.

Not done yet.

**Comment by zcorpan** [comment]
ping

**Comment by zcorpan** [comment]
PRs are merged.
