### ISSUE TITLE
Consider adding `infinity`/`NaN` tests for more interop-2023-mathfunctions tests

### ISSUE THREAD

**Issue by CanadaHonk** [web-platform-tests/interop#306]
`exp-log-*`, `hypot-pow-sqrt-*`, and `round-mod-rem-*` all lack any tests using `infinity` or `-infinity` or `NaN`, would be nice to have those as well like the other `interop-2023-mathfunctions` tests (imo).

**Comment by foolip** [comment]
@nairnandu has checked with @lilles, this one is OK for Chromium.

**Comment by nt1m** [comment]
Seems fine to have more test coverage, though do we have the test list?

**Comment by CanadaHonk** [comment]
Fwiw, I've also added various new NaN/inf calc tests whilst improving Gecko's implementation downstream in the last ~month. (Usually ones I've caught whilst improving so other vendors can ensure they don't have the same issues which were otherwise untested.)

**Comment by jgraham** [comment]
I believe we're OK with this; the tests were added as part of the Gecko implementation. I don't think we can/should extend the scope to NaN/Infinity handling beyond the math functions (although of course having the tests is useful anyway). CC @emilio

**Comment by CanadaHonk** [comment]
@foolip I was mostly ensuring it's fine to add tests under interop 2023 label(s) for some potential Gecko implementation improvements with inf/nan, will likely add some in the upcoming month(s) if ran into. Thanks!

**Comment by foolip** [comment]
@CanadaHonk please do improve test coverage if you're able to while working on this in Gecko. If they are new tests and we'll need to label them to include in Interop 2023, would you mind filing a new issue? For now, I'll go ahead and close this.
