### ISSUE TITLE
Remove the pointerevent test that is for touch input

### ISSUE THREAD

**Issue by EdgarChen** [web-platform-tests/interop#307]
### Test List

https://wpt.fyi/results/pointerevents/pointerevent_pointercancel_touch.html

### Rationale

The test is for touch input, but according to https://github.com/web-platform-tests/interop/issues/202#issue-1406264526, we have decided to exclude touch and stylus from Interop 2023 due to the lack of WPT testing support across all browsers. Therefore, Interop 2023 will focus only on mouse input. Should we drop this test from Interop 2023?

**Comment by flackr** [comment]
Sounds good to me to remove these touch tests from the 2023 focus.

I hope that we can eventually support them in 2024 or later - I think there are a fair number of discrepancies in touch handling.

**Comment by foolip** [comment]
I'm dropping the test in https://github.com/web-platform-tests/wpt-metadata/pull/4095.
