### ISSUE TITLE
Tests for non-standard `MouseEvent.toElement`/`MouseEvent.fromElement` properties

### ISSUE THREAD

**Issue by EdgarChen** [web-platform-tests/interop#308]
### Test List

https://wpt.fyi/results/pointerevents/pointerevent_attributes_hoverable_pointers.html%3Fmouse?label=experimental&label=master&aligned
https://wpt.fyi/results/pointerevents/pointerevent_attributes_nohover_pointers.html

### Rationale

The tests are currently using [pointerevent_supports.js](https://github.com/web-platform-tests/wpt/blob/master/pointerevents/pointerevent_support.js) which tests `MouseEvent.toElement` and `MouseEvent.fromElement` properties. However, these properties are not currently implemented in Firefox and are not defined in the spec (https://github.com/w3c/uievents/issues/84) either. So either these would need to be spec'ed or removed from the test, how should we proceed?

**Comment by foolip** [comment]
@flackr can you review this proposal?

**Comment by nt1m** [comment]
If this isn't something that we agreed on to test during the investigations, this is fine for us (cc @dcrousso who no longer works at Apple).

**Comment by flackr** [comment]
I believe this is just intended to test the assertion that `fromElement` and `toElement` if defined in mouse events, are null in pointer events, per [this note](https://www.w3.org/TR/pointerevents/#:~:text=In%20those%20user%20agents%2C%20the%20values%20of%20those%20(inherited)%20attributes%20in%20PointerEvents%20must%20be%20null):

> Many user agents expose non-standard attributes fromElement and toElement in MouseEvents to support legacy content. In those user agents, the values of those (inherited) attributes in PointerEvents must be null to encourage the use of the standardized alternates (i.e. target and relatedTarget).

So it sounds like `assert_implements_optional` is the right way to go.

**Comment by gsnedders** [comment]
https://github.com/web-platform-tests/wpt/pull/39302 has a concrete PR to resolve this.

**Comment by foolip** [comment]
I have merged https://github.com/web-platform-tests/wpt/pull/39302, calling this done.
