### ISSUE TITLE
Remove forms/the-input-element/email-set-value.html from Interop 2023

### ISSUE THREAD

**Issue by sefeng211** [web-platform-tests/interop#309]
### Test List

https://wpt.fyi/results/html/semantics/forms/the-input-element/email-set-value.html?label=experimental&label=master&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2022-forms%20or%20label%3Ainterop-2023-forms

### Rationale

This test uses Selection.toString() which is not specified according to https://github.com/w3c/selection-api/issues/7, so the behaviour is not consistent across browsers.

**Comment by foolip** [comment]
@mfreed7 can you review this proposed change?

**Comment by mfreed7** [comment]
> This seems fine. @rniwa attempted in the past to change that test to not rely on `Selection.toString()`, but it's actually not trivial.

Given this comment, I'm supportive of removing this test from Interop.
