### ISSUE TITLE
Rename yearly goals to remove the "20" prefix?

### ISSUE THREAD

**Issue by chrishtr** [web-platform-tests/interop#310]
I'd like to suggest renaming Interop 2023 to Interop23.

Why:

* Hard to say twenty-twenty-three--a bit of a tongue-twister
* The twenty is redundant since we're not even halfway through the decade at this point
* I keep hearing people outside the project accidentally say Interop23 in conversations or email (related to bullet 1)
* `#Interop23` is easier to hashtag

Group, WDYT?

**Comment by foolip** [comment]
I've definitely stumbled on words when trying to say this, often going with twenty-twenty-twenty-three instread.

Interop &rsquo;23 SGTM.

**Comment by jgraham** [comment]
I'm against rebranding in the middle of a year. Of course we can have the conversation for 2024.

**Comment by gsnedders** [comment]
> I'm against rebranding in the middle of a year. Of course we can have the conversation for 2024.

We're +1 on this.
