### ISSUE TITLE
Add css/css-overflow/overflow-overlay.html to WebCompat focus area

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/interop#311]
### Test List

https://wpt.fyi/results/css/css-overflow/overflow-overlay.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=overflow-overlay

### Rationale

https://github.com/web-platform-tests/interop/issues/187 proposed including `overflow:overlay` aliased as `overflow:auto` in the web compatibility focus area, because not supporting this property was breaking many sites. At the time there wasn't a test, or a spec. But now we have a test, and the [spec has been updated](https://drafts.csswg.org/css-overflow-3/#valdef-overflow-auto) so it makes sense to label this test as originally intended.

**Comment by nt1m** [comment]
Seems fine.

**Comment by nairnandu** [comment]
Spoke to @chrishtr about this one and he agrees with this change
