### ISSUE TITLE
Remove /html/semantics/forms/the-input-element/selection-pointer.html from Interop 2023

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/interop#313]
### Test List

https://wpt.fyi/results/html/semantics/forms/the-input-element/selection-pointer.html?label=experimental&label=master&aligned

### Rationale

Per discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1738866 this test fails in Firefox because we support multiple selections. There's a spec issue about this at https://github.com/w3c/selection-api/issues/41 and it looks like there's some interest to support multiple selections also in Chromium.

cc @masayuki-nakano

**Comment by karlcow** [comment]
That said the spec issue has not been discussed for 5 years.

Last meaningful updates 
* 5 years ago on https://bugs.webkit.org/show_bug.cgi?id=186465
* 4 years ago https://bugs.chromium.org/p/chromium/issues/detail?id=851279

Should the discussion restart on the WG to test if there is new will on moving forward?

cc @rniwa too

**Comment by hsinyi** [comment]
AFAIK, there is still recent discussion about multiple ranges in https://github.com/w3c/selection-api/issues/161.

**Comment by foolip** [comment]
@mfreed7 can you review this proposed change?

**Comment by mfreed7** [comment]
Hmm, I'm still not convinced about the multi-range thing being discussed on https://github.com/w3c/selection-api/issues/161.

But aside from that - rather than just remove the test entirely, perhaps it's possible to instead modify the test so that it's compatible with multiple ranges? E.g. for the cases where the selection includes an unselectable item, make the test pass in either the single-range or multi-range support case?

**Comment by foolip** [comment]
We discussed this in https://github.com/web-platform-tests/interop/issues/323 and the conclusion is if that if the test can be updated to tolerate either behavior for selections and ranges, everyone will be happy.

**Comment by mfreed7** [comment]
> We discussed this in #323 and the conclusion is if that if the test can be updated to tolerate either behavior for selections and ranges, everyone will be happy.

So I've updated the test here: https://github.com/web-platform-tests/wpt/pull/39753

I wasn't able to run the actual test locally on Gecko or WebKit, but my local testing looks like it should have worked. I can tweak as needed, if someone points out an issue.
