### ISSUE TITLE
Add new border-image tests

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#314]
### Test List

css/css-backgrounds/border-image-repeat-repeat-001.html
css/css-backgrounds/border-image-slice-fill-001.html
css/css-backgrounds/border-image-slice-fill-002.html
css/css-backgrounds/border-image-slice-fill-003.html

### Rationale

These were added to the WPT repo after the interop launch and reveal some interop issues regarding border-image.

https://github.com/web-platform-tests/wpt/commit/d14a5dd7d73fd4492fb52fef372a3823614f3777
https://github.com/web-platform-tests/wpt/commit/0c7d29a3be0c265fb8d5b6416d978686c5644242

**Comment by jgraham** [comment]
@dholbert does this seem reasonable to you?

**Comment by dholbert** [comment]
Yeah, this is fine.  These test-failures appear to be tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1819485 , for what it's worth.

**Comment by dholbert** [comment]
(I haven't looked too deeply at the `border-image-repeat-repeat-001.html` test failure, but based on the naming & properties used, I'd guess it's testing the same thing as [css3-border-image-repeat-repeat.html](https://wpt.fyi/results/css/css-backgrounds/css3-border-image-repeat-repeat.html] and failing in Firefox for the same reason as that test.  That one is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1820659 .

**Comment by nt1m** [comment]
Thanks Daniel! @foolip can you find someone from the Google side to review this test change proposal?

**Comment by progers** [comment]
This proposal looks good from the Google side too.

**Comment by nt1m** [comment]
https://github.com/web-platform-tests/wpt-metadata/pull/4051
