### ISSUE TITLE
Proposal to remove <audio> element from contain-inline-size-replaced.html

### ISSUE THREAD

**Issue by vmpstr** [web-platform-tests/interop#317]
### Test List

https://wpt.fyi/results/css/css-contain/contain-inline-size-replaced.html

### Rationale

I'm proposing to remove <audio> element subtests from the contain-inline-size-replaced.html tests, which is a part of containment interop

The <audio> element is underspecified and is implemented in different ways in different browsers. It is sized differently and responds to containment in different ways. One of the subtests is failing on 3/3 major browsers. The other subtest is failing on 2/3 major browsers. 

Additional discussion: https://github.com/web-platform-tests/wpt/issues/39325

**Comment by vmpstr** [comment]
@dholbert you mentioned that you would be ok with this change, is that still the case?

@nt1m would you be able to say if WebKit is OK with change as well?

If everyone agrees, I can make the change

/cc @foolip as an fyi

**Comment by nt1m** [comment]
@rwlbuis @cathiechen What do you think?

**Comment by dholbert** [comment]
Yes, I'm still OK with the change; my [thinking from the "additional discussion" linked-issue](https://github.com/web-platform-tests/wpt/issues/39325#issuecomment-1493448584) still applies.

(tl;dr: the test is assuming that browsers don't have UA stylesheet rules to apply a particular `writing-mode` or default `width`/`height` values on this element. In practice, browsers do actually do those things.  And in terms of actual author-impacting interop concerns, the "does contain:size collapse an audio element to 0x0" question does not seem particularly important.)

**Comment by rwlbuis** [comment]
> @rwlbuis @cathiechen What do you think?

Cathie knows size containment better. FWIW, at the time audio was the only subtest I could not fix (https://bugs.webkit.org/show_bug.cgi?id=244799), so would be nice to get this corrected and passing.

**Comment by cathiechen** [comment]
Sorry for the slow reply!

Yes, this change looks good to me!
In WebKit, audio has `min-width: 44px !important`, so `contain: inline-size` is not effective in this case.
