### ISSUE TITLE
Remove /css/css-flexbox/flexbox-align-self-baseline-horiz-008.xhtml from Interop 2023

### ISSUE THREAD

**Issue by davidsgrogan** [web-platform-tests/interop#320]
### Test List

https://wpt.fyi/results/css/css-flexbox/flexbox-align-self-baseline-horiz-008.xhtml?label=experimental&label=master&product=chrome&product=firefox&product=safari&aligned&view=subtest

### Rationale

Relies on having implemented `writing-mode: sideways-rl;`, a feature that neither Webkit nor Blink have shipped, and isn't part of Interop 2023.

**Comment by foolip** [comment]
@jgraham can you review this for Gecko?

@gsnedders @nt1m can you review this for WebKit?

**Comment by nt1m** [comment]
Is it possible to replace with `vertical-lr/rl`? or is that already covered by another test?

But yeah, I agree we shouldn't have tests relying on sideways WM for Interop 2023

**Comment by davidsgrogan** [comment]
That's kind of covered by http://wpt.live/css/css-flexbox/flexbox-align-self-baseline-horiz-006.xhtml . I say "kind of" because 006 is about orthogonal children, not where the whole container is in a vertical writing mode.

Other than that, there isn't a straight translation of flexbox-align-self-baseline-horiz-008.xhtml for vertical writing modes.

Switching to vertical writing mode SGTM.

**Comment by davidsgrogan** [comment]
Sorry, I'm new to the process... does the process require input from all 3 engines before there can BE a conclusion? (Haven't heard from gecko yet.)

**Comment by bfgeek** [comment]
This test should just be excluded rather than changing. The test is valuable for implementations which implement the sideways variant, and we shouldn't decrease their test coverage to make a number go up. :).

Ian

**Comment by davidsgrogan** [comment]
+1 to Ian. The more I thought about it I agree that we shouldn't change the test... it is a totally valid test as is, it just covers an area we're not doing this year.

**Comment by davidsgrogan** [comment]
ping @nt1m and @jgraham

**Comment by nt1m** [comment]
that seems fine too

**Comment by jgraham** [comment]
@emilio Does removing this test seem reasonable?

**Comment by emilio** [comment]
Seems reasonable

**Comment by foolip** [comment]
Cool, we have enough support for this now, I'll land https://github.com/web-platform-tests/wpt-metadata/pull/4156.
