### ISSUE TITLE
Change motion path <ray> <contain> test references as per spec change

### ISSUE THREAD

**Issue by danielsakhapov** [web-platform-tests/interop#321]
### Test List

https://wpt.fyi//css/motion/offset-path-ray-contain-001-ref.html
https://wpt.fyi//css/motion/offset-path-ray-contain-002-ref.html
https://wpt.fyi//css/motion/offset-path-ray-contain-003-ref.html
https://wpt.fyi//css/motion/offset-path-ray-contain-004-ref.html
https://wpt.fyi//css/motion/offset-path-ray-contain-005-ref.html

### Rationale

Spec: https://drafts.fxtf.org/motion/#valdef-ray-contain
Test changes are due to the recent spec change: previously <contain> implied that the box should be inside the circle, formed by the radius of the ray length. Now it became easier as <contain> just reduces the ray length by a fixed value.

CL to see the changes: https://chromium-review.googlesource.com/c/chromium/src/+/4453583

**Comment by danielsakhapov** [comment]
@tabatkins @BorisChiou @dirkschulze FYI

**Comment by BorisChiou** [comment]
Thanks for updating the tests. :)

**Comment by foolip** [comment]
@BorisChiou can we treat that as a thumbs from Gecko to update these tests? cc @jgraham

@nt1m @gsnedders can you take a look for WebKit?

**Comment by BorisChiou** [comment]
Yes. Just a nitpick: perhaps we can tweak `offset-path-ray-contain-001.html` a little bit to avoid using non integer value, e.g. `translate(64.645px, -164.645px)` in the ref html.

Anyway, the current version of your patch (WPT part) looks good to me (from Gecko).

**Comment by foolip** [comment]
We discussed this in https://github.com/web-platform-tests/interop/issues/323 and the summary is that while not everyone has studies the changes in detail, there was no objection to making the changes and following up as implementers uncover more issues in the course of working on the feature. (Which is business as usual.) But we wanted some paper trail of WebKit approval to update the tests, so I'll assign this to @nt1m.

**Comment by danielsakhapov** [comment]
@gsnedders yes, it is

**Comment by nt1m** [comment]
Based on internal feedback, I think we can go ahead and adjust again later as we find issues when implementing.

**Comment by foolip** [comment]
Thank all, this proposal is approved based on feedback above. @danielsakhapov please feel free to land the changes.
