### ISSUE TITLE
Split tests depending on style() queries out of query-container.html

### ISSUE THREAD

**Issue by lilles** [web-platform-tests/interop#322]
### Test List

Tests that rely on style() queries fail in all browsers in:

https://wpt.fyi/css/css-contain/container-queries/query-evaluation.html

### Rationale

Since none of the browsers support style() queries for standard properties, I propose that we move the tests depending on style() queries out of query-evaluation.html into a new style-query-evaluation.html file which is not covered by Interop 2023.

Also, change the queries to use custom property queries instead, but that is not really relevant to Interop 2023.

**Comment by foolip** [comment]
@jgraham can you review this for Gecko?

@gsnedders @nt1m can you review this for WebKit?

**Comment by nt1m** [comment]
Style queries were explicitly excluded from the original proposal so we're in favor of splitting the test.

**Comment by foolip** [comment]
@lilles do you have a PR showing what this will look like?

**Comment by jgraham** [comment]
Yes, that seems like it's just a test fix to match the agreed scope, so it's fine.

**Comment by foolip** [comment]
Thanks all, we have enough signoff of this now so I'll close the issue. @lilles please feel free to go ahead with the changes.
