### ISSUE TITLE
Add more currentcolor in color-mix() tests into Interop 2023

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#324]
### Test List

css/css-color/color-mix-currentcolor-003.html
css/css-backgrounds/color-mix-currentcolor-border-repaint-parent.html
css/css-backgrounds/color-mix-currentcolor-border-repaint.html
svg/painting/color-mix-currentcolor-fill-stroke-repaint.html

### Rationale

These exercise actual browser bugs.

**Comment by nt1m** [comment]
@emilio

**Comment by lilles** [comment]
sgtm

**Comment by foolip** [comment]
Reopening to make sure it's all actually landed.

**Comment by foolip** [comment]
Alright, done in https://github.com/web-platform-tests/wpt-metadata/pull/4158 + https://github.com/web-platform-tests/wpt-metadata/pull/4159 + https://github.com/web-platform-tests/wpt-metadata/pull/4162.
