### ISSUE TITLE
Investigation area documentation norms

### ISSUE THREAD

**Issue by boazsender** [web-platform-tests/interop#325]
We're creating some documentation for how to test ARIA in https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/40 and https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/24, and I'm realizing that it might make sense to norm on where we'd like those docs to live. I would propose adding new docs created by investigation areas to http://web-platform-tests.org/writing-tests/index.html. Does this make sense to y'all?

**Comment by jgraham** [comment]
I don't think there's a general rule for where documentation coming out of investigation efforts in particular should live. If for any specific investigation (or documentation in general) should live it's probably worth opening an issue in web-platform-tests, ask in the wpt matrix channel, or ask the wpt core team.
