### ISSUE TITLE
Add css/css-contain/container-queries/container-units-content-box.html

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#326]
### Test List

css/css-contain/container-queries/container-units-content-box.html

### Rationale

Exercises a browser bug.

**Comment by nairnandu** [comment]
@lilles @jgraham does this look good to you?

**Comment by lilles** [comment]
lgtm

**Comment by foolip** [comment]
Thanks all, I've labeled the test in https://github.com/web-platform-tests/wpt-metadata/pull/4265.
