### ISSUE TITLE
Remove a test case of custom-elements/custom-element-registry/per-global.html from interop 2023

### ISSUE THREAD

**Issue by xiaochengh** [web-platform-tests/interop#330]
### Test List

`custom-elements/custom-element-registry/per-global.html`

(and any other test using `/common/object-association.js`)

### Rationale

The first test case of this test (and similar tests) is controversial.

It asserts that the `Window` object is reused when navigating from the initial empty document, and therefore, the global objects (`window.customElements` etc) are preserved. While this is currently correct per-spec, there are discussions (e.g. https://github.com/whatwg/html/issues/3267 and https://bugs.chromium.org/p/chromium/issues/detail?id=717715#c25) whether to change this behavior.

So I think we shouldn't include this test case. We should move the test case into a new test file that's not in interop 2023, and keep the remaining two test cases in interop 2023.

@domenic @rakina

**Comment by domenic** [comment]
I'd rather not split the file, as it uses a generic helper that we want to keep centralized and maintained. But hopefully Interop 2023 can figure out how to make their scoring system work.

**Comment by xiaochengh** [comment]
Or do we really need this test in interop 2023?

It doesn't have anything specific with web components, but is more of testing the page lifecycle. So putting it under the "Web Components" is already a bit misplaced. And page lifecycle isn't a target area of interop 2023.

**Comment by gsnedders** [comment]
Yeah, dropping this as it is primarily a page lifecycle thing (and only tangentially custom elements) seems like the sensible thing here.

**Comment by xiaochengh** [comment]
Can I go ahead to remove the test, or is more process needed?

**Comment by foolip** [comment]
We also need sign-off from someone Mozilla. @jgraham @zcorpan can you take a look?

**Comment by zcorpan** [comment]
LGTM

**Comment by foolip** [comment]
Thank all for the feedback, we have enough support for this change now. I've unlabeled the test in https://github.com/web-platform-tests/wpt-metadata/pull/4264.
