### ISSUE TITLE
Interop 2024 brainstorming

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#331]
In https://github.com/web-platform-tests/interop/issues/329 we discussed the upcoming process for Interop 2024. @gsnedders mentioned Apple has been discussing internally and have something to share soon.

Here's the skeleton of a proposal that I wrote down a while ago, lightly edited to share now:

**Embrace these constraints**:

- Limit number of focus areas to 25 (keep it focused)
- Don’t evaluate all proposals, only the more promising ones (reduce amount of work)

**Process outline**:

- Be more aggressive about retiring focus areas, calling them done.
- Be careful to only include focus areas we believe we can complete.
- For new proposals, require public support from 2 orgs, similar to WHATWG normative spec changes. That puts the proposal up for a decision.
- Decide on inclusion of the proposal by consensus rules. Decisions are recorded in public notes. (Off-the-record conversations are still possible, but we cannot just say “there was a veto” in the notes.)

**Observations**:

- No champion for a proposal means no action required by anyone, cutting down time required for those proposals.

**Comment by jgraham** [comment]
> **Embrace these constraints**:
> 
>     * Limit number of focus areas to 25 (keep it focused)

That makes sense, but I think some thought is required about how to know how many slots there are given that things may still be landing when the proposal selection is going on. There's some danger we end up with a fraction of the slots filled with things that are complete before the new Interop launches.

>     * Don’t evaluate all proposals, only the more promising ones (reduce amount of work)

I think how to decide what counts as a "promising" proposal is a problem.

>     * For new proposals, require public support from 2 orgs, similar to WHATWG normative spec changes. That puts the proposal up for a decision.

I don't think this makes sense from an ordering point of view. It's very likely that there are proposals that we in principle think are good ideas, but might not fit into Interop 2024 given other proposals and constraints.

>     * Decide on inclusion of the proposal by consensus rules. Decisions are recorded in public notes. (Off-the-record conversations are still possible, but we cannot just say “there was a veto” in the notes.)

I continue to believe that the Interop team should be prepared to take collective responsibility for the outcomes of its processes.

**Comment by foolip** [comment]
> > **Embrace these constraints**:
> > 
> > * Limit number of focus areas to 25 (keep it focused)
> 
> That makes sense, but I think some thought is required about how to know how many slots there are given that things may still be landing when the proposal selection is going on. There's some danger we end up with a fraction of the slots filled with things that are complete before the new Interop launches.

Yeah, as you pointed out in the meeting we might not know until late in the year how many existing focus areas we can call done. One idea is to rank the tentatively accepted proposals and fill as many slots as open up, but ranking is not trivial, it brings along some of the challenges as voting (as opposed to consensus).

> > * Don’t evaluate all proposals, only the more promising ones (reduce amount of work)
> 
> I think how to decide what counts as a "promising" proposal is a (solvable, but important) problem.

What I had in mind here is the "require public support from 2 orgs" condition. It would reduce the amount of work, and byt how much depends a lot on how organizations treat the step to express public support. If it's done sparingly it would reduce the amount of work by a lot, and if done very liberally it won't reduce work much.

> > * For new proposals, require public support from 2 orgs, similar to WHATWG normative spec changes. That puts the proposal up for a decision.
> 
> I don't think this makes sense from an ordering point of view. It's very likely that there are proposals that we in principle think are good ideas, but might not fit into Interop 2024 given other proposals and constraints.

Can you elaborate? The public support would mean "we think this might be a good fit for Interop 2024" and the absence of public support would at most mean "there are other things we think are a better fit", and certainly not "we think this feature is bad." The latter is more the realm of standards positions repos. 

> > * Decide on inclusion of the proposal by consensus rules. Decisions are recorded in public notes. (Off-the-record conversations are still possible, but we cannot just say “there was a veto” in the notes.)
> 
> I continue to believe that the Interop team should be prepared to take collective responsibility for the outcomes of its processes.

This is about how we communicate the outcome, and I don't think that is at odds with recording decisions. Like many working groups, we can make group decisions and communicate with one voice. In the retrospective we had a discussion about the extra time it took to write joint feedback and how it sometimes made the feedback better and sometimes less clear, but I think that's a separable question.

**Comment by karlcow** [comment]
@foolip To better understand the proposal.

> Decide on inclusion of the proposal by consensus rules. 

ok. So during the meeting there was at least 2 orgs, and no opposition.

> Decisions are recorded in public notes. (Off-the-record conversations are still possible, but we cannot just say “there was a veto” in the notes.)

So here the proposal is to record organization dissent. 
Was there an issue the previous years which needs to be solved? 

In a collective responsibility scenario: Something is accepted or rejected. There's no need to even say "There was a veto." (Signaling veto right away makes the collective responsibility feeble and destroy the notion of a unified group with one voice.)

**Comment by foolip** [comment]
> @foolip To better understand the proposal.
> 
> > Decide on inclusion of the proposal by consensus rules.
> 
> ok. So during the meeting there was at least 2 orgs, and no opposition.

Yes, that's the idea, although it's not essential that decisions are made in meetings, we can also make decisions async on GitHub, in spreadsheets, etc.

> > Decisions are recorded in public notes. (Off-the-record conversations are still possible, but we cannot just say “there was a veto” in the notes.)
> 
> So here the proposal is to record organization dissent. Was there an issue the previous years which needs to be solved?

The big issue from my point of view is that it was not clear during the process what would be public and not. The process we wrote down made no mention of confidentiality, so some participants assumed that it would all be public, just like Interop 2022 planning. Other participants assumed the oppose. The conclusion from our retrospective was that we need to be clear up front about expectations.

> In a collective responsibility scenario: Something is accepted or rejected. There's no need to even say "There was a veto." (Signaling veto right away makes the collective responsibility feeble and destroy the notion of a unified group with one voice.)

I believe we can communicate the results in one voice, and can do so with care. The joint feedback drafting for Interop 2023 was very time consuming, but if the team thinks it's valuable and essential, we can keep doing that.

**Comment by othermaciej** [comment]
> In #329 we discussed the upcoming process for Interop 2024. @gsnedders mentioned Apple has been discussing internally and have something to share soon.
> 
> Here's the skeleton of a proposal that I wrote down a while ago, lightly edited to share now:
> 
> **Embrace these constraints**:
> 
> * Limit number of focus areas to 25 (keep it focused)

Limiting the number of focus areas is good, but 25 may already be too high. The 15 total over of Interop 2022 seemed like a sweet spot for focused progress (even if the 2022 "compat" bucket was a bit of a grab bag). The 26 count of Interop 2023s seem like too much, while the 5 count from 2021 was probably fewer than optimal. 

For the 2022 results as of today:

- 20% of areas have an interop score >98%
- 53% of areas have an interop score >95%
- 73% of areas have an interop score >90%
- 93% of areas have an interop score >85%

Some of this is due to continuing improvements past the end of calendar 2022, admittedly, but this is pretty good. Do we expect Interop 2023 results to look this good in May 2024? I would guess not. Worst case we can look at it then and apply lessons learned to Interop 2025 planning.

**Comment by BearCooder** [comment]
Of course this number 90% is just arbitrary, I dont know whats the good fit is. 100% would be obviously a dream but not sure if thats achievable for every area

**Comment by foolip** [comment]
@BearCooder we haven't entirely settled how we're going to decide which focus areas from 2023 to carry over into 2024, but the 90% cutoff point has in fact been proposed. However, I think the more likely criteria we're going to use is that everyone agrees to carry it forward, and that the score will inform us in a non-binding way about what's most worth continuing.

Since Interop 2024 opened up for proposals yesterday, I'll close this issue now.
