### ISSUE TITLE
Make color-mix() and RCS using rgb, hsl and hwb return round-trippable, unbounded results in color(srgb ...)

### ISSUE THREAD

**Issue by mysteryDate** [web-platform-tests/interop#333]
### Test List

https://wpt.fyi/results/css/css-color/parsing/color-computed-color-mix-function.html 
https://wpt.fyi/results/css/css-color/parsing/color-mix-out-of-gamut.html
~~https://wpt.fyi/results/css/css-color/parsing/color-computed-relative-color.html
https://wpt.fyi/results/css/css-color/parsing/color-valid-relative-color.html~~
 
These will all need to change to return `color(srgb ...)` for inputs with `rgb`, `hsl` and `hwb`, and that no gamut mapping is applied. Also "gamut-mapping.html" should be renamed to "color-mix-out-of-gamut.html".

### Rationale

From the discussion here: https://github.com/w3c/csswg-drafts/issues/8444
The following resolution was reached: https://github.com/mozilla/wg-decisions/issues/1125

Parsed and computed results of `color-mix` and relative color syntax for legacy colors should return colors in the format `color(srgb ....)`.

**Comment by emilio** [comment]
Relative colors were explicitly not part of interop 2023 right? I'd avoid adding those tests...

**Comment by foolip** [comment]
@emilio that's right, https://github.com/web-platform-tests/interop/issues/226 was not accepted for Interop 2023.

@mysteryDate are these tests entirely about relative colors, or is there something you want to test here that's independent of that?

**Comment by mysteryDate** [comment]
Yes! This is not only about relative colors, it is also about `color-mix`. 

https://wpt.fyi/results/css/css-color/parsing/gamut-mapping.html
https://wpt.fyi/results/css/css-color/parsing/color-computed-color-mix-function.html

Do not contain any relative colors. We should just include those.

**Comment by nairnandu** [comment]
> Yes! This is not only about relative colors, it is also about `color-mix`.
> 
> https://wpt.fyi/results/css/css-color/parsing/gamut-mapping.html https://wpt.fyi/results/css/css-color/parsing/color-computed-color-mix-function.html
> 
> Do not contain any relative colors. We should just include those.

@emilio could you please review for Gecko?
@nt1m could you please review for WebKit?

**Comment by emilio** [comment]
Those sound good.

**Comment by nt1m** [comment]
Seems ok to add

**Comment by svgeesus** [comment]
These changes reflect current CSSWG consensus and bring those WPT into line with the CSS Color 4 (for interpolation) and 5 (for color-mix) specifications

**Comment by mysteryDate** [comment]
With the latest addition, I believe this issue can be closed. Feel free to reopen if I am mistaken.
