### ISSUE TITLE
[motion-1] Add coord-box motion path tests

### ISSUE THREAD

**Issue by danielsakhapov** [web-platform-tests/interop#334]
### Test List

https://wpt.fyi/results/css/motion?label=master&label=experimental&aligned&q=offset-path-coord-box-001.html%20or%20offset-path-coord-box-002.html%20or%20offset-path-coord-box-003.html

### Rationale

Test offset-path: coord-box behaviour

**Comment by danielsakhapov** [comment]
@BorisChiou @nt1m

**Comment by BorisChiou** [comment]
I have been started to work on this and other basic shapes support. Thanks for adding these tests.

**Comment by nt1m** [comment]
@nmoucht What do you think?

**Comment by nmoucht** [comment]
> @nmoucht What do you think?

I would probably change offset-path-coord-box-001.html to result in a transform without decimal values (or at least add some pixel tolerance), as chrome also appears to be failing this test. Besides that these seem fine.

**Comment by foolip** [comment]
I've labeled the 3 tests in https://github.com/web-platform-tests/wpt-metadata/pull/4314.
