### ISSUE TITLE
[math functions] Change mod() math function subtest

### ISSUE THREAD

**Issue by danielsakhapov** [web-platform-tests/interop#335]
### Test List

https://wpt.fyi/css/css-values/round-mod-rem-computed.html

### Rationale

Change mod(-18px,100% / 15) to mod(-18px,100% / 10) and expected value from to 2px 4.5px. As Chrome doesn't pass due to some rounding of layout units. Probably Firefox would like to change mod(-18%,5%) also, as they fail for the same reason.

**Comment by foolip** [comment]
@danielsakhapov can you link to a draft CL / PR for this change?

**Comment by foolip** [comment]
Thanks @danielsakhapov! That's exported at https://github.com/web-platform-tests/wpt/pull/40008/files.

@jgraham can you handle this proposal for Gecko?
@gsnedders @nt1m can you handle this proposal for WebKit?

**Comment by nt1m** [comment]
This is fine (the math looks correct either way), but a bit surprising diving 75 / 10 produces rounding errors while 75 / 15 doesn't.

**Comment by foolip** [comment]
@dholbert @tiaanl are either of you able to review this for Gecko? (I pinged James and he suggested one of you might be the right contact.)

**Comment by dholbert** [comment]
Yeah, this seems fine to me. Change makes sense, and Firefox still passes the test after the change locally for me, so we're not e.g. trading between different implementation float rounding edge cases. :)

**Comment by dholbert** [comment]
> Probably Firefox would like to change mod(-18%,5%) also, as they fail for the same reason.

I noticed that one too, yeah.  It looks like our float-rounding error goes away if I change `-18%` to `-19%` there, and the expected-equivalent value to `1%`. And it looks like other browsers render those consistently, too, based on [this testcase](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cdiv%20style%3D%22width%3A75px%22%3E%0A%20%20%3Cdiv%20style%3D%22margin-left%3A%20mod(-19%25%2C5%25)%22%3ETest%3C%2Fdiv%3E%0A%20%20%3Cdiv%20style%3D%22margin-left%3A%201%25%22%3ERef%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A)

@danielsakhapov would you mind making that edit while you're here, for the same reason? i.e. changing line 131 from...
```
test_math_used('mod(-18%,5%)', '2%');
```
...to:
```
test_math_used('mod(-19%,5%)', '1%');
```

**Comment by danielsakhapov** [comment]
@dholbert Sure thing, done! Thanks everyone!
