### ISSUE TITLE
[math functions] Change incorrect tests

### ISSUE THREAD

**Issue by danielsakhapov** [web-platform-tests/interop#336]
### Test List

https://wpt.fyi/css/css-values/round-mod-rem-computed.html

### Rationale

Change calc(mod(1px + 0%, 1px + 0%)) and calc(rem(1px + 0%, 1px + 0%)) to calc(mod(3px + 0%, 2px + 0%)) to have an expected value to be 1px, as the current JS framework checks that the computed value is not a default one, which is 0px in this case. That's the reason for the test failure.

**Comment by foolip** [comment]
@danielsakhapov it sounds like you know exactly what the test edit should be. Can you link a CL / PR with the concrete changes?

**Comment by danielsakhapov** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/4532024

**Comment by foolip** [comment]
Thanks! https://github.com/web-platform-tests/wpt/pull/40010/files is a place to view the changes for someone more familiar with GitHub.

@jgraham can you handle this proposal for Gecko?
@gsnedders @nt1m can you handle this proposal for WebKit?

**Comment by nt1m** [comment]
This looks good to me.

**Comment by foolip** [comment]
Thanks @nt1m and @zcorpan! @danielsakhapov please consider this resolved and go ahead with the test changes.
