### ISSUE TITLE
[math functions] remove incorrect tests

### ISSUE THREAD

**Issue by danielsakhapov** [web-platform-tests/interop#337]
### Test List

https://wpt.fyi/results/css/css-values/exp-log-serialize.html and https://wpt.fyi/results/css/css-values/round-mod-rem-serialize.html

### Rationale

We can't expect -infinity and NaN as a computed value for opacity and transform, so I propose either to remove them or test only the specified value.

**Comment by foolip** [comment]
@danielsakhapov can these tests be updated in some way, or is there no pass condition that makes sense?

**Comment by danielsakhapov** [comment]
@foolip we can test only for the specified value and not the computed one.

**Comment by foolip** [comment]
Thanks @danielsakhapov!

@jgraham can you handle this proposal for Gecko?
@gsnedders @nt1m can you handle this proposal for WebKit?

**Comment by jgraham** [comment]
@emilio does removing the computed value tests seem reasonable here? Should we be testing some other behaviour instead?

**Comment by emilio** [comment]
We should probably test that those produce what the spec says, which IIRC is that `NaN` computes to `0`, and that `infinity` / `-infinity` compute to a very large (or small, respectively) but finite number.

cc @canadahonk

**Comment by danielsakhapov** [comment]
@emilio Please have a look at my change https://github.com/web-platform-tests/wpt/pull/40567
