### ISSUE TITLE
Permissions-Policy web-share=self

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/interop#34]
**Description**

**Bug reports**
https://bugs.chromium.org/p/chromium/issues/detail?id=1196138
https://bugs.webkit.org/show_bug.cgi?id=214448
https://bugzilla.mozilla.org/show_bug.cgi?id=1701841
https://bugzilla.mozilla.org/show_bug.cgi?id=1737541

**Specification**
https://w3c.github.io/web-share/#permissions-policy

**Tests**
https://wpt.fyi/results/web-share?label=master&label=experimental&aligned&q=web-share (not sure if this is covered)

This is a bug to include in #9

**Comment by gsnedders** [comment]
Did we ever end up with any tests covering this?

**Comment by karlcow** [comment]
> Did we ever end up with any tests covering this?

Maybe @marcoscaceres knows.

**Comment by marcoscaceres** [comment]
Yes. 
https://github.com/web-platform-tests/wpt/blob/master/web-share/disabled-by-permissions-policy.https.sub.html

However, YouTube might still be a blocker.

**Comment by marcoscaceres** [comment]
Actually, we need a test for `allow="web-share"` to test cross origin in WPT. We only have the HTTP test above.

**Comment by marcoscaceres** [comment]
I put together some tests:
https://github.com/web-platform-tests/wpt/pull/36495

@karlcow, any chance you could spare some cycles and check the state of YouTube again? At TPAC, folks from Google said that they had at least added a try/catch, but apparently it's still failing in Firefox (Windows Desktop). Not sure if you have access to a Windows box, but maybe you can check?

**Comment by marcoscaceres** [comment]
I'm reopening while we discuss...

**Comment by karlcow** [comment]
> I put together some tests: [web-platform-tests/wpt#36495](https://github.com/web-platform-tests/wpt/pull/36495)
> 
> @karlcow, any chance you could spare some cycles and check the state of YouTube again? At TPAC, folks from Google said that they (YouTube) had at least added a try/catch around the offending code, but apparently it's still failing in Firefox (Windows Desktop). 

I can check.

> Not sure if you have access to a Windows box, but maybe you can check?

Nope.

**Comment by karlcow** [comment]
YouTube doesn't offer the fancy sharing.

![Screenshot 2022-10-18 at 12 01 09](https://user-images.githubusercontent.com/505230/196326272-3ae789b2-54ea-40e4-bd14-2c0b6d3b3bf3.png)
![Screenshot 2022-10-18 at 12 02 09](https://user-images.githubusercontent.com/505230/196326282-40eb6665-e1d5-4d3d-ae7d-f5e4cba53700.png)

While twitter does.

![Untitled](https://user-images.githubusercontent.com/505230/196327792-14df4e80-25f8-4535-987a-4a352664c47b.png)

**Comment by marcoscaceres** [comment]
Sorry, I don't think I was very clear. The blockers here are:

 * Chrome: doesn't implement the policy. @foolip, can you enquire if/when the policy will be implemented?
 * Firefox:  YouTube's code didn't handle Firefox well last we checked. @jgraham or @saschanaz, can you please check in Firefox for Windows? Is YouTube's share button working as expected?
 * Safari/WebKit: Currently implements "*". I can switch it over if we get agreement from Chrome to implement (Firefox was already doing the "right thing" per spec).

Let me and @karlcow and I can patch WebKit.

**Comment by gsnedders** [comment]
> * Safari/WebKit: Currently implements "*" as the policy. I can switch it over to 'self' if we get agreement from Chrome to implement (Firefox was already doing the "right thing" per spec).

And for those confused, https://bugs.webkit.org/show_bug.cgi?id=241363 changed the policy from `self` to `*` due to various bits of site breakage.

**Comment by miketaylr** [comment]
😞 I will ping the internal bugs again, and send some emails.

**Comment by mgiuca** [comment]
Thanks @saschanaz for spelling out the error you get in Firefox. I have mentioned this comment to the YouTube team internally.

> I do see YT did something to improve if navigator.share fails, but it still ultimately throws an error with the share button

I worked with YT a few months back to add code to catch the `NotAllowedError` and fall back to the HTML share sheet (this means that any embed without `allow=web-share` — i.e. basically all of them at the moment as it is not part of the boilerplate — would fall back gracefully to the HTML share sheet instead of doing nothing). However it seems that that fix, at least in Firefox, was buggy.

@marcoscaceres have you tested it in Safari since August? Trying to figure out if this is only a problem in Firefox or if it affects other browsers too.

**Comment by marcoscaceres** [comment]
@mgiuca, yes, Karl tested Safari a few days ago: https://github.com/web-platform-tests/interop/issues/34#issuecomment-1281760377 (it goes to the fallback code, which is ok)

**Comment by saschanaz** [comment]
> @mgiuca, yes, Karl tested Safari a few days ago: https://github.com/web-platform-tests/interop/issues/34#issuecomment-1281760377 (it goes to the fallback code, which is ok)
> 

Please retry with some embedded YT since the full YT does not use Web Share.

**Comment by mgiuca** [comment]
The full YT does also use Web Share (under "Apps"), but it's totally different code. The broken code in question is YT embeds.

**Comment by saschanaz** [comment]
> The full YT does also use Web Share (under "Apps"), but it's totally different code. The broken code in question is YT embeds.

Interesting, I don't immediately see any button labeled Apps, could you give me a screenshot?

**Comment by inexorabletash** [comment]
FYI that we're still pushing on this, but if there are YT changes required they're unlikely to happen before the start of 2023.

**Comment by marcoscaceres** [comment]
@inexorabletash, that's ok. 

The larger question is around coordinating across UAs on switching the permissions policy itself. We basically all need to ship that across UAs around the same time (at least, in the case of Safari and Chrome, as Firefox already uses `self`).

**Comment by ewilligers** [comment]
We are preparing to ship the permission policy with `self` in Chrome 110. Stable in Feb '23.

**Comment by marcoscaceres** [comment]
Ok, that's great news @ewilligers! I'll patch WebKit now... thanks also for merging that WPT test.

**Comment by foolip** [comment]
This is an Interop 2022 proposal, closing.
