### ISSUE TITLE
[motion-1] Fix offset-path parsing test

### ISSUE THREAD

**Issue by danielsakhapov** [web-platform-tests/interop#340]
### Test List

https://wpt.fyi/results/css/motion/parsing/offset-path-parsing-valid.html

### Rationale

Update tests to be up-to-date with the spec
https://github.com/web-platform-tests/wpt/pull/40120

**Comment by danielsakhapov** [comment]
@BorisChiou @nmoucht

**Comment by BorisChiou** [comment]
Thanks. The parsing test and computed value test are out-of-date of course. I'm also trying to add more tests for shapes/coord-box in parsing-valid and computed tests.

**Comment by nt1m** [comment]
The margin-box one looks OK. I'm not sure about the omitting the position part. @Emilio @Loirooriol, should we always serialize the position here?

**Comment by BorisChiou** [comment]
About the serialization, the current spec requires us to serialize `<position>` always, https://drafts.csswg.org/css-shapes-1/#basic-shape-serialization. However, there is a spec issue talking about this: https://github.com/w3c/csswg-drafts/issues/8695.

**Comment by Loirooriol** [comment]
https://drafts.csswg.org/css-shapes-1/#funcdef-basic-shape-ellipse

> The position argument defines the center of the ellipse. This defaults to center if omitted.

https://drafts.csswg.org/css-backgrounds-3/#valdef-background-position-center

> `center`: Computes to `50%`

https://drafts.csswg.org/cssom/#serializing-css-values

> If component values can be omitted or replaced with a shorter representation without changing the meaning of the value, omit/replace them.

So it seems to me that `ellipse(50% 60%)` should NOT serialize as `ellipse(50% 60% at 50% 50%)`.
In fact, `ellipse(50% 60% at 50% 50%)` should serialize as `ellipse(50% 60%)`.

Same for the `circle(100px)` above.

**Comment by emilio** [comment]
Agreed with @Loirooriol, that test fix is wrong.

**Comment by emilio** [comment]
(in principle, at least).

The spec says:

> omitting components when possible without changing the meaning

Which seems true in this case. But then in the non-normative example it says:

> Omitting components means that some default values do not show up in the serialization. But since [<position>](https://drafts.csswg.org/css-values-4/#typedef-position) always uses the 2- or 4-value form, a default <position> is not omitted.

I don't quite understand why we shouldn't omit it, but I'm really jet-lagged so maybe I'm not parsing that right.

**Comment by BorisChiou** [comment]
BTW, [the spec](https://drafts.fxtf.org/motion-1/#valdef-offset-path-basic-shape) of `offset-path` says:
> If [circle()](https://drafts.csswg.org/css-shapes-1/#funcdef-basic-shape-circle) or [ellipse()](https://drafts.csswg.org/css-shapes-1/#funcdef-basic-shape-ellipse) is used, and an explicit center position is not given, they default to using the [offset starting position](https://drafts.fxtf.org/motion-1/#offset-starting-position), rather than their standard default.

So now I feel weird if we serialize it as `50% 50%` if the user doesn't give the center position. We do not use `50% 50%` as default value for `offset-path`. Serializing it as `50% 50%` may mislead people.

**Comment by BorisChiou** [comment]
cc @tabatkins

**Comment by BorisChiou** [comment]
I filed a spec for this: https://github.com/w3c/fxtf-drafts/issues/514.

**Comment by BorisChiou** [comment]
OK, the comment in https://github.com/w3c/csswg-drafts/issues/8695#issuecomment-1563497665 makes sense to me. We should omit `at <position>` if it was not given. And _preserve_ the `at <position>` even if it specifies the default value, for the same reason.

**Comment by danielsakhapov** [comment]
@BorisChiou @nt1m updated the test, please, have a look

**Comment by danielsakhapov** [comment]
done

**Comment by nt1m** [comment]
The test looks good to me now.
