### ISSUE TITLE
Add new image-set tests

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#341]
### Test List

https://github.com/web-platform-tests/wpt/pull/40129

css/css-images/image-set/image-set-negative-resolution-rendering-3.html
css/css-images/image-set/image-set-zero-resolution-rendering-2.html
css/css-images/image-set/image-set-zero-resolution-rendering.html

css/css-images/image-set/image-set-calc-x-rendering.html
css/css-images/image-set/image-set-calc-x-rendering-2.html

### Rationale

Shows some interop issues in image-set

**Comment by nt1m** [comment]
Here's a link: https://wpt.fyi/results/css/css-images/image-set?label=master&label=experimental&aligned&q=not%20label%3Ainterop-2023-webcompat

**Comment by nt1m** [comment]
@Emilio @foolip What do you think?

**Comment by tcaptan-cr** [comment]
Including these tests in Interop 2023 sounds good to me.

**Comment by foolip** [comment]
Thanks @tcaptan-cr! Ping @emilio @zcorpan for Gecko.

**Comment by emilio** [comment]
Sounds good to me as well, thanks.

**Comment by nt1m** [comment]
https://github.com/web-platform-tests/wpt-metadata/pull/4280
