### ISSUE TITLE
Remove tests related to commit in Offscreencanvas

### ISSUE THREAD

**Issue by yiyix** [web-platform-tests/interop#344]
### Test List

[offscreencanvas.commit.html ](https://wpt.fyi/results/html/canvas/offscreen/manual/the-offscreen-canvas/offscreencanvas.commit.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-offscreencanvas%20chrome%3A%21ok%20chrome%3A%21pass)

### Rationale

Commit is no longer supported in Canvas. That's why all three browsers have it failed. I propose to remove this test as well.

**Comment by nt1m** [comment]
Should we just remove it from WPT altogether?

**Comment by foolip** [comment]
That seems best. Everyone already fails the test so there's no reason to even add an historical test asserting that `commit()` isn't supported.

**Comment by zcorpan** [comment]
SGTM
