### ISSUE TITLE
Unreviewed scope increase: <input pattern> supporting RegExp v

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/interop#345]
### Test List

https://wpt.fyi/results/html/semantics/forms/the-input-element/pattern_attribute.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2022-forms%20or%20label%3Ainterop-2023-forms

### Rationale

RegExp v flag wasn't in scope for Interop 2023. The new subtests for https://github.com/whatwg/html/pull/7908 added in https://github.com/web-platform-tests/wpt/pull/38547 currently fail in Firefox and Safari.

- `<input pattern> supports set difference syntax`
- `<input pattern> supports string literal syntax`
- `<input pattern> enables the RegExp v flag`

We could either remove this test file from Interop (since no other subtests fail), or split into two files, or mark the new tests with `assert_implements_optional` (maybe feature-checking support for the `v` flag on RegExp).

**Comment by foolip** [comment]
cc @mathiasbynens. If it's easy to split these tests out, that would be the most expedient I think.

**Comment by zcorpan** [comment]
PR https://github.com/web-platform-tests/wpt/pull/40343

**Comment by zcorpan** [comment]
@annevk wrote

> I somewhat prefer excluding this instead, but I don't care too strongly.

Either way is ok for me. @foolip what say you?

**Comment by zcorpan** [comment]
@gsnedders @nt1m fyi

**Comment by nt1m** [comment]
Seems fine to me either way, no strong opinion.
