### ISSUE TITLE
Fix canvas tests with broken promise rejection chaining

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#348]
### Test List

https://github.com/web-platform-tests/wpt/pull/40248 shows the intended changes. 4 tests are affected in Chrome/Firefox, and 58 in Safari:
https://wpt.fyi/results/html/canvas/offscreen/fill-and-stroke-styles?diff&filter=ADC&q=is%3Adifferent&run_id=4828703681413120&run_id=5178412581257216
https://wpt.fyi/results/html/canvas/offscreen/fill-and-stroke-styles?diff&filter=ADC&q=is%3Adifferent&run_id=6316612234248192&run_id=5158270023499776
https://wpt.fyi/results/html/canvas/offscreen?diff&filter=ADC&q=is%3Adifferent&run_id=5105157619056640&run_id=5126268826157056

### Rationale

These tests did not wait for the important part of the tests to run, but could instead pass early without running any assertions. The first diff in https://github.com/web-platform-tests/wpt/pull/40248/files illustrates the pattern:

```diff
   promise.then(function(response) {
-      createImageBitmap(response).then(bitmap => {
+      return createImageBitmap(response).then(bitmap => {
           ctx2.drawImage(bitmap, 0, 0);
           ctx.fillStyle = 'rgba(0, 255, 255, 0.5)';
           ctx.fillRect(0, 0, 100, 50);
           ctx.globalCompositeOperation = 'clear';
           ctx.drawImage(offscreenCanvas2, 0, 0);
           _assertPixelApprox(canvas, 50,25, 0,0,0,0, 5);
-      }, t_fail);
+      });
   }).then(t_pass, t_fail);
```

The test needs to wait for `createImageBitmap()` to finish and then actually run the assertions.

These are test bugs, but I'm filing this issue because I cannot be certain that all of the tests that will go from passing to failing in Safari should really fail. There could be additional test bugs that cause those failures, and I'd like review from the WebKit team in particular before making the change.

**Comment by foolip** [comment]
@annevk @gsnedders @nt1m can you review this for WebKit?

@jgraham @zcorpan can you review this for Gecko?

**Comment by zcorpan** [comment]
The fix LGTM

**Comment by foolip** [comment]
I'll take @annevk's review of https://github.com/web-platform-tests/wpt/pull/40248 as an OK from WebKit, closing this and proceeding.
