### ISSUE TITLE
Setting a time limit for Test Change Proposal feedback

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#354]
We currently require explicit sign-off from a representative for each of Chromium, Gecko and WebKit to accept test change proposals.

This requires pinging people on GitHub and often we use interop team meeting time for this as well, but usually just for what amounts to a ping, rarely discussion.

Using https://github.com/web-platform-tests/interop/issues/327 as an example, it took a month to resolve.

Since the vast majority of changes are not controversial, I would like to suggest a change to the process to not require explicit sign-off. Taking inspiration from https://github.com/web-platform-tests/rfcs, I would suggest adding this to our README:

> In the case of no substantive disagreement the test change proposal is considered accepted after 1 week.

**Comment by nt1m** [comment]
I disagree with this suggestion, I usually try to answer test change proposals ASAP (in fact most of them take under a week), but sometimes I prefer having an expert review the tests. In the case of #327, our Motion Path expert was out, hence the long reply time, but this is usually the exception.

**Comment by jgraham** [comment]
Yeah I agree with @nt1m. Changing the tests that form the metric is a non-trivial action, and it's important that people don't feel like this is happening without their explicit consent.

**Comment by foolip** [comment]
In that case, is there something else we can do to resolve test change proposals faster? One month is an outlier, but my hunch is that two weeks is pretty typical.
