### ISSUE TITLE
Unreviewed change in scope: customElements.getName()

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#358]
### Test List

https://github.com/web-platform-tests/wpt/commit/a6441061e9932fccca47b61093d4124ab5891939

**Comment by nairnandu** [comment]
@mfreed7 could you review for Chromium?
@jgraham / @zcorpan could you review for Gecko?

**Comment by xiaochengh** [comment]
Hmm, didn't realize it would go into interop 2023.

Since the test change is for a proposed spec change (https://github.com/whatwg/html/pull/9195), I think we should move these new tests into a separate .tentative test file.

**Comment by mfreed7** [comment]
> Hmm, didn't realize it would go into interop 2023.

+1 I missed that these were missing the `.tentative` suffix. Xiaocheng has a patch up to revert the test changes here.
