### ISSUE TITLE
Change WPTs svg-scale-013.html and -014.html to avoid fractional and imprecise positions and sizes

### ISSUE THREAD

**Issue by dholbert** [web-platform-tests/interop#359]
### Test List

https://wpt.fyi/results/css/css-transforms/scale/svg-scale-013.html
https://wpt.fyi/results/css/css-transforms/scale/svg-scale-014.html

### Rationale

These tests each have have:
* a rect of fractional size and position (x or y and width or height are `+/-133.333px`)
* ...which get scaled by 1.5px.
* ...and then the test has precise expectations about the position and size of the rect (the test wants it to precisely cover up a 200px by 200px red square).

There are issues with this:
(1) If browsers use pixel-snapping to handle the (pre-transform) fractional position or size, then the scaled-up rect will end up being off from the expected position by a very small (subpixel) amount, which results in an antialiased seam where some red shows through.
(2) The test's expectations aren't quite valid -- `133.333 * 1.5` is not quite 200px -- it's `199.9995`.  So a very small seam is actually appropriate, given sufficient levels of precision/fidelity.

Firefox fails this test right now, I believe due to issue (1) above. (Issue (2) is more theoretical/belt-and-suspenders type concern.)

We can trivially fix this by changing `133.333px` to `160px` and `1.5` to `1.25` throughout these tests.  (`160 * 1.25` is precisely 200, and doesn't trigger any fuzzy rounding or snapping behavior.)

I propose we make that change to these tests.

**Comment by dholbert** [comment]
I've got a patch to fix the test as-proposed, over in https://phabricator.services.mozilla.com/D180749

**Comment by dholbert** [comment]
Also: as far as I can tell (visually), the amended tests still pass (no noticeable change) in other browsers.

**Comment by nt1m** [comment]
Seems fine.

**Comment by dholbert** [comment]
Thanks, @nt1m!

@davidsgrogan maybe you could rubberstamp from Chrome side?  (tl;dr: just changing some values in two WPTs to avoid using explicit fractional pixel values, to avoid a fuzzy-failure due to resulting pixel-snapping implementation details)

**Comment by davidsgrogan** [comment]
The proposed change seems good.

**Comment by foolip** [comment]
There's enough support for this proposal now, @dholbert feel free to make the changes.

**Comment by dholbert** [comment]
Done, thanks! Landed via https://github.com/web-platform-tests/wpt/pull/40561
