### ISSUE TITLE
Remove test for 'border-image-source' interpolation

### ISSUE THREAD

**Issue by fsoder** [web-platform-tests/interop#360]
### Test List

https://wpt.fyi/results/css/css-backgrounds/animations/border-image-source-interpolation.html

### Rationale

The 'border-image-source' property accepts a syntax `none | <image>`. The ability to interpolate `<image>`s is not defined in L3 of CSS Images [1] (as referenced by CSS Backgrounds L3), while it is in L4 [2] (referenced by CSS Backgrounds L4). Some UAs have (at least to a degree) implemented the L4 behavior, while others have not. The listed test is currently written against the CSS Backgrounds L3 (and thus the CSS Images L3) behavior. Having UAs with the L4 behavior roll back to the L3 behavior seems counterproductive on the whole (and could potentially affect real content - per use counters [3]). Given the limited syntax it seems like the best course of action for Interop 2023 would be to remove the test from the set. If there are cases that show interop bugs that would be good to address - that does not fall under the issue described above - then perhaps more focused tests for those cases could be added instead (not of aware of any such issues though).

[1] https://drafts.csswg.org/css-images-3/#interpolation
[2] https://drafts.csswg.org/css-images-4/#interpolation
[3] https://chromestatus.com/metrics/css/timeline/animated/47

**Comment by nairnandu** [comment]
Had a quick chat with @progers on this and we have an lgtm for Chromium.

@jgraham @zcorpan could you take a look at this for Gecko?

@gsnedders @nt1m could you take a look at this for WebKit?

**Comment by nt1m** [comment]
Seems fine to me

**Comment by dholbert** [comment]
Seems fine to me, for Gecko.
