### ISSUE TITLE
Remove the html/canvas/offscreen/text/2d.text.measure.advances.* tests

### ISSUE THREAD

**Issue by jfkthame** [web-platform-tests/interop#365]
### Test List

[html/canvas/offscreen/text/2d.text.measure.advances.html
html/canvas/offscreen/text/2d.text.measure.advances.worker.html
](https://wpt.fyi/results/html/canvas/offscreen/text?label=master&label=experimental&aligned&q=html%2Fcanvas%2Foffscreen%2Ftext%2F2d.text.measure.advances)

### Rationale

The [HTML spec](https://html.spec.whatwg.org/multipage/canvas.html#textmetrics) for the `TextMetrics` interface does not define an `advances` attribute at all.

**Comment by nt1m** [comment]
If it's not in the spec, we should consider renaming the test to .tentative as well (or potentially remove).

**Comment by nt1m** [comment]
Removing from Interop seems fine to me otherwise

**Comment by nairnandu** [comment]
@fserb / @yiyix could you please review this proposal for Chromium?

**Comment by fserb** [comment]
lgtm

**Comment by jfkthame** [comment]
This was resolved by https://github.com/web-platform-tests/wpt-metadata/pull/4509.
