### ISSUE TITLE
Remove offset-path-interpolation-005.html subtest that expects unspecified <position> to behave like 50% 50% for css transition interpolation

### ISSUE THREAD

**Issue by dholbert** [web-platform-tests/interop#367]
### Test List

https://wpt.fyi/results/css/motion/animation/offset-path-interpolation-005.html

Specifically, this subset that was added 3 weeks ago:
https://github.com/web-platform-tests/wpt/commit/983934daa4efaf60450ff630d791498715d9f812#diff-1276dceb6b17a9318f4085605d5c0b5a60b9cee16b1867faa5d54821d1a97a58R126-R137

### Rationale

This test expects that interpolation between these values is possible:
```
ray(-10deg farthest-corner)
ray(-50deg farthest-corner at 100% 100%)
```
...and the test expects interpolation to proceed as if the first value had `...at 50% 50%` as its `<position>`.

However, that expectation is not correct.  The spec says unspecified `<position>` is special:
https://drafts.fxtf.org/motion-1/#valdef-ray-at-position
> If omitted, it uses the [offset starting position](https://drafts.fxtf.org/motion-1/#offset-starting-position) of the element, given by [offset-position](https://drafts.fxtf.org/motion-1/#propdef-offset-position).

And "offset-position" links to this text:
> Specifies the offset starting position that is used by the [<offset-path>](https://drafts.fxtf.org/motion-1/#typedef-offset-path) functions if they don’t specify their own starting position.
> [...]
> normal:    The element does not have an [offset starting position](https://drafts.fxtf.org/motion-1/#offset-starting-position).
> auto:     The [offset starting position](https://drafts.fxtf.org/motion-1/#offset-starting-position) is the top-left corner of the box.

`auto` is the default.

So: whether or not these values are interpolatable, the test's expectation about using "50% 50%" seems definitely not correct.  So, I think we should remove this subtest from the test.

**Comment by dholbert** [comment]
CC @BorisChiou who's working on this feature in Gecko.

CC @danielsakhapov who authored these test-changes; hoping you can confirm my understanding.

**Comment by dholbert** [comment]
To make this more concrete, here's the specific subtest that was just [recently added](https://github.com/web-platform-tests/wpt/commit/983934daa4efaf60450ff630d791498715d9f812#diff-1276dceb6b17a9318f4085605d5c0b5a60b9cee16b1867faa5d54821d1a97a58R126-R137) that I'm proposing we remove:
```JavaScript
      test_interpolation({
        property: 'offset-path',
        from: 'ray(-10deg farthest-corner)',
        to: 'ray(-50deg farthest-corner at 100% 100%)'
      }, [
        {at: -1, expect: 'ray(30deg farthest-corner at 0% 0%)'},
        {at: 0, expect: 'ray(-10deg farthest-corner)'},
        {at: 0.125, expect: 'ray(-15deg farthest-corner at 56.25% 56.25%)'},
        {at: 0.875, expect: 'ray(-45deg farthest-corner at 93.75% 93.75%)'},
        {at: 1, expect: 'ray(-50deg farthest-corner at 100% 100%)'},
        {at: 2, expect: 'ray(-90deg farthest-corner at 150% 150%)'},
      ]);
```

You can tell that the test is (incorrectly) expecting the browser to treat the `from` value's unspecified `<position>` as if it were `50% 50%`, by `<position>` values in the test's expected intermediate values.  (The `56.25%` value at `t=0.125` is exactly 0.125 of the way between 50% and 100%, and similar for the `93.75%` expected position at `t=0.875`.)

(Side note: I don't think there was a test-change-proposal filed here for that commit when it landed -- ideally it would've been good if we'd had one of those, since the changes were effectively expanding the scope of the interop-2023 testsuite, and it was introducing new test-failures in Firefox and Safari.  Though as it turns out the test failures are due to a bug in the test as described here, I think.)

**Comment by nt1m** [comment]
I trust @dholbert's judgment :)

**Comment by danielsakhapov** [comment]
I feel like the spec should mention explicitly what to do with this case. I agree to remove the test.

**Comment by dholbert** [comment]
Thanks! I'll go ahead and submit a PR to remove it then.

**Comment by dholbert** [comment]
PR https://github.com/web-platform-tests/wpt/pull/40775 posted to address this. (That PR preserves the "at: 1" portion of the subtest, since that's unambiguous, and removes the rest of the expectations which depend on particular interpolation behavior.)

**Comment by nairnandu** [comment]
@dholbert closing this issue as the changes have been merged.

**Comment by dholbert** [comment]
Thanks!
