### ISSUE TITLE
Add testcases for that `<span contenteditable>` is followed by `<div>`

### ISSUE THREAD

**Issue by masayuki-nakano** [web-platform-tests/interop#368]
### Test List

https://wpt.fyi/results/?label=master&label=experimental&aligned&q=%2Fediting%2Fother%2Finsertparagraph-in-inline-editing-host.tentative.html

### Rationale

I forgot to put the testcases into the test. If `insertParagraph` at `<span contenteditable>foo[]</span><div>bar</div>` occurs, `<span contenteditable>foo<br></span><div>bar</div>` is not enough to make the new empty line visible. The builtin editors need to make it `<span contenteditable>foo<br><br></span><div>bar</div>`.

* https://github.com/web-platform-tests/wpt/blob/87005245a34519740e07e17b2b9f18e28563d9da/editing/other/insertparagraph-in-inline-editing-host.tentative.html#L127-L168
* https://github.com/web-platform-tests/wpt/blob/87005245a34519740e07e17b2b9f18e28563d9da/editing/other/insertparagraph-in-inline-editing-host.tentative.html#L329-L370

I think we should duplicate those tests and replace the outer `<br>` element with `<div>efg</div>`.

**Comment by nt1m** [comment]
@masayuki-nakano Could you put up a PR of what the test changes would look like?

**Comment by masayuki-nakano** [comment]
(Sorry for the delay to reply, I was on a short vacation, I'll post it in this week.)

**Comment by nt1m** [comment]
Seems ok to me

**Comment by nairnandu** [comment]
@jgraham / @zcorpan could you review the proposed change for Gecko?
@kojiishi could you review the proposed change for Chromium?

**Comment by jgraham** [comment]
@masayuki-nakano is working on Gecko, so I think we need Chromium input on this one.

**Comment by chrishtr** [comment]
Approved from Chromium.

**Comment by nt1m** [comment]
@masayuki-nakano Please feel free to merge the PR and close this issue fwiw.

**Comment by masayuki-nakano** [comment]
@nt1m Nobody has reviewed my patch so that I cannot merge the PR.

**Comment by nt1m** [comment]
@makotokato / @rniwa Can you help take a look at this PR: https://github.com/web-platform-tests/wpt/pull/41036 ?

**Comment by nairnandu** [comment]
@kojiishi / @makotokato / @rniwa could you help review the PR: https://github.com/web-platform-tests/wpt/pull/41036 ?
