### ISSUE TITLE
Exclude test for unspecified `<input pattern>` backtracking limit

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/interop#371]
### Test List

https://wpt.fyi/results/html/semantics/forms/constraints/infinite_backtracking.html

### Rationale

This was implemented in WebKit/Blink but not specified (yet). See https://bugs.chromium.org/p/chromium/issues/detail?id=966405

**Comment by vinhill** [comment]
See https://github.com/whatwg/html/issues/9469 for including this in the specification.

**Comment by nt1m** [comment]
Seems ok to remove.

**Comment by nairnandu** [comment]
@dizhang168 or @josepharhar could you review for Chromium

**Comment by zcorpan** [comment]
https://github.com/web-platform-tests/wpt-metadata/pull/4506
