### ISSUE TITLE
Remove html/semantics/interactive-elements/the-dialog-element/simulated-click-inert.html

### ISSUE THREAD

**Issue by emilio** [web-platform-tests/interop#373]
This fails in Firefox, but it's just testing that a synthetic click triggered by the WPT harness hits the element.

The expectation is rather dubious to begin with (why would you be able to hit it if the user wouldn't be able to?) but in any case there's nothing web-facing, and thus probably shouldn't be in interop?

**Comment by nt1m** [comment]
This was part of Interop 2022 (and isn't part of 2023) fwiw.

@emilio Looking at the test, it seems like the expectation is that a `<label>` that is associated to a checkbox changes the checkbox state when clicked. Sounds like a correct expectation with the current inert spec unless I'm misreading? I'm open to changing the spec if that's what you're suggesting though.

In any case, there is a behavior difference here, if you open the test in Firefox, and hit "CLICK ME": http://wpt.live/html/semantics/interactive-elements/the-dialog-element/simulated-click-inert.html

Firefox doesn't toggle the checkbox, whereas Safari & Chrome do.

**Comment by emilio** [comment]
ah! I misread the "simulated" part of the test title then. You're right!
