### ISSUE TITLE
`pointerevent_pointercapture_in_frame.html` listens to `lostpointercapture` at too late timing

### ISSUE THREAD

**Issue by masayuki-nakano** [web-platform-tests/interop#374]
### Test List

https://wpt.fyi/results/pointerevents/pointerevent_pointercapture_in_frame.html%3Fmouse?label=master&label=experimental&aligned

### Rationale

irst, [the test listens to `pointerup` event in the outer `<div>` of the `<iframe>`](https://searchfox.org/mozilla-central/rev/7907fd85f6fd1cee3acaddbaf27a76b23d6d9993/testing/web-platform/tests/pointerevents/pointerevent_pointercapture_in_frame.html#145). Then, [it starts to listen to `lostpointercapture` event in the outer `<div>`](https://searchfox.org/mozilla-central/rev/7907fd85f6fd1cee3acaddbaf27a76b23d6d9993/testing/web-platform/tests/pointerevents/pointerevent_pointercapture_in_frame.html#146-147) **after** a tick because of after [the `Promise`](https://searchfox.org/mozilla-central/rev/7907fd85f6fd1cee3acaddbaf27a76b23d6d9993/testing/web-platform/tests/resources/testharness.js#976) is resolved. This means that the test assumes that `pointerup` and `lostpointercapture` events are fired in different event loop ticks.

However, according to <https://github.com/w3c/pointerevents/issues/357#issuecomment-1601040840> and [the spec](https://w3c.github.io/pointerevents/#event-dispatch), `lostpointercapture` should be dispatched as a default action of `pointerup` within same event loop. Therefore, the test has a bug and that causes [Firefox fails](https://wpt.fyi/results/pointerevents/pointerevent_pointercapture_in_frame.html%3Fmouse?q=pointerevent_pointercapture_in_frame&run_id=5168876453625856&run_id=5141516572426240&run_id=5199990874439680&run_id=5150569356853248).

**Comment by nt1m** [comment]
@masayuki-nakano Do you have a PR? seems reasonable in principle, but would be good to see the code change.

**Comment by nt1m** [comment]
Looks ok

**Comment by masayuki-nakano** [comment]
No problem, thank you!
