### ISSUE TITLE
Add clamp() function tests

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#376]
### Test List

https://wpt.fyi/results/css/css-values?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=clamp-length

### Rationale

There seems to be differences in serialization across browsers.

Not sure why this test wasn't included in the first place. Fwiw, some tests for clamp() somehow ended up in this Interop 2023 test: https://wpt.fyi/results/css/css-values/signs-abs-computed.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-mathfunctions (which I'll move over)

**Comment by nt1m** [comment]
@emilio @tiaanl Can you help review for Gecko?

@xiaochengh / @nairnandu Can you help review for Chromium?

**Comment by emilio** [comment]
Looks fine to add to me.

**Comment by xiaochengh** [comment]
LGTM
