### ISSUE TITLE
Improve skew-test1.html to be more probably sound and to not require fuzz

### ISSUE THREAD

**Issue by dholbert** [web-platform-tests/interop#378]
### Test List

https://wpt.fyi/results/css/css-transforms/skew-test1.html

### Rationale

The test visually passes in all browsers, but it doesn't seem quite sound.

In particular:
- it requires an extreme amount of annotated fuzz in at least WebKit and Gecko.  For WebKit, it's currently annotated to allow `maxDifference=17-233;totalPixels=90-858`.   That means it could misrender with 850 ~arbitrarily-colored pixels anywhere and still pass. Firefox [requires a very-slightly-more-permissive annotation than what the test currently has baked in](https://searchfox.org/mozilla-central/rev/ada05ac4faf1f79944a35a9eb79083a684a98975/testing/web-platform/meta/css/css-transforms/skew-test1.html.ini#3), which is why wpt.fyi currently shows us failing.  (We could just increase the annotation, but it's already kind of past the point of reasonable fuzzy tolerance, which prompted [some legitimate review pushback](https://phabricator.services.mozilla.com/D182605#6035532) when I wrote a patch to do that.)  Also, notably, the test doesn't currently expect to exactly match in any rendering engine, since `0` isn't included in either of the fuzzy ranges.
- The [vertex positions in the reference case](https://github.com/web-platform-tests/wpt/blob/a5b79c3469f743ce880bde06071dc82ac57fe3b5/css/css-transforms/reference/skew-test1-ref.html#L30) are arbitrary-looking (e.g. `54.595535`) and are hard to manually verify & reason-about, when investigating a test-failure.  It's not clear to-what-extent these particular numeric values are technically correct, vs. were just extracted to be good-enough for one particular browser's rendering at some point in the past.

I'm proposing to replace the test with a new version that addresses these issues in two ways, making the test much more robust while still testing the same thing (a div with two different angles in its `skew()` expression):
(1) To address the arbitrary-looking/hard-to-validate numeric values issue, for the "reference" shapes: let's use multiples of `45deg` as the angles in the `skew()` expression. `skew(45deg,45deg)` has a nice property that it produces a diamond whose bounding box is 2x the width and height of the original rect, which is a rendering that we can easily mock up with an SVG polygon using whole-numbered pixel values.
(2) To address other sources of fuzz (from e.g. different pixel-snapping or antialiasing behavior along diagonal lines between SVG vs. transformed divs): we can make the reference shapes be SVG polygons that are *slightly* larger/smaller than the transformed div, and validate that one element fully covers the other.

I've got a version of the test locally that passes (in Firefox) with no fuzz required, which is fixed up along these lines.

**Comment by dholbert** [comment]
> ### Test List
> 
> https://wpt.fyi/results/css/css-transforms/skew-test1.html
> ### Rationale
> 
> The test visually passes in all browsers, but it doesn't seem quite sound.
> 
> In particular:
> 
>     * it requires an extreme amount of annotated fuzz in at least WebKit and Gecko.  For WebKit, it's currently annotated to allow `maxDifference=17-233;totalPixels=90-858`.   That means it could misrender with 850 ~arbitrarily-colored pixels anywhere and still pass. Firefox [requires a very-slightly-more-permissive annotation than what the test currently has baked in](https://searchfox.org/mozilla-central/rev/ada05ac4faf1f79944a35a9eb79083a684a98975/testing/web-platform/meta/css/css-transforms/skew-test1.html.ini#3), which is why wpt.fyi currently shows us failing.  (We could just increase the annotation, but it's already kind of past the point of reasonable fuzzy tolerance, which prompted [some legitimate review pushback](https://phabricator.services.mozilla.com/D182605#6035532) when I wrote a patch to do that.)  Also, notably, the test doesn't currently expect to exactly match in any rendering engine, since `0` isn't included in either of the fuzzy ranges.
> 
>     * The [vertex positions in the reference case](https://github.com/web-platform-tests/wpt/blob/a5b79c3469f743ce880bde06071dc82ac57fe3b5/css/css-transforms/reference/skew-test1-ref.html#L30) are arbitrary-looking (e.g. `54.595535`) and are hard to manually verify & reason-about, when investigating a test-failure.  It's not clear to-what-extent these particular numeric values are technically correct, vs. were just extracted to be good-enough for one particular browser's rendering at some point in the past.
> 
> 
> I'm proposing to replace the test with a new version that addresses these issues in two ways, making the test much more robust while still testing the same general thing (i.e. still testing a div with two different angles in its `skew()` expression): (1) To address the arbitrary-looking/hard-to-validate numeric values issue, for the "reference" shapes: let's use multiples of `45deg` as the angles in the `skew()` expression. `skew(45deg,45deg)` has a nice property that it produces a diamond whose bounding box is 2x the width and height of the original rect, which is a rendering that we can easily mock up with an SVG polygon using whole-numbered pixel values. (2) To address other sources of fuzz (from e.g. different pixel-snapping or antialiasing behavior along diagonal lines between SVG vs. transformed divs): we can make the reference shapes be SVG polygons that are _slightly_ larger/smaller than the transformed div, and validate that one element fully covers the other.
> 
> I've got a version of the test locally that passes with no fuzz required, which is fixed up along these lines.

Here's the pull request with my rewritten version of this test:
https://github.com/web-platform-tests/wpt/pull/40953

**Comment by dholbert** [comment]
Here's wpt.fyi results for this test with the pull request merged (everyone passes):
https://wpt.fyi/results/css/css-transforms/skew-test1.html?sha=29f0fdb927&label=pr_head&max-count=1

Here's a live version of the reworked version of this test, if anyone wants to poke around in a live browser:
https://bug1841349.bmoattachments.org/attachment.cgi?id=9343132

**Comment by nt1m** [comment]
Seems OK as long as you we don't lose test coverage, I trust your judgement on this :)

cc @mattwoodrow @dbaron

**Comment by dholbert** [comment]
Thanks! Yup, we're not losing test coverage.  The test was & is exercising 2-component skew() with `deg` units, and it's still testing that -- it's just now testing `skew(45deg,135deg)` instead of `skew(30deg,20deg)`. (And it's still producing a sort of diamond shape, and it's testing the expectations at least as robustly as before.)

@dbaron approved the pull request in https://github.com/web-platform-tests/wpt/pull/40961#pullrequestreview-1524362650 so I think that means he's fine with this.

I think that means we've got an OK from Gecko/WebKit/Safari.

So, I'll go ahead and merge the PR. thanks everyone!

**Comment by dholbert** [comment]
Closing, now that https://github.com/web-platform-tests/wpt/pull/40961 has been merged.

This shows Chrome/Firefox/Safari passing the updated version of the test:
https://wpt.fyi/results/css/css-transforms/skew-test1.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned

(I removed Edge to get latest results; they haven't had a completed WPT run for a week or so, for some reason.)

**Comment by dbaron** [comment]
FYI, you can also remove "aligned" from the URL to avoid getting non-latest results for some engines.
