### ISSUE TITLE
Remove shadow-dom/focus-navigation/focus-with-negative-index.html from Interop 2023

### ISSUE THREAD

**Issue by sefeng211** [web-platform-tests/interop#379]
### Test List

https://wpt.fyi/results/shadow-dom/focus-navigation/focus-with-negative-index.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-webcomponents

### Rationale

The simplified behaviour difference of the test between Firefox and Chrome/Safari can be found at https://jsfiddle.net/6jk0u9sb/1/. 

STR: 
  1. Click focus `Click focus me`. 
  2. Shift+Tab

Firefox moves the focus to `k1` and Chrome/Safari moves the focus to `k0`. Although `Click focus me` has `tabIndex=1`, it's not a sequential focusable element because it has a `tabIndex=-1` shadow host.
 
More importantly, the sequential focusing behaviour when the current focused element is not in the sequential navigation order is not cleared defined in the spec and I've filed https://github.com/whatwg/html/issues/9081 for this. 

So this test is testing something that's not cleared defined, I think we should remove this from Interop 2023.

**Comment by nairnandu** [comment]
@nt1m / @gsnedders could you review the proposed change for WebKit?
@mfreed7 could you review the proposed change for Chromium?

**Comment by mfreed7** [comment]
I added a comment to https://github.com/whatwg/html/issues/9081 in support of a change to browser behavior if possible. That'll likely require a change to this test. In the meantime, given the lack of clarity, I'm supportive of removing this test from Interop2023.

**Comment by nt1m** [comment]
seems ok

**Comment by nairnandu** [comment]
@sefeng211 closing this as the change has been merged
