### ISSUE TITLE
Questionable assertion in 2d-getcontext-options.any tests

### ISSUE THREAD

**Issue by jfkthame** [web-platform-tests/interop#381]
### Test List

https://wpt.fyi/results/html/canvas/offscreen/the-offscreen-canvas/2d-getcontext-options.any.html
https://wpt.fyi/results/html/canvas/offscreen/the-offscreen-canvas/2d-getcontext-options.any.worker.html

### Rationale

The body of each of these tests makes 4 assertions, but I'm not sure the last one of them is justified by the requirements of the spec.

Taking it step by step:
```
  const canvas = new OffscreenCanvas(100, 50);
  const context = canvas.getContext('2d', options);
  assert_not_equals(context, null, "context");
```
Verifies that we got a non-null context.

```
  assert_array_equals(actual, expected, "order of operations (creation)");
```
This verifies that the options were accessed in the expected order, as per the [offscreen 2d context creation algorithm](https://html.spec.whatwg.org/multipage/canvas.html#offscreen-2d-context-creation-algorithm).

```
  actual = [];
  assert_equals(canvas.getContext('2d', options), context, "cached context");
```
Verifies that calling `getContext` again returns the same context object (does not create a new one).

```
  assert_array_equals(actual, expected, "order of operations (caching)");
```
This is the assertion that troubles me. The [spec for getContext("2d", ...)](https://html.spec.whatwg.org/multipage/canvas.html#dom-offscreencanvas-getcontext) when the canvas context mode is already `2d` simply tells us to

> Return the same object as was returned the last time the method was invoked with this same first argument.

and does not use the optional second argument `options` in any way. Therefore, is it valid to assert that the `options` dictionary keys must all be accessed here (let alone in a specific order), as this assertion seems to require?

So unless I'm missing something here, I propose that this fourth assertion should be dropped.

**Comment by nairnandu** [comment]
@fserb could you please review for Chromium?
@jgraham / @zcorpan could you please review for Gecko?

**Comment by nt1m** [comment]
Seems fine. (note that OP is from Gecko btw)

**Comment by fserb** [comment]
SGTM

**Comment by gsnedders** [comment]
This is partly because the (WebIDL) argument is `optional any options = null`, right? i.e., it's not a dictionary—it's `any`, and thus the order in which dictionaries are read at the WebIDL-level doesn't apply here.
