### ISSUE TITLE
Remove `margin-box` tests for `mask` properties

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#387]
### Test List

https://wpt.fyi/results/css/css-masking/parsing/mask-valid.sub.html?label=master&label=experimental&aligned&q=css%2Fcss-masking%2Fparsing%2Fmask-valid.sub.html (the part that tests `margin-box`)

https://wpt.fyi/css/css-masking/mask-image/mask-origin-2.html (the whole test)

### Rationale

See https://github.com/web-platform-tests/wpt/issues/41166

`mask-origin: margin-box` & `mask-clip: margin-box` was removed from the spec. This WPT should probably be removed entirely.

**Comment by nt1m** [comment]
@dholbert @nairnandu Does this look good for Blink / Gecko?

**Comment by nairnandu** [comment]
@progers could you review this proposal for Chromium?

**Comment by dholbert** [comment]
Sounds good, yeah.  FWIW we've got these two bugs filed for these test failures:
https://bugzilla.mozilla.org/show_bug.cgi?id=1834641 for mask-valid.sub.html (this covers some unrelated subtest failures as well)
https://bugzilla.mozilla.org/show_bug.cgi?id=1823257 for mask-origin-2.html

**Comment by progers** [comment]
Thanks for creating this. Chromium also agrees that we should remove these tests.
