### ISSUE TITLE
[css-properties-values-api] Test coverage for "<string>" component name

### ISSUE THREAD

**Issue by zrhoffman** [web-platform-tests/interop#389]
### Test List

Test | `<string>` test coverage PR
-- | --
https://wpt.live/css/css-properties-values-api/at-property.html | web-platform-tests/wpt#43757
https://wpt.live/css/css-properties-values-api/register-property-syntax-parsing.html | web-platform-tests/wpt#41308

### Rationale

A css-properties-values-api editor accepted a proposal to add the `"<string>"` component name in w3c/css-houdini-drafts#1103. Once the spec is updated, this new syntax component name will need WPT coverage.

**Comment by lilles** [comment]
sgtm

**Comment by nt1m** [comment]
Seems ok, although note that this is `CSS.registerProperty()` not `@property`

**Comment by nt1m** [comment]
I would want the spec PR to be merged before merging the WPT PR fwiw.

**Comment by lilles** [comment]
> Seems ok, although note that this is `CSS.registerProperty()` not `@property`

Yes, we should add tests for `<string>` here too: http://wpt.live/css/css-properties-values-api/at-property.html

> I would want the spec PR to be merged before merging the WPT PR fwiw.

Yes, that's why I blocked https://github.com/web-platform-tests/wpt/pull/41308

**Comment by zrhoffman** [comment]
> > Seems ok, although note that this is `CSS.registerProperty()` not `@property`
> 
> Yes, we should add tests for `<string>` here too: http://wpt.live/css/css-properties-values-api/at-property.html

Tests added in web-platform-tests/wpt#43757.

**Comment by emilio** [comment]
Sounds good to me.

**Comment by foolip** [comment]
https://github.com/w3c/css-houdini-drafts/issues/1103 has still not been merged and Interop 2023 is now closed and the dashboard isn't being updated. I'll close this, but someone please reopen if we should do something retroactively here.

**Comment by zrhoffman** [comment]
> [w3c/css-houdini-drafts#1103](https://github.com/w3c/css-houdini-drafts/issues/1103) has still not been merged and Interop 2023 is now closed and the dashboard isn't being updated. I'll close this, but someone please reopen if we should do something retroactively here.

@foolip The Custom Properties focus area is carried over from Interop 2023 to Interop 2024, so #389 should probably stay open.

**Comment by foolip** [comment]
@zrhoffman sorry, my bad!

**Comment by foolip** [comment]
https://github.com/w3c/css-houdini-drafts/pull/1104 is the PR for this change that we should keep an eye on.

**Comment by zrhoffman** [comment]
The spec is updated. WPT PRs needing review: web-platform-tests/wpt#43757, web-platform-tests/wpt#41308

**Comment by zrhoffman** [comment]
Closing #389 because web-platform-tests/wpt#43757 and web-platform-tests/wpt#41308 are merged. Thanks all! :)
