### ISSUE TITLE
[offscreen-canvas] Remove 2d.path.stroke.prune.* tests for open paths from interop-2023

### ISSUE THREAD

**Issue by jfkthame** [web-platform-tests/interop#392]
### Test List

https://wpt.fyi/results/html/canvas/offscreen/path-objects/2d.path.stroke.prune.arc.html
https://wpt.fyi/results/html/canvas/offscreen/path-objects/2d.path.stroke.prune.arc.worker.html
https://wpt.fyi/results/html/canvas/offscreen/path-objects/2d.path.stroke.prune.curve.html
https://wpt.fyi/results/html/canvas/offscreen/path-objects/2d.path.stroke.prune.curve.worker.html
https://wpt.fyi/results/html/canvas/offscreen/path-objects/2d.path.stroke.prune.line.html
https://wpt.fyi/results/html/canvas/offscreen/path-objects/2d.path.stroke.prune.line.worker.html

### Rationale

The behavior of 0-length subpaths with line-caps is subject to a longstanding [canvas2d spec issue](https://github.com/whatwg/html/issues/1079) that has never been resolved, although discussion there appeared to converge on a consensus that would align behavior with SVG rendering and would *not* match the existing WPT tests here.

Given that the existing spec text is confusing/ambiguous, and discussion in the open spec issue favored a different result than the existing tests expect, I think we should remove these tests from the interop-2023 set until such time as there's a clear resolution of the spec issue.

**Comment by nt1m** [comment]
Seems ok

**Comment by chrishtr** [comment]
@fserb can you review for Chromium?

**Comment by fserb** [comment]
lgtm

**Comment by yiyix** [comment]
This misses the 4 following tests. Could we remove them from interop as well?
[2d.path.stroke.prune.closed.html](https://wpt.fyi/results/html/canvas/offscreen/path-objects/2d.path.stroke.prune.closed.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-offscreencanvas)
[2d.path.stroke.prune.closed.worker.html](https://wpt.fyi/results/html/canvas/offscreen/path-objects/2d.path.stroke.prune.closed.worker.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-offscreencanvas)
[2d.path.stroke.prune.rect.html](https://wpt.fyi/results/html/canvas/offscreen/path-objects/2d.path.stroke.prune.rect.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-offscreencanvas)
[2d.path.stroke.prune.rect.worker.html](https://wpt.fyi/results/html/canvas/offscreen/path-objects/2d.path.stroke.prune.rect.worker.html?label=experimental&label=master&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-offscreencanvas)

**Comment by jfkthame** [comment]
Is there ambiguity about how those should behave? The others were about unclosed paths, where there may potentially be line-caps involved, but that's not an issue for closed paths.

**Comment by yiyix** [comment]
Hi, I am very new to the Path spec. Please help me to understand the spec for closed curves. In the spec, https://html.spec.whatwg.org/multipage/canvas.html#trace-a-path, item 5 says

> Add a straight closing line to each closed subpath in path connecting the last point and the first point of that subpath; change the last point to a join (from the previously last line to the newly added closing line), and change the first point to a join (from the newly added closing line to the first line).

since the start and the end is the same point, it basically added a subpath of length 0. Will the line caps be drawn in this case?

**Comment by jfkthame** [comment]
I don't think it would ever make sense to draw line-caps for a closed subpath (whatever its length). Caps go on open ends of a path. A closed subpath doesn't have open ends, so it doesn't get caps.

**Comment by Kaiido** [comment]
Caps go on each lines of the dash strokes, so you can have these even on closed pathes, e.g. when the dash lines are smaller than the path's total length. What happens for zero length closed pathes is relatively unclear, and seems dependent of the choice that will be done there. Note that SVG does render the caps in this case.

**Comment by jfkthame** [comment]
Yes, caps would go on dash strokes. But intuitively, it seems to me that if the path length is zero, then there would be no instances of the dash, and hence no caps either.

**Comment by Kaiido** [comment]
I'm not saying your reasoning isn't sound, but I fear that both interpretations are, and that would maintain an interop issue with SVG which I believe is against most views expressed in the issue there.
So if the tests aren't passing everywhere today I guess it's fine to remove these too, along with the other problematic ones, until it's all sorted out (though I'd personally rather prefer to see it sorted out quickly...)

**Comment by yiyix** [comment]
[nt1m](https://github.com/nt1m) could you review the change https://github.com/web-platform-tests/wpt-metadata/pull/4775? Thank you so much.
