### ISSUE TITLE
[webcodecs] Support odd coded sizes

### ISSUE THREAD

**Issue by sandersdan** [web-platform-tests/interop#395]
### Test List

- https://wpt.fyi/results/webcodecs/videoFrame-construction.any.html
- https://wpt.fyi/results/webcodecs/videoFrame-construction.any.worker.html
- https://wpt.fyi/results/webcodecs/videoFrame-copyTo.any.html
- https://wpt.fyi/results/webcodecs/videoFrame-copyTo.any.worker.html

### Rationale

Support for odd coded sizes was not included in the initial specification due to ambiguity in interpretation. Based on implementation experience and user feedback, this change picks the most obvious interpretation, as already used in practice by the VP9 codec. The change allows `VideoFrame` coded sizes that were previously disallowed.

WebCodecs Issue: https://github.com/w3c/webcodecs/issues/638
Media WG Meeting Notes: https://www.w3.org/2023/05/16-mediawg-minutes.html#t03
WebCodecs Spec Change: https://github.com/w3c/webcodecs/pull/666

Test changes: https://github.com/web-platform-tests/wpt/pull/39630
Chromium Implementation: https://chromium-review.googlesource.com/c/chromium/src/+/4443092

**Comment by chrishtr** [comment]
@dalecurtis can you review for Chromium?

**Comment by dalecurtis** [comment]
lgtm from the Chromium side.

**Comment by nairnandu** [comment]
@jgraham / @zcorpan could you review for Gecko?
@nt1m / @gsnedders could you review for WebKit?

**Comment by sandersdan** [comment]
Anything I can do to push this along?

@youennf 
@padenot

**Comment by Djuffin** [comment]
Let's put tests for odd sized frames into separate files.

**Comment by sandersdan** [comment]
> Let's put tests for odd sized frames into separate files.

Ok, I'll update the change to remove the existing tests that expect odd-sized frames to fail, and add the tests for odd-sized frames to a new file.

**Comment by sandersdan** [comment]
I've pushed an updated commit, the existing files now only have test removals, and there is a new file for the new tests. Based on the comments above I'll go ahead and push this once the Chromium review is done.

**Comment by nt1m** [comment]
Closing as the PR got merged
