### ISSUE TITLE
Input for State of HTML 2023 survey

### ISSUE THREAD

**Issue by LeaVerou** [web-platform-tests/interop#398]
Hi folks,

As discussed in the call, I’ve been funded by Google to design the inaugural State of HTML survey, to complement the well established State of CSS and State of JS surveys. Despite the name, it’s not exclusively about HTML features, but also HTML-adjacent ones, e.g. Web Components, DOM, PWAs etc. It includes both structured questions around specific features (to capture, usage, awareness, and sentiment), as well as open-ended questions to identify gaps and pain points.

In terms of timeline, it's a high priority goal to have preliminary results well in advance of the [Interop 2024 proposals deadline](https://github.com/web-platform-tests/interop/issues/384).

Almost all planning and design work is happening in the open:
* Draft outline: https://coda.io/@leaverou/state-of-html/survey-outline-7
* Discussion section: https://github.com/Devographics/surveys/discussions
* Roadmap: https://github.com/Devographics/surveys/discussions/112

I would welcome input from this crowd on the content of this survey, especially on:
- Any features that are important for interop and have escaped my radar . 
- Better ways to identify gaps and pain points

Input should preferably go in the [Discussions](https://github.com/Devographics/surveys/discussions) section above, but any way you find convenient is fine (this issue, email, carrier pigeon, whatever, as long as it reaches me 😅).

**Comment by foolip** [comment]
Closing this now as State of HTML 2023 has already run and closed. Preliminary results have been shared in https://github.com/web-platform-tests/interop/issues/550 and as comments on proposals. Thank you for all your work on this @LeaVerou!
