### ISSUE TITLE
insertparagraph-with-white-space-style.tentative.html still expects browsers creating invalid HTML structure

### ISSUE THREAD

**Issue by masayuki-nakano** [web-platform-tests/interop#399]
### Test List

* https://wpt.fyi/results/editing/other?label=master&label=experimental&aligned&q=insertparagraph-with-white-space-style.tentative.html

### Rationale

I wrote the test as aligning the behavior to Chrome. The main purpose of Interop-2023 about the test is, making the builtin editors of browsers stop creating the invalid HTML structure, but passing all of them means that browsers keep creating invalid HTML structure by themselves. (E.g., `<span contenteditable>` will have `<div>`.

Therefore, the `display` value checks of the `<span contenteditable>` should be removed, e.g., here:
https://searchfox.org/mozilla-central/rev/8be17dcf81d9bd894c398b53282d43d782815967/testing/web-platform/tests/editing/other/insertparagraph-with-white-space-style.tentative.html#48-56

**Comment by masayuki-nakano** [comment]
Oops, sorry, the test is not handled in Interop-2023. I misread the line markers.

**Comment by masayuki-nakano** [comment]
FYI: The test will be updated in https://bugzilla.mozilla.org/show_bug.cgi?id=1850472

**Comment by chrishtr** [comment]
With this change will the tests still pass in Chromium?

**Comment by masayuki-nakano** [comment]
Not yet considered which case Mozilla should follow Chrome. Basically, Gecko does not work with style information, but indeed, some behavior of Chrome in the tests makes sense. I'll work on the bug next week, then, I'll comment here about the result.

**Comment by nt1m** [comment]
Closing at this test is not in Interop.

**Comment by masayuki-nakano** [comment]
Sorry for the long delay due to [updating our implementation to check it](https://groups.google.com/a/mozilla.org/g/dev-platform/c/YsAgwshXXms).

The test will be updated like [this](https://phabricator.services.mozilla.com/D188908). I think both Chrome and Safari will start failing the cases when they format the right node (after caret position before `insertParagraph`) with the default paragraph separator which is set to `<p>`.  At least Chrome splits parent `<div style="display:inline">` or `<div style="display:inline-block">` and wrap the right node within new `<p>`. So, the inlined `<div>` elements will be appended to `<p>`, but `<p>` cannot have `<div>` nor `<p>`. So, they need special handling.

Additionally, we will add [new tests](https://phabricator.services.mozilla.com/D188937) for the cases of `<span contenteditable style="display:block">` and `<p contenteditable>` cases. Chrome also puts `<div>` into `<p contenteditable>`.
