### ISSUE TITLE
`custom-elements/reactions/Document.html` depends on WebKit/Blink specific feature

### ISSUE THREAD

**Issue by masayuki-nakano** [web-platform-tests/interop#401]
### Test List

* https://wpt.fyi/results/custom-elements/reactions/Document.html?label=experimental&label=master&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-webcomponents

### Rationale

The test which only Firefox does not pass sets [focus to the editing host](https://searchfox.org/mozilla-central/rev/bdd5b85b56885cd48bd91d262647e0d3499b3a27/testing/web-platform/tests/custom-elements/reactions/Document.html#63). Then, all browsers make `Selection` collapsed at start of the editing host. I.e., it becomes:
```
<div contenteditable>{}<custom-element/></div>
```
Then, it executes [`delete` command](https://searchfox.org/mozilla-central/rev/bdd5b85b56885cd48bd91d262647e0d3499b3a27/testing/web-platform/tests/custom-elements/reactions/Document.html#64), but it's a command which is same as typing `Backspace`. So, in usual editors, it should be "no-op", but the expectation is that it should delete the later content (`<custom-element>`).

[WebKit introduced the behavior in 2009](https://source.chromium.org/chromium/chromium/src/+/a8b59795df6aac740fefec14297db6d5944dc691) and Blink inherits that. The feature is, when typing `Backspace` at start of editing host if and only if [there is no following visual caret position](https://source.chromium.org/chromium/chromium/src/+/main:third_party/WebKit/WebCore/editing/TypingCommand.cpp;l=446;drc=49f8aec42a2380ef6df92d08cac8c892aed58121) unless [there is only one `<br>` element](https://source.chromium.org/chromium/chromium/src/+/main:third_party/WebKit/WebCore/editing/TypingCommand.cpp;l=400-403;drc=49f8aec42a2380ef6df92d08cac8c892aed58121), [removes all content in the editing host](https://source.chromium.org/chromium/chromium/src/+/main:third_party/WebKit/WebCore/editing/TypingCommand.cpp;l=406-407;drc=49f8aec42a2380ef6df92d08cac8c892aed58121). So, the test depends on this feature. I tried to emulate this feature, but I cannot reproduce it with `<img>`, `<hr>`, etc because users can move caret after them. Therefore, I stopped emulating it in Firefox.

Anyway, it does not make sense to depend on unusual behavior of specific implementation(s) since this test does not check the feature.

**Comment by nt1m** [comment]
Change seems fine
