### ISSUE TITLE
webcodecs/videoFrame-serialization.crossAgentCluster.https.html is testing that transferring VideoFrames out of cluster is not working

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#402]
### Test List

Add: webcodecs/videoFrame-serialization.https.html
Remove: webcodecs/videoFrame-serialization.crossAgentCluster.https.html

### Rationale

See https://github.com/web-platform-tests/wpt/issues/41635 for more context.

**Comment by nt1m** [comment]
@dalecurtis / @sandersdan Can you please review from the Chrome side?

@ChunMinChang / @padenot Can you please review from the Mozilla side?

**Comment by dalecurtis** [comment]
lgtm

**Comment by sandersdan** [comment]
lgtm

**Comment by padenot** [comment]
yeah looks good, sorry for the delay.

I filed https://github.com/w3c/webcodecs/issues/717 to clarify this in the spec, considering implementations don't support  sending frames to other clusters, and that I don't think it's particularly useful.
