### ISSUE TITLE
Remove shape() tests from interop-2023-cssmasking

### ISSUE THREAD

**Issue by progers** [web-platform-tests/interop#403]
### Test List

css/css-masking/animations/clip-path-interpolation-shape.html
css/css-masking/clip-path/animations/clip-path-shape-interpolation-001.html
css/css-masking/clip-path/animations/clip-path-shape-interpolation-002.html
css/css-masking/clip-path/clip-path-shape-001.html
css/css-masking/clip-path/clip-path-shape-002-units.html
css/css-masking/clip-path/clip-path-shape-002.html
css/css-masking/clip-path/clip-path-shape-003.html
css/css-masking/clip-path/clip-path-shape-004.html
css/css-masking/parsing/clip-path-shape-parsing.html

### Rationale

Shape() is a new ([css-shapes-2](https://drafts.csswg.org/css-shapes-2/#funcdef-shape)) feature that is not yet supported in any engine, and all implementations fail these tests. Shape was not discussed during the initial interop proposal (https://github.com/web-platform-tests/interop/issues/148) and was likely included due to including all tests under the css-masking directory.

@nt1m @dholbert @nandu

**Comment by nt1m** [comment]
Lgtm

**Comment by dholbert** [comment]
Sounds fine. Thanks!
