### ISSUE TITLE
Remove tests related to whatwg/html#9571 from Interop 2023

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#406]
### Test List

- workers/modules/dedicated-worker-import-csp.html
- workers/modules/shared-worker-import-csp.html
- workers/modules/dedicated-worker-import-data-url-cross-origin.html
- workers/modules/shared-worker-import-data-url-cross-origin.html
  * static import script from data: URL should be allowed. (split this subtest out)
- workers/modules/dedicated-worker-import-data-url.any.html
- workers/modules/dedicated-worker-import-data-url.any.worker.html
- workers/modules/shared-worker-import-data-url.window.html
   * [Static import (redirect).] (split this subtest out)
   
### Rationale

Exact behavior is pending on spec discussion in https://github.com/whatwg/html/issues/9571

**Comment by nt1m** [comment]
@nairnandu / @jgraham Can you find someone to review for Blink / Gecko?

**Comment by nairnandu** [comment]
@nyaxt could you review this test change proposal for Blink?

**Comment by nt1m** [comment]
@youennf Can you check if the list of tests affected by https://github.com/whatwg/html/issues/9571 is exhaustive? 

cc @allstarschh

**Comment by allstarschh** [comment]
Hi, thanks for adding me in.

I think there are some other tests also affected by https://github.com/whatwg/html/issues/9571

- /workers/modules/dedicated-worker-import-data-url-cross-origin.html
- /workers/modules/shared-worker-import-data-url-cross-origin.html
  - [static import script from data: URL should be allowed.]

- /workers/modules/dedicated-worker-import-data-url.any.html
- /workers/modules/dedicated-worker-import-data-url.any.worker.html
- /workers/modules/shared-worker-import-data-url.window.html
  - [Static import (redirect).]

Please see the summary in 
https://phabricator.services.mozilla.com/D187900
https://phabricator.services.mozilla.com/D187901

cc @smaug----

**Comment by youennf** [comment]
Agreed with the additional tests plus shared-worker-import-csp.html as well.

**Comment by hayatoito** [comment]
I am not sure whether https://github.com/whatwg/html/issues/9571 is the right direction or not.

That being said, it's likely that the following tests could also be impacted by the issue, as they all utilize imports within workers:

workers/modules/shared-worker-parse-error-failure.html
workers/modules/shared-worker-import-failure.html
workers/modules/dedicated-worker-import-failure.html

Could you add these tests?

These are tracked on https://crbug.com/1446246 on Blink.

**Comment by allstarschh** [comment]
Hi, @hayatoito 
Those tests are correct, and not related to https://github.com/whatwg/html/issues/9571

> That being said, it's likely that the following tests could also be impacted by the issue, as they all utilize imports within workers:
> 
> workers/modules/shared-worker-parse-error-failure.html

Please see domenic's comment from  https://github.com/whatwg/html/issues/2289#issuecomment-1676721412

> workers/modules/shared-worker-import-failure.html
> workers/modules/dedicated-worker-import-failure.html
See https://github.com/web-platform-tests/wpt/issues/41745
and also https://github.com/web-platform-tests/wpt/issues/41745#issuecomment-1701307485
for the explanation of the current spec.

**Comment by hayatoito** [comment]
Thanks! I understand these tests are not related to the whatwg/html#9571.

I haven't had the time to fully understand the current standard yet,
so you can ignore my previous comment and proceed.

**Comment by foolip** [comment]
@nt1m would you mind preparing a PR against wpt-metadata to make it very easy to see which tests should be removed, given the many comments on this issue?

**Comment by allstarschh** [comment]
PR is sent in https://github.com/web-platform-tests/wpt-metadata/pull/4780
