### ISSUE TITLE
scrollbar-color CSS property

### ISSUE THREAD

**Issue by ramiy** [web-platform-tests/interop#417]
### Description

Developers need a standard and cross-browser solution to style scrollbars for elements with `overflow: scroll;`.

There are two alternatives to style scrollbars, the widely supported non-standard `::-webkit-scrollbar-*` pseudo-elements or the new standard `scrollbar-*` properties defined in the [CSS Scrollbars Styling Module](https://drafts.csswg.org/css-scrollbars/) spec. Both alternatives are not cross-browser supported.

The [non-standard `::-webkit-scrollbar-*` pseudo-elements](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar) supported by all browsers except Firefox. While [`scrollbar-width`](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width) and [`scrollbar-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color) properties are supported only by Firefox.

This is not an optimal situation for developers. We need a single solution implemented by all browsers.

### Specification

https://drafts.csswg.org/css-scrollbars/

### Tests

https://wpt.fyi/results/css/css-scrollbars?label=master&label=experimental&aligned

### Current Implementations

- [ ] Blink
- [X] Gecko
- [ ] WebKit

### Browser bug reports

https://bugs.chromium.org/p/chromium/issues/detail?id=891944

### Polls & Surveys

[`scrollbar-gutter`](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter) was mentioned in [State of CSS 2023](https://2023.stateofcss.com/en-US/features/#reading_list) and [State of CSS 2022](https://2022.stateofcss.com/en-US/features/interactions/).

This CSS property is not related to this spec but it is related to scrollbars in general.

### Existing Usage

https://caniuse.com/css-scrollbar
https://chromestatus.com/metrics/css/timeline/popularity/763
https://chromestatus.com/metrics/css/timeline/popularity/680

### Workarounds

Non-standard `::-webkit-scrollbar-*` pseudo-elements or JS libraries.

**Comment by lukewarlow** [comment]
https://github.com/web-platform-tests/interop/issues/419 issue for `scrollbar-gutter` that was referenced above

**Comment by lukewarlow** [comment]
FYI here's some links to somethings missing above:

[WebKit `scrollbar-color` request](https://bugs.webkit.org/show_bug.cgi?id=231590) and [WebKit `scrollbar-width` request](https://bugs.webkit.org/show_bug.cgi?id=231588)

[WebKit `scrollbar-color` standards position](https://github.com/WebKit/standards-positions/issues/134) and [WebKit `scrollbar-width` standards position](https://github.com/WebKit/standards-positions/issues/133)

[Chrome Intent to Prototype CSS Scrollbars](https://groups.google.com/a/chromium.org/g/blink-dev/c/zwG2m_KG0RY)

**Comment by lukewarlow** [comment]
As for accessibility impact the standard properties should be a net positive for accessibility as you can use user styles to more easily `undo` the styles. There's also better integration with the likes for `forced-colors` mode (scrollbar-color is reset to auto).

**Comment by lukewarlow** [comment]
It's also worth being aware there's partial implementations of both `scrollbar-color` and `scrollbar-width` in Chromium and WebKit so the gap to interopability shouldn't be as big as if there was no implementation. (Safari is blocked by platform APIs for scrollbar-color however)

**Comment by karlcow** [comment]
This is a pressure point for Firefox webcompat. 
https://github.com/search?q=repo%3Amozilla-extensions%2Fwebcompat-addon%20scrollbar&type=code

**Comment by foolip** [comment]
Scrollbar Styling is also a common answer in https://2023.stateofcss.com/en-US/usage/#css_interoperability_features, and in https://2022.stateofcss.com/en-US/usage/#interoperability_features_freeform before that.

**Comment by nt1m** [comment]
Can we split this proposal into scrollbar-width & scrollbar-color for evaluation?

**Comment by nt1m** [comment]
I split out scrollbar-width into its own proposal: https://github.com/web-platform-tests/interop/issues/571

**Comment by lukewarlow** [comment]
Chromium intent to ship: https://groups.google.com/a/chromium.org/g/blink-dev/c/PkEsMirl2zE/m/ArphSa39AAAJ

**Comment by svgeesus** [comment]
Safari failures seem to mainly relate to:

- CSS keywords like `inherit`, `initial` 
- interaction with `::-webkit-scrollbar*`

**Comment by nt1m** [comment]
Safari doesn't have scrollbar-color support enabled, because the visual effect of the property isn't implemented atm.

**Comment by lukewarlow** [comment]
Safari's pass rate will be inflated as well because many of the tests are for invalidation which appears to pass in safari (because the property has no actual effect).

I don't think WPT can effectively test the actual rendering as it's so platform dependent

**Comment by foolip** [comment]
Thank you for proposing the `scrollbar-color` CSS property for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
