### ISSUE TITLE
HTML `<search>` Element

### ISSUE THREAD

**Issue by ramiy** [web-platform-tests/interop#418]
### Description

Add cross-browser support for the new [HTML `<search>` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/search) which according to the [spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-search-element) is used to identify regions containing a set of form controls or other content related to performing a search or filtering operation.

This new [landmark element](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles#3._landmark_roles) has an implicit `role=”search”` attribute. Pages that use this element improve semantics, but more importantly, they improve accessibility.

There are [8 landmark roles](https://www.w3.org/TR/wai-aria-1.2/#landmark_roles), 7 of which have an equivalent HTML element (`<header>`, `<footer>`, `<aside>`, `<main>`, `<nav>`, `<section>` and `<form>`). The `<search>` tag is the last landmark element that until recently didn’t have an equivalent HTML element.

The new `<search>` element was introduced at the beginning of the year, therefore it’s not yet supported by all browsers. Let’s change that.

### Specification

https://html.spec.whatwg.org/multipage/grouping-content.html#the-search-element

### Tests

https://wpt.fyi/results/html?label=master&label=experimental&aligned&q=search-styles%20or%20search-element

### Current Implementations

- [X] Gecko
- [X] WebKit
- [x] Blink

### Existing Usage

https://caniuse.com/mdn-html_elements_search

### Workarounds

Currently you can use the search role:

```html
<div role="search">
  <form>
    ...
  </form>
</div>
```

The search tag simplifies the markup as it has an implicit search role builtin:

```html
<search>
  <form>
    ...
  </form>
</search>
```

### Accessibility Impact

As mentioned above, this is a landmark element. It improves page semantics significantly therefore it improve accessibility.

This element should help distinguish search forms from other forms (registration, newsletter, etc.).

**Comment by ramiy** [comment]
Hi @lukewarlow,

I know that this feature is shipping with **[Firefox 118](https://bugzilla.mozilla.org/show_bug.cgi?id=1824121)**  and **[Safari 17](https://bugs.webkit.org/show_bug.cgi?id=254327)**, but not **[Chrome 118](https://bugs.chromium.org/p/chromium/issues/detail?id=1294294)**.

Also see the https://developer.chrome.com/blog/chrome-118-beta/

**Comment by lukewarlow** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1294294 - There was an oversight on chromestatus (which is where these blogs get their data from) but it is actually enabled on chrome 118.

**Comment by ramiy** [comment]
Thank you @lukewarlow  for clarifying this. According to [chromestatus](https://chromestatus.com/feature/5126108151808000) the HTML `<search>` element is shipped in Chrome 118. I've sent a PR to update MDN browser compatibility data.

**Comment by gsnedders** [comment]
A brief glance at the test results suggests that with this now in Chrome we have broad interoperability; the only failures relate to bidi isolation which is a much broader and longer-standing issue.

Is there, in fact, any work still to be done here? (Like: is there any evidence of non-interoperability, especially which is causing pain for users or web developers?)

**Comment by lukewarlow** [comment]
Given the new element has the same style of display: block and all have an implicit aria role of search I can't imagine there's particularly room for any interop issues left. So I imagine this can be discounted from the proposals as already complete.
