### ISSUE TITLE
text-box-trim

### ISSUE THREAD

**Issue by nileshprajapati** [web-platform-tests/interop#422]
### Description

The [text-box-trim](https://www.w3.org/TR/css-inline-3/#propdef-text-box-trim) property allows trimming this additional space above and below the first and last lines of a block, allowing more precise control over spacing around the glyphs. Moreover, by relying on font metrics rather than hard-coded lengths, it allows content to be resized, rewrapped, and rendered in a variety of fonts while maintaining that spacing.

### Specification

https://www.w3.org/TR/css-inline-3/

### Tests

https://wpt.fyi/results/css/css-inline/text-box-trim?label=master&label=experimental&aligned

### Current Implementations

- [ ] Blink
- [ ] Gecko
- [X] WebKit

**Comment by gsnedders** [comment]
To note: CSS Inline 3 doesn't meet the bar we set for spec maturity; it is yet to be published as a CR, and per the CSS WG policy, ["should not be released broadly for general use"](https://www.w3.org/TR/CSS/#experimental).

**Comment by gsnedders** [comment]
Previously proposed in #155 (albeit since renamed).

**Comment by foolip** [comment]
@gsnedders the issue template asks only for Recommendation Track for W3C specs, which I take to mean FPWD. https://github.com/web-platform-tests/interop#requirements-for-focus-area-proposals says only "mature-enough".

**Comment by jlarmstrongiv** [comment]
This proposal also benefits designers, whose design tools already support `leading-trim`:

- [Figma](https://help.figma.com/hc/en-us/articles/360039956634-Explore-text-properties#h_01H96FW9Z3W7J7Z2HEN8V17BZT)
- [Sketch](https://www.sketch.com/docs/designing/text/#adjusting-line-height) with baseline alignment

According to [designers](https://forum.figma.com/t/vertical-trim-is-nice-but-without-css-support-its-kind-of-useless-what-am-i-missing/41605)—unfortunately, without browser support, the design tool support of vertical trim is not only useless, but also causes more work for the developer.

Google fonts [references](https://fonts.google.com/knowledge/using_type/vertical_spacing_and_line_height_in_design_systems#upcoming-css-feature-leading-trim) the upcoming `leading-trim` feature too.

**Comment by nileshprajapati** [comment]
Intent to Prototype: CSS text-box-trim and text-box-edge 
https://groups.google.com/a/chromium.org/g/blink-dev/c/Sn8TF5KHrRU/m/ldJKnA0MAgAJ

**Comment by bkardell** [comment]
Thank you for proposing text-box-trim for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

As of the deadline, the specifications for text-box-trim were not yet complete enough to allow interoperable implementations. To make progress on this area in the future, it will first be necessary to ensure that the feature has a clear specification in a standards track document.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
