### ISSUE TITLE
Support for open media codecs (AV1 & Opus)

### ISSUE THREAD

**Issue by AshleyScirra** [web-platform-tests/interop#425]
### Description

For many years there has not been a single video/audio codec that can be relied upon to work in all browsers. Further, proprietary codecs can involve licensing fees that make some uses cases uneconomical, including making it difficult for open source projects to support. This is a major point of interop pain, resulting in having to transcode media files to multiple formats, or use workarounds like codecs implemented in WebAssembly.

I would like to propose that browsers commit to supporting:

- AV1 for video
- Opus for audio
- WebM as a container format

They are well-specified modern, open, royalty-free codecs which already have substantial support across the industry. If all browsers consistently supported both formats across all relevant web media features (video element, audio element, Web Audio, and WebCodecs) then there would *finally* be one codec that can be relied upon cross-browser for both video and audio support.

As it stands, AV1 is not yet supported in Safari, and Edge requires the "AV1 Video Extension" to be installed from the Microsoft Store so it can't be relied upon to work out-of-the-box.

Opus support is *nearly* there, but while it's ostensibly supported in Safari, it's actually been broken for some time and so cannot be used reliably (see issues [238546](https://bugs.webkit.org/show_bug.cgi?id=238546) and [245428](https://bugs.webkit.org/show_bug.cgi?id=245428)).

According to caniuse, all major browsers already have support for WebM as a container format (barring bugs).

### Specification

AV1 is specified by AOMedia and Opus is specified by the IETF codec working group. However AFAIK no web-related specification currently mandates support for any specific codecs.

### Tests

It looks like WPT only has tests specifically mentioning AV1 and Opus for WebCodecs (plus one AV1 test for WebRTC). There are already lots of tests for other APIs like Web Audio; presumably there would need to be some variants added which make use of AV1 and Opus.

### Current Implementations

- [ ] Blink
- [ ] Gecko
- [ ] WebKit

### Standards Positions

Chrome and Firefox already support AV1. Edge already has optional support for AV1. WebKit [supports AV1](https://webkit.org/standards-positions/#position-55).

All browsers already have some support for Opus. The only problem there is bugs in Safari that are blocking its use.

All browsers already have some support for WebM.

### Browser bug reports

Safari issues for Opus: [238546](https://bugs.webkit.org/show_bug.cgi?id=238546), [245428](https://bugs.webkit.org/show_bug.cgi?id=245428)

Not sure any public issue exists for Safari support for AV1.

### Developer discussions

This has been an important and widely-discussed topic since the introduction of the video element in the late 2000s. Apparently it was originally proposed to require support for Ogg Theora/Vorbis, but that was replaced with wording along the lines of "there are no known codecs that satisfy all the current players". I am hopeful that the situation has now changed, with nearly-there support for Opus, and all major browser makers are governing members of the Alliance for Open Media which specifies AV1.

### Workarounds

Transcoding media to multiple formats, or using WebAssembly for codecs. Both have significant downsides (e.g. complexity, cost, performance).

### Accessibility Impact

Users using open-source software may find that media on the web is unavailable if it depends on proprietary codecs that it is infeasible for the open-source project to support.

**Comment by jensimmons** [comment]
As announced on Sept 12,  AV1 is now supported in Safari 17.0+ on devices that have hardware decoding/encoding support. This includes the iPhone 15 Pro and iPhone 15 Pro Max. 

The challenge here — can WPT infrastructure test Safari's AV1 support on devices that have hardware support? If not, then there isn't any means for one of the three browser engines to participate in this proposal, which makes it impossible for it to be part of Interop 2024.

**Comment by AshleyScirra** [comment]
Perhaps this proposal could be split in to one proposal for WebM Opus audio support, and one proposal for WebM AV1 video support. There are use cases for audio without video, such as game engine sound effects/music, podcasts, music players etc., which are still held up on interop issues with WebM Opus, and I don't think hardware decoding should be necessary for Opus decoding support.

**Comment by jensimmons** [comment]
I would recommend breaking this into two separate proposals (perhaps in new issues, and close this). That way we can debate the merits of each. 

Also, you might be interested to learn that Safari 17.0 on macOS Sonoma adds support for stereo-only Opus in WebM and MPEG-4 containers. See: https://webkit.org/blog/14445/webkit-features-in-safari-17-0/

**Comment by AshleyScirra** [comment]
I'll split this in to two separate proposals for audio and video then (will get round to it shortly).

I'm always happy to see progress on WebM Opus, but as issues [238546](https://bugs.webkit.org/show_bug.cgi?id=238546) and [245428](https://bugs.webkit.org/show_bug.cgi?id=245428) are still open, it looks to me like they will still be affecting Safari 17. If those issues were fixed, then presumably those issues would have been closed. Leaving them open seems to signal that nothing has yet been done about them.

**Comment by AshleyScirra** [comment]
Split in to #484 for audio and #485 for video, so closing this proposal.

**Comment by AshleyScirra** [comment]
@jensimmons can I ask why you reacted to my previous comment with a "laugh" emoji? This has been a painful problem for us for many years, and the lack of clarity about the situation from Apple has caused a lot of stress and frustration on our part, we really do want to better understand what the exact situation is, and that response makes it look like you're not taking it seriously. I suspect perhaps it was an accidental response.

**Comment by jensimmons** [comment]
Ashley, I responded with a smile. To say "thanks for making the effort, taking the time to split these proposals out". 

<img width="216" alt="Screenshot 2023-09-30 at 4 14 43 PM" src="https://github.com/web-platform-tests/interop/assets/108474/8fb2e3fe-dd7e-4c81-85ee-48fb221779e3">

I know writing these proposals takes a lot of energy. And having to split the original into two took even more work.

Thank you for doing so. I suggested they be split because I genuinely believe it will make each easier to understand and debate. And give each a higher likelihood of making it through the process.

**Comment by jensimmons** [comment]
<img width="323" alt="Screenshot 2023-09-30 at 4 19 19 PM" src="https://github.com/web-platform-tests/interop/assets/108474/716da88e-7b5f-46bc-9fb8-9d6bce5d93eb">

GitHub doesn't really give us a lot of options. Perhaps the thumbs up or heart would have been clearer?

**Comment by AshleyScirra** [comment]
I see. I appreciate the explanation and can see how this is a misunderstanding. GitHub describes that response as a "laugh emoji" as shown below, but I understand that you meant to respond positively. Thanks for clarifying.

![image](https://github.com/web-platform-tests/interop/assets/768723/9c7a8be8-ee04-48bb-8617-a0f319f15640)
