### ISSUE TITLE
Relative Color Syntax

### ISSUE THREAD

**Issue by Jothsa** [web-platform-tests/interop#426]
### Description

CSS Relative colors syntax allows colors to be created from an origin color. The new color can use the color channels of the origin color as is, manipulate them with math functions, or replace them with another value. The CSS Relative color syntax lets developers easily create variants of colors 

### Specification

https://www.w3.org/TR/css-color-5/#relative-colors

### Tests

https://wpt.fyi/results/css/css-color?label=master&label=experimental&aligned&q=relative
<https://wpt.fyi/results/css/css-color/parsing?label=master&label=experimental&aligned&q=relative>

### Current Implementations

- [x] Blink
- [ ] Gecko
- [X] WebKit

### Browser bug reports

<https://bugs.chromium.org/p/chromium/issues/detail?id=1475009&q=Relative%20Color%20syntax&can=2>

<https://bugzilla.mozilla.org/show_bug.cgi?id=1701488>

### Developer discussions

<https://stackoverflow.com/questions/55329996/how-to-create-color-shades-using-css-variables-similar-to-darken-of-sass>
<https://stackoverflow.com/a/71098929>
<https://chriscoyier.net/2023/01/26/relative-color-syntax-plzzzzz/>
<https://stackoverflow.com/questions/52037809/add-alpha-channel-to-hex-color-declared-on-css-variable>

### Polls & Surveys

In the State of CSS 2023 survey, over 1000 developers added relative colors to their reading list. <https://2023.stateofcss.com/en-US/features/#reading_list>

### Workarounds

<https://preset-env.cssdb.org/blog/postcss-relative-color-syntax/>

### Accessibility Impact

This would make designing accessible color palettes much easier, especially when used with a perceptually linear color space such as oklch. It becomes much easier to create higher contrast variants of colors.

For example:

```css
button {
    background-color: var(—secondary);

    &:hover, &:focus-visible {
        background-color: oklch(from var(—secondary), calc( l + .3) c h);
}
```

In this example, a hover variant is created of a color, ensuring that the new color is 30% lighter than the old color.

**Comment by lukewarlow** [comment]
Chrome Intent to Ship: https://chromestatus.com/feature/5205844613922816

Firefox Standards Position: https://github.com/mozilla/standards-positions/issues/841

**Comment by svgeesus** [comment]
[current WPT results for RCS](https://wpt.fyi/results/css/css-color?label=master&label=experimental&aligned&q=relative)

![image](https://github.com/web-platform-tests/interop/assets/2506926/4012bd77-30cd-45ce-be5b-eba0012ea481)

**Comment by emilio** [comment]
@tiaanl mentioned that WPTs expect gamut mapping at computed value time, is that right @svgeesus? I thought gamut mapping should only happen at used value time?

**Comment by emilio** [comment]
Untangling RCS from gamut mapping would be nice in terms of supporting this proposal fwiw.

**Comment by tiaanl** [comment]
@emilio it was my mistake. Exactly the opposite is true. They should NOT be gamut mapped. Sorry for the confusion.

**Comment by svgeesus** [comment]
> @tiaanl mentioned that WPTs expect gamut mapping at computed value time, is that right @svgeesus? 

No

> I thought gamut mapping should only happen at used value time?

Correct.

**Comment by zcorpan** [comment]
Thank you for proposing Relative Color Syntax for inclusion in Interop 2024.

We are pleased to let you know that this proposal was accepted as part of the Relative Color Syntax focus area. You can follow the progress of this focus area on the [Interop 2024 dashboard](https://wpt.fyi/interop-2024).

For an overview of our process, see the [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you for contributing to Interop 2024!

_Posted on behalf of the Interop team._
