### ISSUE TITLE
margin-trim

### ISSUE THREAD

**Issue by rctneil** [web-platform-tests/interop#429]
### Description

Imagine you are coding the layout of a site. You have the typical top and bottom margin on all your headlines, paragraphs, and many other elements that appear in text flow (figure, img, etc). Now imagine you are creating a component card of content — with a border or drop shadow around the outer edge of that box. 

<img width="1252" alt="diagram of example with headline and paragraphs with margins marked in orange, padding marked in green" src="https://github.com/web-platform-tests/interop/assets/108474/6b1e28c6-ddd1-4cf4-ba21-3bfe43e9c2fd">

You want a consistent amount of padding around the content, between it and the edge of the box. But, the top margin of the first element and the bottom margin of the last element get added to the padding, creating more space than you want at the top and bottom. 

<img width="1252" alt="same example, showing too much space above and below" src="https://github.com/web-platform-tests/interop/assets/108474/a5ac9c2c-0210-4124-9f34-25eca65add52">

The `margin-trim` property gives you an easy tool for removing any margins that are butting up against a box. 

<img width="1252" alt="example using margin trim to get rid of the extra space" src="https://github.com/web-platform-tests/interop/assets/108474/ea2f2fd4-37c9-4ccd-914a-636afbd25621">

### Specification

https://drafts.csswg.org/css-box-4/#margin-trim

### Open Issues

https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue+is%3Aopen+margin-trim+label%3Acss-box-4

### Tests

https://wpt.fyi/results/css/css-box/margin-trim?label=master&label=experimental&aligned&view=subtest

### Current Implementations

- [ ] Blink
- [ ] Gecko
- [x] WebKit

### Browser bug reports

Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1506241
Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1405835 

### Workarounds

The workaround is to manually override margins for each element that might be adjacent to the card box (or similar), under every possible permutation of content. It's not that hard to list off `h1`, `h2`, `h3`, `p`... but it's all too easy to miss something, like a `figure` or `ul`, and end up with layout bugs on the website. 

### Accessibility Impact

Margin trim has no accessibility impact. 

### Privacy Impact

Margin trim has no privacy impact.

**Comment by gsnedders** [comment]
To note: CSS Box Level 4 doesn't currently meet the bar we set for spec maturity; it is yet to be published as a CR, and per the CSS WG policy, ["should not be released broadly for general use"](https://www.w3.org/TR/CSS/#experimental).

**Comment by jsnkuhn** [comment]
Links for browser bug reports:

Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1506241
Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1405835

**Comment by jensimmons** [comment]
We would love to see `margin-trim` included in Interop 2024. 

This property was not included in State of CSS 2023, so there was no opportunity for developers to register their relative prioritization for it. To get some developer feedback, I asked on Mastodon: https://elk.zone/front-end.social/@jensimmons/111173319031791077 (click through to read comments in replies). 

<img width="620" alt="Screenshot 2023-10-05 at 2 48 16 PM" src="https://github.com/web-platform-tests/interop/assets/108474/955f0159-f56c-4df5-8d83-eac914f09597">
