### ISSUE TITLE
CSS Logical Properties and Values

### ISSUE THREAD

**Issue by ramiy** [web-platform-tests/interop#434]
### Description

[CSS logical properties and values](https://drafts.csswg.org/css-logical/) follow the content flow (inline/block axes, start/end position), rather than the screen flow (top/bottom/left/right). It helps developers style websites for all kinds of writing modes: left-to-right (LTR), right-to-left (RTL) and top-to-bottom (TTB).

The last two years, browsers did an amazing job introducing logical properties and values, however when you try to fully migrate to logical properties you find properties (or values) which support only physical properties.

There are groups:

* CSS properties with excellent browser and cross-browser support (`margin`, `padding`, `border`, `inset`, `border-radius`, `width`, `height` and `text-align`)

* CSS properties which are not cross-browser supported (`float`, `clear` and `resize`), but they are planed to be fixed in the coming releases.

* CSS properties which are not cross-browser supported and not planed to be fixed in the near future, like `caption-side` property. Or `overflow-block` and `overflow-inline` (which are covered by a [different spec](https://drafts.csswg.org/css-overflow/#overflow-control) ).

* CSS properties that have no logical equivalence. For example, `background-position-x` and `background-position-y`. Or the CSS `<position>` data-type values which supports only physical values.

### Specification

https://drafts.csswg.org/css-logical/

### Current Implementations

- [X] Blink
- [X] Gecko
- [X] WebKit

**Comment by foolip** [comment]
Tests: https://wpt.fyi/results/css/css-logical?label=master&label=experimental&aligned (don't know if they're comprehensive)

Open spec issues: https://github.com/w3c/csswg-drafts/labels/css-logical-1

There's also https://github.com/w3c/csswg-drafts/labels/css-logical-2 but no published Level 2 of the spec AFAICT, so I'm not sure if those issues are relevant.

**Comment by dholbert** [comment]
> CSS properties that have no logical equivalence. For example, background-position-x and background-position-y. Or the CSS <position> data-type values which supports only physical values.

(This part is probably is out-of-scope for interop-2024 at this point; I think we're trying to focus on things that are already-specced, not propose additional features/aliases that could hypothetically be added/specced.)

**Comment by ramiy** [comment]
@dholbert You are correct, the last group is out-of-scope for interop-2024, I mentioned to complete the list.

The 3rd group is the most important, and I guess there are more CSS properties & values that can be added.

**Comment by Loirooriol** [comment]
Worth noting that the [logical values for `caption-side`](https://drafts.csswg.org/css-logical/#caption-side) are only "for implementations that support `left` and `right`". That does not apply to [Blink](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/css/css_properties.json5;drc=c704e9e51bc30032bed14d88d009e33459e25884;l=2457), [WebKit](https://searchfox.org/wubkat/rev/5dfffd1d9c0cdf683b9302cd72303bf9e6700921/Source/WebCore/rendering/style/RenderStyleConstants.h#755), nor [Gecko](https://searchfox.org/mozilla-central/rev/90dce6b0223b4dc17bb10f1125b44f70951585f9/servo/components/style/values/specified/table.rs#33).
So it's not that the implementation is not planned, there is simply nothing to implement.

**Comment by ramiy** [comment]
> Worth noting that the [logical values for `caption-side`](https://drafts.csswg.org/css-logical/#caption-side) are only "for implementations that support `left` and `right`". That does not apply to [Blink](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/css/css_properties.json5;drc=c704e9e51bc30032bed14d88d009e33459e25884;l=2457), [WebKit](https://searchfox.org/wubkat/rev/5dfffd1d9c0cdf683b9302cd72303bf9e6700921/Source/WebCore/rendering/style/RenderStyleConstants.h#755), nor [Gecko](https://searchfox.org/mozilla-central/rev/90dce6b0223b4dc17bb10f1125b44f70951585f9/servo/components/style/values/specified/table.rs#33). So it's not that the implementation is not planned, there is simply nothing to implement.

The [Cascading Style Sheets Level 2 Revision 2 (CSS 2.2)](https://drafts.csswg.org/css2/#propdef-caption-side) spec mentions only `top` | `bottom` | `inherit` physical values.

The [CSS Logical Properties and Values Level 1](https://drafts.csswg.org/css-logical/#caption-side) spec mentions `block-start` | `block-end` | `inline-start` | `inline-end` logical values. They are not supported by any browser.

@Loirooriol, browsers can implement `block-start` | `block-end`, placing the caption based on the values of `writing-mode` and `direction` properties.

**Comment by Loirooriol** [comment]
> The [CSS Logical Properties and Values Level 1](https://drafts.csswg.org/css-logical/#caption-side) spec mentions `block-start | block-end | inline-start | inline-end`

No? It mentions `inline-start | inline-end`. And "The existing top and bottom values are idiosyncratically redefined as assigning to the [block-start](https://drafts.csswg.org/css-writing-modes-4/#block-start) and [block-end](https://drafts.csswg.org/css-writing-modes-4/#block-end) sides of the table, respectively". So there is no need to add `block-start` and `block-end` synonyms.

**Comment by ramiy** [comment]
> * CSS properties that have no logical equivalence. For example, `background-position-x` and `background-position-y`. Or the CSS `<position>` data-type values which supports only physical values.

See [CSS Backgrounds Module Level 4](https://drafts.csswg.org/css-backgrounds-4/) spec which adds support for `background-position-inline` and `background-position-block` properties.

**Comment by foolip** [comment]
Thank you for proposing CSS Logical Properties and Values for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
