### ISSUE TITLE
import attributes / JSON modules / CSS modules

### ISSUE THREAD

**Issue by o-t-w** [web-platform-tests/interop#436]
### Description

Import attributes are a way to import JSON modules and CSS modules in JavaScript.

### Specification

https://github.com/tc39/proposal-import-attributes

### Open Issues

https://github.com/whatwg/html/issues/7233
There is an [open PR](https://github.com/whatwg/html/pull/9486) that would close this issue. 

### Tests

https://wpt.fyi/results/html/semantics/scripting-1/the-script-element?label=master&label=experimental&aligned&q=%28import-attributes%20or%20json%20or%20css%29%20and%20not%20assertions

### Current Implementations

- [X] Blink
- [ ] Gecko
- [X] WebKit

### Standards Positions

Safari Technology Preview supports import attributes and JSON modules. 
WebKit position on [CSS module scripts](https://github.com/WebKit/standards-positions/issues/77)

Chrome Canary is [currently updating](https://bugs.chromium.org/p/v8/issues/detail?id=13856#c11) the import attribute syntax from import assertions. 

Gecko standards position on [CSS modules](https://github.com/mozilla/standards-positions/issues/541)

### Browser bug reports

[Gecko bug for import attributes](https://bugzilla.mozilla.org/show_bug.cgi?id=1736059). 
[Gecko bug for CSS modules scripts](https://bugzilla.mozilla.org/show_bug.cgi?id=1720570) 

### Developer discussions

This Tweet has almost 900 likes https://x.com/mattpocockuk/status/1694679999117246640?s=20

### Accessibility Impact

No impact.

### Privacy Impact

No impact.

**Comment by gsnedders** [comment]
> ### Tests
> https://wpt.fyi/results/html/semantics/scripting-1/the-script-element/css-module?label=experimental&label=master&aligned

maybe something more like https://wpt.fyi/results/html/semantics/scripting-1/the-script-element?label=master&label=experimental&aligned&q=%28import-attributes%20or%20json%20or%20css%29%20and%20not%20assertions?

**Comment by zcorpan** [comment]
Can we split this into JSON modules and CSS modules?

**Comment by gsnedders** [comment]
> Can we split this into JSON modules and CSS modules?

And let's include the basic import attributes tests in both, because if both get accepted we'll presumably merge them into a single focus area. (And if we don't, we can figure out how to deal with the scoring later!)

**Comment by dandclark** [comment]
Per the Interop Team discussion earlier today, I've filed these two issues to track JSON and CSS modules separately during proposal selection, including the import attributes tests in both:
https://github.com/web-platform-tests/interop/issues/596
https://github.com/web-platform-tests/interop/issues/597

Closing out this issue since it will be tracked in #596 and #597 going forward.
