### ISSUE TITLE
css fill/stroke

### ISSUE THREAD

**Issue by jsnkuhn** [web-platform-tests/interop#440]
### Description

This would include adding filling and stroking of text which it new to Level 3 of the CSS Fill and Stroke Module

targeted properties would include properties listed under:
`3.3. Fill Paint`
`4.2. Stroke Geometry`
`4.4. Stroke Paint`

### Specification

https://drafts.fxtf.org/fill-stroke/

### Tests

current tests for -webkit prefixed filling/stroking
https://wpt.fyi/results/css?label=master&label=experimental&aligned&q=%2Fcss%2Fcss-fill-stroke

### Current Implementations

- [ ] Blink
- [ ] Gecko
- [ ] WebKit

### Standards Positions

nothing is open on this for gecko or webkit yet

### Browser bug reports

Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1686566

### Developer discussions

article on the current state of stroke text in CSS:
https://blog.logrocket.com/create-beautiful-stroked-text-css/

it's notable that `-webkit-background-clip: text;` is currently in use to mimic the the functionality of `fill-image`. But is not a very good solution for this as it clips off anything outside the bounds of the text (text-shadows, filter: drop-shadow(), etc ). 

### Existing Usage

most of the existing -webkit prefixed properties don't seem to be tracked on Chrome Platform Status

-webkit-text-fill: https://chromestatus.com/metrics/css/timeline/popularity/321

### Workarounds

The original -webkit spec that is overwhelmingly supported including `-webkit-text-stroke` and `-webkit-text-fill` 
https://compat.spec.whatwg.org/#text-fill-and-stroking

**Comment by meyerweb** [comment]
Should WebKit and Gecko be checked in the “Current Implementations” section?

**Comment by jsnkuhn** [comment]
I wasn't really sure what to do there when filling this out. It almost seems like none of them should be checked? If what we're talking about here is specifically `fill-stroke-3` support then probably there is no support at all. All existing support seems to be for https://compat.spec.whatwg.org/#text-fill-and-stroking . There also doesn't seem to be a fill-stroke-1 or fill-stroke-2 that I can find?? Was that all specific to SVG at the time?

**Comment by bkardell** [comment]
Thank you for proposing css fill/stroke for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

As of the deadline, the specifications for css fill/stroke were not yet complete enough to allow interoperable implementations. To make progress on this area in the future, it will first be necessary to ensure that the feature has a clear specification in a standards track document.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
