### ISSUE TITLE
Viewport-Percentage Lengths in WebViews and In App Browsers

### ISSUE THREAD

**Issue by johannesodland** [web-platform-tests/interop#444]
### Description

The new viewport units lv*, sv*, and dv* were one of the focus areas during Interop 2022. While Interop claims 100% interoperability for main browsers, it doesn't account for WebViews and In App Browsers. With a significant portion of users accessing websites via apps like Facebook, Instagram, and Slack, these viewport units pose inconsistencies. This proposal seeks investigation into improving tests or configurations to address these challenges.

### Rationale

Viewport units have been a longstanding challenge. With the introduction of new viewport units and the achievement of 100% support in main browsers, the inconsistent support in WebViews and In App Browsers has become the primary obstacle to full adaptation.

Issues indicating this inconsistency include:

- https://bugs.webkit.org/show_bug.cgi?id=255708
- https://bugs.webkit.org/show_bug.cgi?id=255852
- https://bugs.webkit.org/show_bug.cgi?id=250621
- https://github.com/mozilla-mobile/firefox-ios/issues/8819
- https://github.com/mozilla-mobile/firefox-ios/issues/11574

### Investigation Roadmap

1. Examine Support: Review support for new viewport units across WebViews and In App Browsers.
2. Discuss with Implementers: Engage with WebView and IAB developers to understand the challenges faced.
3. Explore Testing: Evaluate methods to test these platforms, even if integration into WPT seems unlikely.
4. Propose Solutions: Recommend potential solutions based on the investigation's findings.

**Comment by jensimmons** [comment]
Is this only about inconsistencies on iOS, or is there a cross-platform aspect to the proposed investigation?

**Comment by johannesodland** [comment]
I'm sure there's a cross-platform aspect here. 
We just tested David Bokan's test page on a Chrome Custom Tab on Android (Using Slack), and saw that the vh and lvh units were mutated when the browser chrome retracted: 

https://bugs.chromium.org/p/chromium/issues/detail?id=1488356

**Comment by foolip** [comment]
Thank you for proposing this investigation effort for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year. Thank you for raising the inconsistencies with viewport units in this proposal. However, we would like to focus on test infrastructure for mobile browsers before expanding our scope to WebViews in-app browsers. We would welcome this proposal being resubmitted next year if the issues persist.

For an overview of our process, see the [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you for contributing to Interop 2024!

_Posted on behalf of the Interop team._
