### ISSUE TITLE
Bar for spec maturity

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#445]
In https://github.com/web-platform-tests/interop/issues/429#issuecomment-1722304944 @gsnedders commented:

> To note: CSS Box Level 4 doesn't currently meet the bar we set for spec maturity; it is yet to be published as a CR, and per the CSS WG policy, ["should not be released broadly for general use"](https://www.w3.org/TR/CSS/#experimental).

I'm filing this issue to discuss the bar within the interop team.

Our [issue template](https://github.com/web-platform-tests/interop/blob/main/.github/ISSUE_TEMPLATE/focus-area-proposal.yml) asks only for Recommendation Track for W3C specs, which I take to mean FPWD.

https://github.com/web-platform-tests/interop#requirements-for-focus-area-proposals says only "mature-enough".

**Comment by gsnedders** [comment]
I don't think there's any need to have this on the agenda? I think I've mixed up what we concluded this year versus what we did in some prior year?

(We can totally discuss it, but "Sam mixed things up" isn't a super exciting discussion!)

**Comment by gsnedders** [comment]
FYI: I've gone through and edited (largely to strikethrough, but also correct) my prior comments, plus hidden them as "resolved".

**Comment by foolip** [comment]
Thanks Sam! We never elaborated beyond "Recommendation Track" in writing, so it's no surprise different interpretations are possible. I'll resolve this and remove the agenda label.
