### ISSUE TITLE
Accessibility Testing Investigation Area Report

### ISSUE THREAD

**Issue by boazsender** [web-platform-tests/interop#459]
Opening this issue to share what's been accomplished and make the case for continuing this work in 2024.

## What's been accomplished
Here's a link to the [Accessibility Testing Investigation Area Roadmap](https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/3) if you'd like to browse the details. In summary:

* We wrote the initial infrastructure for accessibility testing in WPT
* Gecko implemented support for computed role/label (matching prior implementations in Chrome and WebKit)
* We wrote [over 500 new automated accessibility tests](https://wpt.fyi/results/?label=master&label=experimental&aligned&q=label%3Aaccessibility) so far, and are still working.
* We are in the process of extending WPT test capabilities (see AOM [#197](https://github.com/WICG/aom/issues/197) and [#203](https://github.com/WICG/aom/issues/203)) to allow more direct access to browser accessibility internals
* We are in the process of making new testing utility for [accessibility tree dumping](https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/51), and using that to write new WPTs that are not currently possible. This is being done in the chromium repo as an experiment for now with an eye toward taking learnings from that and implementing something in WPT.

## What's coming in 2024
There are a couple of trains heading toward accessibility testing tools in WPT in 2024:

1. We have talked about continuing the tree dump research from 2023, and upstreaming it to WPT. In order to do this we'll need to map between tree dump interfaces in other engines. There's also a nascent conversation starting in the AOM WICG about standardizing parts of the accessibility tree which would bolster this work. Emphasis on *parts*.
2. There is a new [proposal for a WebDriver accessibility extension](https://github.com/WICG/aom/issues/203) which we think will gain traction next year.
4. [AT-driver](https://w3c.github.io/at-driver/) is being chartered into BTT, and the integration with browsers is being sharpened quite a bit. This was an option that was decided against by the Investigation Area team at the beginning of 2023, but may become relevant again in 2024.

These are all trains that we should be tracking and integrating into WPT in order to be able to more effectively conformance test accessibility on the web so that we can drive web accessibility interop in future years.

## Other 2024 thoughts
It would also make sense to start a focus area in 2024 based on the output of the 2023 Investigation Area in order to convert the value of the 2023 investigation area into interoperability changes to browser engines in 2024.

cc @cookiecrook @chrishtr @howard-e @mzgoddard et al. Please add anything I missed, or any other editorials.

**Comment by zcorpan** [comment]
> It would also make sense to start a focus area in 2024 based on the output of the 2023 Investigation Area in order to convert the value of the 2023 investigation area into interoperability changes to browser engines in 2024.

https://github.com/web-platform-tests/interop/issues/526

**Comment by cookiecrook** [comment]
Agreed that #526 can be a good Focus Area, and that is not mutually exclusive with a follow-on Investigation.
