### ISSUE TITLE
Carryover evaluation: CSS Math Functions

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#462]
Let's evaluate whether to continue the CSS Math Functions focus area in Interop 2024.

Original proposal: https://github.com/web-platform-tests/interop/issues/149 by @ramiy

Tests:
- [All tests](https://wpt.fyi/results/css/css-values?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-mathfunctions)
- [Failing tests](https://wpt.fyi/results/css/css-values?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-mathfunctions%20status%3A%21ok%20status%3A%21pass)

We should also consider whether we should add tests for 2024.

**Comment by foolip** [comment]
Summary of remaining failures:
- Chrome failures due to bugs linked to https://crbug.com/1415303
- Firefox failures tracked by https://bugzilla.mozilla.org/show_bug.cgi?id=1834361 and https://bugzilla.mozilla.org/show_bug.cgi?id=1848385
- Safari failures have no filed bugs AFAICT

**Comment by jgraham** [comment]
Looking at the Firefox failures, one (which is in common with Chrome) seems to be about precision loss in trig functions that should evaluate to exactly 0. My guess is that one is somewhat unlikely to come up in practice (unless using these serialized values in scripts is more common than I expect).

The other one (which is in common with Safari) is about resolving length/percentages inside `calc()`, which, assuming it's something that has real use cases, seems potentially more likely to affect real sites.
