### ISSUE TITLE
Carryover evaluation: CSS Pseudo-classes

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#463]
Let's evaluate whether to continue the CSS Pseudo-classes focus area in Interop 2024.

Original proposals:
- https://github.com/web-platform-tests/interop/issues/135 by @jensimmons
- https://github.com/web-platform-tests/interop/issues/177 by @brandonmcconnell
- https://github.com/web-platform-tests/interop/issues/178 by @brandonmcconnell
- https://github.com/web-platform-tests/interop/issues/225 by @nt1m

Tests:
- [All tests](https://wpt.fyi/results/css/selectors?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-pseudos)
- [Failing tests](https://wpt.fyi/results/css/selectors?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-pseudos%20status%3A%21ok%20status%3A%21pass)

We should also consider whether we should add tests for 2024.

**Comment by dbaron** [comment]
For what it's worth, I'm adding quite a few tests for `:dir()` as part of https://crbug.com/576815 (though unfortunately the linked WPT PRs are 3 clicks away from that -- via the different chromium-review.googlesource.com links and a comment by the export bot that links to the WPT PR), which I expect will show a bunch of bugs in other engines.  There's also some ongoing related spec work, mostly to specify the behavior described in https://github.com/whatwg/html/issues/3699#issuecomment-951423468 via https://github.com/whatwg/html/pull/9554 / https://github.com/whatwg/html/pull/9166 / etc.  (That said, it's not super-clear how important those bugs are relative to the demand for the original feature, though it may depend on what they are.)
