### ISSUE TITLE
CSS image() function

### ISSUE THREAD

**Issue by jsnkuhn** [web-platform-tests/interop#465]
### Description

>The image() function allows an author to:

>-  use [media fragments](https://www.w3.org/TR/media-frags/) to clip out a portion of an image
>- use a solid color as an image
>- fallback to a solid-color image, when the image at the specified url can’t be downloaded or decoded
>- automatically respect the image orientation specified in the image’s metadata

spec fixes many long standing issues with CSS images:

- a simplified syntax for image spriting that doesn't require 3 different CSS properties: `background-image: image('sprites.svg#xywh=40,0,20,20');`. This is a similar syntax as is used in `object-view-box`. Would be wonderful to finally have parity for background and foreground images. This also opens up the use of background-size and background-position for actual sizing and positioning of these images instead of dealing with the spriting.

- ability to create a solid color image like this: background-image: image(red); instead of hacking a gradient like this: linear-gradient(red, red). Is good for devs because it's less repetition in the code and for browser vendors i'm guessing this would allow a path to a separate algorithm for just rendering a solid colored image.

- Proper image fall-backs which url() can't do. When the image at the specified url can’t be downloaded or decoded, fallback to another image or color. This could lead to less background colors that are never seen being painted behind images.

- automatically respect the image orientation specified in the image’s metadata.

FYI: the above are all from images-4 but the CSSWG is already looking at expanding image() in images-5 for things like background video (https://github.com/w3c/csswg-drafts/issues/6732) and @image-manipulation (https://github.com/w3c/csswg-drafts/issues/6807)

more detailed explainer: https://12daysofweb.dev/2022/css-image/

### Specification

https://drafts.csswg.org/css-images-4/#image-notation

### Open Issues

There do not appear to be any issues open with the CSSWG specifically about image()

### Tests

https://wpt.fyi/results/?label=master&label=experimental&aligned&view=subtest&q=css-image-fallbacks

- only 5 tests right now all seems to be about "Solid-color Images" and "Image Fallbacks"
- linked bug for chrome is about image-set() not image() - https://bugs.chromium.org/p/chromium/issues/detail?id=630597

### Current Implementations

- [ ] Blink
- [ ] Gecko
- [ ] WebKit

### Standards Positions

Mozilla: https://github.com/mozilla/standards-positions/issues/856

### Browser bug reports

Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=703217
chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=254753#c_ts1639769079
webkit bug: https://bugs.webkit.org/show_bug.cgi?id=72584

(looks like in webkit and firefox put in a considerable amount of work towards this in the early 2010s but then was just abandoned?)

### Polls & Surveys

https://2023.stateofcss.com/en-US/features/

are aware: 2876
have used: 1418

![image](https://github.com/web-platform-tests/interop/assets/1286791/c7414115-7f0c-427a-9ee2-17b9391937bd)

1158 added it to their reading list. That's the 10 most added property

![image](https://github.com/web-platform-tests/interop/assets/1286791/3da8501a-11b1-499a-98e7-ea3d9ce3c691)

### Workarounds

There is a postCSS plugin for `image(<color>)`
https://github.com/valtlai/postcss-color-image

**Comment by dandclark** [comment]
Thank you for proposing CSS image() function for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

We could not find any tests for CSS image() function in the Web Platform Tests.  Such tests are crucial for measuring interoperability status and progress.  Once there are WPT entries covering this proposal, we welcome it being resubmitted for a future round of Interop.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
