### ISSUE TITLE
Carryover evaluation: WebCodecs (video)

### ISSUE THREAD

**Issue by nairnandu** [web-platform-tests/interop#468]
To evaluate continuation of the Web Codecs (video) focus area in Interop 2024

Original proposal:

- https://github.com/web-platform-tests/interop/issues/175

Labeled tests (2023):

- [All tests](https://wpt.fyi/results/webcodecs?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-webcodecs)
- [Failing tests](https://wpt.fyi/results/webcodecs?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-webcodecs%20status%3A%21ok%20status%3A%21pass)

Also consider the possibility of adding new tests in 2024

**Comment by dalecurtis** [comment]
If we're proposing new tests I'd suggest we add all other tests in the directory. Effectively:
- ImageDecoder (#1 by usage)
- AudioDecoder (#3 by usage)
- AudioEncoder (#5 by usage)

(VideoDecoder is #2, VideoEncoder is #4)

@padenot @youennf
