### ISSUE TITLE
Carryover evaluation: Subgrid

### ISSUE THREAD

**Issue by nairnandu** [web-platform-tests/interop#470]
To evaluate continuation of the Subgrid focus area in Interop 2024

Original proposal:

- Carried over from 2022

Labeled tests (2023):

- [All tests](https://wpt.fyi/results/css/css-grid/subgrid?label=experimental&label=master&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2022-subgrid)
- [Failing tests](https://wpt.fyi/results/css/css-grid/subgrid?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2022-subgrid%20status%3A%21ok%20status%3A%21pass)

Also consider the possibility of adding new tests in 2024

**Comment by foolip** [comment]
Subgrid continues to be prominent in surveys, this time as no 4 in https://2023.stateofcss.com/en-US/usage/#css_interoperability_features. Also note the unusual number of comments in https://2023.stateofcss.com/en-US/features/layout/#subgrid, 531. One comment that captures the spirit is "I am waiting for Chrome and Edge to support it." It's coming in Chrome/Edge 117.

For such a highly anticipated feature I think it makes sense to ensure it's interoperable in depth, so I hope a Subgrid expert can check the remaining [test failures](https://wpt.fyi/results/css/css-grid/subgrid?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2022-subgrid%20status%3A%21ok%20status%3A%21pass) and evaluate whether they are important.

All of the [unlabeled tests](https://wpt.fyi/results/css/css-grid/subgrid?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2022-subgrid) are passing anywhere, so there are no existing tests for scope expansion.

**Comment by foolip** [comment]
For survey data and web developer demand, in [preliminary results from State of HTML 2023](https://github.com/web-platform-tests/interop/issues/550), Subgrid was a fairly common response to the question "Which existing HTML features or browser APIs are you unable to use because of browser differences or lack of support?"

To answer Subgrid was to ignore the scope of the question, but it says something about the demand for Subgrid.
