### ISSUE TITLE
Carryover evaluation: Scrolling

### ISSUE THREAD

**Issue by nairnandu** [web-platform-tests/interop#471]
To evaluate continuation of the Scrolling focus area in Interop 2024

Original proposal:

- https://github.com/web-platform-tests/interop/issues/21
- Carried over from 2022

Labeled tests (2023):

- [All tests](https://wpt.fyi/results/css?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2022-scrolling)
- [Failing tests](https://wpt.fyi/results/css?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2022-scrolling%20status%3A%21ok%20status%3A%21pass)

Also consider the possibility of adding new tests in 2024

**Comment by foolip** [comment]
We should consider the overlap between this and https://github.com/web-platform-tests/interop/issues/492 filed by @johannesodland.

There are a lot of [unlabeled tests](https://wpt.fyi/results/css/css-scroll-snap?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2022-scrolling) for scroll snap to consider.

**Comment by brunostasse** [comment]
I strongly recommend that scrolling be carried over.

There are still plenty of interoperability issues in this area. To point to a few in WebKit:

Body scrolling which cannot be reliably prevented (mentioned before interop 2023):
- https://github.com/web-platform-tests/interop/issues/84
- https://bugs.webkit.org/show_bug.cgi?id=240860
- https://bugs.webkit.org/show_bug.cgi?id=240859

Issues with CSS pointer-events:
- https://wpt.fyi/results/pointerevents/pointerevent_hit_test_scroll_visible_descendant.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-events
- https://bugs.webkit.org/show_bug.cgi?id=258255
- https://bugs.webkit.org/show_bug.cgi?id=183870
Working in Firefox, fixed recently in Chromium (although not fully) and broken in WebKit.

Other issues related to touch/pointer events, overscroll and scroll-snap:
- https://bugs.webkit.org/show_bug.cgi?id=251513
- https://bugs.webkit.org/show_bug.cgi?id=240183
- https://bugs.webkit.org/show_bug.cgi?id=240235
- https://bugs.webkit.org/show_bug.cgi?id=236536
- https://bugs.webkit.org/show_bug.cgi?id=253080
- https://bugs.webkit.org/show_bug.cgi?id=240241

**Comment by johannesodland** [comment]
Issue #492 was closed in favor of this issue, so I'm pasting over a list of scroll-snap bugs from that issue. I doubt that these bugs are covered by WPT as most occur on mobile devices – related to the dynamic mobile viewport, gestures such as scroll-to-top, search, screen readers and so on.

I hope these bugs can be included in Interop 2024, or that an effort can be made to investigate how one can improve test coverage for these kinds of issues.

This is not a complete list of bugs, but a list of issues I'm aware of or found through a quick search.

https://bugs.webkit.org/show_bug.cgi?id=251003
https://bugs.webkit.org/show_bug.cgi?id=218709
https://bugs.webkit.org/show_bug.cgi?id=245722
https://bugs.webkit.org/show_bug.cgi?id=253056
https://bugs.webkit.org/show_bug.cgi?id=255592
https://bugs.webkit.org/show_bug.cgi?id=255592
https://bugs.chromium.org/p/chromium/issues/detail?id=953285
https://bugs.chromium.org/p/chromium/issues/detail?id=1404006
https://bugs.chromium.org/p/chromium/issues/detail?id=1245459
https://bugs.chromium.org/p/chromium/issues/detail?id=1154509
https://bugs.chromium.org/p/chromium/issues/detail?id=1423359
https://bugzilla.mozilla.org/show_bug.cgi?id=1848917

**Comment by denvercoder21** [comment]
This came to our attention recently and probably belongs here as well.

https://bugzilla.mozilla.org/show_bug.cgi?id=1857898

**Comment by foolip** [comment]
Here's a wpt.fyi view of the proposed test expansion in https://github.com/web-platform-tests/interop/issues/471#issuecomment-1759542740:

https://wpt.fyi/results/css/css-scroll-snap?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=path%3A%2Fcss%2Fcss-scroll-snap%2Fscroll-target-align-001.html%20or%20path%3A%2Fcss%2Fcss-scroll-snap%2Fscroll-target-align-002.html%20or%20path%3A%2Fcss%2Fcss-scroll-snap%2Fscroll-target-snap-001.html%20or%20path%3A%2Fcss%2Fcss-scroll-snap%2Fscroll-target-snap-002.html%20or%20path%3A%2Fcss%2Fcss-scroll-snap%2Finput%2Fsnap-area-overflow-boundary.html%20or%20path%3A%2Fcss%2Fcss-scroll-snap%2Foverflowing-snap-areas.html%20or%20path%3A%2Fcss%2Fcss-scroll-snap%2Foverscroll-snap.html%20or%20path%3A%2Fcss%2Fcss-scroll-snap%2Fscroll-on-large-element-not-covering-snapport.tentative.html%20or%20path%3A%2Fcss%2Fcss-scroll-snap%2Fscroll-snap-nested-snap-area-layout-changed.html%20or%20path%3A%2Fcss%2Fcss-scroll-snap%2Fscroll-snap-stop-002.html%20or%20path%3A%2Fcss%2Fcss-scroll-snap%2Fsnap-after-relayout%2Fchanging-scroll-snap-align.html%20or%20path%3A%2Fcss%2Fcss-scroll-snap%2Fsnap-into-covering-area.html
