### ISSUE TITLE
Carryover evaluation: Pointer and Mouse events

### ISSUE THREAD

**Issue by nairnandu** [web-platform-tests/interop#472]
To evaluate continuation of the Pointer & Mouse events focus area in Interop 2024

Original proposal:

- https://github.com/web-platform-tests/interop/issues/202

Labeled tests (2023):

- [All tests](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-events)
- [Failing tests](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-events%20status%3A%21ok%20status%3A%21pass)

Also consider the possibility of adding new tests in 2024

**Comment by foolip** [comment]
cc @hvanops @mustaqahmed

**Comment by foolip** [comment]
For reference, tests that aren't labeled, to consider for scope expansion:
- [/uievents/mouse/](https://wpt.fyi/results/uievents/mouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events)
- [/pointerevents/](https://wpt.fyi/results/pointerevents?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events)

**Comment by hsinyi** [comment]
cc @smaug----  @EdgarChen

**Comment by mustaqahmed** [comment]
Here is a snapshot of @foolip's queries above, where I have marked 29 out of 94 PointerEvents test for 2024:
- [Interop 2024 Proposed WPTs: Pointer and Mouse events](https://docs.google.com/spreadsheets/d/1GVqvTfRBh_film7kzMflCSJjIkq1TV4mRcPoldNSK1Q/edit?usp=sharing)

@graouts @EdgarChen @smaug---- Please add your suggestions and comments in columns E-G there. 
 You can add new test names at the bottom too, just ignore the warning I added to prevent accidental edits.

**Comment by foolip** [comment]
Thank you @mustaqahmed!

**Comment by mustaqahmed** [comment]
@masayuki-nakano I am seeing a new failing WPT on all browsers: [dashboard](https://wpt.fyi/results/uievents/mouse?label=master&label=experimental&aligned&q=synthetic-mouse-enter-leave-over-out-button-state-after-target-removed.tentative)

Do you think we can add it to the [spreadsheet above](https://github.com/web-platform-tests/interop/issues/472#issuecomment-1747617702) for Interop 2024?  I am asking because I don't know why this test is marked as "tentative".

(Here is the Chrome [bug](https://crbug.com/1495467) for the failure.)

**Comment by aprotyas** [comment]
cc @nt1m @gsnedders @jensimmons

**Comment by nt1m** [comment]
> Here is a snapshot of @foolip's queries above, where I have marked 29 out of 94 PointerEvents test for 2024:
> 
> * [Interop 2024 Proposed WPTs: Pointer and Mouse events](https://docs.google.com/spreadsheets/d/1GVqvTfRBh_film7kzMflCSJjIkq1TV4mRcPoldNSK1Q/edit?usp=sharing)
> 
> @graouts @EdgarChen @smaug---- Please add your suggestions and comments in columns E-G there. You can add new test names at the bottom too, just ignore the warning I added to prevent accidental edits.

A general comment on the spreadsheet is that we should not include tests for touch events in Interop 2024. We do not have the right infrastructure to test touch input. At least for Safari, it doesn't really make sense to test touch on a platform that does not support for touch (macOS).

**Comment by gsnedders** [comment]
Likewise for pen input. There is no user or web developer need for Safari on macOS to support touch/pen input when macOS itself does not support touch or pen input.

**Comment by mustaqahmed** [comment]
@nt1m and @gsnedders: based on your feedback, I excluded all tests that require touch/pen input.  If you have any other suggestions, please comment in Column F.

After this update, our [spreadsheet](https://docs.google.com/spreadsheets/d/1GVqvTfRBh_film7kzMflCSJjIkq1TV4mRcPoldNSK1Q/edit?usp=sharing) currently has 25 tests marked with `#include`: 23 in the first tab (for Pointer Events) plus 2 in the second tab (for Mouse Events).

**Comment by nairnandu** [comment]
To summarize, these are the proposed additions. @jgraham @zcorpan @gsnedders @nt1m could you review?

1. [coalesced_events_attributes_under_load.https.html?mouse](https://wpt.fyi/results/pointerevents/coalesced_events_attributes_under_load.https.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
2. [coalesced_events_attributes.html?mouse](https://wpt.fyi/results/pointerevents/coalesced_events_attributes.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
3. [idlharness.window.html](https://wpt.fyi/results/pointerevents/idlharness.window.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
4. [mouse-pointer-boundary-events-for-shadowdom.html](https://wpt.fyi/results/pointerevents/mouse-pointer-boundary-events-for-shadowdom.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
5. [pointerevent_after_target_appended.html?mouse](https://wpt.fyi/results/pointerevents/pointerevent_after_target_appended.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
6. [pointerevent_attributes_hoverable_rightbutton.html?mouse](https://wpt.fyi/results/pointerevents/pointerevent_attributes_hoverable_rightbutton.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
7. [pointerevent_auxclick_is_a_pointerevent.html?mouse](https://wpt.fyi/results/pointerevents/pointerevent_auxclick_is_a_pointerevent.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
8. [pointerevent_boundary_events_at_implicit_release_hoverable_pointers.html](https://wpt.fyi/results/pointerevents/pointerevent_boundary_events_at_implicit_release_hoverable_pointers.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
9. [pointerevent_capture_suppressing_mouse.html](https://wpt.fyi/results/pointerevents/pointerevent_capture_suppressing_mouse.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
10. [pointerevent_click_during_capture.html](https://wpt.fyi/results/pointerevents/pointerevent_click_during_capture.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
11. [pointerevent_click_is_a_pointerevent_multiple_clicks.html?mouse](https://wpt.fyi/results/pointerevents/pointerevent_click_is_a_pointerevent_multiple_clicks.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
12. [pointerevent_click_is_a_pointerevent.html?mouse](https://wpt.fyi/results/pointerevents/pointerevent_click_is_a_pointerevent.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
13. [pointerevent_constructor.html](https://wpt.fyi/results/pointerevents/pointerevent_constructor.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
14. [pointerevent_contextmenu_is_a_pointerevent.html?mouse](https://wpt.fyi/results/pointerevents/pointerevent_contextmenu_is_a_pointerevent.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
15. [pointerevent_fractional_coordinates.html?mouse](https://wpt.fyi/results/pointerevents/pointerevent_fractional_coordinates.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
16. [pointerevent_mouse_capture_change_hover.html](https://wpt.fyi/results/pointerevents/pointerevent_mouse_capture_change_hover.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
17. [pointerevent_mouse_pointercapture_inactivate_pointer.html](https://wpt.fyi/results/pointerevents/pointerevent_mouse_pointercapture_inactivate_pointer.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
18. [pointerevent_pointermove_on_chorded_mouse_button.html](https://wpt.fyi/results/pointerevents/pointerevent_pointermove_on_chorded_mouse_button.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
19. [pointerevent_pointerout_no_pointer_movement.html](https://wpt.fyi/results/pointerevents/pointerevent_pointerout_no_pointer_movement.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
20. [pointerevent_releasepointercapture_events_to_original_target.html?mouse](https://wpt.fyi/results/pointerevents/pointerevent_releasepointercapture_events_to_original_target.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
21. [pointerevent_sequence_at_implicit_release_on_click.html?mouse](https://wpt.fyi/results/pointerevents/pointerevent_sequence_at_implicit_release_on_click.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
22. [pointerevent_touch-action-keyboard.html](https://wpt.fyi/results/pointerevents/pointerevent_touch-action-keyboard.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
23. [predicted_events_attributes.html?mouse](https://wpt.fyi/results/pointerevents/predicted_events_attributes.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
24. [synthetic-mouse-enter-leave-over-out-button-state-after-target-removed.tentative.html?buttonType=LEFT&button=0&buttons=1](https://wpt.fyi/results/uievents/mouse/synthetic-mouse-enter-leave-over-out-button-state-after-target-removed.tentative.html%3FbuttonType%3DLEFT%26button%3D0%26buttons%3D1?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events)
25. [synthetic-mouse-enter-leave-over-out-button-state-after-target-removed.tentative.html?buttonType=MIDDLE&button=1&buttons=4](https://wpt.fyi/results/uievents/mouse/synthetic-mouse-enter-leave-over-out-button-state-after-target-removed.tentative.html%3FbuttonType%3DMIDDLE%26button%3D1%26buttons%3D4?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events)

**Comment by nt1m** [comment]
@nairnandu The carryover spreadsheet didn't mention any new scope for this focus area (it said "Carryover full scope", not "Carryover with new scope").

**Comment by nairnandu** [comment]
I don't believe we discussed this additional scope in our carryover evaluation.

**Comment by jgraham** [comment]
Note that although this issue is closed, the scope discussion is now happening in https://github.com/web-platform-tests/interop/issues/628
