### ISSUE TITLE
Carryover evaluation: Custom Properties

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#477]
Let's evaluate whether to continue the Custom Properties focus area in Interop 2024.

Original proposal: https://github.com/web-platform-tests/interop/issues/158 by @Afif13

Tests:
- [All tests](https://wpt.fyi/results/css/css-properties-values-api?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-property)
- [Failing tests](https://wpt.fyi/results/css/css-properties-values-api?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-property%20status%3A%21ok%20status%3A%21pass)

We should also consider whether we should add tests for 2024.

**Comment by foolip** [comment]
The remaining failures here are in Firefox and are linked to https://bugzilla.mozilla.org/show_bug.cgi?id=1684605 and https://bugzilla.mozilla.org/show_bug.cgi?id=1821552

**Comment by jgraham** [comment]
I believe this is actively being worked on in Gecko. Clearly in the current state it should be carried over, but I think it's likely the situation will change before the end of the year. @emilio might have more information.
