### ISSUE TITLE
Carryover evaluation: Font Feature Detection and Palettes

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#479]
Let's evaluate whether to continue the Font Feature Detection and Palettes focus area in Interop 2024.

Original proposal: https://github.com/web-platform-tests/interop/issues/164 by @drott

Tests:
- [All tests](https://wpt.fyi/results/css?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-fonts)
- [Failing tests](https://wpt.fyi/results/css?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-fonts%20status%3A%21ok%20status%3A%21pass)

We should also consider whether we should add tests for 2024.

**Comment by drott** [comment]
What are the criteria for deciding on a continuation? Since we reached a high interop value of almost 100% it seems to be intuitively that this category has served its purpose? I'd be happy to extend interop work to specific color font support such as COLRv1 (which is in FF and Blink based browsers) - but I am not sure we can find consensus for that in the Interop forums?

**Comment by jensimmons** [comment]
We are simply opening an issue for every current area to debate whether/not to carry it over to 2024. You are correct @drott that this is almost at 100%, and therefore should probably be retired! Yay!

 Of course, people might have other ideas, and this is the place to express them.

**Comment by drott** [comment]
Thinking about this more, my suggestion would be to revive and edit this topic to cover font-palette animation. We've just merged two new tests covering this in https://github.com/web-platform-tests/wpt/pull/42187 

* css/css-fonts/animations/font-palette-interpolation.html
* css/css-fonts/palette-mix-computed.html

CC @tursunova
