### ISSUE TITLE
Carryover evaluation: Forms

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#480]
Let's evaluate whether to continue the Forms focus area in Interop 2024.

Original proposal: https://github.com/web-platform-tests/interop/issues/11 by @mfreed7 

Tests:
- [All tests](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2022-forms%20or%20label%3Ainterop-2023-forms)
- [Failing tests](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%28label%3Ainterop-2022-forms%20or%20label%3Ainterop-2023-forms%29%20status%3A%21ok%20status%3A%21pass)

We should also consider whether we should add tests for 2024.

**Comment by jgraham** [comment]
So gecko has two remaining failures here. One is [Bug 1685926](https://bugzilla.mozilla.org/show_bug.cgi?id=1685926), which is in the process of being fixed and the other is [Bug 1825222](https://bugzilla.mozilla.org/show_bug.cgi?id=1825222) which is about how form restoration interacts with bfcache, which is arguably not an interop issue.

**Comment by mfreed7** [comment]
Chromium similarly only has a few failures left from the original list. Indeed all browsers made great progress on the original list. Nice work!

The main area of interop that still remains from that list looks like vertical writing modes. Would folks agree? Perhaps we should keep at least that area going for Interop 2024? I don't know if there are additional things from [@josepharhar 's original list](https://github.com/web-platform-tests/interop/issues/11#issuecomment-976047408) that didn't make it into the official 2023 list? Perhaps we could include those also?
