### ISSUE TITLE
Carryover evaluation: Grid

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#481]
Let's evaluate whether to continue the Grid focus area in Interop 2024.

Original proposals:
- https://github.com/web-platform-tests/interop/issues/2 by @chrishtr
- https://github.com/web-platform-tests/interop/issues/242 by @bfgeek

Tests:
- [All tests](https://wpt.fyi/results/css/css-grid?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2021-grid%20or%20label%3Ainterop-2023-grid)
- [Failing tests](https://wpt.fyi/results/css/css-grid?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%28label%3Ainterop-2021-grid%20or%20label%3Ainterop-2023-grid%29%20status%3A%21ok%20status%3A%21pass)

We should also consider whether we should add tests for 2024.

**Comment by jgraham** [comment]
I think we should be aware that https://wpt.fyi/interop-2023?feature=interop-2023-grid shows basically zero change over 2023 so far. 

I'm not claiming that means we shouldn't carry it over — its certainly an important feature — just noting that this seems like a case where being in Interop 2023 doesn't seem to have had much effect so far. Maybe it will by the end of the year.

**Comment by bfgeek** [comment]
FWIW see see many Firefox specific failures related to: https://bugzilla.mozilla.org/show_bug.cgi?id=1300366 still (and a number of the testcases in this suite are related to this).
