### ISSUE TITLE
Carryover evaluation: Inert

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#483]
Let's evaluate whether to continue the Inert focus area in Interop 2024.

Original proposal: https://github.com/web-platform-tests/interop/issues/135 by @jensimmons 

Tests:
- [All tests](https://wpt.fyi/results/inert?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-inert)
- [Failing tests](https://wpt.fyi/results/inert?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-inert%20status%3A%21ok%20status%3A%21pass) (none!)

We should also consider whether we should add tests for 2024.

**Comment by jgraham** [comment]
It seems like there's one test that's been added here: https://wpt.fyi/results/inert/inert-inlines-around-selection-range-in-contenteditable.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned
