### ISSUE TITLE
WebM Opus audio codec

### ISSUE THREAD

**Issue by AshleyScirra** [web-platform-tests/interop#484]
### Description

> [!NOTE]
> This proposal is split from #425 which originally proposed video and audio together. This proposal is only for audio, as it has use cases without video, e.g. gaming, music and podcasts.

For many years there has not been a single audio codec that can be relied upon to work in all browsers. Further, proprietary codecs can involve licensing fees that make some uses cases uneconomical, including making it difficult for open source projects to support. This is a major point of interop pain, resulting in having to transcode media files to multiple formats, or use workarounds like codecs implemented in WebAssembly.

I would like to propose that browsers commit to supporting the **Opus audio codec** and the **WebM container**. Opus is a well-specified modern, open, royalty-free codec, and both Opus and WebM already have substantial support across the industry. If all browsers consistently supported Opus across all relevant web media features (video element, audio element, Web Audio, and WebCodecs) then there would finally be one codec that can be relied upon cross-browser for audio support.

Opus support is already nearly there, but while it's ostensibly supported in Safari, it's actually been broken for some time and so cannot be used reliably (see issues [238546](https://bugs.webkit.org/show_bug.cgi?id=238546) and [245428](https://bugs.webkit.org/show_bug.cgi?id=245428)).

According to caniuse, all major browsers already have support for WebM as a container format (barring bugs).

### Specification

Opus is specified by the IETF codec working group. However AFAIK no web-related specification currently mandates support for any specific codecs.

### Tests

It looks like WPT only has tests specifically mentioning Opus for WebCodecs. There are already lots of tests for other APIs like Web Audio; perhaps there should be new tests added which make use of decoding Opus audio in various scenarios with all relevant APIs to ensure robust cross-browser support.

### Current Implementations

- [X] Blink
- [X] Gecko
- [X] WebKit

### Standards Positions

All browsers already have some support for Opus. The only problem there is bugs in Safari that are blocking its use. Further it seems there's a case to update the specification to mandate Opus support.

All browsers already have some support for WebM.

### Browser bug reports

Safari issues for Opus: [238546](https://bugs.webkit.org/show_bug.cgi?id=238546), [245428](https://bugs.webkit.org/show_bug.cgi?id=245428)

### Developer discussions

This has been an important and widely-discussed topic since the introduction of the video element in the late 2000s. Apparently it was originally proposed to require support for Vorbis as the audio codec, but that was replaced with wording along the lines of "there are no known codecs that satisfy all the current players". I am hopeful that the situation has now changed, with nearly-there support for Opus.

Ideally support for Opus could be mandated in the specification, presumably also with WebM as the container. I don't see why not if all browsers have added some degree of support already, and it would give additional confidence to web developers that the codec can be relied upon.

### Workarounds

Transcoding media to multiple formats, or using WebAssembly for codecs. Both have significant downsides (e.g. complexity, cost, performance).

### Accessibility Impact

Users using open-source software may find that media on the web is unavailable if it depends on proprietary codecs that it is infeasible for the open-source project to support.

**Comment by jzern** [comment]
cc @robUx4

**Comment by bdougherty** [comment]
I would also like to see this added to Interop 2024, but with MPEG-4 container support as well.

**Comment by AshleyScirra** [comment]
@bdougherty - I'm not sure what the exact legal status is, but the MPEG-4 container is or at least was patent-encumbered, which may complicate support. This proposal sticks to open container and codec formats to avoid that issue.

**Comment by AshleyScirra** [comment]
FWIW, I tested Safari 17 on iOS and it seems it still does not support WebM Opus in HTML5 audio.

**Comment by othermaciej** [comment]
WebKit doesn't support the WebM container on iOS in currently shipping software. It does on Mac.

I don't think the MPEG-4 container has royalty-bearing patent issues. WebM is not a standard and isn't even on track to be by any SDO so if this is taken up, it would be better to take the standards path.

**Comment by foolip** [comment]
Thank you for proposing WebM Opus audio codec for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
