### ISSUE TITLE
Remove style containment tests

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#487]
### Test List

https://wpt.fyi/results/css/css-contain?label=master&label=experimental&aligned&q=contain-style%20label%3Ainterop-2023-contain
https://wpt.fyi/results/css/css-contain?label=master&label=experimental&aligned&q=counter-scoping%20label%3Ainterop-2023-contain
https://wpt.fyi/results/css/css-contain?label=master&label=experimental&aligned&q=quote%20label%3Ainterop-2023-contain

### Rationale

https://github.com/w3c/csswg-drafts/issues/9212 is open for discussion. This needs clarification in the CSSWG. Also it's unclear to me whether the behavior that is tested is a sensible one, given the complexity required for the implementators. A sensible spec for something like style containment shouldn't be complex to implement.

**Comment by nt1m** [comment]
@danielsakhapov @emilio Can you review for Blink / Gecko?

**Comment by nt1m** [comment]
I think it would make sense to defer style containment from Interop until we have definitions on how it affects other named things:
* view-timeline
* anchor-name
* container-name

etc.

I would like the spec to at least progress to that point, with a model that makes sense.

As it stands now, I'm not sure including style containment is very useful without those defined.

**Comment by danielsakhapov** [comment]
Since the mentioned issue has been resolved, should we close this issue?

**Comment by nt1m** [comment]
I think it's a bit of a late clarification to address this in Interop 2023 (and it seems like no browser currently implements everything correctly either). I would still be in favor of removing the tests in the context of 2023 and having this re-apply for next year.

**Comment by foolip** [comment]
@nt1m I went ahead and added `label:interop-2023-contain` do your search queries to exclude a few tests that aren't in Interop 2023 anyway.

**Comment by foolip** [comment]
Looking through changes to the tests that have happened this year, I find https://github.com/web-platform-tests/wpt/pull/41799, rewriting contain-style-counters-004.html. IIUC the old test was wrong, but since that didn't go through a test change proposal, removing the test is OK if that change on its own makes sense. (I presume that restoring the old test doesn't make sense, otherwise that should be the default outcome in case of disagreement.)
