### ISSUE TITLE
Canvas2D filter and reset

### ISSUE THREAD

**Issue by benjamind** [web-platform-tests/interop#493]
### Description

The Canvas2D `filter` and `reset` functionality are the last two remaining pieces for full cross browser support for the Canvas2D APIs.

https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-reset
https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-filter-dev

The `reset` functionality is of somewhat lesser importance and I don't think it is widely used, but Canvas2D filter support is extremely powerful and needs tests. Currently it is unimplemented in Safari only.

The `filter` functionality is in use by our apps at Adobe, though we are now having to build workarounds.

### Specification

https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-reset

### Current Implementations

- [X] Blink
- [X] Gecko
- [ ] WebKit

### Browser bug reports

https://bugs.webkit.org/show_bug.cgi?id=198416

There is an open PR for over a year, so support for this should be easy to land.

### Workarounds

No good workarounds exist without full re-implementation of the filter functionality in WebGL and juggling of image data between Canvas2D and WebGL contexts to achieve the same effects. As far as I can see no polyfills exist.

**Comment by tomayac** [comment]
FYI, here's a test case for `CanvasRenderingContext2D.filter` for how it _should_ look like: https://canvas-svg-filter.glitch.me/: 

<img width="1366" alt="Screenshot 2023-09-26 at 18 58 31" src="https://github.com/web-platform-tests/interop/assets/145676/626894ab-2108-4a56-a9e1-ff47aace52ea">

**Comment by nt1m** [comment]
Canvas2D reset is shipping in STP fwiw

**Comment by fserb** [comment]
I think it would be more useful to change this from "filter and reset" to "layers (with filter support) and reset", as current WhatWG discussions pointed out that filter support on layers is the agreed path forward by all browsers.

**Comment by foolip** [comment]
@fserb can you link to the WHATWG issue where that's being discussed?

**Comment by foolip** [comment]
Looks like @fserb is out of office, but I found https://github.com/whatwg/html/issues/8476 + https://github.com/whatwg/html/pull/9537.

**Comment by foolip** [comment]
@nairnandu and I have discussed with @fserb to understand the layers suggestion. Google would like to suggest adjusting the scope of this to be layers, which is the agreed-upon way to do filters. The complete test list would be:

- https://wpt.fyi/results/html/canvas/element/layers?label=master&label=experimental&aligned
- https://wpt.fyi/results/html/canvas/element/reset?label=master&label=experimental&aligned
- https://wpt.fyi/results/html/canvas/offscreen/layers?label=master&label=experimental&aligned
- https://wpt.fyi/results/html/canvas/offscreen/reset?label=master&label=experimental&aligned

**Comment by foolip** [comment]
Thank you for proposing Canvas2D filter and reset for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
