### ISSUE TITLE
HTMLVideoElement.requestVideoFrameCallback()

### ISSUE THREAD

**Issue by ydaniv** [web-platform-tests/interop#494]
### Description

"The `requestVideoFrameCallback()` method allows web authors to register a callback that runs in the rendering steps when a new video frame is sent to the compositor. This is intended to allow developers to perform efficient per-video-frame operations on video, such as video processing and painting to a canvas, video analysis, or synchronization with external audio sources."

  -- from [web.dev article](https://web.dev/requestvideoframecallback-rvfc/)

This method enables authors to develop features that are impossible, for some cases, or cumbersome and inefficient at best.

Unfortunately, this is not yet an official W3C spec, and is still only a WICG draft.
However, it has already been shipped in Chrome/Edge and Safari for quite some time.

**Another note**: this spec has been reviewed and approved by TAG: https://github.com/w3ctag/design-reviews/issues/429.

### Specification

https://wicg.github.io/video-rvfc/

### Tests

https://wpt.fyi/results/video-rvfc?label=experimental&label=master&aligned

### Current Implementations

- [X] Blink
- [ ] Gecko
- [X] WebKit

### Standards Positions

Was marked as `ready to add` here: https://github.com/mozilla/standards-positions/issues/250
And also as [`worth prototyping`](https://github.com/mozilla/standards-positions/issues/250#issuecomment-611951175).

### Accessibility Impact

May improve performance and thus more power-friendly.

**Comment by AshleyScirra** [comment]
Also note it's not currently supported in Android WebView: https://bugs.chromium.org/p/chromium/issues/detail?id=1306926

**Comment by zcorpan** [comment]
> Unfortunately, this is not yet an official W3C spec, and is still only a WICG draft.

Is there a plan to move this to a W3C WG/WHATWG?

**Comment by ydaniv** [comment]
> > Unfortunately, this is not yet an official W3C spec, and is still only a WICG draft.
> 
> Is there a plan to move this to a W3C WG/WHATWG?

Good question! @tomayac @tguilbert-google ?

**Comment by tguilbert-google** [comment]
I had plans to add this to the full HTML spec directly, following [this comment](https://github.com/whatwg/html/pull/5332#issuecomment-594184703), but didn't end up working on it.

Is the next step to move this to a W3C WG/WHATWG in order to "graduate" the spec, and then add it to the HTML spec?

**Comment by zcorpan** [comment]
Adding it to HTML is the same as moving to the WHATWG. 👍

**Comment by tguilbert-google** [comment]
Ok, thanks! I will work on this this quarter.

**Comment by dandclark** [comment]
This proposal has been accepted as part of Interop 2024!  On behalf of the entire Interop team, thank you for proposing it.  You’ll be able to track progress on this topic throughout the year via the [Interop 2024 dashboard](https://wpt.fyi/interop-2024).
