### ISSUE TITLE
Top Layer Animations

### ISSUE THREAD

**Issue by josepharhar** [web-platform-tests/interop#495]
### Description

Top Layer Animations is a set of features which makes top layer elements, like `<dialog>`s and elements with the `popover` attribute animatable as they enter and exit the top layer:
- The `transition-behavior` CSS property: https://drafts.csswg.org/css-transitions-2/#transition-behavior-property
- The `overlay` CSS property: https://drafts.csswg.org/css-position-4/#overlay
- The `@starting-style` CSS @ rule: https://drafts.csswg.org/css-transitions-2/#defining-before-change-style-the-starting-style-rule
- Supporting animation of the `display` property: https://drafts.csswg.org/css-display-4/#display-animation

Supporting explainer: https://github.com/chrishtr/rendering/blob/master/entry-exit-animations.md

Now that the popover attribute and dialog element are being implemented and shipped in all browsers, these features are the next step in making them useful for web developers.

### Specification

Multiple W3C CSSWG specs

### Tests

starting-style: https://wpt.fyi/results/css?label=master&label=experimental&aligned&q=starting-style
overlay: https://wpt.fyi/results/css/css-position/overlay
transition-behavior: https://wpt.fyi/results/css/css-transitions/parsing/transition-behavior.html
display animation: https://wpt.fyi/results/css/css-display/animations/display-interpolation.html

### Current Implementations

- [X] Blink
- [ ] Gecko
- [ ] WebKit

### Standards Positions

Gecko:
- https://github.com/mozilla/standards-positions/issues/763
- https://github.com/mozilla/standards-positions/issues/777
- https://github.com/mozilla/standards-positions/issues/833
- https://github.com/mozilla/standards-positions/issues/762

WebKit:
- https://github.com/WebKit/standards-positions/issues/148
- https://github.com/WebKit/standards-positions/issues/169
- https://github.com/WebKit/standards-positions/issues/210
- https://github.com/WebKit/standards-positions/issues/147

### Browser bug reports

No bugs filed yet that I know of

### Existing Usage

transition-behavior: https://chromestatus.com/metrics/css/timeline/popularity/766
starting-style: https://chromestatus.com/metrics/feature/timeline/popularity/4486
overlay: https://chromestatus.com/metrics/css/timeline/popularity/748

**Comment by nt1m** [comment]
This would be easier to assess split up into 4 different proposals.

**Comment by jensimmons** [comment]
@foolip @nairnandu Could you see about your team re-proposing this as four separate proposals, so we can discuss them separately.

**Comment by josepharhar** [comment]
I split this into four proposals:
- https://github.com/web-platform-tests/interop/issues/580
- https://github.com/web-platform-tests/interop/issues/581
- https://github.com/web-platform-tests/interop/issues/582
- https://github.com/web-platform-tests/interop/issues/583

**Comment by o-t-w** [comment]
It's a lot of new concepts just to achieve a relatively simple outcome. I played around with these properties in Canary and found it all a bit overwhelming and confusing tbh. Particularly wanting different transitions for entry and exit seemed overly complex.
