### ISSUE TITLE
font-family keywords

### ISSUE THREAD

**Issue by o-t-w** [web-platform-tests/interop#499]
### Description

Support for specifying a CSS `font-family` using keywords is inconsistent between browsers. 
Safari support `system-ui`, [`ui-serif`, `ui-sans-serif`, `ui-monospace`, and `ui-rounded`](https://fullystacked.net/posts/system-font-deep-dive/).
Other browsers only support `system-ui`. 

Support for [`font-family: emoji`](https://fullystacked.net/posts/using-emoji-on-the-web/) is currently not supported by any browser. Developers have to list out the various system emoji fonts:

```css
 font-family: "Twemoji Mozilla", Apple Color Emoji, "Segoe UI Emoji", "Noto Color Emoji", "EmojiOne Color";
```

Having access to the high-quality fonts available on a users system helps performance as they can be used instead of an `@font-face` request.  
In HTML email, where custom fonts are not supported by many email clients, having access to a wider range of fonts would be highly desirable. 

### Specification

https://drafts.csswg.org/css-fonts-4/#ui-serif-def

### Tests

https://wpt.fyi/results/css/css-fonts?label=master&label=experimental&aligned&q=system

### Current Implementations

- [ ] Blink
- [ ] Gecko
- [X] WebKit

### Browser bug reports

[Chromium bug for `font-family: emoji`](https://bugs.chromium.org/p/chromium/issues/detail?id=1240119&q=&can=5&sort=-modified)
[Broader Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1240117&sort=-modified&q=ui-sans-serif&can=1)
[Gecko bug for ui-serif](https://bugzilla.mozilla.org/show_bug.cgi?id=1598879)
[Gecko bug for ui-monospace](https://bugzilla.mozilla.org/show_bug.cgi?id=1598881)

**Comment by svgeesus** [comment]
Related:

 - https://github.com/w3c/csswg-drafts/issues/9292
 - https://github.com/w3c/csswg-drafts/issues/9407

both of which are trying to clarify, and thus improve interop, on system font families and the newer generic font families

**Comment by svgeesus** [comment]
[Current WPT tests for system fonts](https://wpt.fyi/results/css/css-fonts?label=master&label=experimental&aligned&q=system)

Only `system-ui` is really tested. The CSS Fonts 4 spec also notes

> [ui-serif](https://drafts.csswg.org/css-fonts-4/#valdef-font-family-ui-serif) is not expected to map to any font on platforms without an appropriate system font.

which makes creating a reftest harder

**Comment by drott** [comment]
Didn't we say somewhere that the `emoji` font family keyword is somewhat deprecated now that there is `font-variant-emoji` to express preference for a presentation style? 

ui-serif, ui-monospace, and ui-rounded are somewhat Mac OS specific and are not very well interopable across platforms. That said, on Mac OS they can be supported, but I wonder to what extent they are well defined for the web.

**Comment by drott** [comment]
CC @kojiishi

**Comment by drott** [comment]
> [Current WPT tests for system fonts](https://wpt.fyi/results/css/css-fonts?label=master&label=experimental&aligned&q=system)

From the filtered list that @svgeesus mentioned, from the Chrome side, we're kinda disputing whether the Arabic vs. Urdu and Chinese vs. Japanese system font tests are valid. We need spec clarification on whether the language attribute should be taken into account. Filed as https://github.com/w3c/csswg-drafts/issues/9518

**Comment by svgeesus** [comment]
> Didn't we say somewhere that the `emoji` font family keyword is somewhat deprecated now that there is `font-variant-emoji` to express preference for a presentation style?

Not yet but that does seem to be the general opinion so far

 - https://github.com/w3c/csswg-drafts/issues/9359
 
 On agenda, no resolution yet, good to hear back from implementers

**Comment by dandclark** [comment]
Thank you for proposing font-family keywords for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
