### ISSUE TITLE
Declarative Shadow DOM

### ISSUE THREAD

**Issue by mfreed7** [web-platform-tests/interop#501]
### Description

Declarative Shadow DOM is a declarative API that allows the creation of shadow roots using only HTML and no Javascript. This API allows Web Components that use Shadow DOM to make use of Server-Side Rendering (SSR), to get rendered content on screen quickly without requiring Javascript for shadow root attachment.

### Specification

https://github.com/whatwg/html/pull/5465

### Open Issues

https://github.com/whatwg/dom/issues/831

### Tests

https://wpt.fyi/results/shadow-dom/declarative?label=master&label=experimental&aligned&view=subtest

### Current Implementations

- [X] Blink
- [ ] Gecko
- [X] WebKit

### Standards Positions

This is [implemented and shipped in Blink](https://chromestatus.com/feature/5161240576393216), and [WebKit](https://github.com/WebKit/WebKit/commit/e7d5dde467956b24438d23f458d4d527f7fd108d). Gecko is [positive and implementing](https://github.com/mozilla/standards-positions/issues/335#issuecomment-1714182997).

### Browser bug reports

https://crbug.com/1379513

### Existing Usage

https://chromestatus.com/metrics/feature/timeline/popularity/3196

**Comment by foolip** [comment]
For survey data and web developer demand, in [preliminary results from State of HTML 2023](https://github.com/web-platform-tests/interop/issues/550), Declarative Shadow DOM was a common response to the question "Which existing HTML features or browser APIs are you unable to use because of browser differences or lack of support?"

**Comment by foolip** [comment]
Shadow DOM was also a somewhat common response.

**Comment by mbrodesser-Igalia** [comment]
Be aware that Selection (https://developer.mozilla.org/en-US/docs/Web/API/Selection) works differently in Gecko/Firefox than in other engines, since Gecko supports multiple ranges. Existing issues like https://bugzilla.mozilla.org/show_bug.cgi?id=1455893 in Gecko might become more relevant. They're potentially time-consuming to fix.

**Comment by foolip** [comment]
From State of HTML preliminary results, Declarative Shadow DOM was among the [features that respondents expressed the most interest for](https://github.com/web-platform-tests/interop/issues/550#issuecomment-1777758744). Note that this wasn't freeform, it's based on the features the survey asked about experience and sentiment for.

**Comment by gsnedders** [comment]
What's the status of https://github.com/web-platform-tests/wpt/blob/master/shadow-dom/declarative/getinnerhtml.tentative.html? The test links to https://github.com/whatwg/dom/issues/831, but as Declarative Shadow DOM landed there's no `getInnerHTML`, and there [doesn't seem to be any open issue](https://github.com/whatwg/dom/issues?q=+getinnerhtml+) asking for it to be added.

On the face of it, we should replace that test with a historical test that `getInnerHTML` isn't supported.

**Comment by mfreed7** [comment]
> What's the status of https://github.com/web-platform-tests/wpt/blob/master/shadow-dom/declarative/getinnerhtml.tentative.html? The test links to [whatwg/dom#831](https://github.com/whatwg/dom/issues/831), but as Declarative Shadow DOM landed there's no `getInnerHTML`, and there [doesn't seem to be any open issue](https://github.com/whatwg/dom/issues?q=+getinnerhtml+) asking for it to be added.
> 
> On the face of it, we should replace that test with a historical test that `getInnerHTML` isn't supported.

https://github.com/whatwg/html/issues/8867 is the issue discussing getInnerHTML.

**Comment by gsnedders** [comment]
> > What's the status of https://github.com/web-platform-tests/wpt/blob/master/shadow-dom/declarative/getinnerhtml.tentative.html? The test links to [whatwg/dom#831](https://github.com/whatwg/dom/issues/831), but as Declarative Shadow DOM landed there's no `getInnerHTML`, and there [doesn't seem to be any open issue](https://github.com/whatwg/dom/issues?q=+getinnerhtml+) asking for it to be added.
> > On the face of it, we should replace that test with a historical test that `getInnerHTML` isn't supported.
> 
> [whatwg/html#8867](https://github.com/whatwg/html/issues/8867) is the issue discussing getInnerHTML.

Ah, okay, so it's an ongoing open issue; I'd clearly misunderstood (and somehow failed to find that issue!).

**Comment by mfreed7** [comment]
> Several of the tests ([`/shadow-dom/declarative/declarative-shadow-dom-attachment.html`](https://wpt.fyi/results/shadow-dom/declarative/declarative-shadow-dom-attachment.html?label=master&label=experimental&aligned=), [`/shadow-dom/declarative/declarative-shadow-dom-basic.html`](https://wpt.fyi/results/shadow-dom/declarative/declarative-shadow-dom-basic.html?label=master&label=experimental&aligned=)) rely on Element.prototype.setHTMLUnsafe and Document.prototype.parseHTMLUnsafe.
> 
> This probably isn't really part of Declarative Shadow DOM, and there's no good reason for the tests to rely on these; the tests were only changed to rely on these functions in [web-platform-tests/wpt#41704](https://github.com/web-platform-tests/wpt/pull/41704), which effectively _reduced_ test coverage of Declarative Shadow DOM for Firefox and Safari (as they now all fail before running the actual test).
> 
> See [web-platform-tests/wpt#43202](https://github.com/web-platform-tests/wpt/pull/43202) to partially revert that.

I'm ok with doing that, but it'll take (a lot!) more work. You'll have to manually recursively traverse into shadow roots and serialize the whole tree yourself.

This is precisely why I really wanted to get `setHTMLUnsafe` and `parseHTMLUnsafe` landed in the spec before we landed declarative shadow DOM. It's basically required to use the feature. I'd consider them dependent features.

**Comment by dandclark** [comment]
This proposal has been accepted as part of Interop 2024!  On behalf of the entire Interop team, thank you for proposing it.  You’ll be able to track progress on this topic throughout the year via the [Interop 2024 dashboard](https://wpt.fyi/interop-2024).
