### ISSUE TITLE
Remove css/css-masking/clip-path/clip-path-svg-text-backdrop-filter.html

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#502]
### Test List

css/css-masking/clip-path/clip-path-svg-text-backdrop-filter.html

### Rationale

Depends on backdrop-filter. This test passes with -webkit-backdrop-filter added, see https://github.com/web-platform-tests/wpt/pull/42225 , but I've been told that's against WPT policy.

**Comment by nt1m** [comment]
@foolip / @jgraham Can you review this test change proposal?

**Comment by nt1m** [comment]
@progers / @dholbert Does removing this test seem reasonable to you ?

**Comment by dholbert** [comment]
Given that it's depending on `backdrop-filter` which I guess isn't universally implemented in an unprefixed way yet (and isn't part of interop-2023), then it seems fine to me to remove it from the test-set, yeah.

(I'm curious if/when WebKit plans to support unprefixed `backdrop-filter`; if that happened soon, then it'd be valuable to keep this in the test set, as a way of validating interoperability about how these features interact.  But for the time being, removal seems fine to me.)

**Comment by progers** [comment]
I'm also okay with removing this test, as it is testing an interaction with a feature not part of interop 2023.
