### ISSUE TITLE
Remove flex-align-baseline-table-002.html and grid-align-baseline-table-002.html

### ISSUE THREAD

**Issue by dholbert** [web-platform-tests/interop#504]
### Test List

https://wpt.fyi/results/css/css-flexbox/alignment/flex-align-baseline-table-002.html
https://wpt.fyi/results/css/css-grid/alignment/grid-align-baseline-table-002.html

(These are specifically the tests that have a checkLayout-tested flexbox/grid in the top-left corner, with a **`table` with multiple captions** and with `writing-mode:vertical-rl` (**right-to-left** block-axis flow). Under this setup: if the browser fails to render the table's block-end `<caption>`, then all of other content shifts leftwards, and the x-positions will be different from what the test expects.)

### Rationale

Rationale:
These two tests indirectly require that HTML `<table>` can render multiple captions, which isn't really relevant to grid and flexbox interoperability.

More details:
Firefox has a long-standing bug where we [only ever render the first caption](https://bugzilla.mozilla.org/show_bug.cgi?id=144517) and ignore any others.Hopefully we'll fix that quirk in our table code eventually, but that's not really a fix that we want to commit to as part of achieving interop **on flexbox and grid** in 2023.

So: I propose we simply remove these two tests from the interop-2023 test set. Note that we'll still have interop-2023 test-coverage for nearly the identical setup with two other writing-modes (`horizontal-tb` and `vertical-lr`) in the adjacent -001 and -003 tests, i.e. these ones would remain:
https://wpt.fyi/results/css/css-flexbox/alignment/flex-align-baseline-table-001.html
https://wpt.fyi/results/css/css-flexbox/alignment/flex-align-baseline-table-003.html
https://wpt.fyi/results/css/css-grid/alignment/grid-align-baseline-table-001.html
https://wpt.fyi/results/css/css-grid/alignment/grid-align-baseline-table-003.html
Those remaining ones are fine from the perspective of this issue -- for them, it's no trouble if the second caption doesn't render, since the second caption's placement is on the "far" side of the content whose offsets we're checking.  It's only the `vertical-rl` (right-to-left) ones where the caption's presence/absence influences the x-offsets of its neighboring content.

**Comment by dholbert** [comment]
> Note that we'll still have interop-2023 test-coverage for nearly the identical setup with two other writing-modes (`horizontal-tb` and `vertical-lr`) in the adjacent -001 and -003 tests, i.e. these ones would remain:
https://wpt.fyi/results/css/css-flexbox/alignment/flex-align-baseline-table-001.html
https://wpt.fyi/results/css/css-flexbox/alignment/flex-align-baseline-table-003.html
https://wpt.fyi/results/css/css-grid/alignment/grid-align-baseline-table-001.html
https://wpt.fyi/results/css/css-grid/alignment/grid-align-baseline-table-003.html


Side note: the two remaining grid tests that I linked here do currently have some test failures in Firefox, due to a known grid baseline bug, which we [intend to fix](https://bugzilla.mozilla.org/show_bug.cgi?id=1848446). Those failures are unrelated to this proposal.

**Comment by dholbert** [comment]
@progers / @nt1m  does this proposal sound OK to you?

**Comment by progers** [comment]
@bfgeek , can you please review this proposal for Chromium?

**Comment by nt1m** [comment]
Seems reasonable.

**Comment by progers** [comment]
@bfgeek , ping?

**Comment by davidsgrogan** [comment]
Removing the -002 tests because the second caption messes up `data-offset-x` in `vertical-rl` is fine.

**Comment by dholbert** [comment]
Thanks! I'll post a PR to do that tomorrow.

**Comment by nt1m** [comment]
@dholbert Just going through old proposals, were you planning to post a PR for this one?

**Comment by dholbert** [comment]
Yup, been stuck on my to-do list. I'll do that now.
