### ISSUE TITLE
`prefers-reduced-transparency` Media Query

### ISSUE THREAD

**Issue by lukewarlow** [web-platform-tests/interop#507]
### Description

Following on from Interop 2023s Media Queries 4 focus area, it would be good for some of Media Queries 5 to be focussed on next. This request is specifically for the prefers-reduced-transparency media query, this has shipped in Chromium recently.

### Specification

https://drafts.csswg.org/mediaqueries-5/#prefers-reduced-transparency

### Tests

https://wpt.fyi/results/css/mediaqueries/prefers-reduced-transparency.html

### Current Implementations

- [X] Blink
- [ ] Gecko
- [ ] WebKit

### Standards Positions

WebKit: https://github.com/WebKit/standards-positions/issues/145

Gecko: https://github.com/mozilla/standards-positions/issues/851

Gecko Intent to Prototype: https://groups.google.com/a/mozilla.org/g/dev-platform/c/l410J8odZjA/m/JdWVMNtSAQAJ

### Accessibility Impact

This will help sites to honour user preferences for reduced transparency.

### Privacy Impact

This exposes a new fingerprinting bit (like all user preference media queries)

### Other

There's a PR to webkit that implements this, and Firefox has an implementation behind a flag.

**Comment by cookiecrook** [comment]
Although I originally proposed this media feature, I'm not sure what can be done about this for Interop 2024 given that abuse of `matchMedia()` hasn't been addressed with some of the user preference (`prefers-*`) media features... And, unlike the users with vestibular impairments clamoring for `prefers-reduced-motion`, we're not seeing the same amount of user need. (Though I acknowledge transparency contributes to reduced readability among low vision users, many are making do with existing features such as font size increase and `prefers-contrast`)

I'd love to see this media feature ship, but I am concerned about proposing it for Interop 2024 given that there is an open debate about the privacy implication.

Additional context on why this isn't implemented in WebKit yet found in [WebKit Position #145](https://github.com/WebKit/standards-positions/issues/145) and [CSS #8651](https://github.com/w3c/csswg-drafts/issues/8651) (quoting from the latter):

> ### Note on Fingerprinting
> 
> [ Several proposed media features, including this one] are subject to changes based on the 
> outcome of https://github.com/WebKit/standards-positions/issues/145 and other related privacy issues. We debated 
> not proposing https://github.com/w3c/csswg-drafts/issues/8651 until after privacy issues with @media/matchMedia() 
> had been resolved, but decided to propose it here anyway to further the discussion.

**Comment by lukewarlow** [comment]
That's absolutely fair. I was wondering if instead of proposing this it might be better to propose a research focus for finding a solution to the privacy issue (such as making certain media features opt in to exposing the true value)

**Comment by cookiecrook** [comment]
yes please

**Comment by lukewarlow** [comment]
See https://github.com/web-platform-tests/interop/issues/515

**Comment by lukewarlow** [comment]
Closing this in favour of discussing mitigations in the csswg
