### ISSUE TITLE
Ready-made counter styles

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#511]
### Description

According to https://github.com/w3c/csswg-drafts/issues/8636 , ready-made counter styles from https://www.w3.org/TR/predefined-counter-styles/ should be supported by every UA. 

### Specification

https://www.w3.org/TR/predefined-counter-styles/

### Tests

There are no tests yet. 

### Current Implementations

- [x] Blink
- [x] Gecko
- [x] WebKit

### Other

Great internalization impact, and there are partial implementations in Blink & WebKit.

**Comment by jensimmons** [comment]
I just updated the above post with the link to tests.

**Comment by foolip** [comment]
Are there any tests for this? `find * -name '*predefined-counter-styles*'` and `git grep predefined-counter-styles` both come up empty in a WPT repo checkout.

**Comment by nt1m** [comment]
There's a whole test suite on the i18n-tests repo that will need to be ported to WPT: https://w3c.github.io/i18n-tests/results/predefined-counter-styles

(and I think this is a smaller subset from 2015 than what's in the spec now)

@r12a Is getting tests in shape for WPT something you can help us do? This is our folder for WPT: https://github.com/web-platform-tests/wpt/tree/master/css/css-counter-styles

It would be great to get this in Interop so everyone can start using predefined counter styles across all browsers.

**Comment by r12a** [comment]
@nt1m I don't think you need to test whether all the ready-made styles work – the tests i originally put together were exploratory, and written at the time the CSS Counter Styles spec was being finalised.  I think that as long as the basic styles of counters are supported (ie. tests like those at https://www.w3.org/International/i18n-tests/#css3-counter-styles) then all the ready-made styles will work.

I did a large amount of test development a few years ago, and ported them to WPT, but unfortunately i really don't have the bandwidth any more to work on that kind of thing.

**Comment by nt1m** [comment]
@r12a I agree that this is trivial work for any engine that Having specific WPT for each of the ready made counter styles is unfortunately the only way we can assess progress in the context of interop. 

Did you ever develop an automated test generator that takes a `@counter-style` rule and generates a test? That would be helpful if you have one.

**Comment by r12a** [comment]
I don't remember creating an automated test script for these (though i do remember that it involved a lot of work...), but i wonder whether this might help? https://r12a.github.io/app-counters/

The selection list needs to be updated with a bunch of recent additions to Ready-made Counter Styles, but you can simply copy the code from that document into the textarea to generate results.  (I have another 2 styles to add soon.)

**Comment by dandclark** [comment]
Thank you for proposing Ready-made counter styles for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
