### ISSUE TITLE
Unit division and multiplication for mixed units of the same type within calc()

### ISSUE THREAD

**Issue by scottkellum** [web-platform-tests/interop#513]
### Description

The CSS Values and Units Module has supported division of values of the same type for some time now. This is particularly useful for [creating graphs with CSS](https://youtu.be/ZuZizqDF4q8?si=ga5x9u6tERBr3vV5&t=2410), applying various styles based on viewport/element widths, and trig functions combined with new anchor positioning.

Example: `calc(1rem / 1px)` would result in a value of `16` typed as a number assumed type sizes are default.

### Specification

https://www.w3.org/TR/css-values-4/#calc-type-checking

### Open Issues

- https://github.com/w3c/csswg-drafts/issues/7448
- https://github.com/w3c/csswg-drafts/issues/5635

### Tests

- [css/css-values/getComputedStyle-calc-mixed-units-003.html](https://wpt.fyi/results/css/css-values/getComputedStyle-calc-mixed-units-003.html)
- [css/css-values/calc-in-media-queries-with-mixed-units.html](https://wpt.fyi/results/css/css-values/calc-in-media-queries-with-mixed-units.html)

### Current Implementations

- [ ] Blink
- [ ] Gecko
- [ ] WebKit

### Browser bug reports

- WebKit: https://bugs.webkit.org/show_bug.cgi?id=255280
- Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1827404
- Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1432187 and https://bugs.chromium.org/p/chromium/issues/detail?id=1213338

### Developer discussions

- https://twitter.com/anatudor/status/1537881090223853568

### Workarounds

- https://dev.to/janeori/css-type-casting-to-numeric-tanatan2-scalars-582j

**Comment by foolip** [comment]
@scottkellum do you know what the current behavior of different browsers is here? And are there any tests for this?

**Comment by foolip** [comment]
@danielsakhapov You've mentioned this behavior before with math functions. Do you know if there are any tests for this in WPT?

**Comment by scottkellum** [comment]
@foolip All browsers currently fail to calculate anything, invalidating the property.

I do not have any tests for this (or know where to start to find/make them).

Also I found this issue for Chromium by @andruud and will update the issue with it: https://bugs.chromium.org/p/chromium/issues/detail?id=1213338

**Comment by brandonmcconnell** [comment]
100% on board for this. It's attainable, a no-op, and it's fully spec'd 💯

@scottkellum:

I've been fighting for this one for years. Here are the bugs I opened with the different web engines for this:
- WebKit: https://bugs.webkit.org/show_bug.cgi?id=255280
- Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1827404
- Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1432187

May I suggest renaming this issue to use the "mixed units" keyword? 🙂

**Comment by thebabydino** [comment]
This has to be one of my top CSS wishes. I detailed a use case in this thread https://twitter.com/anatudor/status/1537881090223853568

**Comment by scottkellum** [comment]
Thanks for the notes @brandonmcconnell, that was super helpful and I made updates.

**Comment by brandonmcconnell** [comment]
@scottkellum Sure thing! I also just noticed that there was an update on my WebKit bug ticket with another GitHub discussion link, which had its own related issue, so here are a couple more:

- https://github.com/w3c/csswg-drafts/issues/8169
- https://github.com/w3c/css-houdini-drafts/issues/1080

**Comment by scottkellum** [comment]
Linking related people involved with this spec and implementation. I’m sure I’m missing a lot in the original post and would love some help filling things out and improving reach/visibility of this issue. (again, thanks @brandonmcconnell for assistance here!)

Spec and related discussions:
- @tabatkins
- @Loirooriol
- @xiaochengh

Browser bug report owners
- WebKit
  - @nt1m
- Mozilla/Gecko
  - @emilio
- Chromium/Blink
  - @andruud
  - @bramus

**Comment by nmn** [comment]
I've been asking for this since before Container Queries were even considered possible. This combined with the round() function will be hugely useful!

**Comment by kizu** [comment]
I want to add one article for the “workarounds” field: https://dev.to/janeori/css-type-casting-to-numeric-tanatan2-scalars-582j by @propjockey

It would be awesome to not rely on hacks like `tan(atan2(…))` to achieve this. There is also at least one other workaround for this, even more involved (I'll share it here as well, when I'll finish my article about it).

**Comment by gsnedders** [comment]
> ### Tests
> _No response_

I can't find any, at least. And I guess https://github.com/w3c/csswg-drafts/commit/ea66912c7bf8db5036d428450e6f34c1c9b6c2af predates the CSS WG having any policy requiring tests for specs as they progress.

**Comment by foolip** [comment]
We (Google) think this is a strong proposal and the use case is clear, but without tests, we can't create a focus area with a score to track progress. We don't expect Interop proposal authors to write specs or tests, so this is not a criticism of the proposal, but someone would need to put in a significant effort in a short amount of time for this to work out.

**Comment by brandonmcconnell** [comment]
@foolip Do you have examples of tests for similar/related features so I can see all that it would entail to create tests for this proposal?

If someone can list out what a solid list of tests would be for this, maybe a few of us can come together to split the load.

If the tests will need to be written in C/C++, my help may be more limited, but I can still try to lend a hand.

What is the deadline for these tests?

**Comment by nt1m** [comment]
@brandonmcconnell https://wpt.fyi/results/css/css-values?product=chrome&product=firefox&product=safari&aligned=&view=interop&q=label%3Ainterop-2023-mathfunctions&label=master&label=experimental

**Comment by nt1m** [comment]
It would be preferable to contribute those as separate tests rather than extending the existing ones.

**Comment by brandonmcconnell** [comment]
@nt1m Thanks. It's a rough first pass on my part, but something to get the ball rolling:

https://github.com/web-platform-tests/wpt/pull/42517

**Comment by foolip** [comment]
Thanks @brandonmcconnell for contributing tests, that's great! You asked about a deadline, and Nov 30 is when we expect to make most of the preliminary decisions of what to include and not in Interop 2024. Participating organizations (like Google) will need to make an internal decision earlier than this, however.

I'll ask around for someone to review the tests, and I think there will be enough time in the end.

**Comment by thebabydino** [comment]
Starting from the `atan2()` hack, I've done something awful...

I was curious if 

`tan(atan2(atan2(var(--dj), var(--di)), 1turn))`

would work so we can then use it in an `animation-delay` value... and it does!

Demos: [one](https://codepen.io/thebabydino/pen/dywwLJo/6b0e676b37707af48afcb11f72793ab1), [two](https://codepen.io/thebabydino/pen/bGOzNWR/aca44c635cd7d615b12597f482d79a19), [three](https://codepen.io/thebabydino/pen/jOXdMdK/5cdee141b75c9e83885a9fa9dbf32aac)

**Comment by scottkellum** [comment]
@thebabydino I’ve been using it in animation-delay as well and can confirm this workaround works well! https://codepen.io/scottkellum/pen/ZEVPMav

It would be nice if value typing were implicit rather than explicit. I had expected it to implicitly work as things like `calc(2vw + 0.8rem)` work without explicitly stating what type the value is.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/42517 has just landed. There haven't been full runs of WPT yet, but the results can be seen here:
https://wpt.fyi/results/css/css-values?label=pr_head&max-count=1&pr=42517

**Comment by brandonmcconnell** [comment]
@scottkellum Here are the new tests

````markdown
### Tests

- [css/css-values/getComputedStyle-calc-mixed-units-003.html](https://wpt.fyi/results/css/css-values/getComputedStyle-calc-mixed-units-003.html)
- [css/css-values/calc-in-media-queries-with-mixed-units.html](https://wpt.fyi/results/css/css-values/calc-in-media-queries-with-mixed-units.html)
````

**Comment by dandclark** [comment]
Thank you for proposing Unit division and multiplication for mixed units of the same type within calc() for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

We believe this proposal is too broad, and that as such, Interop 2024 is not the right venue to do this focus area.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._

**Comment by brandonmcconnell** [comment]
@dandclark I'm not sure how this proposal could be any narrower. It's also worth noting that this is not a proposal but an arithmetic bug that exists in nearly every browser right now.

Most if not all modern browsers perform math incorrectly according to the official spec. This interop issue seeks to align browsers with the official current spec.

This one bug is also a major blocker for several other features dependent on CSS's ability to execute math correctly.

I would urge the interop selection team to seriously reconsider this.

**Comment by nt1m** [comment]
I don't know why this answer was picked for this issue, it was just that this wasn't high priority enough compared to the accepted proposals.

**Comment by brandonmcconnell** [comment]
@nt1m Any idea when this fix would be implemented. At the moment, most/all modern browser perform basic math with mixed units incorrectly, which also blocks quite a few other proposals. That is all this PR seeks to achieve.

**Comment by nt1m** [comment]
That's up to each browser vendor.

**Comment by Loirooriol** [comment]
Note this is not "an arithmetic bug", it's a new feature from CSS Values 4. CSS Values 3 didn't allow dividing by dimensions.

**Comment by brandonmcconnell** [comment]
@Loirooriol Yes, arithmetic in its current implementation does not match the latest spec, CSS Values 4. That is all I meant.

**Comment by scottkellum** [comment]
From what I've gathered over my years lobbying for this is that it is likely not going to see traction until one vendor picks it up. Once one vendor picks it up it will create more use cases and browser inconsistencies to get more traction with interop. I hope a vendor picks this up. This is a somewhat abstract feature so while it's incredibly useful, the use cases are often not as straightforward as other features.

**Comment by nmn** [comment]
I can provide use-cases if that helps prioritise this feature.

**Comment by danielsakhapov** [comment]
Note that the full support for the typed arithmetic would require a solid rewrite of the math representation for all web engines.
Nevertheless, I feel like a workaround using progress*() functions can be used for now and is easier to implement for web engines.
https://drafts.csswg.org/css-values-5/#progress
https://wpt.fyi/css/css-values/progress-computed.tentative.html

**Comment by nmn** [comment]
> Note this is not "an arithmetic bug", it's a new feature from CSS Values 4. CSS Values 3 didn't allow dividing by dimensions.

While this is technically true, it should be noted that it is already possible to divide lengths in CSS in all modern browsers using `tan(atan2(length, length))`.

This approach has been detailed in [this blog post](https://dev.to/janeori/css-type-casting-to-numeric-tanatan2-scalars-582j).

Now, as the blog post mentions, there are "arithmetic bugs" when using this approach in all of the browsers which can be worked around by using CSS variables with `number` types etc.

So, even if `calc` isn't improved to support scalar division as is specced in CSS Values 4, can we at least prioritise fixing the bugs when using `tan(atan2(length, length))` so it can be used in the meantime?

**Comment by trollkotze** [comment]
> While this is technically true, it should be noted that it is already possible to divide lengths in CSS in all modern browsers using `tan(atan2(length1, length2))`.
No, it isn't.
>Now, as the blog post mentions, there are "arithmetic bugs" when using this approach in all of the browsers which can be worked around by using CSS variables with number types etc.
So there is no division by dimensions here.

**Comment by nmn** [comment]
> No, it isn't.

Did you even see the link? There are actual examples of the technique being used to divide dimensions. And it works. It's just hacky. It *is* supported.

**Comment by brandonmcconnell** [comment]
@nmn are there any similar techniques you know of for multiplication?

**Comment by nmn** [comment]
@brandonmcconnell 

Multiplication of two lengths doesn't make sense, as you'd get area units.

`10px / 1px === 10` without a unit. But `10px * 1px === 10(px^2)` `px^2` is an invalid unit as we do not units for areas in CSS.

If you need multiplication of two lengths, you'd always need to divide by a length as well to get a proper length unit. For such scenarios, you can just divide first as multiplication/division is associative.
