### ISSUE TITLE
Remove css/css-grid/subgrid/orthogonal-writing-mode-005.html

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#514]
### Test List

css/css-grid/subgrid/orthogonal-writing-mode-005.html

### Rationale

There's active discussion in https://github.com/web-platform-tests/wpt/issues/41831 and https://github.com/w3c/csswg-drafts/issues/9418 on what the correct behavior should be.

**Comment by nt1m** [comment]
@KurtCattiSchmidt / @foolip  Can you review for Chromium?
@dholbert Can you review for Gecko?

**Comment by nt1m** [comment]
@bfgeek Can you review this for Chromium?

**Comment by dholbert** [comment]
I'm fine with removing given the active discussion in the spec issue, yeah.

(Maybe we can resolve that spec-issue and update the test & implementation(s) as-needed in the coming weeks, but we shouldn't pin interop2023 on all of that happening immediately, given that it's late in the year.)

**Comment by nt1m** [comment]
We're going to fix the test instead now that the spec editors have clarified WebKit's behavior is correct.
