### ISSUE TITLE
Indexed DB v3

### ISSUE THREAD

**Issue by evanstade** [web-platform-tests/interop#516]
### Description

Storage APIs allow web sites to store data locally in the browser, providing caching of resources, access to data while offline, and local state for applications. Indexed DB is the primary storage API for structured data, providing durability and transactions. It is commonly used by developers through libraries which provide higher level query APIs.

As of 2023, all engines have very good coverage for "V2" features, but some are missing some "V3" features that had been requested by developers, and there are inconsistencies in BFCache behavior.

### Specification

https://www.w3.org/TR/IndexedDB/

### Tests

https://wpt.fyi/results/IndexedDB

### Current Implementations

- [X] Blink
- [X] Gecko
- [X] WebKit

### Standards Positions

base API already shipping in all major browsers

### Browser bug reports

https://bugzilla.mozilla.org/show_bug.cgi?id=934640

https://bugzilla.mozilla.org/show_bug.cgi?id=1112702 (FF implements only non-standard and experimental API for specifying durability)

### Developer discussions

https://stackoverflow.com/questions/69118042/if-there-is-any-function-in-firefox-to-get-all-indexeddb-names

### Existing Usage

[Dexie](https://github.com/dexie/Dexie.js/issues/1018)

**Comment by foolip** [comment]
https://chromestatus.com/metrics/feature/timeline/popularity/9 and https://chromestatus.com/metrics/feature/timeline/popularity/3023 show that Indexed DB is very widely used. Some of that usage likely due to "fake" usage like fingerprinting, but at any rate it's true to say that Indexed DB is widely used, which makes interoperability more important.

**Comment by gsnedders** [comment]
Is the intention here to include tests for all of IndexedDB, or only the new-in-V3 features?

**Comment by evanstade** [comment]
The failing tests are pretty much all related to v3 features. I'm not sure if there's an easy way to link to those specifically.

**Comment by foolip** [comment]
This is a view of only failing tests:
https://wpt.fyi/results/IndexedDB?label=master&label=experimental&aligned&q=status%3A%21ok%20status%3A%21pass

That's 46 of a total of 457 tests. In the past we have not scoped focus areas to _just_ the failing tests, but if there are large swaths of tests that are passing and that predate v3, it could make sense to exclude those.

**Comment by evanstade** [comment]
@zcorpan is correct -- those `storage-buckets` tests should be marked `tentative` and not included in this proposal.

**Comment by inexorabletash** [comment]
Maybe we can slip https://github.com/w3c/IndexedDB/issues/375 in there? Really minor but it'd be nice to align. Gecko needs no changes (IIRC), Chromium changes are ready to go, just waiting for an implementation commitment from WebKit.

**Comment by inexorabletash** [comment]
Possibly https://github.com/w3c/IndexedDB/issues/412 as well though that is more intrusive and perhaps not in the spirit of Interop.

**Comment by dandclark** [comment]
This proposal has been accepted as part of Interop 2024!  On behalf of the entire Interop team, thank you for proposing it.  You’ll be able to track progress on this topic throughout the year via the [Interop 2024 dashboard](https://wpt.fyi/interop-2024).
