### ISSUE TITLE
Detect UA Transitions on same-document Navigations

### ISSUE THREAD

**Issue by khushalsagar** [web-platform-tests/interop#518]
### Description

Smooth visual transitions as users navigate on the web can lower cognitive load by helping users stay in context. However, the user experience is bad if both the site author and the UA add these transitions: the transitions may conflict and cause confusion for the user. This API avoids such cases to ensure only one visual transition is executed at a time.

The API adds a boolean on `PopStateEvent` and `NavigateEvent` to indicate whether the UA has executed a visual transition for this navigation. Authors can use this to skip their custom transition.

### Specification

https://github.com/whatwg/html/pull/9579

### Tests

[Formerly:] https://github.com/web-platform-tests/wpt/pull/41326 and https://github.com/web-platform-tests/wpt/pull/41623.

https://wpt.fyi/results/?label=master&label=experimental&aligned&q=path%3A%2Fnavigation-api%2Fnavigate-event%2Fnavigate-navigation-back-same-document.html%20or%20path%3A%2Fnavigation-api%2Fnavigate-event%2Fevent-constructor.html%20or%20path%3A%2Fhtml%2Fbrowsers%2Fbrowsing-the-web%2Fhistory-traversal%2FPopStateEvent.html%20or%20path%3A%2Fhtml%2Fbrowsers%2Fbrowsing-the-web%2Fhistory-traversal%2Fpopstate_event.html

Note: The WPTs only test that the attribute is defined. When a UA transition is executed is left to the UA, so by design tests can't validate when the value should be set to true. 

### Current Implementations

- [X] Blink
- [ ] Gecko
- [ ] WebKit

### Standards Positions

Webkit: https://github.com/WebKit/standards-positions/issues/176
Mozilla: https://github.com/mozilla/standards-positions/issues/783
Blink Intent to Ship: https://groups.google.com/a/chromium.org/g/blink-dev/c/OTGqhEZ7aug/m/tDfjCG4KAQAJ

### Developer discussions

This issue has come up for Webkit based browsers, [example](https://stackoverflow.com/questions/66867737/iphone-safari-detect-swipe-navigation#:~:text=Ideally%2C%20I%27d%20like%20to%20be%20able%20to%20detect%20the%20swipe%20functionality%20somehow.%20That%20is%2C%20some%20event%2C%20or%20something%20in%20the%20popstate%20event%20to%20indicate%20that%20a%20swipe%20navigation%20is%2C%20or%20has%20just%20occurred%3F), since Webkit is the only engine shipping browser transitions for these navigations today.

### Workarounds

Authors could try to polyfill it by listening to `touchStart` events, some details [here](https://pqina.nl/blog/blocking-navigation-gestures-on-ios-13-4/). But there's no easy way to know whether the browser will turn a touch action stream into a navigation gesture which makes this approach brittle.

**Comment by gsnedders** [comment]
> ### Tests
> [Formerly:] [web-platform-tests/wpt#41326](https://github.com/web-platform-tests/wpt/pull/41326) and [web-platform-tests/wpt#41623](https://github.com/web-platform-tests/wpt/pull/41623).
> 
> https://wpt.fyi/results/?label=master&label=experimental&aligned&q=path%3A%2Fnavigation-api%2Fnavigate-event%2Fnavigate-navigation-back-same-document.html%20or%20path%3A%2Fnavigation-api%2Fnavigate-event%2Fevent-constructor.html%20or%20path%3A%2Fhtml%2Fbrowsers%2Fbrowsing-the-web%2Fhistory-traversal%2FPopStateEvent.html%20or%20path%3A%2Fhtml%2Fbrowsers%2Fbrowsing-the-web%2Fhistory-traversal%2Fpopstate_event.html
> 
> Note: The WPTs only test that the attribute is defined. When a UA transition is executed is left to the UA, so by design tests can't validate when the value should be set to true.

We might want to exclude the tests that rely on navigation-api (a proposal in its own right, #435).

**Comment by nairnandu** [comment]
Thank you for proposing [Detect UA Transitions on same-document Navigations](https://github.com/web-platform-tests/interop/issues/518#top) for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop 2024. This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year, if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
