### ISSUE TITLE
[css-values-5] `attr()` support extended capabilities

### ISSUE THREAD

**Issue by brandonmcconnell** [web-platform-tests/interop#521]
### Description

The attr() [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) [function](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions) is used to retrieve the value of an attribute of the selected element and use it in the stylesheet. It can also be used on [pseudo-elements](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements), in which case the value of the attribute on the pseudo-element's originating element is returned. ([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/attr))

### Specification

<a href="https://w3c.github.io/csswg-drafts/css-values-5/#attr-notation" target="_blank">CSS Values and Units Module Level 5<br /># attr-notation</a>

### Open Issues

* https://github.com/w3c/csswg-drafts/issues/5092
* https://github.com/w3c/csswg-drafts/issues/5079
* https://github.com/web-platform-tests/interop/issues/86 (not open, but a related issue from Interop 2023)

### Tests

The below list of tests was generated using [`wpt-find`](https://github.com/brandonmcconnell/wpt-find) (`wpt-find -mlc 'attr('`)

- [/largest-contentful-paint/observe-css-generated-text.html](https://wpt.fyi/largest-contentful-paint/observe-css-generated-text.html)
- [/css/css-conditional/at-supports-namespace-001.html](https://wpt.fyi/css/css-conditional/at-supports-namespace-001.html)
- [/css/css-content/attr-case-sensitivity-001.html](https://wpt.fyi/css/css-content/attr-case-sensitivity-001.html)
- [/css/css-content/attr-case-sensitivity-003.html](https://wpt.fyi/css/css-content/attr-case-sensitivity-003.html)
- [/css/css-content/attr-case-sensitivity-002.html](https://wpt.fyi/css/css-content/attr-case-sensitivity-002.html)
- [/css/css-gcpm/string-set-012.html](https://wpt.fyi/css/css-gcpm/string-set-012.html)
- [/css/css-align/self-alignment/self-align-safe-unsafe-flex-003.html](https://wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-flex-003.html)
- [/css/css-align/self-alignment/self-align-safe-unsafe-flex-002.html](https://wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-flex-002.html)
- [/css/css-align/self-alignment/self-align-safe-unsafe-grid-002.html](https://wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-grid-002.html)
- [/css/css-align/self-alignment/self-align-safe-unsafe-grid-003.html](https://wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-grid-003.html)
- [/css/css-align/self-alignment/self-align-safe-unsafe-grid-001.html](https://wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-grid-001.html)
- [/css/css-align/self-alignment/self-align-safe-unsafe-flex-001.html](https://wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-flex-001.html)
- [/css/css-variables/variable-generated-content-dynamic-001.html](https://wpt.fyi/css/css-variables/variable-generated-content-dynamic-001.html)
- [/css/cssom/serialize-values.html](https://wpt.fyi/css/cssom/serialize-values.html)
- [/css/cssom/css-style-attr-decl-block.html](https://wpt.fyi/css/cssom/css-style-attr-decl-block.html)
- [/css/css-values/attr-in-max.html](https://wpt.fyi/css/css-values/attr-in-max.html)
- [/css/css-values/attr-color-valid.html](https://wpt.fyi/css/css-values/attr-color-valid.html)
- [/css/css-values/attr-invalid-type-008.html](https://wpt.fyi/css/css-values/attr-invalid-type-008.html)
- [/css/css-values/attr-length-valid-zero-nofallback.html](https://wpt.fyi/css/css-values/attr-length-valid-zero-nofallback.html)
- [/css/css-values/attr-color-invalid-cast.html](https://wpt.fyi/css/css-values/attr-color-invalid-cast.html)
- [/css/css-values/attr-length-valid.html](https://wpt.fyi/css/css-values/attr-length-valid.html)
- [/css/css-values/attr-invalid-type-002.html](https://wpt.fyi/css/css-values/attr-invalid-type-002.html)
- [/css/css-values/attr-color-invalid-fallback.html](https://wpt.fyi/css/css-values/attr-color-invalid-fallback.html)
- [/css/css-values/attr-length-valid-zero.html](https://wpt.fyi/css/css-values/attr-length-valid-zero.html)
- [/css/css-values/attr-px-invalid-fallback.html](https://wpt.fyi/css/css-values/attr-px-invalid-fallback.html)
- [/css/css-values/attr-px-invalid-cast.html](https://wpt.fyi/css/css-values/attr-px-invalid-cast.html)
- [/css/css-values/attr-invalid-type-001.html](https://wpt.fyi/css/css-values/attr-invalid-type-001.html)
- [/css/css-values/attr-length-invalid-cast.html](https://wpt.fyi/css/css-values/attr-length-invalid-cast.html)
- [/css/css-values/attr-px-valid.html](https://wpt.fyi/css/css-values/attr-px-valid.html)
- [/css/css-values/calc-rgb-percent-001.html](https://wpt.fyi/css/css-values/calc-rgb-percent-001.html)
- [/css/css-values/attr-length-invalid-fallback.html](https://wpt.fyi/css/css-values/attr-length-invalid-fallback.html)
- [/css/CSS2/generated-content/content-attr-case-001.html](https://wpt.fyi/css/CSS2/generated-content/content-attr-case-001.html)
- [/html/semantics/embedded-content/the-img-element/sizes/support/sizes-iframed.sub.html](https://wpt.fyi/html/semantics/embedded-content/the-img-element/sizes/support/sizes-iframed.sub.html)
- [/resource-timing/content-type.html](https://wpt.fyi/resource-timing/content-type.html)

### Current Implementations

- [ ] Blink
- [X] Gecko
- [ ] WebKit

### Standards Positions

* Gecko/Mozilla
  * [Intent to prototype and ship: CSS attr() fallback](https://groups.google.com/a/mozilla.org/g/dev-platform/c/SsXXqvp8O3s/m/epsq8vlaCAAJ?pli=1) ([related bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1448248))
* Chromium/Blink
  * [Intent to Implement and Ship: CSS advanced attr() function](https://groups.google.com/a/chromium.org/g/blink-dev/c/FGCgsKmylhw/m/BSUrk2roCQAJ)
  * [Intent to Prototype: CSS advanced attr() function (Was: Intent to Implement and Ship)](https://groups.google.com/a/chromium.org/g/blink-dev/c/viBACPfSsEM/m/URCnDl81AAAJ)

### Browser bug reports

* Chromium
  * https://bugs.chromium.org/p/chromium/issues/detail?id=1486443
  * https://bugs.chromium.org/p/chromium/issues/detail?id=246571
  * https://bugs.chromium.org/p/chromium/issues/detail?id=1082477
  * https://bugs.chromium.org/p/chromium/issues/detail?id=1081995
* Gecko
  * https://bugzilla.mozilla.org/show_bug.cgi?id=435426
  * https://bugzilla.mozilla.org/show_bug.cgi?id=1481150
  * https://bugzilla.mozilla.org/show_bug.cgi?id=1854104
  * https://bugzilla.mozilla.org/show_bug.cgi?id=1369329
* WebKit
  * https://bugs.webkit.org/show_bug.cgi?id=25851
  * https://bugs.webkit.org/show_bug.cgi?id=26609
  * https://bugs.webkit.org/show_bug.cgi?id=182343

### Developer discussions

Some posts in support of `attr()`:

#### X/Twitter

* https://x.com/LukyVJ/status/1377917512638201858
* https://x.com/chrisshank23/status/1704618645262041304
* https://x.com/shshaw/status/1150852516264980480
* https://x.com/CanadaHonk/status/1694111906158510220
* https://x.com/FWeinb/status/367748678737727489
* https://x.com/superissarah/status/1054939204038225920
* https://x.com/cramforce/status/654157266761846784
* https://x.com/codepo8/status/359357417026359297
* https://x.com/LeaVerou/status/591859793528233984
* https://x.com/pawelgrzybek/status/1548234308107636736
* https://x.com/calebwilliams12/status/1448325875750121478
* https://x.com/pbakaus/status/1155704562080083968
* https://x.com/blvdmitry/status/1303019591501852674
* https://x.com/rxgx/status/763867149320409088

#### StackOverflow

* https://stackoverflow.com/questions/18408488/setting-width-with-css-attr
* https://stackoverflow.com/questions/20490704/combine-calc-with-attr-in-css
* https://stackoverflow.com/questions/64476303/adding-attr-to-css
* https://stackoverflow.com/questions/42932294/css-attr-concatenation-with-url-path
* https://stackoverflow.com/questions/45194482/setting-width-with-css-attr
* https://stackoverflow.com/questions/35687762/using-css-attr-function-to-rotate-an-element
* https://stackoverflow.com/questions/48662218/css-attr-for-integers-what-is-a-good-way-to-solve-this
* https://stackoverflow.com/questions/48459561/attr-not-working
* https://stackoverflow.com/questions/8769786/css3s-attr-doesnt-work-in-major-browsers

If you search X/Twitter for "CSS attr" you will see plenty of posts from people excited about and/or curious about the future features of CSS `attr()`. You'd also see many posts echoing [one opinion calling the `attr()` useless](https://x.com/chriscoyier/status/923198749739859971), especially [in comparison to CSS custom properties](https://css-tricks.com/css-attr-function-got-nothin-custom-properties).

<img src="https://github.com/web-platform-tests/interop/assets/5913254/6bc255ce-8b4d-42a6-8cc9-b65031caae07" width="596" height="auto" />

I'd like to disagree with that sentiment, but… he's **right**. As the `attr()` function stands today, `attr()` is really only useful when trying to pull plain text from attributes to display using a pseudo-element.

It's mostly useless, but it doesn't have to be.

With these newer features, `attr()` would be exceedingly useful, not taking the place of CSS custom properties by any means but rather bridging the gap between markup values and CSS values. This would stand as a very productive separation of concerns.

### Workarounds

The primary workaround for this is to use CSS custom properties, but this has several drawbacks and only lives in the markup in the form of inline styles. One of the greatest advantages of `attr()` is the ability to utilize the values set on the markup.

To achieve this with CSS custom properties, one would need to apply those values twice, once to the attributes for actual markup functionality and again as a CSS custom property for CSS usage. Example:

```html
<!-- tightly coupled redundancies in the attributes vs. inline styles -->
<progress min="0" max="100" value="50" style="--min: 0; --max: 100; --value: 50;"></progress>

<style>
  progress {
    --percentage: calc((var(--value) - var(--min)) / (var(--max) - var(--min)) * 100%);
    background: linear-gradient(to right, green var(--percentage), white var(--percentage));
  }
</style>
```

With `attr()`, we can achieve this more concisely, using attribute values directly:

```html
<!-- here, the styles will inherit from the attributes dynamically, so no need to set the explicit values twice -->
<progress min="0" max="100" value="50"></progress>

<style>
  progress {
    /* I'm using `attr()` directly in this calculation, but these values could also be abstracted to CSS custom properties for ease of reuse */
    --percentage: calc((attr(value number) - attr(min number)) / (attr(max number) - attr(min number)) * 100%);
    background: linear-gradient(to right, green var(--percentage), white var(--percentage));
  }
</style>
```

### Accessibility Impact

Tightly coupled code can lead to inconsistencies due to human/developer-error when updates are made. The DRY coding principle would reasonably apply here.

### Privacy Impact

This issue focuses on security concerns using `attr()`, but there are already good ideas re how to circumvent those issues, the primary of which would be whitelisting: https://github.com/w3c/csswg-drafts/issues/5092

**Comment by webstrand** [comment]
I like to use `display: grid` for `<table>` markup. Being able to write generic css that handles most of the built-in table attributes would be nice, e.g. `rowspan` `colspan` ...

**Comment by thebabydino** [comment]
Here's another use case: images with a spaced out gradient border `that` looks extracted from the image.

![images surrounded by a gap then by a gradient border obtained from the image](https://pbs.twimg.com/media/Fu5Rs3XWwAYXian?format=jpg&name=medium)

The markup for an image would be just

```
<img src='meow.jpg' alt='fluffy black cat'/>
```

Then in the CSS, this would do the trick for the image with the spaced out "gradient" (actually very blurred) border:

```
img {
	border: solid 1em;
	border-image: filter(src(attr(src)), blur(99px)) 10%;
	padding: 1em; /* space between image and border */
	width: 12em;
	aspect-ratio: 1;
	object-fit: cover
}
```

No browser currently supports this and it's not just because of `attr()`. [`src()`](https://www.w3.org/TR/css-values/#ref-for-funcdef-src) doesn't seem to be in any browser at the moment, while [`filter()`](https://www.w3.org/TR/filter-effects-1/#FilterCSSImageValue) is only supported in Safari (has been supported there for over 8 years at this point, but no other browser followed).

So instead, I need to do all of this to get the desired result:

```
figure {
	display: grid;
	width: 16em;

	img, &::after {
		grid-area: 1/ 1;
		border: solid $b hsla(0, 0%, 0%, .001)
	}
	
	img {
		box-sizing: border-box;
		border-image: var(--url) 10%;
		padding: $b;
		width:100%;
		aspect-ratio: 1;
		object-fit: cover
	}
	
	&::after {
		backdrop-filter: blur(99px);
		mask: 
			linear-gradient(red 0 0) padding-box exclude, 
			linear-gradient(red 0 0);
		content: ''
	}
}
```

And this doesn't even include the `-webkit-`-prefixed version for `mask`, which is still needed at this point ([live demo](https://codepen.io/thebabydino/pen/VwqEapG)).

---

> With `attr()`, we can achieve this more concisely, using attribute values directly:
> 
> ```
> 
> <progress min="0" max="100" value="50"></progress>
> 
> <style>
>   progress {
>     /* I'm using `attr()` directly in this calculation, but these values could also be abstracted to CSS custom properties for ease of reuse */
>     --percentage: calc((attr(value number) - attr(min number)) / (attr(max number) - attr(min number)) * 100%);
>     background: linear-gradient(to right, green var(--percentage), white var(--percentage));
>   }
> </style>
> ```

I'm intrigued! This looks very good in theory and I'd love to be able to use something like this for inputs! For example, for `input[type=range]`, this would eliminate the need for JS as we wouldn't need to rely on a JS-updated custom property for the value, like I'm doing in [this demo](https://codepen.io/thebabydino/pen/jOQVZNV).

But one thing that confuses me is that I don't see the `value` attribute for such an `input` changing in DevTools as I drag the thumb. The actual value (that I update the `--val` custom property with) does change, but not the number value in the `value` attribute. So would `attr(value)` actually work, or would it just be always the same value set initially in the `value` attribute?

![DevTools screenshot. Shows how after dragging the slider thumb, the --val custom property in the style attribute has changed value, but the value attribute has kept the initial value it was set to.](https://github.com/web-platform-tests/interop/assets/76854602/c4902af7-623e-495a-9edf-eeb3d9967969)

**Comment by brandonmcconnell** [comment]
@thebabydino Solid feedback all around. Examples like that greatly help to express this feature like this. Thank you!!

Re the `value` attribute updating, I've run into that as well a number if times and have a couple other proposals to address that—
1. [[css-values-5] `value()` function](https://github.com/w3c/csswg-drafts/issues/7869)
  
    This proposal introduces a CSS function for incorporating the live value of an input, exactly as you've put it here
  
2. [[css-properties-values-api] add support for scope-global variables](https://github.com/w3c/csswg-drafts/issues/7866)
  
    This proposal introduces a completely new way to work with CSS custom properties — globally.
    
    <details><summary><b>(expand/collapse explainer)</b></summary><br />
    
    Hypothetically, you could use `@property` to set up a custom property with a new `global` option on its `@property` config set to `true`. When the custom property is set up this way, it only ever has one value — that with the highest specificity. This way, we can set global values using states such as a checkbox or an input value and access it anywhere else in that scope.
    
    For example, you could create a dark mode toggle checkbox somewhere on the page, and without needing to resort to some top-level `:has()` (not inherently bad, but an alternative), you could have that checkbox's `checked` state update the global value naturally, like this:
    
    ```css
    @property --color-bg {
      syntax: "<color>";
      inherits: true;
      initial-value: white; /* ⬜️ */
      global: true;
    }
    @property --color-text {
      syntax: "<color>";
      inherits: true;
      initial-value: black; /* ⬛️ */
      global: true;
    }
    #darkmode:checked {
      --color-bg: black; /* ⬛️ */
      --color-text: white; /* ⬜️ */
    }
    #page {
      background-color: var(--color-bg); /* ⬛️ */
      color: var(--color-text); /* ⬜️ */
    }
    ```
    
    </details>
    
    A feature like this would be essential for exposing attributes as well as the `value` property of descendant elements that cannot otherwise expose them upwards. I'm considering this feature a dependency of my other `value()` proposal.


I would certainly appreciate any support you'd show to either of those proposals as well. Thank you 🙂

**Comment by webstrand** [comment]
@thebabydino
> This looks very good in theory and I'd love to be able to use something like this for inputs! For example, for input[type=range]

This was my first thought, too. Range is a pain to style, currently: <https://codepen.io/webstrand/pen/bGLXdPR>

> So would `attr(value)` actually work, or would it just be always the same value set initially in the `value` attribute?

Traditionally, `<input>` elements don't update their attribute when their value property changes. Changing this behavior would be a breaking change as there's quite a lot of things that reuse `inputEl.getAttribute("value")` to restore fields to their initial state. For instance `<button type="reset">` looks at the attribute value to determine what to reset to.

I'm not sure I'd be a fan of adding special cases for `attr(value)` though.

**Comment by brandonmcconnell** [comment]
@webstrand I agree; I don't think we should introduce any special cases using `attr()`.

If you're interested, take a peek at those other two proposals, I mentioned, namely this one: [[css-values-5] `value()` function](https://github.com/w3c/csswg-drafts/issues/7869)

**Comment by jacobrask** [comment]
Another concrete example, an icon component that should be sized in `rem`s to scale with the text. Currently we do something like this

```
.icon {
  width: var(--_height);
  height: var(--_height);

  &[height='80'] {
    --_height: 5rem;
  }
  &[height='64'] {
    --_height: 4rem;
  }
  &[height='48'] {
    --_height: 3rem;
  }
  &[height='40'] {
    --_height: 2.5rem;
  }
  &[height='32'] {
    --_height: 2rem;
  }
  &[height='24'] {
    --_height: 1.5rem;
  }
  &[height='16'] {
    --_height: 1rem;
  }
  &[height='12'] {
    --_height: 0.75rem;
  }
  &[height='8'] {
    --_height: 0.5rem;
  }
}
```

**Comment by brandonmcconnell** [comment]
@jacobrask Great example. I've done something similar for custom progress bars:

```html
<div class="progress-wrapper">
  <progress min=0 max=100 value=75></progress>
</div>
```
```css
progress[min][max][value] {
  .progress-wrapper:has(&) {
    --percentage: calc((var(--value) - var(--min)) / (var(--max) - var(--min)) * 100%);
    height: 100vh;
    width: 100vw;
    background: linear-gradient(to right, red var(--percentage), white var(--percentage));
  }
  .progress-wrapper:has(&) & {
    display: none;
  }

  /* min */
  .progress-wrapper:has(&[min="0"]) { --min: 0; } /* ... */
  .progress-wrapper:has(&[min="100"]) { --min: 100; }

  /* max */
  .progress-wrapper:has(&[max="0"]) { --max: 0; } /* ... */
  .progress-wrapper:has(&[max="100"]) { --max: 100; }

  /* value */
  .progress-wrapper:has(&[value="0"]) { --value: 0; } /* ... */
  .progress-wrapper:has(&[value="100"]) { --value: 100; }
}
```
[CodePen demo](https://codepen.io/brandonmcconnell/pen/JjweENe/285634d036b3849a3e80c12d327826f7)

<img width="241" alt="" src="https://github.com/web-platform-tests/interop/assets/5913254/bb82be7e-0237-4308-b76b-0e55e5d888f2">

**Comment by bkardell** [comment]
Thank you for proposing `attr()` support extended capabilities for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

As of the deadline, the specifications for `attr()` support extended capabilities were not yet complete enough to allow interoperable implementations. To make progress on this area in the future, it will first be necessary to ensure that the feature has a clear specification in a standards track document.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._

**Comment by brandonmcconnell** [comment]
@bkardell What features from the official specification are not complete enough to move forward with this feature? The spec is complete and has been for years.

Not only has this been suggested for the past consecutive few years both via interop and otherwise, **this issue garnered more attention and praise and engagement than any other interop issue proposed** which should really be weighed when considering proposed features for interop.

One of the primary functions of proposing issues for interop is to give the community the ability to vote on which issues they desire to see implemented in the web platform most. The results clearly show that this is a top priority if not THE top priority.

**Comment by foolip** [comment]
@brandonmcconnell you're right that there's a lot of developer demand for this, that is very clear. The issue with the spec isn't really that it's "not yet complete enough to allow interoperable implementations", but that there are security issues that at least the Chrome team believes are serious enough to need solving before shipping. That is the topic of https://github.com/w3c/csswg-drafts/issues/5092, and we now have a sketch of a solution that might work. I am going to follow up on that work so that the security issues can be resolved. (I did take a look while we were evaluating proposals too, but there just wasn't enough time to fix it there and then.)

**Comment by brandonmcconnell** [comment]
@foolip (cc @tabatkins) Given the recent progress and resolutions in https://github.com/w3c/csswg-drafts/issues/5092, and the exceeding demand on this interop proposal the past two consecutive years, could we reconsider including it in this year's interop effort, as the blocker is now removed?

**Comment by bkardell** [comment]
We can't, as part of Interop 2024.  Interop choices and tests are carefully chosen so that we have measurable goals that don't significantly change during the year... But don't be too disheartened by that answer: It doesn't mean teams can't all prioritize it independently -- in my opinion, another benefit of the Interop project is just that it gets us _collectively_ thinking/talking about priorities... So, it's totally possible if the situation regarding specs is resolved, that it might get interoperable support in the same year without actually being a part of the Interop project.

**Comment by brandonmcconnell** [comment]
@bkardell Thanks, I totally understand that 🙂
