### ISSUE TITLE
WebXR

### ISSUE THREAD

**Issue by msub2** [web-platform-tests/interop#522]
### Description

The WebXR Device API allows for access to VR (virtual reality) and AR (augmented reality) devices on the web, allowing users to create immersive content that can be accessed solely through the browser. While this API is technically present in the major browser engines, levels of implementation vary heavily: 

- Blink is by far the furthest ahead and the only one actively shipping a fairly complete implementation via Chromium. 
- Gecko has not seen significant work on its implementation since the relevant Mozilla team members were laid off in 2020 before finishing it (and the existing VR-related configurations were recently set to be disabled by default in Firefox, adding another barrier for those attempting to use the existing WebXR implementation). 
- WebKit, while seeming to have a mostly complete implementation ready thanks to work by Apple + Igalia, lacks any major browser shipping the API save for Safari on visionOS, which is not available to the public yet.

### Specification

https://www.w3.org/TR/webxr/

### Tests

https://wpt.fyi/results/webxr

### Current Implementations

- [X] Blink
- [X] Gecko
- [X] WebKit

### Standards Positions

https://github.com/mozilla/standards-positions/issues/218
https://github.com/WebKit/standards-positions/issues/155 (without position, but shipping in Safari for visionOS)

### Browser bug reports

https://bugs.chromium.org/p/chromium/issues/list?q=component%3ABlink%3EWebXR&can=2
https://bugzilla.mozilla.org/buglist.cgi?product=Core&component=WebVR&resolution=--- (contains both WebVR and WebXR-related bugs)
https://bugs.webkit.org/buglist.cgi?component=WebXR&product=WebKit&resolution=---

### Developer discussions

[Developer inquries on the meta bug in WebKit's bug tracker](https://bugs.webkit.org/show_bug.cgi?id=208988)
[User unable to enter WebXR experience on Firefox](https://www.reddit.com/r/WebVR/comments/ss8jcl/moonrider_not_entering_vr_mode_on_mozilla_firefox/)

### Polls & Surveys

https://2022.stateofjs.com/en-US/features/browser-apis/ (The direct share link seems to be broken, but scroll down to "WebXR Device API")
![image](https://github.com/web-platform-tests/interop/assets/70986246/76277f1d-84a5-4499-8ae2-22e8e418f152)

### Existing Usage

*Chrome Use*

https://chromestatus.com/metrics/feature/timeline/popularity/2413 - navigator.xr
https://chromestatus.com/metrics/feature/timeline/popularity/3036 - navigator.xr.isSessionSupported

*Libraries using the feature*

https://github.com/aframevr/aframe
https://github.com/mrdoob/three.js
https://github.com/BabylonJS/Babylon.js
https://github.com/playcanvas/engine

### Workarounds

https://github.com/immersive-web/webxr-polyfill

**Comment by dandclark** [comment]
Thank you for proposing WebXR for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

We are still missing test infrastructure for testing WebXR. Please note this should not be taken as a comment on the technology as a whole, and once the test infrastructure issues are resolved, we would welcome  this proposal being resubmitted for a future round of Interop.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._

**Comment by Link2Twenty** [comment]
@msub2 gonna resubmit this year?
