### ISSUE TITLE
Text Fragments

### ISSUE THREAD

**Issue by jnjaeschke** [web-platform-tests/interop#529]
### Description

Text fragments allow URLs to include a fragment of text from the destination page, which the UA will bring to the user's attention. This allows generating links to precise sections of a document, even when the underlying markup doesn't provide necessary anchors.

### Specification

Currently https://wicg.github.io/scroll-to-text-fragment/ but https://github.com/whatwg/html/issues/8282 to migrate to WHATWG

### Open Issues

https://github.com/whatwg/html/issues/8282
https://github.com/WICG/scroll-to-text-fragment/issues/
notably #[233](https://github.com/WICG/scroll-to-text-fragment/issues/233)

### Tests

[wpt.fyi/results/scroll-to-text-fragment](https://wpt.fyi/results/scroll-to-text-fragment?label=experimental&label=master&aligned), except the iframe support ones
[wpt.fyi/results/css/css-pseudo](https://wpt.fyi/results/css/css-pseudo?label=master&label=experimental&aligned&q=target)

### Current Implementations

- [X] Blink
- [ ] Gecko
- [X] WebKit

### Standards Positions

https://mozilla.github.io/standards-positions/#scroll-to-text-fragment

### Browser bug reports

https://bugzilla.mozilla.org/show_bug.cgi?id=1753933

### Existing Usage

[Chrome use counter](https://chromestatus.com/metrics/feature/timeline/popularity/2901). It is also used by some large web properties e.g. Google search in "Featured Snippets".

### Accessibility Impact

There are known a11y interop problems with the feature, but these are out of scope for this focus area since they require WebDriver additions.

**Comment by jgraham** [comment]
Thank you for proposing Text Fragments for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

We did not have consensus to include this proposal. This should not be taken as a comment on the technology as a whole

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
