### ISSUE TITLE
CSS Zoom

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/interop#530]
### Description

Support standardization of the CSS Zoom property by investigating compatibility constraints and producing relevant testcases.

### Rationale

CSS Zoom is a nonstandard property that has been shipping in WebKit and Blink based browsers for a long time. This causes significant compatibility issues for other engines and results in a large amount of [observed site breakage](https://bugzilla.mozilla.org/show_bug.cgi?id=390936).

Recently there was an [attempt](https://groups.google.com/a/chromium.org/g/blink-dev/c/V7q43bgutbo/m/1ri4zFgwAQAJ?pli=1) to unship Zoom in Blink. However this failed due to the ongoing use of the feature on major web properties. Instead the current plan is to standardise the CSS Zoom property in the CSS Working Group.

The goal of this investigation would be to support that standardisation effort by ensuring that it is not blocked on questions around compatibility. The investigation would concentrate on answering such questions and producing testcases, with the aim of ensuring that once the standard is complete it is possible for all engines to rapidly implement and converse on the standardised behaviour.

### Investigation Roadmap

To be finalised, but but we expect it to mostly consist of:
* Testcase production, to understand the current behaviour of the Zoom properties in existing implementations
* Investigating usage and compatibility questions (e.g. via HTTP Archive, telemetry, crawls, etc.) as required to answer questions from the specification editors in the CSSWG.

**Comment by jgraham** [comment]
CC @emilio

**Comment by boazsender** [comment]
cc @jugglinmike
