### ISSUE TITLE
WebRTC “end-to-end-encryption”

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/interop#533]
### Description

The `RTCRtpScriptTransform` API allows websites to plug JavaScript workers into WebRTC’s realtime media pipeline, to transform sent and received encodings. Websites use this API to implement their own audiovisual encryption to protect users from middleboxes the website may employ (but not from the website itself).

Unfortunately, bifurcation exists in implementations, with two browsers implementing the spec, and one implementing a now non-standard predecessor, forcing websites today to work against two different APIs, causing a major interoperability headache.

### Specification

https://w3c.github.io/webrtc-encoded-transform/ 

### Tests

* Tests starting with “script-” in https://wpt.fyi/results/webrtc-encoded-transform
* Other tests of non-standards-track APIs in this folder are not part of this nomination

### Current Implementations

- [X] Blink
- [X] Gecko
- [X] WebKit

### Privacy Impact

This proposal covers a technology that's explicitly designed to be privacy-enhancing.

### Other

Note that WebRTC in general does not show up as a priority on developer surveys as it's generally used by a small number of sites that specialize in video conferencing and related services. However those sites are often very popular and compatibility issues highly visible to users (see e.g. [webcompat.com issue reports](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+WebRTC+))

**Comment by jgraham** [comment]
CC @jan-ivar

**Comment by youennf** [comment]
This makes sense to me. There might be interactions between script transforms and things like simulcast that would be useful to drill into (aka write more tests) as well.

**Comment by foolip** [comment]
For survey data and web developer demand, in [preliminary results from State of HTML 2023](https://github.com/web-platform-tests/interop/issues/550), WebRTC was a somewhat common response to the question "Which existing HTML features or browser APIs are you unable to use because of browser differences or lack of support?"

**Comment by foolip** [comment]
There are some important use cases covered by the older version of the spec that Chrome implemented, which aren't yet handled by the new spec. The Chrome team is engaged on these issues to try to resolve this, so that we can converge on a single interoperable API:

- https://github.com/w3c/webrtc-encoded-transform/issues/89
- https://github.com/w3c/webrtc-encoded-transform/issues/211
- https://github.com/w3c/webrtc-encoded-transform/issues/200
- https://github.com/w3c/webrtc-encoded-transform/issues/206
- https://github.com/w3c/webrtc-encoded-transform/issues/172
- https://github.com/w3c/webrtc-encoded-transform/issues/162
- https://github.com/w3c/webrtc-encoded-transform/issues/160

My understanding is it's unlikely that work on the new API will start until we're confident it can fully replace what we've already shipped.

**Comment by jan-ivar** [comment]
Thanks @foolip for the context.

> My understanding is it's unlikely that work on the new API will start until we're confident it can fully replace what we've already shipped.

What prevents Google from implementing both? The standards-track API already interoperates in Safari and Firefox, satisfying the requirement to exit CR. Chrome's API lacks consensus. What's the best way forward for interop? 

Main-thread processing is possible in a worker-first API. The burden of transfer merely goes the other way.

The other issues are all newer and seem orthogonal to the API shape and main-thread processing. Can you explain what the concern is?

**Comment by alvestrand** [comment]
The lack of concern shown with meeting Chrome requirements (see timeline on #89, lack of progress on #200) means that we have no customers for the Firefox/Safari proposal. The proposal is not yet CR (no consensus call has been issued), so it's a bit early to talk about exiting CR.
(We have a successful consensus call for adoption).

**Comment by fippo** [comment]
> What prevents Google from implementing both?

Web developer feedback from April 2020 [here](http://webrtcbydralex.com/index.php/2020/03/30/secure-frames-sframes-end-to-end-media-encryption-with-webrtc-now-in-chrome/), [here](https://webrtchacks.com/true-end-to-end-encryption-with-webrtc-insertable-streams/) and [here](https://levelup.gitconnected.com/adding-metadata-to-media-frames-via-insertable-streams-api-for-webrtc-47f7a740e457]) has been enthusiastic, the API is in production and doing well and getting used for additional use-cases such as [dynamic audio redundancy](https://github.com/jitsi/lib-jitsi-meet/pull/2067)?

See [here](https://github.com/w3c/webrtc-encoded-transform/issues/216#issuecomment-1837951514) for adoption of the new API (or lack thereof).

Framing Chromium as the interop problem after not shipping anything for three years... wow!

**Comment by jan-ivar** [comment]
> The lack of concern shown with meeting Chrome requirements (see timeline on https://github.com/web-platform-tests/interop/issues/89, lack of progress on https://github.com/web-platform-tests/interop/issues/200)

Do you mean https://github.com/w3c/webrtc-encoded-transform/issues/89 and https://github.com/w3c/webrtc-encoded-transform/issues/200?

**Comment by alvestrand** [comment]
Yes, forgot about autoformatting linking these wrongly. Sorry.

**Comment by jgraham** [comment]
Thank you for proposing WebRTC “end-to-end-encryption” for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

We did not have consensus to include this proposal. This should not be taken as a comment on the technology as a whole

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
