### ISSUE TITLE
Fetch Web API - Content-type parsing

### ISSUE THREAD

**Issue by MayyaSunil** [web-platform-tests/interop#536]
### Description

The [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) is a very popular standard WEB API. Although this has been implemented by the major browsers from a very long time, we still have [compat issues](https://wpt.fyi/results/fetch/content-type/response.window.html?label=experimental&label=master&aligned) with regard to content-type parsing. 

### Specification

https://fetch.spec.whatwg.org/

### Tests

https://wpt.fyi/results/fetch/content-type?label=master&label=experimental&aligned

### Current Implementations

- [X] Blink
- [X] Gecko
- [X] WebKit

### Browser bug reports

- https://bugs.webkit.org/show_bug.cgi?id=192000

- https://bugzilla.mozilla.org/show_bug.cgi?id=1510180

- https://bugs.chromium.org/p/chromium/issues/detail?id=908765

**Comment by dlrobertson** [comment]
Thanks for posting this! I too find content-type handling to be interesting.

Browser bugs from [this comment](https://github.com/whatwg/fetch/pull/831#issuecomment-441993627):

>   * https://bugs.webkit.org/show_bug.cgi?id=192000
> 
>   * https://bugzilla.mozilla.org/show_bug.cgi?id=1510180
> 
>   * https://bugs.chromium.org/p/chromium/issues/detail?id=908765

**Comment by dkrecichwo** [comment]
A lack of full cross-browser support for `keepalive` and `priority` is also holding the Fetch API back:

https://bugzilla.mozilla.org/show_bug.cgi?id=1342484
https://bugzilla.mozilla.org/show_bug.cgi?id=1839319

**Comment by foolip** [comment]
cc @annevk

**Comment by gsnedders** [comment]
If the intention is just the web API, does wpt /fetch/api include everything relevant there @annevk?

**Comment by annevk** [comment]
I think so. There might be some other subdirectories that could be reasonable to include, such as `/range`. That wouldn't really address the issue OP raised though with regards to `Content-Type`.

**Comment by jgraham** [comment]
The scope here is specifically about content-type parsing. Apologies for the earlier confusion. The test link in the original post has been updated to reflect that: https://wpt.fyi/results/fetch/content-type?label=master&label=experimental&aligned

**Comment by karlcow** [comment]
@jgraham do you remember any webcompat issues created by content-type parsing differences?
