### ISSUE TITLE
HTML `focusgroup` attribute

### ISSUE THREAD

**Issue by ramiy** [web-platform-tests/interop#537]
### Description

This is an accessibility improvement for users that use keyboards to navigate websites..

Currently, developers can manage keyboard focus navigation among focusable elements (`<a>`, `<button>`, `<summary>`, `<input>`, `<select>`, `<textarea>` etc.) using "**TAB**" and "**SHIFT**+**TAB**" keys. To add navigation using "**Arrow Keys**" (left/right, up/down, home/end) for special groups of elements like Tabs, Accordions, Mega Menus, Carousels and others, we use JavaScript.

Developers have the ability to control keyboard navigation only with three global HTML attributes - `tabindex`, `autofocus` and `inert`. The `focusgroup` attribute is a complementary attribute that facilitates keyboard focus navigation using arrow keys (not tabs), among a set of focusable elements.

### Specification

https://open-ui.org/components/focusgroup.explainer/

### Current Implementations

- [ ] Blink
- [ ] Gecko
- [ ] WebKit

### Standards Positions

https://chromestatus.com/feature/5637601087193088
https://github.com/mozilla/standards-positions/issues/631

### Browser bug reports

https://bugs.chromium.org/p/chromium/issues/detail?id=1286127
https://bugs.webkit.org/show_bug.cgi?id=255482

### Workarounds

Currently we use custom JS for arrow keys navigation.

### Accessibility Impact

This feature has a huge potential to improve web accessibility by providing a built-in browser support for arrow-keys navigation among groups of focusable elements.

**Comment by lukewarlow** [comment]
https://github.com/WebKit/standards-positions/issues/171 WebKit standards position request

**Comment by lukewarlow** [comment]
Focus group still needs design and spec work before it's ready to ship. And as much as I think it's a great idea I don't think it'll be ready in time for interop 2024.

**Comment by nt1m** [comment]
An OpenUI explainer does not meet the criteria for a spec, it needs work to be in a WHATWG living standard.

**Comment by scottaohara** [comment]
Agreed with the above. Focus group still has many open questions (many of which I have yet to file from discussion with the aria working group). This is not ready

**Comment by foolip** [comment]
From State of HTML preliminary results, the `focusgroup` attribute was among the [features that respondents expressed the most interest for](https://github.com/web-platform-tests/interop/issues/550#issuecomment-1777758744). Note that this wasn't freeform, it's based on the features the survey asked about experience and sentiment for.

**Comment by LeaVerou** [comment]
> From State of HTML preliminary results, the `focusgroup` attribute was among the [features that respondents expressed the most interest for](https://github.com/web-platform-tests/interop/issues/550#issuecomment-1777758744). Note that this wasn't freeform, it's based on the features the survey asked about experience and sentiment for.

To provide more details, out of the features we asked about that corresponded to an Interop proposal, it came second in terms of interest:

<img width="1387" alt="image" src="https://github.com/web-platform-tests/interop/assets/175836/c516e5ad-16ad-42e1-8fe7-e901c35ac80b">

In terms of freeform questions, focus management came up frequently as an a11y pain point:
<img width="912" alt="image" src="https://github.com/web-platform-tests/interop/assets/175836/be3264e9-24df-47c8-a0d1-b83a51c07e49">

…and a11y in general was the 3rd biggest interactivity pain point:
<img width="911" alt="image" src="https://github.com/web-platform-tests/interop/assets/175836/75b907e4-e451-4f62-bc52-a9d5043e7fe9">

**Comment by jgraham** [comment]
Thank you for proposing HTML `focusgroup` attribute for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

As of the deadline, the specifications for HTML `focusgroup` attribute were not yet complete enough to allow interoperable implementations. To make progress on this area in the future, it will first be necessary to ensure that the feature has a clear specification in a standards track document.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
