### ISSUE TITLE
font-size-adjust

### ISSUE THREAD

**Issue by firefoxic** [web-platform-tests/interop#541]
### Description

The `font-size-adjust` property allows you to make different fonts the same visual size. This is useful when replacing a local font with a custom font, or when different fonts are adjacent on the same line.

### Specification

https://www.w3.org/TR/css-fonts-3/#font-size-adjust-prop

### Tests

https://wpt.fyi/results/css/css-fonts?label=experimental&label=master&aligned=&q=font-size-adjust

### Current Implementations

- [ ] Blink
- [X] Gecko
- [X] WebKit

### Browser bug reports

https://crbug.com/451346
https://crbug.com/1219875

### Other

https://developer.mozilla.org/en-US/docs/Web/CSS/font-size-adjust
https://caniuse.com/font-size-adjust

**Comment by jensimmons** [comment]
This would be a great thing to add to Interop 2024. We should be sure to include all three parts:
- basic support for `font-size`adjust`
- support for the `from-font` keyword
- support for two value syntax (which allows the developer to size according to another metric, not just x-height)

<img width="1398" alt="Screenshot 2023-10-05 at 6 38 06 PM" src="https://github.com/web-platform-tests/interop/assets/108474/4a1a9cf5-5c2a-4a44-b995-792414e9c987">

The tests are not working correctly if Chrome has not yet added support for `font-size-adjust`, but passes 88.8% of the tests.... so we need to take a look at the tests.

**Comment by jensimmons** [comment]
Ah, that makes sense. Great news. 

That means the current experiment scores are:
Chrome Dev: 88.8%
Firefox Nightly: 100%
Safari Technology Preview: 98.5%

There's a chance the scores will be too high to make sense to consider for Interop 2024 — that we have interop before the year starts.

**Comment by firefoxic** [comment]
I am skeptical about this. After all, Chrome has had this property behind the flag for years. And I have no hope at all that this will change. My only hope is Interop ❤️

**Comment by kojiishi** [comment]
This is a recent progress, please see crbug.com/1219875. @shivamidow @drott

**Comment by shivamidow** [comment]
I have pushed `font-size-adjust` to both Blink and WebKit this year. All necessary pieces are in the review pipeline, so Blink and WebKit will hit 100% soon.

Blink:
* https://chromium-review.googlesource.com/c/chromium/src/+/4904424

WebKit:
* https://github.com/WebKit/WebKit/pull/18425
* https://github.com/WebKit/WebKit/pull/18319

**Comment by firefoxic** [comment]
Is there similarly positive news regarding `size-adjust` #542 ?

**Comment by drott** [comment]
In the process, we should try to get a resolution on https://github.com/w3c/csswg-drafts/issues/8967 CC @svgeesus

**Comment by jensimmons** [comment]
The proposed test set includes [font-size-adjust-metrics-override.html](https://wpt.fyi/results/css/css-fonts/font-size-adjust-metrics-override.html?label=master&label=experimental&aligned&q=font-size-adjust) — which requires support for `ascent-override` / `descent-override`, a feature WebKit does not yet support. We'd like this test to not be included, since it's an 'off topic dependency'.

**Comment by zcorpan** [comment]
Thank you for proposing font-size-adjust for inclusion in Interop 2024.

We are pleased to let you know that this proposal was accepted as part of the font-size-adjust focus area. You can follow the progress of this focus area on the [Interop 2024 dashboard](https://wpt.fyi/interop-2024).

For an overview of our process, see the [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you for contributing to Interop 2024!

_Posted on behalf of the Interop team._
