### ISSUE TITLE
Web Audio API

### ISSUE THREAD

**Issue by hoch** [web-platform-tests/interop#544]
### Description

The Web Audio API allows complex processing of audio streams, and is used by a variety of verticals including creativity (e.g. audio and video editing) and communication (e.g. via Zoom, Meet, etc). The API has been shipping in all browsers for several years.

As of 2023, coverage across browsers is pretty good but there are test failures affecting [AudioContext](https://wpt.fyi/results/webaudio/the-audio-api/the-audiocontext-interface?label=experimental&label=master&aligned), [AudioWorklet](https://wpt.fyi/results/webaudio/the-audio-api/the-audioworklet-interface?label=experimental&label=master&aligned), and others that do impact developers.

### Specification

https://www.w3.org/TR/webaudio/

### Tests

The top-level WPT dashboard: [Web Audio API](https://wpt.fyi/results/webaudio/the-audio-api?label=experimental&label=master&aligned)

The test suite with significant interop problems:
- [AudioContext](https://wpt.fyi/results/webaudio/the-audio-api/the-audiocontext-interface?label=experimental&label=master&aligned)
- [AudioWorklet](https://wpt.fyi/results/webaudio/the-audio-api/the-audioworklet-interface?label=experimental&label=master&aligned)
- [MediaElementAudioSourceNode](https://wpt.fyi/results/webaudio/the-audio-api/the-mediaelementaudiosourcenode-interface?label=experimental&label=master&aligned)

### Current Implementations

- [X] Blink
- [X] Gecko
- [X] WebKit

### Browser bug reports

* Chromium: [bugs under Blink>WebAudio](https://bugs.chromium.org/p/chromium/issues/list?q=component%3ABlink%3EWebAudio&can=2&colspec=ID%2BPri%2BStars%2BType%2BComponent%2BStatus%2BSummary%2BOwner%2BTarget%2BM%2BReporter%2BModified%2BOpened&sort=-stars) 
* Gecko: [bugs under Web Audio](https://bugzilla.mozilla.org/buglist.cgi?product=Core&component=Web%20Audio&bug_status=__open__)
* WebKit: [bugs under Web Audio](https://bugs.webkit.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&component=Web%20Audio&product=WebKit&query_format=advanced)

### Polls & Surveys

From the [developer survey from 2020](https://docs.google.com/forms/d/e/1FAIpQLSfwSxxCuOHaWS1fHW7ceSVX5RhyG1hsprpyD0zsPu_dL9bgUw/viewanalytics) [1], many developers expressed frustration on poor interoperability between 3 major browsers:

- “Inconsistent feature support between browsers”
- “dealing with inconsistencies between platforms”
- “Safari browser is light years behind. Makes it hard to target in iOS devices.”
- “Can’t use the microphone within a Safari Webview on iOS”
- “Reliability/consistency across browsers”
- “Cross-platform is a huge pain. Safari has many small differences, and it's hard to keep track.”
- “some web browsers require strict samplerates or will just refuse to play things properly…”
- “the rules are set capriciously, changably and are different for every browser/platform combination.”
- “Browsers implement list of audio input/output devices differently”
- “Compatibility, I'm using https://github.com/chrisguttandin/standardized-audio-context to handle it.”
- “Browser compatibility (e.g., glitchy WebAudio performance in Safari, lack of built-in resampling in Firefox)”
- “Variety of supported features in browsers”
- “x-browser limitations”

For the last 3 years, the situation has not been changed and the developer frustration remains the same.

[1] See the question “What are the biggest challenges compared to how you handle audio on other platforms?”

### Existing Usage

- Chrome use counter: https://chromestatus.com/metrics/feature/timeline/popularity/1698

### Workarounds

- An AudioContext polyfill developed by @chrisguttandin: https://github.com/chrisguttandin/standardized-audio-context

**Comment by foolip** [comment]
Single link to just the "significant interop problems" tests:
https://wpt.fyi/results/webaudio/the-audio-api?label=master&label=experimental&aligned&q=path%3A%2Fwebaudio%2Fthe-audio-api%2Fthe-audiocontext-interface%2F%20or%20path%3A%2Fwebaudio%2Fthe-audio-api%2Fthe-audioworklet-interface%2F%20or%20path%3A%2Fwebaudio%2Fthe-audio-api%2Fthe-mediaelementaudiosourcenode-interface%2F

**Comment by nairnandu** [comment]
Thank you for proposing [Web Audio API](https://github.com/web-platform-tests/interop/issues/544#top) for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop 2024. This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year, if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
