### ISSUE TITLE
EXPAND `:has()` to include support for more pseudo-classes

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/interop#555]
### Description

`:has()` is amazing. 
Developers are thrilled.

Some of the most interesting usecases are when you put another pseudo-class inside of `:has()`. For example, :has(:playing) targets an element if there's a video or audio element playing inside of it. :has(:user-invalid) targets an element if there's a form field inside of it that's in an invalid state — making it very easy, for example, to create a red border on a text label when its field is not filled out correctly.

It would be great to see if we can get support for all of the pseudo-class (except, of course, for the ones that are disallowed in the standard). 

I started a spreadsheet to try and list what's currently supported where: https://docs.google.com/spreadsheets/d/1NZeNiJqOEiphHJiAIB9iWsp2yxsn8fsqAJj1syM6K10/edit?usp=sharing

It needs work, but the list of the pseudo-classes alone are helpful. 

### Specification

https://drafts.csswg.org/selectors/#relational

### Current Implementations

- [X] Blink
- [X] Gecko
- [X] WebKit

**Comment by dbaron** [comment]
Are there particular examples of pseudo-classes where:
 * an engine supports `:has()`,
 * an engine supports the pseudo-class,
 * the pseudo-class isn't forbidden by the spec from matching inside of `:has()`, and
 * the engine doesn't support the pseudo-class inside of `:has()`?

(I just [tested](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0A%0Adiv%3Ahas(%3Ahover)%20%7B%20background%3A%20lime%3B%20color%3A%20black%20%7D%0Adiv%3Ahas(%3Achecked)%20%7B%20background%3A%20yellow%3B%20color%3A%20black%3B%20%7D%0Ap%20%7B%20background%3A%20silver%3B%20color%3A%20black%20%7D%0A%0A%3C%2Fstyle%3E%0A%0A%3Cdiv%3E%0A%20%20div%0A%20%20%3Cp%3Ep%3C%2Fp%3E%0A%20%20%3Cinput%20type%3Dcheckbox%3E%0A%3C%2Fdiv%3E) `:hover` and `:checked` inside of `:has()` in Chrome Canary, and they worked fine.)

**Comment by nt1m** [comment]
@dbaron Matching works fine in most browsers, it's mostly invalidation that needs work, although both Chrome & WebKit have made progress in that area over the past year.

**Comment by foolip** [comment]
A list of tests will be need to evaluate the work required for this proposal, as it's not clear if there are things that don't work in Chrome here, beyond pseudo-classes that aren't supported at all yet.

**Comment by jgraham** [comment]
Thank you for proposing EXPAND `:has()` to include support for more pseudo-classes for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

We could not find any tests for EXPAND `:has()` to include support for more pseudo-classes in the Web Platform Tests.  Such tests are crucial for measuring interoperability status and progress.  Once there are WPT entries covering this proposal, we welcome it being resubmitted for a future round of Interop.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
