### ISSUE TITLE
overscroll-behavior on the root scroller

### ISSUE THREAD

**Issue by theres-waldo** [web-platform-tests/interop#560]
### Description

There is implementation divergence on whether overscroll-behavior on the root scroller needs to be specified on the `<html>` element or the `<body>` element.

Gecko only respects it on the `<html>` element.
Blink only respects it on the `<body>` element ([Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=954423)).
Webkit behaviour to be investigated.

Based on [this example in the spec](https://drafts.csswg.org/css-overscroll/#example-64e64c20), and [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=954423#c11) in the Chromium issue, I believe the Gecko behaviour is the correct one.

I'm not aware of a Web Platform Test currently exercising this but I think one could be added and I filed a [Gecko issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1857130) to contribute one.

### Specification

https://drafts.csswg.org/css-overscroll/

### Tests

https://bugzilla.mozilla.org/show_bug.cgi?id=1857130

https://wpt.fyi/results/css/css-overscroll-behavior/overscroll-behavior-root.html

### Current Implementations

- [ ] Blink
- [X] Gecko
- [ ] WebKit

### Browser bug reports

https://bugs.chromium.org/p/chromium/issues/detail?id=954423

**Comment by foolip** [comment]
@theres-waldo are the tests you're contributing in https://bugzilla.mozilla.org/show_bug.cgi?id=1857130 necessarily manual, or could they be automated? We have no infrastructure to run manual tests and include them in Interop 202X scores, unfortunately.

**Comment by theres-waldo** [comment]
> @theres-waldo are the tests you're contributing in https://bugzilla.mozilla.org/show_bug.cgi?id=1857130 necessarily manual, or could they be automated? We have no infrastructure to run manual tests and include them in Interop 202X scores, unfortunately.

I believe they can be automated, we just haven't had a chance to create automated versions yet.

**Comment by theres-waldo** [comment]
A WPT for this is now written: https://wpt.fyi/results/css/css-overscroll-behavior/overscroll-behavior-root.html?label=experimental&label=master&aligned

**Comment by gsnedders** [comment]
> A WPT for this is now written: https://wpt.fyi/results/css/css-overscroll-behavior/overscroll-behavior-root.html

Not investigated this closely right now, but this appears to be flaky in Safari: https://wpt.fyi/results/css/css-overscroll-behavior/overscroll-behavior-root.html?run_id=5075658012622848&run_id=5067793499684864&run_id=5092253229383680&run_id=5183875124297728&run_id=5197312265027584&run_id=5080252931375104&run_id=5161214339973120&run_id=5166121340108800&run_id=5069068727484416&run_id=5182223533211648&run_id=5132804272160768&run_id=5126419560005632&run_id=5097209126715392&run_id=5079107785719808&run_id=5184001288962048

**Comment by gsnedders** [comment]
Also, to note, this is the only overscroll-behavior test _not_ in the existing scrolling focus area: https://wpt.fyi/results/css/css-overscroll-behavior?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=not%20label%3Ainterop-2022-scrolling%20path%3A%2Fcss%2Fcss-overscroll-behavior. (See also: #471.)

**Comment by theres-waldo** [comment]
> There is implementation divergence on whether overscroll-behavior on the root scroller needs to be specified on the `<html>` element or the `<body>` element.
> 
> Gecko only respects it on the `<html>` element. Blink only respects it on the `<body>` element ([Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=954423)). [...]
> 
> Based on [this example in the spec](https://drafts.csswg.org/css-overscroll/#example-64e64c20), and [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=954423#c11) in the Chromium issue, I believe the Gecko behaviour is the correct one.

We can think of the changes that Blink would need to make to align with the current spec as having wo parts:

 1. Start respecting `overscroll-behavior` on `<html>`
 2. Stop respecting `overscroll-behavior` on `<body>`

Would it be fair to say that (1) is a less risky change than (2)?

I think, from a web compat point of view, we mostly care about (1). Would it help increase consensus on this issue to explicitly reduce the scope to just (1)? (The WPT already only tests (1), but I can see the issue's scope being ambiguous from the description.)

**Comment by nairnandu** [comment]
Thank you for proposing [overscroll-behavior on the root scroller](https://github.com/web-platform-tests/interop/issues/560#top) for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop 2024. This is because we got many more proposals than we could include in this year's project. Note that individual vendors may nevertheless choose to advance work in this area during the forthcoming year. We would welcome this proposal being resubmitted again next year, if necessary.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
