### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by annevk** [web-platform-tests/interop#565]
### Description

URL was a focus area in 2023 and I think it should remain one in 2024 as the primary developer complaint around non-special URLs not being interoperable continues to be true.

Additionally there are still a significant number of differences in IDNA support which is not great for end users.

Also, with #525 potentially being included I think this becomes even more important as that builds upon the URL Standard and the sole browser implementation of URLPattern doesn't implement the URL Standard correctly.

### Specification

https://url.spec.whatwg.org

### Open Issues

https://github.com/whatwg/url/labels/topic%3A%20idna might be relevant here, but note that these are deliberately not tested in WPT until we have reached agreement with Unicode on a way forward.

### Tests

https://wpt.fyi/results/url (scoping this down similar to last year would be acceptable)

I've done some work to improve https://wpt.fyi/results/html/infrastructure/urls/resolving-urls/query-encoding (as well as https://wpt.fyi/results/fetch/api/basic/url-parsing.sub.html%3Fencoding%3Dx-cp1251 and siblings) and it would be great to include those this year as well.

### Current Implementations

- [X] Blink
- [X] Gecko
- [X] WebKit

**Comment by foolip** [comment]
@annevk since this is an existing focus area, can you make the case for carryover and any scope expansion in https://github.com/web-platform-tests/interop/issues/424? (It was first also filed as a focus area, but we renamed/relabeled it.)

**Comment by annevk** [comment]
Thanks @foolip. I added https://github.com/web-platform-tests/interop/issues/424#issuecomment-1750417238 and will close this as a duplicate.
