### ISSUE TITLE
HTTP(S) URLs for WebSocket

### ISSUE THREAD

**Issue by annevk** [web-platform-tests/interop#567]
### Description

The `WebSocket` constructor required `ws:` and `was:` URLs for the longest time, preventing folks from using relative URLs. Which in turn led to a lot of clunky code trying to work around that.

This has been recently resolved in https://github.com/whatwg/websockets/pull/45 and quickly adopted by WebKit, but hasn't made its way to other engines yet. Perhaps Interop 2024 can help?

### Specification

https://websockets.spec.whatwg.org

### Tests

https://wpt.fyi/results/websockets?label=master&label=experimental&aligned&q=path%3A%2Fwebsockets%2FCreate-http-urls.any.%20or%20path%3A%2Fwebsockets%2FCreate-invalid-urls.any.%20or%20path%3A%2Fwebsockets%2FCreate-non-absolute-url.any.%20or%20path%3A%2Fwebsockets%2FCreate-url-with-windows-1252-encoding.html (from https://github.com/web-platform-tests/wpt/pull/39955)

### Current Implementations

- [ ] Blink
- [ ] Gecko
- [X] WebKit

### Browser bug reports

* https://bugs.chromium.org/p/chromium/issues/detail?id=1379162
* https://bugzilla.mozilla.org/show_bug.cgi?id=1797449

**Comment by CanadaHonk** [comment]
Gecko has implemented this in latest Nightly, now passes all WPTs linked above.

**Comment by dandclark** [comment]
This proposal has been accepted as part of Interop 2024!  On behalf of the entire Interop team, thank you for proposing it.  You’ll be able to track progress on this topic throughout the year via the [Interop 2024 dashboard](https://wpt.fyi/interop-2024).
