### ISSUE TITLE
WIP: Typography bucket investigation

### ISSUE THREAD

**Issue by myakura** [web-platform-tests/interop#570]
### Description

I propose typography-related features excluded from the past Interop focus area to be an Investigation effort for Interop 2024.

### Rationale

There has been a number of improvements on the web typography this year:

* `text-wrap: pretty`, `text-wrap: balance`
* `text-box-trim`
* `text-spacing-trim`
* `text-autospace`
* (anything else?)

There are however, still number of features missing in the web platform. 
And there are some features Interop project has considered, but excluded as focus area.

* hanging punctuation
* Initial Letter
* Color fonts
* Segment Break Transformation rules

(from https://github.com/web-platform-tests/interop/issues/39)

perhaps `line-clamp`, [another excluded proposal](https://github.com/web-platform-tests/interop/issues/16) can be a part of the bucket.

**Comment by jensimmons** [comment]
Can you explain why you believe this work should be done by the Interop 2024 project, instead of the CSS Working Group?

**Comment by jgraham** [comment]
Thank you for proposing WIP: Typography bucket investigation for inclusion in Interop 2024.

We wanted to let you know that this proposal was not selected to be part of Interop this year.

We believe this proposal is too broad, and that as such, Interop 2024 is not the right venue to do this investigation.

For an overview of our process, see [proposal selection](https://github.com/web-platform-tests/interop/blob/main/2024/selection-process.md). Thank you again for contributing to Interop 2024!

_Posted on behalf of the Interop team._
