### ISSUE TITLE
Remove pointerevents/pointerevent_attributes_nohover_pointers.html since it is a touch input test

### ISSUE THREAD

**Issue by aprotyas** [web-platform-tests/interop#574]
### Test List

https://wpt.fyi/results/pointerevents/pointerevent_attributes_nohover_pointers.html

### Rationale

This test is for touch input, but the [focus area proposal](https://github.com/web-platform-tests/interop/issues/202#issue-1406264526) for Pointer and Mouse events says:

> explicitly exclude touch and stylus due to lack of WPT testing support across all browsers.

As such, this test is out of scope of this focus area and we should drop this test from Interop 2023.

**Comment by aprotyas** [comment]
This test was also explicitly called out in https://github.com/web-platform-tests/interop/issues/307#issuecomment-1490272569 but was not removed as part of said issue's resolution.

**Comment by aprotyas** [comment]
CC'ing participants from #307: @gsnedders @flackr @foolip

**Comment by nt1m** [comment]
cc @EdgarChen @smaug---- for Mozilla input.

**Comment by smaug----** [comment]
Yeah, I think this should be removed from interop, since it is explicitly testing touch.

**Comment by flackr** [comment]
Yeah touch specific tests weren't intended to be included in the 2023 area.
