### ISSUE TITLE
Interop 2024 Reactions

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#579]
I created https://foolip.github.io/interop-reactions/ to gauge the level of "engagement" on different proposals. It simply adds up all reactions, positive or negative.

This is one signal among many, but at minimum a lot of reactions means that a lot of people care and will be watching the outcome.

---

P.S. This is a quick fork of https://foolip.github.io/spec-reactions/, and just sorting by individual reactions gives similar results.

**Comment by jensimmons** [comment]
Is this being updated as people continue to put emojis on issues?

**Comment by foolip** [comment]
Yes, it's updated once per day.

**Comment by foolip** [comment]
I have stopped updating https://foolip.github.io/interop-reactions/ now, since it broke when we closed all the issues. It's now showing the state as of Jan 31, the day before Interop 2024 launched.
