### ISSUE TITLE
The `@starting-style` CSS rule

### ISSUE THREAD

**Issue by josepharhar** [web-platform-tests/interop#582]
### Description

The `@starting-style` CSS rule allows developers to specify styles which apply during the start of a transition. This is necessary in order to make transitions for `display:none` elements, since `display:none` elements have to styles to start transitions from. Dialogs and popovers start from display:none when entering the top layer, so this feature is necessary in order to make top layer elements animatable: https://github.com/chrishtr/rendering/blob/master/entry-exit-animations.md

### Specification

https://drafts.csswg.org/css-transitions-2/#defining-before-change-style-the-starting-style-rule

### Tests

https://wpt.fyi/results/css?label=master&label=experimental&aligned&q=starting-style

### Current Implementations

- [X] Blink
- [ ] Gecko
- [ ] WebKit

### Standards Positions

Gecko: https://github.com/mozilla/standards-positions/issues/833

WebKit: https://github.com/WebKit/standards-positions/issues/210

### Browser bug reports

No bugs filed yet that I know of

### Existing Usage

https://chromestatus.com/metrics/feature/timeline/popularity/4486

**Comment by josepharhar** [comment]
Original proposal: https://github.com/web-platform-tests/interop/issues/495

**Comment by dandclark** [comment]
This proposal has been accepted as part of Interop 2024!  On behalf of the entire Interop team, thank you for proposing it.  You’ll be able to track progress on this topic throughout the year via the [Interop 2024 dashboard](https://wpt.fyi/interop-2024).
