### ISSUE TITLE
Update mask-image-3-ref.html to not use mask

### ISSUE THREAD

**Issue by progers** [web-platform-tests/interop#585]
### Test List

mask-image-3a.html
mask-image-3b.html
mask-image-3c.html
mask-image-3d.html
mask-image-3e.html
mask-image-3f.html
mask-image-3g.html
mask-image-3h.html
mask-image-3i.html

### Rationale

[mask-image-3-ref.html](https://github.com/web-platform-tests/wpt/blob/b5c73fa21b044e84d44e21845e1c13b9ebdb4a99/css/css-masking/mask-image/mask-image-3-ref.html) is the reference file for several mask-image tests ([list](https://wpt.fyi/results/css/css-masking/mask-image?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=mask-image-3)), and the reference itself uses mask. Engines that have not yet fully masked up incorrectly pass (Blink and Webkit).

This test change proposal is to make this reference file not use mask. It will cause Chromium and Safari to start failing some of these tests (Firefox will continue to pass), and it will make it easier to fix these.

Proposed change: https://github.com/web-platform-tests/wpt/pull/42555

@nt1m @dholbert

**Comment by progers** [comment]
Sure thing! I went ahead and landed this in https://chromium.googlesource.com/chromium/src/+/0f2790d0a18ba66d84ca038e605cadc200662364

**Comment by dholbert** [comment]
Thanks for the heads-up!
