### ISSUE TITLE
Review recent changes to Custom Properties tests

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#587]
### Test List

https://wpt.fyi/results/css/css-properties-values-api/at-property-cssom.html
https://wpt.fyi/results/css/css-properties-values-api/at-property.html

These tests were updated in https://github.com/web-platform-tests/wpt/pull/42500 and there's some discussion in https://github.com/w3c/css-houdini-drafts/issues/1098.

The changes have already been made. This introduced test failures in Chrome and Safari.

cc @fred-wang @emilio @lilles

**Comment by foolip** [comment]
cc @andruud

**Comment by emilio** [comment]
@foolip this was discussed in https://github.com/web-platform-tests/interop/issues/575, right? What am I missing?

**Comment by foolip** [comment]
@emilio you're not missing anything, I am, I forgot about that issue and didn't go searching.

I'll close this and hide comments elsewhere.

**Comment by fred-wang** [comment]
WebKit has an approved PR to make these tests pass again: https://github.com/WebKit/WebKit/pull/19050

**Comment by emilio** [comment]
Okay, let's close this then.
