### ISSUE TITLE
Rewrite property-cascade.html with getComputedStyle()

### ISSUE THREAD

**Issue by fred-wang** [web-platform-tests/interop#588]
### Test List

https://wpt.fyi/results/css/css-properties-values-api/property-cascade.html

### Rationale

The following tests from `css-properties-values-api` rely on the
`computedStyleMap()` API from CSS Typed OM Level 1, which is being
proposed for interop 2024 in #490:

```
css/css-properties-values-api/typedom.html
css/css-properties-values-api/at-property-typedom.html
css/css-properties-values-api/property-cascade.html
```

The two first are really testing the Typed OM spec with registered
properties and are not labelled for interop 2023, so that's fine.
However, the last one is included in interop 2023 and fails in Firefox,
(which does not implement the `computedStyleMap()` API yet):

https://wpt.fyi/results/css/css-properties-values-api?q=label%3Ainterop-2023-property

Checking `property-cascade.html` in more details, `computedStyleMap()`
is really only used to get the computed value of sRGB colors, which
[have the same used and resolved values](https://drafts.csswg.org/css-color/#resolving-color-values). So `getComputedStyle()` can just
be used instead.

(After doing that, WebKit and Chrome still pass the tests, while
Firefox Nightly really fails because of it violates the actual
assertion being tested)

**Comment by fred-wang** [comment]
cc @emilio

**Comment by lilles** [comment]
Changing https://wpt.fyi/results/css/css-properties-values-api/property-cascade.html to use getComputedStyle for color lgtm.

**Comment by emilio** [comment]
Yeah sounds good to me fwiw. Thanks Fred!
