### ISSUE TITLE
Remove inline-flexbox-wrap-vertically-width-calculation.html and multiline-shrink-to-fit.html

### ISSUE THREAD

**Issue by davidsgrogan** [web-platform-tests/interop#592]
### Test List

[inline-flexbox-wrap-vertically-width-calculation.html](https://wpt.fyi/results/css/css-flexbox/inline-flexbox-wrap-vertically-width-calculation.html?label=experimental&label=master&product=chrome&product=firefox&product=safari&aligned&view=subtest&q=status%3Afail%20label%3Ainterop-2023-flexbox%20or%20label%3Ainterop-2021-flexbox)
[multiline-shrink-to-fit.html](https://wpt.fyi/results/css/css-flexbox/multiline-shrink-to-fit.html?label=experimental&label=master&product=chrome&product=firefox&product=safari&aligned&view=subtest&q=status%3Afail%20label%3Ainterop-2023-flexbox%20or%20label%3Ainterop-2021-flexbox)

### Rationale

These tests' **expectations rely on the non-standardized** multiline column intrinsic sizing algorithm. Now that **Blink has implemented the standardized** intrinsic size [algorithm](https://drafts.csswg.org/css-flexbox/#intrinsic-cross-sizes:~:text=The%20max%2Dcontent%20cross%20size%20is%20the%20sum%20of%20the%20flex%20line%20cross%20sizes%20resulting%20from%20sizing), Blink doesn't match these expectations.

We could fix the expectations to match the specification. But such update would penalize Webkit and Gecko for not shipping the specified intrinsic sizing algorithms, and implementing those algorithms were definitely not part of interop2023. So: I propose we simply remove these two tests from the interop test set.

/cc @nt1m and @dholbert for review

**Comment by dholbert** [comment]
Sure, removing makes sense. Thanks!

**Comment by nt1m** [comment]
Sounds good to me
