### ISSUE TITLE
Exclude changes to gradient-interpolation-method-computed.html and color-computed-color-mix-function.html

### ISSUE THREAD

**Issue by nairnandu** [web-platform-tests/interop#600]
### Test List

- [gradient-interpolation-method-computed.html](https://wpt.fyi/results/css/css-images/parsing/gradient-interpolation-method-computed.html?label=experimental&label=master&aligned)
- [color-computed-color-mix-function.html](https://wpt.fyi/results/css/css-color/parsing/color-computed-color-mix-function.html?label=experimental&label=master&aligned)

### Rationale

There were changes made to these tests, without an associated test-change-proposal:

- https://github.com/web-platform-tests/wpt/commit/79c26e1b48072705e936333a5443aa2aaf829809
- https://github.com/web-platform-tests/wpt/commit/892583e4adb98da9b63c6ceaf1e0896f2cfb71e7

**Comment by nairnandu** [comment]
adding @mysteryDate as well for review

**Comment by mysteryDate** [comment]
For https://github.com/web-platform-tests/wpt/commit/892583e4adb98da9b63c6ceaf1e0896f2cfb71e7 :

I know that hwb/hsl serialize as legacy srgb, which never serializes "none" and simply swaps it for zero at parse time. According to the spec ["During serialization, any missing values are converted to 0."](https://csswg.sesse.net/css-color-4/#serializing-sRGB-values) and [the tests](https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-valid-rgb.html#L15) agree. But in this instance, the colors are being serialized as non-legacy color(srgb ... ) format, so the "nones" should remain in my opinion. Regardless, I think we should have had a test change proposal.

Could you also explain your reasoning here: https://github.com/web-platform-tests/wpt/commit/79c26e1b48072705e936333a5443aa2aaf829809

I don't understand what this change is meant to be about.

I would ideally like this to just go through a normal test change proposal so we can have an obvious documentation of the reasoning for the test changes.

**Comment by mysteryDate** [comment]
Ah, I now see this

https://github.com/web-platform-tests/wpt/issues/42677

I'll respond there. I have no further objections here.

**Comment by nt1m** [comment]
The commit message from https://github.com/web-platform-tests/wpt/commit/79c26e1b48072705e936333a5443aa2aaf829809 says it all fwiw, computed value serialization should resolve the positions. Which is something neither Blink or WebKit are doing correctly in this case atm.

**Comment by mysteryDate** [comment]
Gotcha, I didn't see the spec link in the commit message, my apologies.
