### ISSUE TITLE
Exclude clip-path-element-userSpaceOnUse-00{3,4}.html from interop-2023

### ISSUE THREAD

**Issue by progers** [web-platform-tests/interop#608]
### Test List

https://wpt.fyi/results/css/css-masking/clip-path/clip-path-element-userSpaceOnUse-003.html
https://wpt.fyi/results/css/css-masking/clip-path/clip-path-element-userSpaceOnUse-004.html

### Rationale

All engines have interoperable behavior here, but violate the spec ([this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1834644) has some additional information). There is not a clear path to passing these tests without introducing compatibility or interoperability issues, so I would like to exclude these from interop-2023.

@nt1m @dholbert

**Comment by nt1m** [comment]
Sounds good to me, it would be good to get a spec issue opened to discuss this behavior more formally.

**Comment by dholbert** [comment]
Agreed, let's exclude these.

**Comment by progers** [comment]
Thanks for removing these!

> Sounds good to me, it would be good to get a spec issue opened to discuss this behavior more formally.

I filed https://github.com/w3c/fxtf-drafts/issues/538 for this.
