### ISSUE TITLE
Inapp exiting (intent link/url and detection)

### ISSUE THREAD

**Issue by shalanah** [web-platform-tests/interop#613]
A substantial amount of web traffic is now through inapp browsers. Users don't understand the tradeoffs of inapp browsers and apps make it hard to escape their control. 

This is especially bad for websites that sole function is to allow downloads. These sites are entirely broken.

Requests
- Detect if downloads are turned off by browser (with JS)
- Detect if in inapp browser (with JS)
- Provide a url that allows user to escape inapp browsers
  - For example: Intent linking / redirecting works in Android/Pixel phones `intent:https://example.com#Intent;end`

**Comment by foolip** [comment]
@shalanah unfortunately the proposal period for Interop 2024 has ended and we're now in the process of evaluating the proposals we have.

What you're describing sounds like a feature request, and it's not easy to say which working group it could make sense for. I would suggest taking a look at https://wicg.io/ and submitting a proposal there.

Note that ultimately any proposal would hinge on in-app browsers accepting that they can be distinguished from regular browsers. If reporting "I'm an in-app browser" has any negative consequences for their users, the incentives are strong to just report that it's a regular browser. It's a little bit like the `navigator.webdriver` boolean, very easy to spoof if needed.
