### ISSUE TITLE
Wrong WebCodecs score for Safari stable on https://wpt.fyi/interop-2023?stable

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#618]
I'm not sure what's going on but https://wpt.fyi/interop-2023?stable shows "87.3%" even though clicking on the focus area link shows 98%: https://wpt.fyi/results/webcodecs?product=chrome&product=firefox&product=safari&aligned=&view=interop&q=label%3Ainterop-2023-webcodecs&label=master&label=stable

I don't really get where this number comes from.

**Comment by nt1m** [comment]
cc @past @DanielRyanSmith @jgraham Do we know why this is getting computed wrong?

**Comment by dbaron** [comment]
It looks like it's wrong in the interop view:  the 8 tests that end in `?av1` show up as "0 of 1 subtests" in the interop view but are shown as green and it seems like no points are deducted.  (Or maybe something is trying to exclude those tests but doing it strangely?)

**Comment by nt1m** [comment]
Ah :( This same issue again. I thought we fixed the AV1 tests, but we only did so in STP apparently. I'll file a wpt-metadata PR to get the AV1 tests removed.
