### ISSUE TITLE
Test change proposal for pointer events

### ISSUE THREAD

**Issue by nairnandu** [web-platform-tests/interop#628]
### Test List

1. [coalesced_events_attributes_under_load.https.html?mouse](https://wpt.fyi/results/pointerevents/coalesced_events_attributes_under_load.https.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
2. [coalesced_events_attributes.html?mouse](https://wpt.fyi/results/pointerevents/coalesced_events_attributes.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
3. [idlharness.window.html](https://wpt.fyi/results/pointerevents/idlharness.window.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
4. [mouse-pointer-boundary-events-for-shadowdom.html](https://wpt.fyi/results/pointerevents/mouse-pointer-boundary-events-for-shadowdom.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
5. [pointerevent_after_target_appended.html?mouse](https://wpt.fyi/results/pointerevents/pointerevent_after_target_appended.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
6. [pointerevent_attributes_hoverable_rightbutton.html?mouse](https://wpt.fyi/results/pointerevents/pointerevent_attributes_hoverable_rightbutton.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
7. [pointerevent_auxclick_is_a_pointerevent.html?mouse](https://wpt.fyi/results/pointerevents/pointerevent_auxclick_is_a_pointerevent.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
8. [pointerevent_boundary_events_at_implicit_release_hoverable_pointers.html](https://wpt.fyi/results/pointerevents/pointerevent_boundary_events_at_implicit_release_hoverable_pointers.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
9. [pointerevent_capture_suppressing_mouse.html](https://wpt.fyi/results/pointerevents/pointerevent_capture_suppressing_mouse.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
10. [pointerevent_click_during_capture.html](https://wpt.fyi/results/pointerevents/pointerevent_click_during_capture.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
11. [pointerevent_click_is_a_pointerevent_multiple_clicks.html?mouse](https://wpt.fyi/results/pointerevents/pointerevent_click_is_a_pointerevent_multiple_clicks.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
12. [pointerevent_click_is_a_pointerevent.html?mouse](https://wpt.fyi/results/pointerevents/pointerevent_click_is_a_pointerevent.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
13. [pointerevent_constructor.html](https://wpt.fyi/results/pointerevents/pointerevent_constructor.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
14. [pointerevent_contextmenu_is_a_pointerevent.html?mouse](https://wpt.fyi/results/pointerevents/pointerevent_contextmenu_is_a_pointerevent.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
15. [pointerevent_fractional_coordinates.html?mouse](https://wpt.fyi/results/pointerevents/pointerevent_fractional_coordinates.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
16. [pointerevent_mouse_capture_change_hover.html](https://wpt.fyi/results/pointerevents/pointerevent_mouse_capture_change_hover.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
17. [pointerevent_mouse_pointercapture_inactivate_pointer.html](https://wpt.fyi/results/pointerevents/pointerevent_mouse_pointercapture_inactivate_pointer.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
18. [pointerevent_pointermove_on_chorded_mouse_button.html](https://wpt.fyi/results/pointerevents/pointerevent_pointermove_on_chorded_mouse_button.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
19. [pointerevent_pointerout_no_pointer_movement.html](https://wpt.fyi/results/pointerevents/pointerevent_pointerout_no_pointer_movement.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
20. [pointerevent_releasepointercapture_events_to_original_target.html?mouse](https://wpt.fyi/results/pointerevents/pointerevent_releasepointercapture_events_to_original_target.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
21. [pointerevent_sequence_at_implicit_release_on_click.html?mouse](https://wpt.fyi/results/pointerevents/pointerevent_sequence_at_implicit_release_on_click.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
22. [pointerevent_touch-action-keyboard.html](https://wpt.fyi/results/pointerevents/pointerevent_touch-action-keyboard.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
23. [predicted_events_attributes.html?mouse](https://wpt.fyi/results/pointerevents/predicted_events_attributes.html%3Fmouse?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events%20%28chrome%3A%21pass%20or%20firefox%3A%21pass%20or%20safari%3A%21pass%29)
24. [synthetic-mouse-enter-leave-over-out-button-state-after-target-removed.tentative.html?buttonType=LEFT&button=0&buttons=1](https://wpt.fyi/results/uievents/mouse/synthetic-mouse-enter-leave-over-out-button-state-after-target-removed.tentative.html%3FbuttonType%3DLEFT%26button%3D0%26buttons%3D1?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events)
25. [synthetic-mouse-enter-leave-over-out-button-state-after-target-removed.tentative.html?buttonType=MIDDLE&button=1&buttons=4](https://wpt.fyi/results/uievents/mouse/synthetic-mouse-enter-leave-over-out-button-state-after-target-removed.tentative.html%3FbuttonType%3DMIDDLE%26button%3D1%26buttons%3D4?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-events)

### Rationale

As part of the carryover evaluation - #472 a new set of tests were proposed to be added. This was not reviewed during the carryover discussion. Raising it as a test change proposal.

**Comment by nairnandu** [comment]
@jgraham @nt1m could you review these changes for Gecko and WebKit?

**Comment by jgraham** [comment]
`pointerevent_attributes_hoverable_rightbutton.html` has been merged into `pointerevent_attributes.html`, so is already in the focus area.

Per @smaug----  `pointerevent_click_during_capture.html` is likely not correct, given that https://github.com/w3c/pointerevents/issues/356 was fixed after the test was written.  However we should fix the test and align implementations.

Generally we think these tests will likely require some work to correctly match the latest specs, but that adding them to the focus area makes sense since this is an area where implementation differences are regularly causing real world difficulties for users and web authors.

**Comment by nt1m** [comment]
cc @aprotyas Here's a link to assess these tests: https://wpt.fyi/results/pointerevents?label=master&label=experimental&aligned&view=interop&q=path%3A%22%2Fpointerevents%2Fcoalesced_events_attributes_under_load.https.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fcoalesced_events_attributes.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fidlharness.window.html%22%20or%20path%3A%22%2Fpointerevents%2Fmouse-pointer-boundary-events-for-shadowdom.html%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_after_target_appended.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_attributes_hoverable_rightbutton.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_auxclick_is_a_pointerevent.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_boundary_events_at_implicit_release_hoverable_pointers.html%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_capture_suppressing_mouse.html%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_click_during_capture.html%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_click_is_a_pointerevent_multiple_clicks.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_click_is_a_pointerevent.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_constructor.html%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_contextmenu_is_a_pointerevent.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_fractional_coordinates.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_mouse_capture_change_hover.html%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_mouse_pointercapture_inactivate_pointer.html%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_pointermove_on_chorded_mouse_button.html%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_pointerout_no_pointer_movement.html%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_releasepointercapture_events_to_original_target.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_sequence_at_implicit_release_on_click.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_touch-action-keyboard.html%22%20or%20path%3A%22%2Fpointerevents%2Fpredicted_events_attributes.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fsynthetic-mouse-enter-leave-over-out-button-state-after-target-removed.tentative.html%3FbuttonType%3DLEFT%26button%3D0%26buttons%3D1%22%20or%20path%3A%22%2Fpointerevents%2Fsynthetic-mouse-enter-leave-over-out-button-state-after-target-removed.tentative.html%3FbuttonType%3DMIDDLE%26button%3D1%26buttons%3D4%22

**Comment by zcorpan** [comment]
The spreadsheet with comments/motivations is at https://docs.google.com/spreadsheets/d/1GVqvTfRBh_film7kzMflCSJjIkq1TV4mRcPoldNSK1Q/edit?usp=sharing

The tests that have "recent consensus" implies that the spec hasn't been fixed yet to reflect the consensus. Where that is the case, I think it would be good to get the spec updated before including the corresponding test in Interop.

**Comment by mustaqahmed** [comment]
> The spreadsheet with comments/motivations is at https://docs.google.com/spreadsheets/d/1GVqvTfRBh_film7kzMflCSJjIkq1TV4mRcPoldNSK1Q/edit?usp=sharing

I will update the sheet now based on the comments above.  If anyone wants to update the sheet, feel free to add your comment in Column F along with your email.

> The tests that have "recent consensus" implies that the spec hasn't been fixed yet to reflect the consensus. Where that is the case, I think it would be good to get the spec updated before including the corresponding test in Interop.

Thanks for calling this out, we have two such tests.  After revisiting the spec status for both just now, I concluded that they are safe to "include".  Please let us know if anyone thinks otherwise:
- `pointerevent_after_target_appended.html?mouse`: We learned yesterday that the spec is in good shape and the test needs a minor update ([link](https://github.com/web-platform-tests/interop/issues/380)).
- `pointerevent_pointerout_no_pointer_movement.html`: the label in the sheet was wrong, oops!  The spec was already correct ([link](https://github.com/w3c/pointerevents/issues/457)).

**Comment by mustaqahmed** [comment]
> I will update the sheet now based on the comments above.

Done.

**Comment by zcorpan** [comment]
Thanks. OK for us to include.

**Comment by nairnandu** [comment]
@nt1m / @aprotyas  could you review the updated scope - [pointerevents](https://wpt.fyi/results/pointerevents?label=master&label=experimental&aligned&view=interop&q=path%3A%22%2Fpointerevents%2Fcoalesced_events_attributes_under_load.https.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fcoalesced_events_attributes.https.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fidlharness.https.window.html%22%20or%20path%3A%22%2Fpointerevents%2Fmouse-pointer-boundary-events-for-shadowdom.html%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_after_target_appended.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_attributes_hoverable_rightbutton.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_auxclick_is_a_pointerevent.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_boundary_events_at_implicit_release_hoverable_pointers.html%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_capture_suppressing_mouse.html%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_click_during_capture.html%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_click_is_a_pointerevent_multiple_clicks.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_click_is_a_pointerevent.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_constructor.html%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_contextmenu_is_a_pointerevent.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_fractional_coordinates.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_mouse_capture_change_hover.html%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_mouse_pointercapture_inactivate_pointer.html%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_pointermove_on_chorded_mouse_button.html%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_pointerout_no_pointer_movement.html%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_releasepointercapture_events_to_original_target.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_sequence_at_implicit_release_on_click.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fpointerevent_touch-action-keyboard.html%22%20or%20path%3A%22%2Fpointerevents%2Fpredicted_events_attributes.html%3Fmouse%22%20or%20path%3A%22%2Fpointerevents%2Fsynthetic-mouse-enter-leave-over-out-button-state-after-target-removed.tentative.html%3Fbuttontype%3Dleft%26button%3D0%26buttons%3D1%22%20or%20path%3A%22%2Fpointerevents%2Fsynthetic-mouse-enter-leave-over-out-button-state-after-target-removed.tentative.html%3Fbuttontype%3Dmiddle%26button%3D1%26buttons%3D4%22) and [uievents](https://wpt.fyi/results/uievents/mouse?label=master&label=experimental&aligned&view=interop&q=path%3A%22%2Fuievents%2Fmouse%2Fsynthetic-mouse-enter-leave-over-out-button-state-after-target-removed.tentative.html%22)

**Comment by mustaqahmed** [comment]
@nairnandu The [2024 dashboard](https://wpt.fyi/interop-2024) entry for pointer/mouse events still point to the 2023 list.  Is it time to include the added scope from your last comment?

**Comment by aprotyas** [comment]
@nairnandu apologies for the delay here -- both scope changes look reasonable to me. I think we can proceed to reflecting this in the 2024 dashboard.

**Comment by nairnandu** [comment]
Thank you @aprotyas and @mustaqahmed 
web-platform-tests/wpt-metadata#6282 and web-platform-tests/wpt-metadata#6283 raised
