### ISSUE TITLE
Why was JPEG XL rejected?

### ISSUE THREAD

**Issue by KParthSingh** [web-platform-tests/interop#637]
### Test List

I was totally disappointed by Interop, they just said "We didn't have consensus to include this proposal", that's it. That's the response to what is, by several times, the most requested feature in Interop 2024?
I would like to know why a feature that received 4.5 times more support than the runner-up was rejected [without any "reasonable" explanation](https://github.com/web-platform-tests/interop/issues/430#issuecomment-1921864485).
Could you please provide some insight into the factors that led to the rejection of JPEG XL? Your response would be greatly appreciated. I’m sure you guys have a lot of experience in making bad decisions.🙂
Thank you very much.

### Rationale

https://cloudinary.com/blog/the-case-for-jpeg-xl

**Comment by jensimmons** [comment]
Simply removing the "test-change-proposal" since discussions of test changes are specifically about debating whether or not we label a test that's in a current focus area — and this is a different item.

**Comment by bkardell** [comment]
Speaking purely as individuals (not officially as part of the interop team), @meyerweb and I talk about the complexities of how we got to the specific things we did, as much as I think we reasonably could:  https://www.igalia.com/chats/interopify 

If you find that helpful.

**Comment by foolip** [comment]
The Interop team doesn't have detailed feedback to give on JPEG XL, but we can give a bit more context on our process. Our process is geared towards finding areas of joint priority, but different Interop team members don't always agree about the priorities. We apologize that this wasn't communicated clearly during the proposal period, and that expectations were not clear enough. We'll improve our communication next time around.

_Posted on behalf of the Interop team._
