### ISSUE TITLE
Add dir-shadow-42 to Text Directionality focus area.

### ISSUE THREAD

**Issue by dbaron** [web-platform-tests/interop#638]
In https://github.com/web-platform-tests/wpt/pull/44621 (also see https://github.com/whatwg/html/issues/10097 and https://github.com/whatwg/html/pull/10140) I effectively split the `dir-shadow-41.html` test into two tests, creating a new `dir-shadow-42.html` test, to make sure that what it used to be testing was still tested appropriately.  (The new test has the directions swapped relative to the old one, to better distinguish inheritance from an `ltr` default.)

I think it would be good to add the new test to the Text Directionality focus area.

**Comment by nairnandu** [comment]
@jgraham can you review for Gecko?
@nt1m can you review for WebKit?

**Comment by nt1m** [comment]
Seems fine: https://wpt.fyi/results/html/dom/elements/global-attributes?label=master&label=experimental&aligned&view=interop&q=dir-shadow-42.html

**Comment by dholbert** [comment]
> @jgraham can you review for Gecko

I can review for Gecko; seems fine to me, based on @dbaron's description and @nt1m's link which seems to show everyone passing the new test.
