### ISSUE TITLE
Add more tests (related to transition-behavior) into "@starting-style & transition-behavior" focus area

### ISSUE THREAD

**Issue by BorisChiou** [web-platform-tests/interop#639]
### Test List

https://wpt.fyi/results/css/css-transitions/transition-behavior.html?label=experimental&label=master&aligned
https://wpt.fyi/results/css/css-masking/clip-path/animations/clip-path-interpolation-discrete.html?label=experimental&label=master&aligned
https://wpt.fyi/results/css/motion/animation/offset-path-interpolation-007.html?label=experimental&label=master&aligned

### Rationale

I renamed `css-transitions/all-with-discrete.tentative.html` as `css-transitions/transition-behaivor.html` because `transtion-property: all` is not a special case now and the spec uses `transition-behavior` to handle discrete transition cases, in this [PR](https://github.com/web-platform-tests/wpt/commit/a62be87f5ffa843c40ac47c959af1100cb9836ea). I added some more sub-tests in `transition-behaivor.html` as well. For now, Gecko and WebKit passed all sub-tests.

I also added `clip-path-interpolation-discrete.html` and `offset-path-interpolation-007.html` (in this [PR](https://github.com/web-platform-tests/wpt/commit/a39b23cb150d1ca3eddf7f2097ffe792a5f911e5#diff-f798e9a45b2abcdb826f39e22a3c8cb37b44affaddeabb47e8c25b11cbf1e014)) to make sure we create the discrete transitions if the animation values fall back to discrete. For now, Gecko and WebKit passed all sub-tests.

Therefore, perhaps it's worth to add these three tests into **@starting-style & transition-behavior** focus area because the current test meta only check the parsing and serialization of `transition-behavior`. It's not enough obviously.

**Comment by BorisChiou** [comment]
cc @nt1m @josepharhar

**Comment by nt1m** [comment]
Looks fine, thanks for adding more test coverage! Would be nice to fix the typo in the test name "transition-behaivor".

**Comment by BorisChiou** [comment]
Oh right. I will upload a PR to fix it.

**Comment by BorisChiou** [comment]
I upload.a Gecko patch: https://phabricator.services.mozilla.com/D202666 to fix the typo.

**Comment by foolip** [comment]
@lilles can you review?

**Comment by josepharhar** [comment]
This seems fine to me

**Comment by BorisChiou** [comment]
The fix of the typo was landed, so I updated the test list with the correct test file name, for the 1st test file, i.e. `transition-behavior.html`.

**Comment by BorisChiou** [comment]
Yes. Two of the tests use `behavior: 'allow-discrete'`, which implicitly setting `transition-behavior` in [interpolation framework](https://github.com/web-platform-tests/wpt/blob/7557e87f6686cb37c27cb789d49d91c7630bdad5/css/support/interpolation-testcommon.js#L71-L73).

**Comment by foolip** [comment]
I have labeled the three tests here:
https://github.com/web-platform-tests/wpt-metadata/pull/5789
https://github.com/web-platform-tests/wpt-metadata/pull/5790
https://github.com/web-platform-tests/wpt-metadata/pull/5791
