### ISSUE TITLE
Remove css/css-cascade/scope-starting-style.html from `@starting-style & transition-behavior` focus-area

### ISSUE THREAD

**Issue by dholbert** [web-platform-tests/interop#641]
### Test List

https://wpt.fyi/results/css/css-cascade/scope-starting-style.html

### Rationale

This test uses the `@scope` CSS feature (and appears to require this feature in order to pass).

`@scope` isn't inherently part of or related to `@starting-style & transition-behavior`. It's nice to test the interaction, but it doesn't make sense to have `@scope` as an implicit implementation *requirement* for another interop-2024 focus area.

(Note that `@scope` isn't broadly available yet -- Safari only has it enabled in TP, and Firefox doesn't have it implemented at all yet -- we've got someone looking at implementing, but nonetheless we'd prefer not to tie it to this mostly-unrelated focus area.)

**Comment by dholbert** [comment]
(Note: it seems this test was included in this focus area simply because the proposal in #582 had a proposed-test-list that matched any WPT with `starting-style` in the name, which includes this one.)

**Comment by nt1m** [comment]
seems fine

**Comment by dholbert** [comment]
Thanks @nt1m!

@josepharhar is this fine with you? (removing scope-starting-style.html from the starting-style interop focus area here)

**Comment by josepharhar** [comment]
is @scope part of interop2024? If it is, then this test should be part of something in interop2024, right? If not then it seems fine to remove

**Comment by nt1m** [comment]
@scope is not part of Interop 2024

**Comment by dholbert** [comment]
Thanks!
