### ISSUE TITLE
Remove some accessibility tests due to new ARIA issue re: contents exposed vs `nameFrom: contents`

### ISSUE THREAD

**Issue by cookiecrook** [web-platform-tests/interop#654]
### Test List

At least one type of subtest will be removed in:
- https://github.com/web-platform-tests/interop-accessibility/issues/118

But there may be more after a resolution in the following ARIA issue... `li` doesn't align with the spec (so that's tracked as a removeal), but `p`, `td`, etc and related roles may be affected.

### Rationale

Open ARIA issue here:
- https://github.com/w3c/aria/issues/2160

**Comment by cookiecrook** [comment]
@nmlapre @jcsteh @twilco @rahimabdi @scottaohara 

Two PRs so far
- https://github.com/web-platform-tests/wpt/pull/45867
- https://github.com/web-platform-tests/wpt/pull/45870

**Comment by cookiecrook** [comment]
@zcorpan Those two PRs were reviewed and merged, by the way. I'm not sure if this tracker needs to stay open beyond that.

**Comment by jcsteh** [comment]
For the record, Mozilla approved both of these changes.
