### ISSUE TITLE
Add "css/css-transitions/parsing/starting-style-parsing.html" and "idlharness-2.html" into "@starting-style & transition-behavior" focus area

### ISSUE THREAD

**Issue by BorisChiou** [web-platform-tests/interop#656]
### Test List

https://wpt.fyi/results/css/css-transitions/parsing/starting-style-parsing.html?label=master&label=experimental&aligned
Updated: https://wpt.fyi/results/css/css-transitions/idlharness-2.html?label=master&label=experimental&aligned

### Rationale

It seems we didn't put this into our meta for this focus area. This is just a simple parsing test for `@starting-style`. Gecko will turn the preference on for NIghtly soon so it will pass this test as well.

Only WebKit has a very tiny issue, and I guess it is trivial.

cc @nt1m @lilles

**Comment by nt1m** [comment]
Looks good to me!

**Comment by BorisChiou** [comment]
Oops, looks like there are one more tests should be in the focus area:
https://wpt.fyi/results/css/css-transitions/idlharness-2.html?label=master&label=experimental&aligned

It tests `CSSStartingStyleRule` interface as well.

It also includes some other tests but I think it should be fine because they are passed on all browsers.

**Comment by nt1m** [comment]
Seems fine to me too

**Comment by lilles** [comment]
lgtm

**Comment by nt1m** [comment]
https://github.com/web-platform-tests/wpt-metadata/pull/6337
https://github.com/web-platform-tests/wpt-metadata/pull/6336
