### ISSUE TITLE
Add one subtest into css/css-properties-values-api/at-property-animation.html, for custom properties focus area

### ISSUE THREAD

**Issue by BorisChiou** [web-platform-tests/interop#662]
### Test List

Add a subtest into https://wpt.fyi/results/css/css-properties-values-api/at-property-animation.html?label=experimental&label=master&aligned

The change is in https://phabricator.services.mozilla.com/D210589#change-L2S1zuPHNYWc

### Rationale

I just fixed an issue on Gecko when we reverse an ongoing transition to its initial state ([Bug 1888317](https://bugzilla.mozilla.org/show_bug.cgi?id=1888317)), and I am trying to add a subtest for it. It seems it may let other browsers get failed on this subtest (e.g. WebKit, per this [comment](https://phabricator.services.mozilla.com/D210589#inline-1166739)), so I filed this issue for the approval before I land my patch.

cc @nt1m, @andruud

**Comment by andruud** [comment]
Looks good to me. (Blink passes the new test, but this looks good regardless of that).

**Comment by BorisChiou** [comment]
The PR: https://github.com/web-platform-tests/wpt/pull/46409

**Comment by BorisChiou** [comment]
It has been merged, so I close this issue.
