### ISSUE TITLE
Add a @starting-style subtest for after-change style inheritance across ancestors

### ISSUE THREAD

**Issue by lilles** [web-platform-tests/interop#664]
There is a subtest for `@starting-style` that tests that transitions are based on the after-change style, which is supposed to not include animation effects when inheriting from the parent:

https://wpt.fyi/results/css/css-transitions/starting-style-cascade.html?label=master&label=experimental&aligned&view=interop&q=label%3Ainterop-2024-starting-style%20or%20label%3Ainterop-2024-transition-behavior

Firefox is the only browser that implements this correctly, but Safari passes because they inherit correctly if the animating element is a direct parent in the case of `@starting-style`.

I would like to either get better coverage by adding a subtest (see CL below), or remove the current subtest from interop. Firefox passes this new tests while Chrome and Safari fails.

https://chromium-review.googlesource.com/c/chromium/src/+/5577020

@emilio @nt1m @josepharhar

**Comment by emilio** [comment]
Sgtm, cc @BorisChiou

**Comment by BorisChiou** [comment]
The subtest looks good to me.

**Comment by foolip** [comment]
@gsnedders @nt1m @stubbornella can you take a look at this for WebKit?

**Comment by nt1m** [comment]
Seems fine! Sorry for the delay, I was out for the last two weeks.

**Comment by foolip** [comment]
Thanks for review everyone. Closing this, @lilles please go ahead and make the change.

**Comment by lilles** [comment]
https://github.com/web-platform-tests/wpt/pull/46688
