### ISSUE TITLE
Add more dir-slots and dir-auto-dynamic tests to interop-dir

### ISSUE THREAD

**Issue by vinhill** [web-platform-tests/interop#668]
### Test List

- [dir-auto-dynamic-changes.window.html](https://wpt.fyi/results/html/dom/elements/global-attributes/dir-auto-dynamic-changes.window.html)
- [dir-slots-directionality.html](https://wpt.fyi/results/html/dom/elements/global-attributes/dir-slots-directionality.html)

### Rationale

I'm working on the Firefox interop-dir failures and found a couple of untested cases that I would like to include in wpt. The changes are under review [here](https://phabricator.services.mozilla.com/D208337).

I think it makes sense to include these tests in the test files mentioned above, but that would mean they would become part of interop. Is this okay for the other implementers?

In 'dir-slots-directionality', the added test cases merely assert behavior that I found odd.  I will file a spec issue about these to clarify whether the behavior is intended.
- dir=auto slot ignores dir attribute of assigned nodes
- dir=auto slot considers text in bdi assigned nodes
- dir=auto slot considers text in value of input element children.

In 'dir-auto-dynamic-changes', the added tests are
- Slotted content affects multiple dir=auto slot
- Removing slotted content resets direction on dir=auto slot
- Removing child of slotted content changes direction on dir=auto slot
- Child directionality gets updated when dir=auto is set on parent
- dir=auto slot is updated by text in value of input element children
- dir=auto slot is updated if input stops being auto-directionality form-associated
- slot provides updated directionality from host to a dir=auto container.

I am unable to test on Safari, but Chrome 127.0.6510.4 fails
- dir=auto slot is updated if input stops being auto-directionality form-associated
- slot provides updated directionality from host to a dir=auto container

**Comment by dbaron** [comment]
I think this seems fine.  It's possible I'll find issues with the tests later, but we can always fix them later.  (It will be easier to debug them once they're landed in WPT, so I'm inclined to just wait for them to land and *then* figure out why Chrome is failing those two tests.)

**Comment by nt1m** [comment]
This seems fine.
