### ISSUE TITLE
Tests of `requestVideoFrameCallback` Focus Area should not require support for WebXR on desktop

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/interop#672]
### Test List

https://wpt.fyi/results/video-rvfc/request-video-frame-callback-before-xr-session.https.html?label=experimental&label=master&aligned&view=interop&q=label%3Ainterop-2024-video-rvfc

https://wpt.fyi/results/video-rvfc/request-video-frame-callback-during-xr-session.https.html?label=master&label=experimental&aligned&view=interop&q=label%3Ainterop-2024-video-rvfc

### Rationale

These two tests depend on the existence of WebXR. Safari on macOS fails these subtests because WebXR is not supported on Mac. 

A dependency on an unrelated technology that's not core to the focus area shouldn't be a blocker.  Ideally, these tests would be run on the appropriate platform — for Safari that would be visionOS. But since that's not possible, these two tests should be unlabeled and not included in Interop 2024.

**Comment by jgraham** [comment]
Agreed that anything that relies on WebXR is out of scope and should be removed.

**Comment by foolip** [comment]
Discussed briefly in https://github.com/web-platform-tests/interop/issues/674 and we have consensus to exclude these tests.
