### ISSUE TITLE
/pointerevents/mouse-pointer-boundary-events-for-shadowdom.html should allow interleaved pointer and compatibility mouse events

### ISSUE THREAD

**Issue by lilyspiniolas** [web-platform-tests/interop#682]
### Test List

https://wpt.fyi/results/pointerevents/mouse-pointer-boundary-events-for-shadowdom.html?label=experimental&label=master&aligned

### Rationale

The test currently checks for an array of four events in a specific order (2 pointer events followed by 2 mouse events) but according to https://w3c.github.io/pointerevents/#compatibility-mapping-with-mouse-events:

> At a high level, compatibility mouse events are intended to be "interleaved" with their respective pointer events. However, this specific order is not mandatory, and user agents that implement compatibility mouse events MAY decide to delay or group the dispatch of mouse events, as long as their relative order is consistent.

The test currently fails for the intended (but not required) interleaved order of events, and should be updated to allow for the correct events to occur in any order.

**Comment by nt1m** [comment]
cc @mustaqahmed @flackr @edgarchen @smaug----

**Comment by mustaqahmed** [comment]
Yes the asserts should have allowed interleaving.  Thanks for spotting this.

FYI: in pointerevent_support.js, we have the utility method [`arePointerEventsBeforeCompatMouseEvents()`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/external/wpt/pointerevents/pointerevent_support.js;drc=cd6d7ddbe22feb00d89ef812607834d9b163edd9;l=457) that checks proper interleaving.

**Comment by lilyspiniolas** [comment]
PR which resolves this issue: https://github.com/web-platform-tests/wpt/pull/47395

**Comment by aprotyas** [comment]
Closing this issue now that https://github.com/web-platform-tests/wpt/pull/47395 has merged.
