### ISSUE TITLE
The `pointerevents/idlharness.https.window.html` test should not require the presence of `onpointerrawupdate`

### ISSUE THREAD

**Issue by rr-codes** [web-platform-tests/interop#684]
### Test List

https://wpt.fyi/pointerevents/idlharness.https.window.html

### Rationale

WebKit does not plan on supporting `onpointerrawupdate` at this time. Additionally, it is still currently an experimental feature. Because of these reasons, we believe  `idlharness.https.window.html` should be updated to pass even if `onpointerrawupdate` is not supported.

**Comment by nt1m** [comment]
cc @mustaqahmed @flackr @EdgarChen @smaug---- @masayuki-nakano

**Comment by smaug----** [comment]
pointerrawupdate is in the spec https://w3c.github.io/pointerevents/ https://w3c.github.io/pointerevents/#extensions-to-the-globaleventhandlers-mixin

**Comment by nt1m** [comment]
We might be able to try to implement pointerrawupdate.

**Comment by masayuki-nakano** [comment]
FYI: I tried to implement `pointerrawupdate` on Firefox, but I got some unclear points.
* https://github.com/w3c/pointerevents/issues/509
* https://github.com/w3c/pointerevents/issues/510
* https://github.com/w3c/pointerevents/issues/511
