### ISSUE TITLE
Pointer Events: replace the coalesced event test in Interop 2024

### ISSUE THREAD

**Issue by mustaqahmed** [web-platform-tests/interop#690]
### Test List

[pointerevents/coalesced_events_attributes_under_load.https.html?mouse](https://wpt.fyi/results/pointerevents/coalesced_events_attributes_under_load.https.html%3Fmouse?label=experimental&label=master&aligned)

We are renaming the test to `.optional.html` to correctly reflect the test's scope.

### Rationale

This test enforces an [optional requirement](https://w3c.github.io/pointerevents/#coalesced-events) in the spec.  When we included the test in Interop 2024, we missed that [one assert](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/external/wpt/pointerevents/coalesced_events_attributes_under_load.https.html;drc=3a65ba58eabc6bef39ea79842bec501b147b0ad8;l=91) wrongly fails the test when the user agent chooses to skip event coalescing.  (FYI when run in the WPT server, Chrome can't be forced to coalesce!)

The good news is that we have a different test already to cover the required asserts in the above test.  I missed proposing this one originally, sorry:
- [pointerevents/coalesced_events_attributes.https.html?mouse](https://wpt.fyi/results/pointerevents/coalesced_events_attributes.https.html%3Fmouse?label=experimental&label=master&aligned).

Possible ways forward for Interop 2024:
- replace the original test with the one I just mentioned, or
- just drop the test if other browsers find it too late.

FYI @smaug---- @nt1m @nairnandu

EDIT: updated the FYI with correct usernames.

**Comment by zcorpan** [comment]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1885287

cc @masayuki-nakano

**Comment by nt1m** [comment]
I'm OK with swapping the tests.

**Comment by aprotyas** [comment]
+1, let's swap the tests.

**Comment by smaug----** [comment]
Could we rather just fix the test. There seems to be > 1 check, that should be >=

**Comment by smaug----** [comment]
...but I can live with renaming

**Comment by mustaqahmed** [comment]
The optional test has been replaced in Interop dashboard.  I will close this issue now.

> Could we rather just fix the test. There seems to be > 1 check, that should be >=

Sec 10.1 says "As a result, the coalesced events lists for these events always contain at least one event".  If this looks questionable, let's discuss in the PEWG.

**Comment by nt1m** [comment]
> The optional test has been replaced in Interop dashboard. I will close this issue now.
> 
> > Could we rather just fix the test. There seems to be > 1 check, that should be >=
> 
> Sec 10.1 says "As a result, the coalesced events lists for these events always contain at least one event". If this looks questionable, let's discuss in the PEWG.

@mustaqahmed "at least one event" reads to me as `>= 1`, not `> 1` to me. To me it means "one or more", not "strictly greater than one".

**Comment by mustaqahmed** [comment]
Sorry my last post was unclear: the WPT seems to follow the spec: `assert_greater_than_equal(coalesced_events.length, 1, ...)`.

Please send a PR to correct whatever I missed.
