### ISSUE TITLE
Is there something wrong with the dashboard scores?

### ISSUE THREAD

**Issue by mfreed7** [web-platform-tests/interop#691]
When I go to "stable" mode, I see this:

![Screenshot 2024-09-03 at 10 54 31 AM](https://github.com/user-attachments/assets/46888625-189e-4d97-866c-531a7059b6d1)

Note Chrome's 90.9% score for Declarative Shadow DOM. Now, when I click on that link for DSD, I get this:

![Screenshot 2024-09-03 at 10 54 41 AM](https://github.com/user-attachments/assets/4bca1309-860d-47a8-b419-44be8bb46f05)

That looks like a 100% score. Which dashboard is wrong here?

**Comment by dbaron** [comment]
The graph makes it looks like this was a recent change:
<img width="611" alt="Screenshot 2024-09-03 at 14 43 04" src="https://github.com/user-attachments/assets/85f608f6-02b7-413d-814c-ff1db1f77e45">

**Comment by gsnedders** [comment]
This is presumably the fact that the scores aren't live data — they're generated every few hours.

Going to the WPT results, removing the other browsers, and adding `&max-count=10` to the query gives: https://wpt.fyi/results/shadow-dom?label=master&label=stable&max-count=10&product=chrome&aligned&view=interop&q=label%3Ainterop-2024-dsd

And that currently shows these results: https://wpt.fyi/results/shadow-dom?q=label%3Ainterop-2024-dsd&run_id=5109534406475776&run_id=5187949369229312&run_id=5200307466534912&run_id=5189795265642496&run_id=5119613084106752&run_id=5174538937827328&run_id=6218290884247552&run_id=5139141830639616&run_id=5131407500509184&run_id=5080230280822784

Notably, this shows there was a singular run where Chrome scored less than 100%: https://wpt.fyi/results/shadow-dom?q=label%3Ainterop-2024-dsd&run_id=5189795265642496

**Comment by mfreed7** [comment]
Ha! So my timing was just exceedingly bad, and I caught one test flake? If so, that explanation works for me. Thanks for looking into this!

**Comment by dbaron** [comment]
Given that the error was `TypeError: window.__wptrunner_process_next_event is not a function` I might call it a harness flake rather than a test flake...
