### ISSUE TITLE
pointerevents/pointerevent_pointerout_no_pointer_movement.html contradicts UIEvents spec and WPT

### ISSUE THREAD

**Issue by mustaqahmed** [web-platform-tests/interop#695]
### Test List

[pointerevents/pointerevent_pointerout_no_pointer_movement.html](https://wpt.fyi/results/pointerevents/pointerevent_pointerout_no_pointer_movement.html?label=master&label=experimental&aligned)

### Rationale

I am proposing to remove the above test from Interop 2024: while the test matches the spec, both the test and the spec contradicts the corresponding behavior defined in UIEvents [7 years ago](https://github.com/w3c/pointerevents/issues/457).

PointerEvents doesn't want pointerover/out events w/o a movement in the mouse pointer, but UIEvents wants mouseover/out events w/o a movement so that hover effect is updated correctly after a layout change or scroll.

FYI @smaug---- @flackr

**Comment by masayuki-nakano** [comment]
Shouldn't be it caused by dispatching a `lostpointercapture` for the implicit pointer capture of the click?

**Comment by masayuki-nakano** [comment]
Err, no, opposite. `pointerup` -> `lostpointercapture` (-> `mouseup`) -> `click` -> layout change. So, no pointer boundary events should be fired.

**Comment by mustaqahmed** [comment]
Good point, I completely forgot about capturing!  I presumed [test_driver.click()](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/external/wpt/resources/testdriver.js;drc=3ba59ebbd03da44aabd418d68f1f39b92eff6590;l=178) is with `pointerType == "mouse"` but the documentation doesn't say anything!  So it could be with "touch" and therefore subject to implicit capture.  Let me file a bug for that.

**Comment by mustaqahmed** [comment]
> Err, no, opposite. `pointerup` -> `lostpointercapture` (-> `mouseup`) -> `click` -> layout change. So, no pointer boundary events should be fired. (So, it seems that the current expectation of the test matches with current spec.)

Let me explain in a different way: both the test and the spec contradicts UIEvent for the simplest case that there is a mouse and no touch or pen (so there is no implicit capturing at all).  When a click adds a `<div>` under the non-moving mouse pointer:
- [`pointerevents/pointerevent_pointerout_no_pointer_movement.html`](https://wpt.fyi/results/pointerevents/pointerevent_pointerout_no_pointer_movement.html?label=experimental&label=master&aligned) expects no "pointerout" event at the `<div>` below, and this conforms to the PointerEvents spec, but
- [`uievents/mouse/layout_change_should_fire_mouseover.html`](https://wpt.fyi/results/uievents/mouse/layout_change_should_fire_mouseover.html?label=experimental&label=master&aligned) expects a "mouseover" event at the `<div>` above, and this conforms to the UIEvent spec.

I don't see how we can support both even when there is a single pointing device.  In Chrome the latter is needed for a consistent hover behavior.

**Comment by gsnedders** [comment]
> Good point, I completely forgot about capturing! I presumed [test_driver.click()](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/external/wpt/resources/testdriver.js;drc=3ba59ebbd03da44aabd418d68f1f39b92eff6590;l=178) is with `pointerType == "mouse"` but the documentation doesn't say anything! So it could be with "touch" and therefore subject to implicit capture. Let me file a bug for that.

It should match the semantics of https://w3c.github.io/webdriver/#element-click, which I think ends up with https://w3c.github.io/webdriver/#dfn-default-pointer-parameters (i.e., `mouse`), though @jgraham might remember these parts of the spec better than me.

**Comment by mustaqahmed** [comment]
Thanks @gsnedders, I just re-posted your comment at https://github.com/web-platform-tests/wpt/issues/48158 (I am planning to send a testdriver PR there).

**Comment by smaug----** [comment]
Why was the test removed?  We should add it back, since it follows the spec.

**Comment by smaug----** [comment]
I'd prefer to add the test back, since it follows the specs. Pointer events (IIRC) on purpose doesn't have the weird behavior mouse events have.

**Comment by mustaqahmed** [comment]
I am reopening this test change proposal because the WPT needs to change to match a recent spec consensus: see the PEWG discussion https://github.com/w3c/pointerevents/issues/529 and the spec PR https://github.com/w3c/pointerevents/pull/532

**Comment by mustaqahmed** [comment]
I am again proposing to [remove the WPT](https://github.com/web-platform-tests/wpt-metadata/pull/7015) from Interop 2024, see my last comment above.  Does this sound reasonable now?  @masayuki-nakano @smaug----

**Comment by masayuki-nakano** [comment]
Yep, the pointer boundary event things were reconsidered recently, so, the pointer boundary event tests should not be in the scope of 2024.
