### ISSUE TITLE
[css-nesting] Add new test for specificity 0 of contextually invalid selector

### ISSUE THREAD

**Issue by mdubet** [web-platform-tests/interop#696]
### Test List

https://wpt.fyi/results/css/css-nesting/contextually-invalid-selectors.html?label=experimental&label=master&aligned	

### Rationale

It is a recent CSS WG resolution which could create some compatibility issue

https://github.com/w3c/csswg-drafts/issues/9600

cc @emilio

**Comment by emilio** [comment]
Cc @andruud 

I think it's ok on our end. A bit late but same applies to https://github.com/web-platform-tests/interop/issues/697 :)

**Comment by andruud** [comment]
Yup, I already thumbs-up'ed this one. Let's add it.
