### ISSUE TITLE
[css-nesting] Include CSSNestedDeclarations?

### ISSUE THREAD

**Issue by andruud** [web-platform-tests/interop#697]
### Test List

(Add) [css/css-nesting/nested-declarations-cssom.html](https://wpt.fyi/results/css/css-nesting/nested-declarations-cssom.html)
(Add) [css/css-nesting/nested-declarations-matching.html](https://wpt.fyi/results/css/css-nesting/nested-declarations-matching.html)

### Rationale

Possibly a bit late to include in 2024, but checking to see if there's interest anyway. cc @emilio @mdubet 

CC'd people already know, but I'll include some examples of potential interop pain anyway:

---

The implicit rule inside `@media` (`color:green`) now matches `<div>` with the specificity of `div`, not the specificty of `:is(div, #unrelated)`:

```
div, #unrelated {
  color: red;
  @media (width > 400px) {
     color: green;
  }
}
```

---

The implicit rule inside `@media` can now match pseudo-elements:

```
div::before {
  content: "narrow";
  @media (width > 400px) {
     content: "wide"; /* Works now, didn't before */
  }
}
```

**Comment by emilio** [comment]
Fwiw it's already kind of included since you fixed the parsing tests, so WebKit and gecko are at ninety something percent now.

I think it's fine on our end, I plan to implement this change sooner rather than later anyways

**Comment by andruud** [comment]
> Fwiw it's already kind of included since you fixed the parsing tests, so WebKit and gecko are at ninety something percent now.

Indeed. But if we don't agree to include CSSNestedDeclarations here, I can remove those tests (from interop, not from WPT), per  https://github.com/web-platform-tests/interop/issues/604.

**Comment by mdubet** [comment]
Fine on our side also 👍

**Comment by emilio** [comment]
@andruud I just noticed that some of these tests have a dependency on `@scope` (which is not on by default in Firefox and not part of interop). Would you be fine if I made the test not depend on it (by either moving the test, or checking for `window.CSSScopeRule` or so)?
