### ISSUE TITLE
Bot needs updating for Interop 2025

### ISSUE THREAD

**Issue by Schweinepriester** [web-platform-tests/interop#701]
Submitted a new issue for Interop 2025

<img width="1178" alt="Bildschirmfoto 2024-09-17 um 18 40 59" src="https://github.com/user-attachments/assets/cb7e3a45-5101-4c33-9d10-48ff3c26b345">

but the bot still added to the 2024 project

<img width="606" alt="Bildschirmfoto 2024-09-17 um 18 41 55" src="https://github.com/user-attachments/assets/a40b1473-ebcd-4616-b8a1-16ab96a88074">

so it would appear it needs to be updated 0:-)

**Comment by nairnandu** [comment]
Thanks for raising it. Disabled the auto-add workflow.
