### ISSUE TITLE
WebDX collaboration on research + tracking availability and adoption

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop#71]
[WebDX](https://docs.google.com/document/d/1AjwI-Drhnrkk1FR2gzeuhLofM8yGPyvLUNlE2J1QCvU/edit?usp=sharing) (Web Developer Experience) is a proposal by @dontcallmedom, @atopal and some people involved in Interop 2022 for a group to collaborate on web developer needs research and tracking of availability and adoption. There have been a few meetings about it, but it's at a brainstorming phase and the group isn't properly formed yet.

There is a big overlap on especially the research side with the Interop 2022 group, since we will need new signals from web developers if we are to do an Interop 2023. That research will probably include State of CSS 2022 and perhaps some smaller MDN surveys.

I am putting this on the April 28 agenda for a very brief introduction, request to review the document, and to gauge interest in a joint meeting to see where this could go. It's not a request to add anything to the Interop 2022 group's responsibilities, but many of the same people might want to be involved.

**Comment by zcorpan** [comment]
Having read the doc now, I think it certainly seems interesting!

**Comment by boazsender** [comment]
+1

**Comment by gsnedders** [comment]
There was a variety of discussion on call about this, and I think it's practically moving into its own group, but nothing is linked from here? Can someone please link where the ongoing discussion is happening and close this issue?

**Comment by dontcallmedom** [comment]
notes of our ongoing discussions inspired by this proposal https://docs.google.com/document/d/1SaotNpE1vT_Pid1DS-IJbtK61HRFBODADZPsNsAOgsE/edit#heading=h.idyfcmdqa250

**Comment by gsnedders** [comment]
and we created to https://github.com/web-platform-dx as repos
