### ISSUE TITLE
CSS Highlight API

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/interop#846]
### Description

The Custom Highlight API allows web pages to style ranges (live and static ranges). This can be useful for implementing custom selection or find-on-page logic, collaboration or syntax highlighting.

This API currently has at least experimental implementations in major browser engines, but some work is required to make it fully interoperable for users.

## Tests ##
https://wpt.fyi/results/css/css-highlight-api?label=experimental&label=master&aligned

### Specification

https://drafts.csswg.org/css-highlight-api-1/

**Comment by BenjaminAster** [comment]
Duplicate of #818?

**Comment by jgraham** [comment]
Oh indeed, I didn't notice that had been submitted since I last checked :) Thanks!
