### ISSUE TITLE
`scrollend` event

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/interop#859]
### Description

The `scrollend` event is fired when a scroll is completed. Not only is this helpful for web developers that wish to be notified when a scroll is completed, but this may be helpful for testing purposes.

## Tests

[dom/events/scrolling/scrollend-event-fired-for-programmatic-scroll.html](https://wpt.fyi/results/dom/events/scrolling?label=master&label=experimental&aligned&q=scrollend-event-fired-for-programmatic-scroll.html)
[dom/events/scrolling/scrollend-event-fired-for-scroll-attr-change.html](https://wpt.fyi/results/dom/events/scrolling?label=master&label=experimental&aligned&q=scrollend-event-fired-for-scroll-attr-change.html)

Note: This was also [proposed](https://github.com/web-platform-tests/interop/issues/528) for Interop 2024, but there were concerns with the use of touch scrolls in some of the scrollend tests. This proposal is limited to only test programmatic scrolls.

### Specification

https://drafts.csswg.org/cssom-view/

### Additional Signals

https://github.com/WebKit/standards-positions/issues/150

**Comment by lukewarlow** [comment]
Duplicate of https://github.com/web-platform-tests/interop/issues/774?

**Comment by jgraham** [comment]
Oh, huh, should have noticed that. Thanks!
