### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by annevk** [web-platform-tests/interop#889]
### Description

I would like to once again propose URLs as a focus area as they are an essential part of web infrastructure that ought to be in a much better shape than they are.

I think one problem why we haven't made as much progress as we could is because some prominent interoperability issues have been able to "hide" in a sea of passing tests. Therefore I would propose that for this year we attempt to only include tests that fail in at least one browser. Some wiggle room should be allowed and ideally we do it without adding much complexity to the test suite, but without doing something I don't think there is sufficient incentive to tackle the issues around non-special URLs, for instance.

So while this is in part carryover, I'm also very much suggesting a different approach.

### Specification

https://url.spec.whatwg.org

**Comment by jgraham** [comment]
This appears to be a duplicate of https://github.com/web-platform-tests/interop/issues/805 (I believe it's fine to propose scope changes in the context of carryover evalutaions).

**Comment by annevk** [comment]
Thanks James, let's mark it as such. I left my suggestion in a comment there.
