### ISSUE TITLE
CSS Custom Highlight API

### ISSUE THREAD

**Issue by aprotyas** [web-platform-tests/interop#890]
### Description

The CSS Custom Highlight API enables webpage authors to create and style custom text highlights beyond the default ::selection pseudo-element. This API is particularly useful for interactive applications such as search engines, word processors, or document editors, where it’s necessary to highlight specific text sections with distinctive styles.

# Tests
- https://wpt.fyi/results/css/css-highlight-api?label=master&label=experimental&aligned

### Specification

W3C

**Comment by jgraham** [comment]
This is a duplicate of https://github.com/web-platform-tests/interop/issues/818
