### ISSUE TITLE
Bust cached JavaScript files with HTTP queries, specifically Safari

### ISSUE THREAD

**Issue by jabcreations** [web-platform-tests/interop#895]
### Test List

WebKit, namely Safari, fails to bust the cache of JavaScript and other asset files in spite of different HTTP queries. I've read some where that it's "defined" that browsers should ignore queries. Even if so consider the following: before leaving where you live you might query the weather to determine if you'll be wearing a light t-shirt, bring an umbrella or gear up like an Eskimo. This clearly has a major impact on the decision and outcome. So no, HTTP queries should be considered unique and different URLs. I'm literally still getting JavaScript error reports from bugs I've fixed and deployed to the live server _months ago_. If you update the same file with the same everything (the exact same HTTP query keys and values) then no, you didn't tell the browser anything changed. This should be in addition to the preexisting aspects of how cache is handled.

### Rationale

Fixing bugs doesn't matter if the browser absolutely refuses to relinquish cached files.

**Comment by jgraham** [comment]
This doesn't sound like a test change proposal, and the Interop 2025 proposal submission period is closed, so I'm going to go ahead and close this.

If you're having difficulty with the cache behaviour in Safari, the right first step would be to file a bug on their bug tracker, hopefully with clear steps to reproduce, and ideally a testcase.
