### ISSUE TITLE
Process for considering issues related to Web Apps in Interop 2023

### ISSUE THREAD

**Issue by mtom55** [web-platform-tests/interop#91]
### Intro
When measured as a percentage of installed applications on mobile ecosystems vs native applications, Mobile Web Apps have failed to gain any meaningful traction despite the advantages of interoperability, business freedom and lack of app store fees.  

Mobile Web Apps have a huge future potential for the web, and could provide enormous benefits to developers, companies and ultimately consumers in the form of a lower development costs, applications that work across all devices and ultimately far more companies being invested in the future of the web. 

There are two key questions that need answering and then addressing:
1.  "why aren't mobile web apps successful" 
2.  "why does a CEO/CTO of a company choose to produce a native app instead of a web app"

### Vested Interest
It needs to be explicitly acknowledged that both Apple and Google, who are custodians of the two largest mobile app stores benefit greatly from the lack of uptake of mobile web apps.  This needs to be a key consideration and actively addressed in any design decisions.   

### Approaches 

There are only three methods by which these issues can be addressed:

1. The Current Approach
Vendors unilaterally decide how core Web App functionality works on the devices they control.  Note this is has been unsuccessful  in generating any meaningful uptake of mobile web apps.

2. A Standards Based Approach
A standards based approach with a deep technical investigation resulting in cohesive solution that addresses or at least identifies the major issues.

3.  Regulatory Approach
Where the Web Community presents these problems to regulators who then eventually compel vendors to take action or to implement specific solutions.

The standards based approach with guardrails to protect against self-preferential behaviour is by far the best option, however it will be necessary to follow the regulatory approach in parallel to hedge against inaction and self-interest and to provide external pressure to follow a standards approach.

### Interop and the 2023 Process

At is core Interop was designed to address key developer pain points.  

These pain points are collected from:
- MDN Developer Needs Assessment Survey
- Browser Compatibility Report 
- Issues lodged on github
- State of CSS Report

If the issue is simply around a ranking issue based on developer feedback, then as long as the appropriate questions are asked I am certain we can campaign to developers so that they are ranked highly, but this is only worth doing if vendors will actually be willing to take on this feedback and address the issues.

There is also an inherent chicken and egg problem with Web Apps, in that while the core functionality and stability does not exist across the mobile ecosystems, they'll continue to have poor uptake which ensures that less developers will be using them.

With that in mind there are two key questions:
1. If we were able to demonstrate clear support that these are issues that need addressing, would the standards community be willing to address them?
    1a. If so, would that be in Interop 2023 or as a separate process?
    1b. If not, is there any other approach that can be taken except for the regulatory one?
2. How can we help design questions to help collect the necessary data?

### Initial List of Web App Issues
The issues we have identified that relate to Web Apps are:

1.  Bugs and issues related to building native like apps
Primarily: 
https://github.com/web-platform-tests/interop-2022/issues/84
but a large number of other issues

2. Installability / Install Prompts / Install Banners
On iOS users do not know that Web Apps exist (even including regulatory bodies who were investigating mobile ecosystems).

4.  Push Notifications (should hopefully be fixed in 2023)

5. WebAPK Minting on Android for browsers other than Chrome

6. AppStore support 

7.  In-App Browsers
- Installation of Web Apps via In-App Browsers
- CCT Equivalent for third party browsers on iOS

8. Badging, Fullscreen, Deep Links, Screen Orientation Lock

Other Considerations:
- Developer control of banners/install prompts between website and native app AND/OR web app
- Install speed / delay (especially when minting an APK on Android) of Web App
- Open App Banners / Dialogs
- Complexity / Number of steps to install a Web App
- Opening or Focusing the icon of a Web App after install.

General:
For every decision that is made the question "Would this decision encourage/discourage the uptake of web apps in relation to native apps" should be asked, and where the answer is discouraged there should be a clear justification.

**Comment by gsnedders** [comment]
As @foolip mentioned, the proposed charter discussion was happening elsewhere. With this now down, and the call for proposals open, I think we can close this in favour of more specific and detailed proposals, including potentially for those listed above.
