### ISSUE TITLE
overlays - The Popup API, CSS Anchor Positioning, :modal pseudoclass - for Interop 2023

### ISSUE THREAD

**Issue by kbrilla** [web-platform-tests/interop#93]
### Description
Implement / update implementations of things needed for native overlays - mostly but not only those from list below. 

### Specifications
Popup AP
[Popup API - Micosoft](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/Popup/explainer.md)
[Popup API - OpenUI](https://open-ui.org/components/popup.research.explainer)
:modal / :top-layer pseudoclass
[:modal / :top-layer](https://github.com/w3c/csswg-drafts/issues/7319)
[:modal w3](https://www.w3.org/TR/selectors-4/#modal-state)
CSS Anchor Positioning,
[CSS Anchor Positioning,](https://tabatkins.github.io/specs/css-anchor-position/)
focusgroup
[focusgroup](https://open-ui.org/components/focusgroup.explainer)

### Rationale
Just as dialog element, Pop Up API will allow users to create overlays that are accessible. 
Most of those APIs are in proposal stage but putting this on Interop 2023 would allow those highly anticipated features as quickly available in multiple browsers as possible. Still focusgroup for example is already in dev traials and planned for origin trails in [chrome/edge](https://chromestatus.com/feature/5637601087193088). 

### Chromium implementation status
[focusgroup](https://chromestatus.com/feature/5637601087193088)\
[CSS Anchor Positioning](https://chromestatus.com/feature/5124922471874560)
[The Popup API](https://chromestatus.com/feature/5463833265045504)
[CSS :modal Pseudo Class](https://chromestatus.com/feature/5192833009975296)

**Comment by foolip** [comment]
Hi @kbrilla! We just opened up for Interop 2023 proposals yesterday, see https://github.com/web-platform-tests/interop/blob/main/2023/README.md for the process and what to expect.

I see that https://github.com/web-platform-tests/interop/issues/135 overlaps slightly with this proposal. Other than `:modal`, it looks like none of the specifications listed are on the standards track. Do you expect all or some of this to be in a standards track spec by the time we start to evaluate proposals?

Can you check out the README and then decide if you want to pursue a Focus Area or Investigation Effort proposal? If you want to edit this issue to match either template that's fine, but I think filing a new issue would be cleaner.

**Comment by gsnedders** [comment]
Closing this without prejudice; the suggestion to re-file to match a template still holds.
