### ISSUE TITLE
CSSWG resolved to clarify Flexbox Intrinsic Main Size algorithm 

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/interop#94]
Details in this issue: https://github.com/w3c/csswg-drafts/issues/7189

This will require tests to be updated / will affect scores. Sounds like @davidsgrogan is working on such test updates.

Just an FYI to help make sure follow-up happens.

**Comment by gsnedders** [comment]
I think this was https://github.com/web-platform-tests/wpt/pull/35214?

**Comment by davidsgrogan** [comment]
There are still some flexbox tests that have not been updated to match the specified intrinsic size algorithm.

**Comment by foolip** [comment]
@davidsgrogan do you know if those could be enumerated to create a burndown list? Or would that amount to reviewing all tests?

**Comment by foolip** [comment]
@bfgeek do you know if the spec changes here are fully reflected in the test suite?

@jensimmons are you aware of test changes still needed?

Yes, I'm wondering if we can close this issue :)

**Comment by jensimmons** [comment]
I don't have any knowledge of the state of the tests.

**Comment by bfgeek** [comment]
Tests are located: https://wpt.fyi/results/css/css-flexbox/intrinsic-size?label=master&label=experimental&aligned&view=subtest&q=css-flexbox

We are still working on this change.

**Comment by foolip** [comment]
@bfgeek if there's a significant change to the tests coming up, can you make sure to file a new test change proposal in this repo, so it doesn't catch anyone working on Interop 2023 by surprise? We're closing this issue because there isn't anything for the interop team to _do_ here now.

**Comment by foolip** [comment]
(Per discussion in https://github.com/web-platform-tests/interop/issues/301.)
