### ISSUE TITLE
Add currentColor color-mix tests

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop#97]
** Test List **

* css/css-color/color-mix-currentcolor-001.html
* css/css-color/color-mix-currentcolor-002.html 

** Rationale **

It's a very useful part of color-mix and Gecko supports this properly, while WebKit doesn't.

**Comment by nt1m** [comment]
cc @emilio

**Comment by jgraham** [comment]
https://wpt.fyi/results/css/css-color?label=master&label=experimental&aligned&q=color-mix-currentcolor

This seems like a substantive change which increases the featureset covered, so we need to have clear consensus to add the tests.

**Comment by emilio** [comment]
I don't think it does if all the other `color-mix()` test-cases are included, does it?

**Comment by emilio** [comment]
(In any case, +1 to add these)

**Comment by bramus** [comment]
@lilles: PTAL

**Comment by foolip** [comment]
@sesse WDYT?

**Comment by sesse** [comment]
No objections from me.

**Comment by foolip** [comment]
Thanks @sesse! With support from representatives of Chromium, Gecko, and WebKit, I'll go ahead and label these two tests now.

**Comment by foolip** [comment]
Done in https://github.com/web-platform-tests/wpt-metadata/pull/2962.
